.github/workflows/client-build.yml, .github/workflows/devp2p-build.yml
Another flaky test that I noticed so retrying that up to 3 times, same as the client syncing tests for goerli. Also lowered the timeout from 15 to 10 minutes because the jobs seem to take around 8 minutes at peak and 5 on average.
=> ci: retry `devp2p` workflow up to 3 times

packages/client/bin/cli.ts, packages/client/lib/sync/beaconsync.ts, packages/client/lib/sync/fullsync.ts, packages/client/lib/sync/lightsync.ts, packages/client/lib/sync/sync.ts, packages/client/test/sync/fullsync.spec.ts
With the new fetchers for AccountRange etc in the snapsync PR https://github.com/ethereumjs/ethereumjs-monorepo/pull/2107, we need fetcher access to be typesafe in their respective synchronizers.
This PR enables the same.
=> client: Make fetcher typesafe in syncronizers

packages/client/test/net/protocol/snapprotocol.spec.ts, packages/client/test/sync/snapsync.spec.ts
This PR adds tests for `snapprotocol` and `snapsync`.
=> client: snap protocol tests

package-lock.json, packages/trie/src/trie/trie.ts, packages/trie/test/trie/secure.spec.ts, packages/trie/test/trie/trie.spec.ts
See discussion in https://github.com/ethereumjs/ethereumjs-monorepo/pull/2071
=> refactor(trie): default to `false` for `persistRoot` option

packages/client/package.json
Upgrades the `jayson` client to the recently released version 4.0 which cuts that dep's size in half and removes some transitive dependencies in the process
=> Upgrade jayson to v4.0

packages/trie/src/trie/secure.ts
Small issue I noticed when upgrading to `beta.3` and a test with key count failing on my end. The `Trie` class already had the correct check https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/trie/src/trie/trie.ts#L752
=> fix(trie): explicitly check for `persistRoot` option being `true` in `SecureTrie`

packages/blockchain/src/types.ts
Fixes 
```
Align comment and code in interface, see https://github.com/ethereumjs/ethereumjs-monorepo/pull/2069/files/48e08c9e6f6ad5956613d067b935aaf07788a23f#r938678329
```
From meta issue #2105.
Fixes misalignment.
=> blockchain: align comment and code for getIteratorHead()

.github/workflows/block-build.yml, .github/workflows/blockchain-build.yml, .github/workflows/client-build.yml, .github/workflows/common-build.yml, .github/workflows/devp2p-build.yml, .github/workflows/ethash-build.yml, .github/workflows/evm-build.yml, .github/workflows/rlp-build.yml, .github/workflows/statemanager-build.yml, .github/workflows/trie-build.yml, .github/workflows/tx-build.yml, .github/workflows/util-build.yml, .github/workflows/vm-build.yml, .github/workflows/vm-pr.yml, config/cli/coverage.sh, packages/client/package.json, packages/evm/package.json, packages/rlp/.nycrc, packages/vm/package.json
Suspecting that codecov has problems without the `coverage/lcov.info` file because it's not able to properly parse the `coverage/lcov` directory.
=> chore: generate `coverage/lcov.info` file for codecov

.github/workflows/block-build.yml, .github/workflows/blockchain-build.yml, .github/workflows/client-build.yml, .github/workflows/common-build.yml, .github/workflows/devp2p-build.yml, .github/workflows/e2e-hardhat.yml.old, .github/workflows/ethash-build.yml, .github/workflows/evm-build.yml, .github/workflows/examples.yml, .github/workflows/node-versions.yml, .github/workflows/rlp-build.yml, .github/workflows/statemanager-build.yml, .github/workflows/trie-build.yml, .github/workflows/tx-build.yml, .github/workflows/util-build.yml, .github/workflows/vm-build.yml, .github/workflows/vm-nightly-test.yml, .github/workflows/vm-pr.yml
> https://docs.npmjs.com/cli/v8/commands/npm-ci
This command is similar to [npm install](https://docs.npmjs.com/cli/v8/commands/npm-install), except it's meant to be used in automated environments such as test platforms, continuous integration, and deployment -- or any situation where you want to make sure you're doing a clean install of your dependencies.
=> ci: use `npm ci` instead of `npm i` to install dependencies

packages/evm/src/types.ts, packages/vm/src/types.ts
If you listen to an event in `evm` or `vm` asynchronously, then you need to call a continuation function once you are done;
```typescript
vm.on('afterTx',  async (e, cont) => {
... do async stuff
cont()
})
```
However, our type signatures stated that this `cont` function should always be called with an argument, which is not the case.
=> evm/vm: update event signatures

packages/vm/src/eei/vmState.ts
`touchAccount` is `protected` which it should not be.
=> vm: make `touchAccount` of state manager non-protected

packages/trie/docs/README.md, packages/trie/docs/classes/CheckpointDB.md, packages/trie/docs/classes/CheckpointTrie.md, packages/trie/docs/classes/ExtensionNode.md, packages/trie/docs/classes/LeafNode.md, packages/trie/docs/classes/SecureTrie.md, packages/trie/docs/classes/Trie.md, packages/trie/docs/classes/TrieReadStream.md, packages/trie/docs/classes/WalkController.md, packages/trie/src/trie/trie.ts, packages/trie/src/util/readStream.ts
Moves the `Trie#_findValueNodes` function to `TrieReadStream` because it is only called there.
=> refactor(trie): move `Trie#_findValueNodes` to `TrieReadStream`

package-lock.json, packages/trie/package.json, packages/trie/src/trie/trie.ts, packages/trie/src/util/semaphore.ts, packages/trie/test/util/semaphore.spec.ts
Drops the `semaphore-async-await` dependency and replaces it with only the bits that we're actually using (which is very little). I left comments with links to the original implementations in the code.
**The trie package is now almost free of third-party dependencies, only the `readable-stream` remains for an unused class. Assuming https://github.com/ethereumjs/ethereumjs-monorepo/pull/2167 gets merged.**
=> refactor(trie): replace `semaphore-async-await` with simpler implementation

packages/block/src/header.ts, packages/block/test/header.spec.ts
This PR reverts on #2081 after a discussion with @acolytec3 on Discord, some extracts:
Example posted by @acolytec3, which was not working any more after the changes:
Reasoning to revert by @holgerd77:
---
I am coming more and more to the conclusion that this in `BlockHeader.fromRLPSerializedHeader()` was the wrong choice:
```typescript
// If an RLP serialized block header is provided and no `hardforkByBlockNumber` opt is provided, default true to
// avoid scenarios where no `opts.common` or `opts.hardforkByBlockNumber` is provided and a serialized blockheader
// is provided that predates London result in a default base fee being added to the block
// (resulting in an erroneous block hash since the default `common` hardfork is London and the blockheader constructor
// adds a default …
```
=> Block: do not auto-activate hardforkByBlockNumber in static BlockHeader constructor

packages/vm/tests/tester/config.ts, packages/vm/tests/tester/index.ts, packages/vm/tests/tester/runners/BlockchainTestsRunner.ts, packages/vm/tests/tester/runners/GeneralStateTestsRunner.ts, packages/vm/tests/tester/testLoader.ts
This PR:
- Improves the types from the vm/tester folder and improve the comments so that the types of the cli args are more obvious. This brings more clarity in usage and also helps document the CLI options a bit better
- Removes all isTruthy/isFalsy from the tester folder
=> vm: improve tester types and remove isTruthy/isFalsy checks

.github/workflows/vm-nightly-test.yml, packages/common/src/common.ts, packages/common/src/types.ts
The VM Nightly run is intended to use a fresh `package-lock.json` and so must use `npm i` to install deps.  This was accidentally changed in a recent update to the CI.  This PR:
- Reverts the changes to `npm i`
- Adds a workflow_dispatch trigger so we can manually trigger this action when testing
- Fixes a validation error in `common.setHardforkByNumber` that checks for `null` but not `undefined` that was causing some edge case tests to fail in the blockchain test runner.
=> Fix VM Nightly

packages/common/tests/customChains.spec.ts, packages/vm/tests/tester/config.ts
#2213 slightly changed the way that hardforks are checked in `common` when calling `getHardforkBlockNumber` or `setHardforkByBlockNumber` so that a hardfork can be passed in the `ChainConfig` object with either `null` or `undefined` set for the `block` property and these hardforks will be treated as being "not applied" in that `common` instance.  This addresses a change introduced in #2207 that broke certain edge cases in the `vm` test runner where some hardforks were getting set to `undefined` in the transition network tests due to missed type checking.
This PR does two things:
- Updates the test runner to explicitly set a hardfork block to 0 when transitionTests are being run and the hardfork is earlier than the last applied hardfork in the `transitionNetworks` set (which was being done …
=> Verify that hardforks without block number or ttd are not applied in common

packages/client/test/rpc/eth/call.spec.ts, packages/client/test/rpc/eth/estimateGas.spec.ts, packages/client/test/rpc/eth/getCode.spec.ts, packages/client/test/rpc/eth/getProof.spec.ts, packages/client/test/rpc/eth/getStorageAt.spec.ts, packages/client/test/rpc/eth/getTransactionCount.spec.ts, packages/evm/src/evm.ts, packages/evm/src/interpreter.ts, packages/evm/src/types.ts, packages/evm/tests/customOpcodes.spec.ts, packages/vm/src/vm.ts, packages/vm/tests/api/EIPs/eip-1153.spec.ts, packages/vm/tests/api/EIPs/eip-2315.spec.ts, packages/vm/tests/api/EIPs/eip-2929.spec.ts, packages/vm/tests/api/EIPs/eip-2930-accesslists.spec.ts, packages/vm/tests/api/EIPs/eip-3074-authcall.spec.ts, packages/vm/tests/api/EIPs/eip-3198-BaseFee.spec.ts, packages/vm/tests/api/EIPs/eip-3529.spec.ts, packages/vm/tests/api/EIPs/eip-3541.spec.ts, packages/vm/tests/api/EIPs/eip-3855.spec.ts, packages/vm/tests/api/EIPs/eip-4399-supplant-difficulty-opcode-with-prevrando.spec.ts, packages/vm/tests/api/events.spec.ts, packages/vm/tests/api/runBlock.spec.ts, packages/vm/tests/tester/runners/GeneralStateTestsRunner.ts
Counter PR against https://github.com/ethereumjs/ethereumjs-monorepo/pull/2229
I'm not sure anymore why we needed the generic types, especially now we can just access these fields from the interface directly (yes, the events are optional, but you can just `vm.events!.on(`)
=> Remove AsyncEventEmitter extension from EVM and VM

packages/common/src/common.ts, packages/common/src/types.ts, packages/common/tests/customChains.spec.ts
Reverts previous changes made in #2217 that allowed a `hardfork.block` value of `undefined` to indicate a not applied hardfork.
Also explicitly checks all the hardforks in the `common.custom` constructor to verify that there are no `undefined` block numbers and throws if so.
=> Common: Add explicit HF block number null checks back, throw on undefined

packages/blockchain/src/blockchain.ts, packages/blockchain/src/lock.ts, packages/trie/src/trie/trie.ts, packages/trie/src/util/lock.ts, packages/trie/test/util/lock.spec.ts
A semaphore with a single permit is called a lock.
=> chore: rename `Semaphore` to `Lock`

packages/block/CHANGELOG.md, packages/block/package.json, packages/blockchain/CHANGELOG.md, packages/blockchain/package.json, packages/client/CHANGELOG.md, packages/client/package.json, packages/common/CHANGELOG.md, packages/common/package.json, packages/devp2p/CHANGELOG.md, packages/devp2p/package.json, packages/ethash/CHANGELOG.md, packages/ethash/package.json, packages/evm/CHANGELOG.md, packages/evm/package.json, packages/rlp/CHANGELOG.md, packages/rlp/package.json, packages/statemanager/CHANGELOG.md, packages/statemanager/package.json, packages/trie/CHANGELOG.md, packages/trie/UPGRADING.md, packages/trie/package.json, packages/tx/CHANGELOG.md, packages/tx/package.json, packages/util/CHANGELOG.md, packages/util/package.json, packages/vm/CHANGELOG.md, packages/vm/package.json
Release notes and version updates for the Monorepo Release Candidate 1 breaking releases, following the Beta 3 releases from #2122.
=> Monorepo RC 1 Releases

packages/evm/src/evm.ts, packages/evm/src/exceptions.ts, packages/evm/tests/runCall.spec.ts
Closes #2065
Adds a new error type to EVM, which allows EVM consumers to figure out the difference between (Homestead or later) contract creation goes OOG, or if the deposited code is too large (exceeds maximum code size).
Checked other errors too, but did not find anything "weird" there.
CC @alcuadrado
=> evm: add error which triggers if code size deposit exceeds the maximum size

packages/evm/README.md
1. Blockchain cannot be used to initiate an EVM, it is not "EVMOpts". 
2. "gasUsed" is not of type "ExecResult"
=> Invalid README examples

packages/trie/benchmarks/engines/level.ts, packages/trie/recipes/level-legacy.ts, packages/trie/recipes/level.ts, packages/trie/src/trie/trie.ts, packages/trie/test/official.spec.ts, packages/trie/test/trie/secure.spec.ts
Extracts the trie package from #2233
=> trie: remove isTruthy and isFalsy

packages/client/lib/rpc/modules/eth.ts, packages/tx/src/baseTransaction.ts, packages/tx/src/types.ts, packages/tx/test/base.spec.ts, packages/tx/test/index.ts, packages/tx/test/transactionRunner.ts
Extracts the tx package from #2233
=> tx: remove isTruthy and isFalsy

packages/vm/src/bloom/index.ts, packages/vm/src/buildBlock.ts, packages/vm/src/eei/vmState.ts, packages/vm/src/runBlock.ts, packages/vm/src/runTx.ts, packages/vm/src/vm.ts, packages/vm/tests/api/EIPs/eip-3074-authcall.spec.ts, packages/vm/tests/api/istanbul/eip-1884.spec.ts, packages/vm/tests/util.ts
Extracts the vm package changes from #2233
=> vm: remove isTruthy and isFalsy

packages/common/src/common.ts
=> common: remove isTruthy and isFalsy

packages/devp2p/examples/peer-communication-les.ts, packages/devp2p/examples/peer-communication.ts, packages/devp2p/examples/simple.ts, packages/devp2p/src/dns/dns.ts, packages/devp2p/src/dpt/kbucket.ts, packages/devp2p/src/dpt/server.ts, packages/devp2p/src/protocol/eth.ts, packages/devp2p/src/protocol/les.ts, packages/devp2p/src/protocol/protocol.ts, packages/devp2p/src/protocol/snap.ts, packages/devp2p/src/rlpx/ecies.ts, packages/devp2p/src/rlpx/peer.ts, packages/devp2p/src/rlpx/rlpx.ts, packages/devp2p/src/util.ts, packages/devp2p/test/integration/util.ts
=> devp2p: remove isTruthy and isFalsy

packages/trie/src/db/checkpoint.ts, packages/trie/src/trie/trie.ts
This is based on https://github.com/ethereumjs/ethereumjs-monorepo/pull/2203/commits/c5fab21431fded59fe8fc050692ce263296901c6 from @jochem-brouwer but packages it with a nicer API for some upcoming additions I would need for more complex uses of the checkpointing mechanism. This also fixes the shallow copy issue mentioned in https://github.com/ethereumjs/ethereumjs-monorepo/pull/2203.
More complex use-cases of https://github.com/ethereumjs/ethereumjs-monorepo/pull/2203 like mine with a trie and multiple copies require access to the `CheckpointDB` to be able to access pending checkpoints and grab them. The new `database` function introduced in this PR serves as a `getter` and `setter` like the `root` function. This also has the added benefit of enabling the ability to change the database …
=> feat(trie): support manual setting of checkpoints

config/eslint.js, packages/blockchain/src/blockchain.ts, packages/client/lib/rpc/modules/eth.ts, packages/client/lib/util/parse.ts, packages/statemanager/src/stateManager.ts, packages/trie/src/proof/range.ts, packages/trie/src/trie/trie.ts, packages/trie/src/util/walkController.ts, packages/trie/test/proof/range.spec.ts, packages/vm/src/eei/vmState.ts, packages/vm/tests/api/buildBlock.spec.ts
Enables https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/return-await.md which ensures that `await` is used appropriately, like for example `return await` inside a `try/catch` to make sure the catch can handle any errors.
=> chore: enable `@typescript-eslint/return-await` rule for `eslint`

packages/evm/src/opcodes/functions.ts
We extend the Memory inside of the write function, so it is unnecessary to do it here.
=> Remove extra computation

package-lock.json, packages/statemanager/package.json, packages/statemanager/src/cache.ts, packages/statemanager/tests/stateManager.spec.ts, packages/vm/package.json
Linked issue: https://github.com/ethereumjs/ethereumjs-monorepo/issues/2283.
=> perf: migrate rbtree to js-sdsl

Dockerfile
The docker file build was failing because of addition of `node-gyp` which requests some more build infra. 
This PR adds the same!
=> client: Fix Dockerfile build

packages/statemanager/src/cache.ts
Fixes tiny issue from #2105
* See if eslint-disable-next-line implicit-dependencies/no-implicit for js-sdsl depdendency import from PR #2285 can be removed (should be possible)
Removing the eslint-disable comments had no effect as expected.
=> statemanager: remove eslint-disable from imports

packages/trie/src/trie/trie.ts, packages/trie/test/trie/prune.spec.ts
Resolves an issue where the function would fail when only the root key is present as a key but not the root value.
=> fix(trie): handle root key and value during pruned integrity verification

package-lock.json, packages/trie/package.json
Fixes an issue where using `TrieReadStream` outside this repository causes type errors that require you to install the dependency mentioned in the title.
=> chore(trie): make `@types/readable-stream` a prod dependency

packages/common/src/common.ts, packages/common/src/types.ts
seems like files might not have name property in them and hence would cause common constructor to error when undefined chain name gets passed.
To prevent this scenario `chain` representing custom chain name is now mandatory field
=> common: use a default chain name  in fromGethGenesis if no chain name specified

packages/common/src/chains/goerli.json, packages/common/src/chains/mainnet.json, packages/common/src/chains/sepolia.json, packages/common/src/common.ts, packages/common/tests/hardforks.spec.ts
Add block numbers where merge hf activates in merge testnet for ease of use (without `td`) requirement.
Also fix forkhash calculation to ignore the merge hardfork even if it might have block number assigned
Tests already cover the forkhash calc change: 
- https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/common/tests/hardforks.spec.ts#L270 
as the forkhash calc tests was failing for these networks upon addition of block number
=> common: Add merge block numbers for merged networks and fix forkhash calc

packages/vm/tests/tester/index.ts
[This line](https://github.com/ethereumjs/ethereumjs-monorepo/blob/9d885c9ba19fdf0a4db7b732dcb7446c1289bca1/packages/vm/tests/tester/testLoader.ts#L100) looks like it will return null when the load is successful.
=> vm: fix vm test

packages/common/src/eips/3675.json
Update status of EIP-3675 to Final since the merge is now no longer soon :tm: but here.
=> common: Update EIP-3675 to final

packages/common/typedoc.js, packages/evm/.eslintrc.js, packages/evm/CHANGELOG.md, packages/evm/typedoc.js, packages/statemanager/test/ethersStateManager.spec.ts, packages/statemanager/typedoc.js, packages/vm/.eslintrc.js, packages/vm/CHANGELOG.md, packages/vm/DEVELOPER.md, packages/vm/test/retesteth/README.md, packages/vm/test/retesteth/transition-cluster.ts, packages/vm/test/tester/scripts/blockchain-test-run-test.sh, packages/vm/test/tester/scripts/state-test-run-test.sh, packages/vm/typedoc.js
Fixes various references to `tests` in packages where the test directory was renamed from `tests` to `test`.  The most impactful one is the update to the `retesteth` configuration which I have tested and verified that it works again.
=> Fix `tests` directory references 

packages/evm/src/evm.ts
4399 is part of merge and is thus not experimental anymore
=> evm: move 4399 to non-experimental

packages/block/src/types.ts, packages/client/README.md, packages/client/lib/execution/receipt.ts, packages/client/test/rpc/eth/getProof.spec.ts, packages/client/test/rpc/eth/getStorageAt.spec.ts, packages/rlp/src/index.ts, packages/trie/benchmarks/suite.ts, packages/trie/test/index.spec.ts
This PR fixes broken eth.wiki links where possible. And removes the few instances where corresponding docs couldn't be found.
=> Monorepo: fix broken eth.wiki links

packages/client/lib/rpc/modules/eth.ts, packages/client/lib/rpc/validation.ts
Fixes a bug discovered in `eth_estimateGas` where the parameter logic was being applied to an optional parameter when the optional parameter didn't exist.
=> client: fix validation logic for optional params in rpc

packages/common/src/common.ts, packages/common/test/mergePOS.spec.ts
One side effect of providing merge block in the config is the `nextHardforkBlock`, which resulted into this error on peer connections on Sepolia
```typescript
[10-17|15:51:51] DEBUG Peer connected: id=7dbed138 address=184.169.161.146:30303 transport=rlpx protocols=eth,snap inbound=true 
[10-17|15:51:51] DEBUG Found full peer: id=7dbed138 address=184.169.161.146:30303 transport=rlpx protocols=eth,snap inbound=true 
[10-17|15:51:51] DEBUG Peer added: id=7dbed138 address=184.169.161.146:30303 transport=rlpx protocols=eth,snap inbound=true 
[10-17|15:51:52] DEBUG Peer disconnected (SUBPROTOCOL_ERROR): id=7dbed138 address=184.169.161.146:30303 transport=rlpx protocols=eth,snap inbound=true 
```
with no peer actually connecting when starting sync before merge.
On investigating the reason found …
=> common: Ignore merge hf in nextHardforkBlock

packages/vm/test/tester/index.ts
Somehow if ethereum/tests now fail, the errors were not printed, this PR fixes it.
=> vm/tests: print failing tests

package-lock.json, packages/block/package.json, packages/blockchain/package.json, packages/client/CHANGELOG.md, packages/client/package.json, packages/common/package.json, packages/devp2p/package.json, packages/ethash/package.json, packages/evm/package.json, packages/statemanager/package.json, packages/trie/package.json, packages/tx/package.json, packages/util/CHANGELOG.md, packages/util/package.json, packages/vm/package.json
This PR fixes releases from #2361 by submitting a forgotten Util release v8.0.1 which caused releases from Blockchain upwards to be broken as well as doing a new Client release v0.6.5 since v0.6.4 has a hardcoded Util v8.0.0 dependency which wouldn't been updated (so v0.6.4 is also broken).
=> Release Fixes (new Util release v8.0.1, new client release v0.6.5 (v0.6.4 broken))

package-lock.json, packages/evm/examples/runCode.ts, packages/evm/package.json, packages/evm/src/evm.ts, packages/evm/src/interpreter.ts, packages/evm/src/types.ts, packages/evm/test/asyncEvents.spec.ts, packages/evm/tsconfig.json, packages/util/package.json, packages/util/src/asyncEventEmitter.ts, packages/util/src/index.ts, packages/util/test/asyncEventEmitter.spec.ts, packages/vm/package.json, packages/vm/src/runBlock.ts, packages/vm/src/runTx.ts, packages/vm/src/vm.ts
Fixes #2366 
This borrows code from the old `async-eventemitter` module, migrates it to typescript, and replaces `eventemitter2` with our original API usage (hopefully).
=> Switch eventemitter2 to local asynceventemitter

packages/evm/src/eof.ts, packages/vm/test/api/EIPs/eip-3670-eof-code-validation.spec.ts
Adds an extra guard in the EOF check to ensure the zero byte is the FORMAT.
Adds 2 VM tests: one with valid EOF code and other with EOF-lookalike code which starts with an unassigned (and thus invalid) byte. 
(Please test when running it with the change in EVM enabled and disabled - before testing ensure to `npm build` the evm before re-running the test in VM)
=> evm/vm: fix EIP3540 header lookalike parsing

packages/evm/src/opcodes/functions.ts, packages/evm/src/opcodes/gas.ts, packages/vm/test/api/runTx.spec.ts
Thanks to @kchojn who found this bug. It was introduced by https://github.com/ethereumjs/ethereumjs-monorepo/pull/2054
The PR fixes 4 bugs in our lib.
This is the situation:
EOA Account `A` has balance `B`, nonce 0, and (of course) no code and no storage.
Account `A` now sends a Tx to contract `C` and it forwards ALL balance upfront to pay for gas. (So, at this point, account `A` has 0 balance as it starts running the contract).
Now JS has 3 bugs in these situations:
Calling `EXTCODEHASH` on account A will put 0 on the stack, not the empty code hash, because we report that account is empty.
`CALL` will charge `callNewAccount` gas when we forward nonzero amount from the contract back into the account
`SELFDESTRUCT` will do the same if we selfdestruct nonzero value to account A.
=> EVM: non-empty "empty" account bugfixes

packages/client/package.json, packages/evm/CHANGELOG.md, packages/evm/package.json, packages/vm/package.json
Follow-up on #2380 
Small bugfix release for the EVM (no other code changes since last relase) to include the last two bugfixes regarding EIP-3540 and empty account handling.
=> New EVM Bugfix Release v1.2.2

packages/client/lib/net/protocol/ethprotocol.ts, packages/client/lib/rpc/modules/eth.ts, packages/client/lib/service/txpool.ts, packages/client/test/integration/fullethereumservice.spec.ts, packages/client/test/miner/miner.spec.ts, packages/client/test/miner/pendingBlock.spec.ts, packages/client/test/net/protocol/ethprotocol.spec.ts, packages/client/test/rpc/eth/getTransactionReceipt.spec.ts, packages/client/test/rpc/eth/sendRawTransaction.spec.ts, packages/client/test/rpc/mockBlockchain.ts, packages/client/test/sync/txpool.spec.ts
- Fixes the `txPool.validate` method so it checks transactions against the correct stateroot when validating accounts
- Adds back missing `eth` protocol handlers for transaction gossip
=> Integrate txpool fixes found in Shandong

packages/evm/src/opcodes/gas.ts, packages/evm/test/eips/eip-3860.spec.ts
In our [EIP 3860](https://eips.ethereum.org/EIPS/eip-3860) implementation, we have not added this rule:
"Furthermore, we introduce a charge of `2` gas for every 32-byte chunk of `initcode` to represent the cost of jumpdest-analysis."
This /does/ happen at `CREATE`s at the tx-level, but it does not happen if we have a `CREATE` or a `CREATE2`
This also passes the [current ethereum/tests tests ](https://github.com/ethereum/tests/pull/990)for EIP 3860.
To check:
```
git checkout update-3860
npm run clean && npm i
cd packages/ethereum-tests
gh pr checkout 990
cd ../vm
npm run test:blockchain -- --fork=London+3860
npm run test:state -- --fork=London+3860
```
All pass.
Note: problem found by @pk910 in block 6601 on the Shandong testnet.
=> evm: fix 3860 implementation + tests

packages/block/src/block.ts, packages/block/src/header.ts, packages/block/src/helpers.ts, packages/block/src/types.ts, packages/block/test/eip4895block.spec.ts, packages/block/test/header.spec.ts, packages/common/src/eips/4895.json, packages/common/src/eips/index.ts, packages/evm/src/evm.ts, packages/vm/src/runBlock.ts, packages/vm/test/api/EIPs/eip-4895-BeaconChainWithdrawals.spec.ts, packages/vm/test/api/types.spec.ts
Implements [EIP 4895](https://eips.ethereum.org/EIPS/eip-4895)
TODOs:
=> Implement EIP4895: Beacon Chain withdrawals

packages/client/lib/sync/skeleton.ts
Extracted from shandong:
- https://github.com/ethereumjs/ethereumjs-monorepo/pull/2316
In the scenario for e.g. when the CL might start from genesis it will signal head which might be before subchain 0's tail. This fix appropriately rests the chain to new head declaration
=> client: Fix skeleton reset scenario when head announced before subchain 0 tail

packages/statemanager/src/index.ts
Closes #2416 
Adds the `EthersStateManager` to the `statemanager` exports so people don't have to deep import it.
=> stateManager: add EthersStateManager to exports

packages/client/lib/net/protocol/ethprotocol.ts, packages/client/lib/net/protocol/lesprotocol.ts, packages/client/lib/net/protocol/snapprotocol.ts, packages/util/src/bytes.ts, packages/util/test/bytes.spec.ts
Extracted and a bit enhanced from shandong 
- https://github.com/ethereumjs/ethereumjs-monorepo/pull/2316
In the devp2p protocol, integer 0 is to be coded as `0x80` and not as buffered `0x00`
Closes: #2402
=> client: Use unpadded int/bigint to buffer in net protocols

packages/client/README.md, packages/client/examples/local-debugging.md, packages/client/lib/util/debug.ts, packages/devp2p/README.md, packages/devp2p/src/protocol/eth.ts, packages/evm/README.md, packages/evm/src/evm.ts, packages/statemanager/src/baseStateManager.ts, packages/vm/README.md, packages/vm/src/eei/vmState.ts, packages/vm/src/vm.ts
Followup to PR #2325 
Addressing issue #2306 
The EVM, VM, StateManager, and devp2p packages all contain a performance feature that will skip calls to debug logging if the Debug output is not desired.
This was implemented like:
```
this.DEBUG = false
if (process.env.DEBUG !== undefined) { 
this.DEBUG === true 
}
```
with a wrapper around calls to debug()
```
if (this.DEBUG) { 
debug('message') 
}
```
This proved problematic for users who wish to enable DEBUG variables for other reasons without incidentally enabling EthJS debuggers.
----
This PR changes the way this.DEBUG is set, by checking instead for a master variable `ethjs`, and enabling this.DEBUG only if that variable is present.
```
this.DEBUG = process?.env?.DEBUG?.includes('ethjs') ?? false
```
The example scripts in the various …
=> EthJS DEBUG variable

packages/trie/README.md
`LevelDB` abstraction was removed and can now not be imported through @ethereumjs/trie >= 5.0.0 anymore. Hence, for most examples in the readme.md file, we're removing references to a top-level exported `LevelDB` abstraction, and we're replacing it with the generic and in-memory `MapDB` implementation.
=> In readme, remove references to LevelDB abstraction

packages/client/bin/cli.ts, packages/common/src/common.ts
While researching #2436, I encountered what I think are a couple of minor logic bugs:
- When the `miner` starts in the client, if your `common` instance's consensus is set to `pow`, it errors trying to access the PoA consensus algorithm's subproperty of `period` since the `consensusConfig` object in the `common._chainParams` is undefined for PoW (this would presumably result in the same error for PoS). This resolve by just returning an empty object `{}` if no configuration parameters are defined.
- I think we had some misplaced parentheses in `cli` in lines 588 - 591.  The error should occur in any scenario where we provide custom genesis parameters and also pass in either `network` or `networkId` since those tell the `common` constructor to pull in predefined network genesis parameters.
=> Common custom chain bugs

packages/client/package.json
Excludes `sim` directory from `client` tests since this isn't really a unit test but an integrated end-to-end test for validating experimental hardforks.
=> Exclude sim from client unit tests

packages/evm/package.json, packages/evm/test/memory.spec.ts
The `evm` tests have been failing since #2405 but the `npm run coverage` script wasn't picking this up due to the way it was constructed and missing the error code returned by the initial call to run the tests.
TODO
=> Fix EVM test scripts

packages/client/lib/miner/pendingBlock.ts, packages/client/lib/rpc/modules/engine.ts, packages/client/test/rpc/engine/withdrawals.spec.ts, packages/vm/src/buildBlock.ts, packages/vm/src/runTx.ts, packages/vm/src/types.ts
on/post shanghai i.e. getPayloadV2 onwards, the getPayload should also return blockValue which natively is to be implemented as fees accrued  to the miner
See 
- https://github.com/ethereum/execution-apis/pull/314/files
This is going to be part of next withdrawal testnet amongst other things
=> client: Add blockValue to the getPayload response

packages/client/test/sim/eof.spec.ts, packages/common/src/hardforks/shanghai.json
Adding the eips for shanghai hf which are now part of the Zhejiang testnet
see discussion here: https://discord.com/channels/595666850260713488/892088344438255616/1055081293450317894
=> common: Add eips 3651,3855,3860 to shanghai hf for Zhejiang shanghai testnet

packages/common/src/common.ts, packages/common/test/timestamp.spec.ts
While trying to sync the eip4844 devnet 3, ethereumjs was disconnecting from peer as it wasn't able to identiy the peer's forkhash which was on sharding hf based on time. 
On debugging realized that the we were not setting forkhashes for timestamp based hardfork.
This PR fixes the same, and as a result was able to peer successfully with the geth which was on sharding hf
=> common: Update setForkHashes to update timebased hardfork forkhashes

packages/block/src/block.ts, packages/block/src/header.ts, packages/block/test/block.spec.ts, packages/block/test/eip4895block.spec.ts, packages/block/test/header.spec.ts
Noticed in eip4844 and elsewhere that its better to set defaults properly for the required fields which makes the UX of initializing a default object easy with just `Block.fromBlockData/Block.fromHeaderData` with correct hardfork defaults.
This fixes the  addTransaction flow in the `vm/src/buildBlock.ts` which has this code flow: 
```
const blockData = { header, transactions: this.transactions }
const block = Block.fromBlockData(blockData, this.blockOpts)
```
where withdrawal defaults are not being explicity added in and hence resulting into the block building failure in shanghai with txs.
=> block: Handle hardfork defaults consistently

packages/common/src/common.ts, packages/common/src/types.ts, packages/vm/test/api/EIPs/eip-4895-withdrawals.spec.ts
This adds the EIP option to the GethConfigOpts. This change makes the workflow a bit easier for verkle trees work (can set directly the EIPs with the `Common.fromGethConfig` helper instead of using `.setEIPs` in a second step) so I'm extracting this in a separate PR. I think this could also be useful for further testnet work.
=> common: add eip option to GethConfigOpts

packages/common/src/common.ts, packages/common/src/types.ts, packages/common/src/utils.ts, packages/common/test/utils.spec.ts
This PR solves #2414 by attempting to get the latest hardfork from the geth genesis file as a fallback when the `fromGethGenesis` constructor isn't provided with an explicit hardfork. It also adds some type improvements to the geth genesis helpers.
=> common: infer latest hardfork from geth genesis file

packages/rlp/src/index.ts
Avoid an intermediate copy when `encode` is called with an Array.
=> rlp: avoid copy in encode

packages/client/package.json, packages/evm/package.json, packages/vm/package.json
Removes the `reporter=text-lcov` option from coverage scripts because it just dumps a bunch of indecipherable output to the terminal like below.  The same data is written to `coverage/lcov.info` and then uploaded to our Code Coverage instance but it does nothing useful for our CI runs and just makes it hard to navigate the CI output.
=> Remove text-lcov reporter from coverage scripts

packages/client/lib/execution/execution.ts, packages/client/lib/execution/vmexecution.ts, packages/client/lib/service/fullethereumservice.ts, packages/client/test/execution/vmexecution.spec.ts
If the client is midway syncing, sending shutdown signal to the client via Ctrl + C for e.g. wouldn't clean stop the sync or execution leading to client hanging mid way (or sometimes just keep processing the jobs it has in queue)
This PR fixes the same by clean stopping the syncronizer and execution and resolves the problem with proper stopping on client
=> client: Clean stop sync and execution to allow client shutdown

config/cli/coverage.sh
Remove one more instance of `lcov-text` to clean up CI logs
=> Remove lcov-text param from coverage script

Dockerfile, Dockerfile.fromSource
Using node18 locally and having no issues, it makes sense to update the dockerfiles to use node18
=> Update Dockerfiles to use node 18

package-lock.json, packages/block/src/block.ts, packages/util/karma.conf.js, packages/util/package.json, packages/util/src/constants.ts, packages/util/src/index.ts, packages/util/src/ssz.ts, packages/util/src/withdrawal.ts, packages/util/test/ssz.spec.ts, packages/util/test/withdrawal.spec.ts
In preparation for moving the ssz root gen capability for withdrawals, this PR adds ssz types and root gen utility method which can be later easily deployed
will just need to switch all Block.genWithdrawlsTrieRoot to Block.genWithdrawalsSSZRoot method when the spec moves to ssz root
=> util: Add ssz roots capability for withdrawals hash tree root

packages/client/bin/cli.ts
This PR makes the CLI args parsing strict, meaning that unknown args will result in yargs throwing instead of them being ignored.
`npm run client:start -- --invalidOption` now results in:
=> client: validate CLI args

.github/workflows/client-build.yml, packages/client/bin/cli.ts, packages/client/bin/startRpc.ts, packages/client/lib/types.ts, packages/client/package.json, packages/client/test/cli/cli-libp2p.spec.ts, packages/client/test/cli/cli-sync.spec.ts
A long over cleanup of the client CLI parameters to make them all camelCase.
=> Change client CLI params to camelCase

packages/tx/src/eip4844Transaction.ts, packages/tx/src/types.ts, packages/tx/test/eip4844.spec.ts
Handle json fields in fromTxData for eip4844 tx
A tx provided to test was not getting being loaded and giving errors on serialization as maxDataFee was still a string. This PR fixes it. 
It also adds a test for hash, which currently doesn't seem to be correct, has been commented out to be fixed in separate issue
=> tx: Handle json fields in fromTxData for eip4844 tx

packages/tx/src/eip4844Transaction.ts, packages/tx/test/eip4844.spec.ts
Removes the internal computation of the `aggregateKzgProof` for the network wrapper version of blob transactions and requires that field to be present when instantiating a blob transaction in the network wrapper format.
=> tx: make kzgProof required field for network wrapper

packages/client/lib/service/txpool.ts, packages/client/test/rpc/eth/sendRawTransaction.spec.ts
Adds one more check missed from the original 4844 implementation to check that data gas is increased by 1.1x on replacement transactions submitted via `sendRawTransaction`.
=> Add checks for replacement data gas too low for blob txs

packages/client/lib/rpc/modules/engine.ts, packages/client/lib/rpc/validation.ts, packages/client/test/rpc/engine/newPayloadv2.spec.ts, packages/client/test/rpc/engine/newPayloadv3.spec.ts, packages/client/test/rpc/validation.spec.ts
Adding to work done in #2502
Adds more specific type labels and validators for engine api based on type descriptions in https://github.com/ethereum/execution-apis/blob/main/src/engine/shanghai.md#engine_forkchoiceupdatedv2
hex string parameters are differentiated into bytevector length (or bitlength) giving us:
- Bytes8
- Bytes20
- Bytes32
- Root
- *Root is a Bytes32 that represents the merkle root of a nested ssz container*
- VariableBytes32
- 0 to 32 bytes
- Bytes48
- Bytes256
- Uint64
- Uint256
- Blob
- because `Bytes131072` is silly
Typenames are chosen to mimic those used in SSZ typing.  They are all just `type === 'string'`.  The actual bytelength check happens in the validators
A new `validator` has been created for each type, checking:
1. type === string
2. prefix === 0x
3. …
=> engine-api-validators

packages/client/lib/rpc/modules/engine.ts, packages/client/lib/rpc/util/CLConnectionManager.ts, packages/vm/src/runTx.ts, packages/vm/test/api/runTx.spec.ts
Some more log improvements related to understand/monitor post-Merge HF switches and get a better feeling for what happens during sync along the new payload calls by adding some comprehensive payload to payload aggregated stats (numbers of blocks processed/assembled, min/max block numbers involved, tx counts per tx types).
Open for review and merge I guess (might add more though, nevertheless: open for merge, then I'll submit on another PR).
=> More Interop Log Improvements

packages/client/lib/rpc/error-code.ts, packages/client/lib/rpc/modules/engine.ts, packages/client/lib/rpc/validation.ts, packages/client/test/rpc/engine/getCapabilities.spec.ts, packages/client/test/rpc/engine/getPayloadBodiesByHashV1.spec.ts, packages/client/test/rpc/engine/getPayloadBodiesByRangeV1.spec.ts
Adds new engine apis
- `getCapabilties` endpoint defined here [https://github.com/ethereum/execution-apis/pull/364](https://github.com/ethereum/execution-apis/pull/364)
- `getPayloadBodiesByHashV1` from [here](https://github.com/ethereum/execution-apis/blob/main/src/engine/shanghai.md#engine_getpayloadbodiesbyhashv1)
- `getPayloadBodiesByRangeV1` from [here](https://github.com/ethereum/execution-apis/blob/main/src/engine/shanghai.md#engine_getpayloadbodiesbyrangev1)
=> client: add new shanghai  engine apis

packages/client/lib/rpc/modules/engine.ts
A couple of small fixes identified while running the `getPayloadBodiesByRange` tests from [this PR](https://github.com/ethereum/hive/pull/700)
=> `getPayloadBodiesByRange` fixes

packages/blockchain/src/blockchain.ts, packages/blockchain/src/types.ts, packages/blockchain/test/index.spec.ts, packages/client/lib/execution/vmexecution.ts, packages/vm/src/eei/eei.ts, packages/vm/src/runTx.ts
Replacement candidate for reverted #2516 after some additional discussion on the breaking implications of this.
This PR now instead adjusts the Blockchain getBlock() interface signature, adds some tests and removes some non-reachable null asserting conditional clauses.
PR also improves on the error message of `getBlock()` as suggested in #2511.
Open for review.
=> Fix blockchain interface getBlock() signature (remove null return option)

packages/trie/README.md, packages/trie/src/trie/trie.ts
Reworks the `trie` readme to more prominently call out the static constructor and also cleans up language around the DB usage.
=> Update trie docs

packages/client/bin/cli.ts, packages/client/devnets/4844-interop/tools/txGenerator.ts, packages/client/package.json, packages/client/test/miner/pendingBlock.spec.ts, packages/client/test/rpc/engine/getBlobsBundleV1.spec.ts, packages/client/test/rpc/eth/sendRawTransaction.spec.ts, packages/client/test/sim/simutils.ts, packages/client/test/sim/txGenerator.ts, packages/tx/src/kzg/kzg.ts
This fixes two bugs related to reading the trusted setup file updated in #2522 and breaking the client build, discovered this while trying to locally build the docker image for playing around with Hive.
1. The trusted setup file had not been included in the build, have added a script addition to the Client `npm run build`  command
2. the relative path references were not working properly especially for the trusted setup file reference in `bin/cli.ts` where path hierarchy would change when copied over to `dist/bin/cli.ts` (one level deeper). This is now mitigated by using client package internal references which - in the dist folder case - leads to taking the - now copied over, see 1. - devnet4.txt file - from `dist/trustedSetups/devnet4.txt`
=> Client trusted setup path fixes

packages/common/src/chains/sepolia.json
Ref: 
- https://github.com/ethereum/execution-specs/pull/716
- https://github.com/eth-clients/sepolia/pull/30
and values picked and confirmed from:
https://discord.com/channels/595666850260713488/745077610685661265/1073549857219952701
Forkhash is validated as part of our hardfork forkhash cal tests:
=> Schedule shanghai on sepolia

packages/blockchain/src/blockchain.ts, packages/blockchain/src/db/helpers.ts, packages/blockchain/src/db/manager.ts, packages/client/bin/cli.ts, packages/client/lib/config.ts, packages/client/lib/execution/vmexecution.ts, packages/client/lib/rpc/modules/engine.ts, packages/client/lib/rpc/modules/eth.ts, packages/client/lib/rpc/util/CLConnectionManager.ts, packages/evm/src/evm.ts, packages/vm/src/eei/eei.ts, packages/vm/src/runTx.ts, packages/vm/src/vm.ts, packages/vm/test/api/eei.spec.ts
Fixes regarding failing hive testvectors
Closes #2498
=> allforks: Hive withdrawal fixes

packages/blockchain/src/db/manager.ts, packages/blockchain/test/index.spec.ts, packages/client/lib/sync/fetcher/blockfetcher.ts
Add extra validations for assuming nil bodies in getBlock
While debugging for 
- https://github.com/ethereumjs/ethereumjs-monorepo/issues/2528
No discrepancy was found: 
synced two ethereumjs peers 
- peer1 from geth  to have full local chain 
(our EF node has the bug of not serving canonical chain in beacon sync like how we discovered in shandong but should have been fixed with latest hive fixes regarding DB ops)
- peer2 from local ethereumjs and added extra validation for the downloaded block
but haven't found the nil withdrawal body issue so far.
However discovered that we need extravalidations 
i) while importing block from peer
ii) Also while assuming nil bodies when bodies not found in the DB (could be some DB bodies write bug)
Hence  PR for the same
Closes …
=> blockchain: Add extra validations for assuming nil bodies in getBlock

packages/common/src/chains/sepolia.json, packages/devp2p/scripts/tester.ts, packages/devp2p/src/dpt/server.ts, packages/devp2p/tsconfig.json, packages/devp2p/tsconfig.prod.json
This analysis has been triggered by trying to connect with the client to `Sepolia` with `npm run client:start -- --network=sepolia` and being dissatisfied by the level of connectivity getting on startup.
When doing some client runs with the devp2p logger being activated I (re-)discovered that we often have the situation with peer connections "looking good" but then nevertheless terminating with a `SUBPROTOCOL_ERROR`.
This is a problem we have for ages, and having these peer connections go through would be especially valuable, since there *are* only a few with some option for success - many many others refuse with `TOO_MANY_PEERS` - and if these few are terminating unexpectedly to some greater extend that is a substantial loss for client connectivity.
I tried to isolate one of these peer …
=> devp2p: Client Peer Connection SUBPROTOCOL Error Analysis

packages/client/lib/miner/pendingBlock.ts, packages/client/lib/rpc/modules/engine.ts, packages/client/test/miner/miner.spec.ts, packages/client/test/miner/pendingBlock.spec.ts, packages/client/test/rpc/engine/withdrawals.spec.ts, packages/vm/src/buildBlock.ts, packages/vm/src/runTx.ts, packages/vm/test/api/buildBlock.spec.ts, packages/vm/test/api/runTx.spec.ts
- Changes `engine_forkchoiceUpdatedV2` withdrawals parameter to `optional` to ensure we return the correct error message if a preShanghai payload is sent
- Adds some caching logic for pending payloads so as to prune pending block payloads once one is built and provided to the CL
- Modifies the logic for including transactions in a pendingBlock by using the pending block's hardfork (instead of the transaction hardfork since transactions are generally hardfork agnostic) when running the transaction in the VM to ensure that it can be executed and included in the block.
Targets Hive tests that can be run using this command:
`go run ./hive.go --client ethereumjs --sim ethereum/engine --sim.limit "engine-withdrawals/Withdrawals Fork on Block 2"`
=> withdrawals and transaction inclusion logic updates

packages/client/lib/net/server/rlpxserver.ts, packages/devp2p/scripts/singlePeerRun.ts, packages/devp2p/src/dpt/server.ts, packages/devp2p/src/rlpx/peer.ts, packages/devp2p/tsconfig.json, packages/devp2p/tsconfig.prod.json
Partly picking up things from #2535 (accidental merge)
This PR does the following:
- Removes (very) outdated Parity DPT ping/pong hack
- Improved devp2p HELLO logging message (added protocol version and client ID)
- Use client ID from Client for client HELLO message exchange (previously devp2p default ID was used)
Ready for review and merge, would be nice to still have this included in the releases since the client ID update is a somewhat prominent change.
=> Devp2p Improvements and Clean-Ups / Client ID Integration

packages/block/src/header.ts, packages/blockchain/src/blockchain.ts, packages/blockchain/test/customConsensus.spec.ts, packages/blockchain/test/index.spec.ts, packages/client/bin/cli.ts, packages/client/lib/blockchain/chain.ts, packages/client/lib/sync/skeleton.ts, packages/client/lib/types.ts
New fixes related to Hive tests
- Adds a new `--loadBlocksFromRlp` CLI parameter that allows for loading RLP encoded blocks on chain start that are fed via the `./chain.rlp` path in various Hive tests.  [Needed by the Hive tests](https://github.com/ethereum/hive/blob/master/docs/clients.md#files)
- Add better handling of reorgs that go pre-merge -- fixes hive tests run by this command - `go run ./hive.go --client ethereumjs --sim ethereum/engine --sim.limit "engine-transition/Single Block PoW Re-org to Higher-Total-Difficulty Chain, Equal Height"`
- Skip extradata check on PoW genesis blocks (since some Hive tests with PoW genesis parameters have `extradata` that does not conform to PoW extradata requirements
=> Various Hive related fixes

packages/client/lib/sync/beaconsync.ts, packages/client/lib/sync/fetcher/fetcher.ts, packages/client/lib/sync/fullsync.ts, packages/client/lib/sync/lightsync.ts, packages/client/test/sync/fetcher/fetcher.spec.ts
As encountered by @holgerd77 , fetcher (and client) would break on error handling because seemingly `errored` property of fetcher was conflicting with the `Readable` class from which fetcher extends causing such errors:
https://nodejs.org/api/stream.html#readableerrored
this fix renames the property to a non conflicting one which doesn't exit the client and keeps it going (forced error throw here to test)
=> Fix the fetcher errored property colliding with Readable class

packages/blockchain/test/index.spec.ts, packages/client/lib/sync/skeleton.ts
Fixes a logic bug related to reorg in skeleton sync where during a reorg that occurs during `fillCanonicalHead` where a skeleton subchain extends backwards passed the current canonical head block (due to a reorg scenario).
Currently, we reset the canonical head block on the chain to match the new skeleton block that we're putting in the chain when a reorg occurs via skeleton sync (i.e. the CL client reports our current head block in an FcU, then reports a different head block in the next FcU and then our client finds via the `ReverseFetcher` that the new head block announced in the FcU involves a reorg away from our current head block).  If that first skeleton block on the reorg chain is invalid for whatever reason, the chain's canonical head block is left as the original head's parent …
=> Fix invalid head block reset bug

packages/tx/package.json, packages/tx/src/utils/blobHelpers.ts
The latest release of `tx` breaks installs where `c-kzg` isn't also included because the `blobHelpers` file points to `c-kzg` instead of our own internal `kzg` interface.  This resolves the import breakage.
=> Fix kzg imports in `tx`

package-lock.json, packages/tx/package.json, packages/util/package.json
Revert ssz version to fix replaceAll error 
Closes #2554
ps: 
- https://github.com/ChainSafe/ssz/pull/309
=> Revert ssz version to fix replaceAll error

packages/client/lib/config.ts, packages/client/package.json
Makes the default transport in the client rlpx only for now since libp2p transport is only semi-functional and can lead to hard to debug port conflicts for code that is not currently being used
=> Turn off libp2p transport by default

README.md
=> v7 Release Monorepo README Branch Table Update

packages/evm/src/precompiles/06-ecadd.ts, packages/evm/src/precompiles/07-ecmul.ts
Replaces #1570
(second commit optimizations from the above PR already done along some subsequent jumpdest analysis/optimization work)
=> VM: bnadd/bnmul Precompile Performance Optimization

packages/evm/src/evm.ts, packages/evm/src/memory.ts, packages/vm/src/eei/vmState.ts
This cuts performance test 1 and 3 in roughly half by avoiding an additional buffer copy on memory read (so 0f0e2828c3eebe0c0f43378bb54784cb9b8df72c is the essential commit here). Additionally there are some more performance optimizations and debug logger enhancements included.
=> EVM: Memory Fix & Other Optimizations

packages/evm/src/evm.ts, packages/evm/src/precompiles/01-ecrecover.ts, packages/evm/src/precompiles/02-sha256.ts, packages/evm/src/precompiles/03-ripemd160.ts, packages/evm/src/precompiles/04-identity.ts, packages/evm/src/precompiles/05-modexp.ts, packages/evm/src/precompiles/06-ecadd.ts, packages/evm/src/precompiles/07-ecmul.ts, packages/evm/src/precompiles/08-ecpairing.ts, packages/evm/src/precompiles/09-blake2f.ts, packages/evm/src/precompiles/0a-bls12-g1add.ts, packages/evm/src/precompiles/0b-bls12-g1mul.ts, packages/evm/src/precompiles/0c-bls12-g1multiexp.ts, packages/evm/src/precompiles/0d-bls12-g2add.ts, packages/evm/src/precompiles/0e-bls12-g2mul.ts, packages/evm/src/precompiles/0f-bls12-g2multiexp.ts, packages/evm/src/precompiles/10-bls12-pairing.ts, packages/evm/src/precompiles/11-bls12-map-fp-to-g1.ts, packages/evm/src/precompiles/12-bls12-map-fp2-to-g2.ts, packages/evm/src/precompiles/14-kzg-point-evaluation.ts, packages/evm/src/precompiles/types.ts
This PR adds some extended logging to the EVM precompiles, WIP.
=> EVM: Precompile Debug Logger Improvements

packages/tx/src/eip1559Transaction.ts, packages/tx/src/eip2930Transaction.ts, packages/tx/src/eip4844Transaction.ts, packages/tx/src/legacyTransaction.ts, packages/tx/test/eip3860.spec.ts
See: https://github.com/ethereumjs/ethereumjs-monorepo/discussions/2569
We limit tx data size to MAX_INITCODE_SIZE (of EIP 3860) previously, but this should only be checked in a CREATE-transaction (to `to` field is empty, i.e. `undefined` or `null`). This PR fixes this.
I would like two people to verify / review this before merging.
Note: apparently we have either not tested this, or we have not joined testnets, or this is not covered by the EIP tests, which should be added/tested.
=> EIP3860: only check max init code size on create contract tx

packages/evm/src/memory.ts, packages/evm/src/opcodes/functions.ts, packages/evm/src/precompiles/04-identity.ts
This is a first cautious test to avoid copying memory buffers on `memory.read()` calls, realized by a new parameter `avoidCopy` which allows to directly return the memory slice in case there is no need for 0-filling.
First PR submit activates this for CREATE opcode to see what this will do to the tests, also generally direct read will likely have the biggest effect for these calling opcodes, since there potentially large chunks of data are read from memory.
=> EVM: Avoid memory.read() Memory Copy

packages/blockchain/src/blockchain.ts
This PR fixes `engine-api/Invalid Terminal Block in ForkchoiceUpdated`
To run in hive: 
`go run ./hive.go --client ethereumjs --sim ethereum/engine --sim.limit "engine-api/Invalid Terminal Block in ForkchoiceUpdated" --docker.output`
=> Hive: fix `engine-api/Invalid Terminal Block in ForkchoiceUpdated`

packages/client/lib/rpc/modules/engine.ts, packages/client/test/rpc/engine/forkchoiceUpdatedV1.spec.ts
This PR fixes:
`go run ./hive.go --client ethereumjs --sim ethereum/engine --sim.limit "engine-api/ForkchoiceUpdated Invalid Payload Attributes" --docker.output`
=> Client/engine: ensure payload attributes have a valid timestamp

packages/client/lib/rpc/modules/engine.ts
This PR fixes:
`go run ./hive.go --client ethereumjs --sim ethereum/engine --sim.limit 'engine-api/ParentHash==BlockHash' --docker.output`
`go run ./hive.go --client ethereumjs --sim ethereum/engine --sim.limit 'engine-api/Bad Hash on NewPayload' --docker.output`
=> Client/engine: ensure invalid blockhash status gets reported correctly

packages/client/lib/sync/snapsync.ts, packages/client/lib/sync/sync.ts, packages/client/lib/types.ts, packages/client/test/sim/simutils.ts, packages/client/test/sim/single-run.sh, packages/client/test/sim/snapsync.md, packages/client/test/sim/snapsync.spec.ts, packages/client/test/sync/snapsync.spec.ts
Setup to dev/test snapsync with sim architecture (The aim of this PR is to setup snapsync sim test/dev infra and not really resolve any snap sync issues which are to be addressed seprately)
tl-dr: run sim like this in build repo from packages/client (supply full path to your `DATADIR` in below command)
```bash
NETWORK=mainnet NETWORKID=1337903 ELCLIENT=geth ADD_EOA_STATE=true SNAP_SYNC=true DEBUG_SNAP=client:*  DATADIR=/usr/app/ethereumjs/packages/client/data npm run tape -- test/sim/snapsync.spec.ts
```
and see snap sync sim from geth peer:
In detail:
FROM: `test/sim/snapsync.md`:
1. Start external geth client:
```bash
NETWORK=mainnet NETWORKID=1337903 ELCLIENT=geth  DATADIR=/usr/app/ethereumjs/packages/client/data test
/sim/single-run.sh
```
2. (optional) Add some txs/state to geth …
=> Setup to dev/test snapsync with sim architecture

packages/client/lib/blockchain/chain.ts, packages/client/lib/execution/vmexecution.ts, packages/client/lib/rpc/modules/engine.ts, packages/client/lib/rpc/modules/eth.ts, packages/client/lib/rpc/validation.ts, packages/client/test/integration/miner.spec.ts, packages/client/test/rpc/engine/forkchoiceUpdatedV1.spec.ts, packages/client/test/rpc/helpers.ts
Add safe and finalized blockoptions to the chain
fix: `engine-api/Safe Re-Org to Side Chain`
Test is passing:
=> client: Add safe and finalized blockoptions to the chain

packages/client/bin/cli.ts, packages/client/lib/config.ts, packages/client/lib/execution/vmexecution.ts, packages/client/lib/net/peerpool.ts, packages/client/lib/types.ts
These are some small things I need for mainnet debugging respectively which are generally useful or improve/optimize on the CLI experience.
First thing is a new constanst MAX_TOLERATED_BLOCK time together with some appropriate logging for too slowly executed blocks. This is particulary helpful if things come to a halt with block execution generally going down to 30+ seconds subsequently (e.g. in some parts of the Shanghai dDoS blocks), but should also be generally valuable information along "normal" execution flows.
Second is a new config option `numBlocksPerIteration` which makes the previously statically set to 50 blocks option in VM execution customizable. Generally useful - before I always edited the code - in particular again in slow-execution phases.
Third thing is a small …
=> Client: Small Debug Helpers and CLI Improvements

packages/evm/src/opcodes/functions.ts, packages/vm/src/eei/journaling.ts, packages/vm/src/eei/vmState.ts, packages/vm/test/util.ts
Part of #1536
Extracted from #2578
PR switches to diff-based touched accounts checkpointing in the VM. This helps to solve the first of Shanghai dDoS attacks going into a recursive `DELEGATECALL` starting at block `2283416` (DAO HF) and repeated in subsequent block txs (with "normally" running blocks in between) and leading our client to crash with heap out of memory ("Javascript Ineffective mark-compacts near heap limit Allocation failed") (a bit in contrast to the attack in #1536 described by me as well as just stating the block execution getting very slow interestingly, not sure if we might have added additional (memory) weight here in the meantime. So this is on an 8GB Apple MacBook Air M1 machine) (I do know about this option to just increase the Node.js memory limit but I explicity …
=> VM: Diff-based Touched Accounts Checkpointing

packages/evm/src/evm.ts, packages/evm/src/interpreter.ts, packages/evm/test/eips/eip-3860.spec.ts, packages/tx/src/baseTransaction.ts, packages/tx/src/eip1559Transaction.ts, packages/tx/src/eip2930Transaction.ts, packages/tx/src/eip4844Transaction.ts, packages/tx/src/legacyTransaction.ts, packages/tx/src/types.ts, packages/tx/test/eip3860.spec.ts
Closes #2588 
This PR adds the `allowUnlimitedInitcodeSize` option. If EIP 3860 is disabled, this does nothing. If it is active, then this only disables the initcode length check, but it will still charge the initcode data gas cost.
This PR also somewhat refactors tx: in all of the tx types the same initcode size check is added, so it makes sense to move this into `baseTransaction`. (However, due to legacy transaction we do not have access to a common there, so either take this from the options or create the default one)
=> EVM+Tx: Add `allowUnlimitedInitcodeSize` option to partially disable EIP-3860

packages/vm/test/retesteth/clients/ethereumjs/config, packages/vm/test/retesteth/clients/ethereumjs/genesis/Shanghai.json, packages/vm/test/retesteth/clients/ethereumjs/genesis/correctMiningReward.json, packages/vm/test/retesteth/clients/version, packages/vm/test/retesteth/transition-child.ts, packages/vm/test/retesteth/transition-cluster.ts, packages/vm/test/util.ts
This PR:
- Ensures we run correctly on London+ hardforks. We always defaulted to base fee 7, while most tests have different base fee.
- Fixes EIP150 tests by ensuring if tx fails, coinbase account is still touched and cleaned up if necessary.
=> Add London+ hardfork support for Retesteth, fix EIP150 tests

package-lock.json, packages/block/karma.conf.js, packages/blockchain/karma.conf.js, packages/client/karma.conf.js, packages/common/karma.conf.js, packages/evm/karma.conf.js, packages/statemanager/karma.conf.js, packages/trie/karma.conf.js, packages/tx/karma.conf.js, packages/tx/package.json, packages/util/karma.conf.js, packages/util/package.json, packages/vm/karma.conf.js
Bumps `@chainsafe/ssz` to `0.11.0`. 
The current version of `@chainsafe/ssz` uses an AssemblyScript based SHA-256 implementation that causes issues on some platforms since it requires `WebAssembly` for execution (e.g. in sites or extensions with strict CSPs). 
This new version uses a pure JS implementation (`@noble/hashes`) as the default hasher for SHA-256 and should fix some of these aforementioned incompatibility issues.
For more context see: https://github.com/ChainSafe/ssz/issues/313
=> Bump `@chainsafe/ssz` to `0.11.0`

packages/blockchain/src/consensus/clique.ts, packages/blockchain/test/clique.spec.ts, packages/client/lib/miner/miner.ts
I added a test, which currently fails, it messes up the `_cliqueLatestSignerStates` somehow (after adding block 2, it adds a new signer to block 2, but also edits the signers of block 0?)
Note: we most likely have this problem with the "latest block signers", and the votes as well.
This PR currently allows to sync Goerli > 5476.
There is another problem with the current implementation: in case of a reorg, the active signers are all still remembered. However, if due to this reorg the signers at block X (where block X is now remembered of the previous change) change, this messes up the signer state internally. It should on reorg actually delete these signers above the block (need to investigate this claim though).
Note to self: local branch `clique-by-blocknum-new`
=> Clique: get signers by block num

packages/tx/src/eip4844Transaction.ts, packages/tx/test/eip4844.spec.ts
In the Uint8Array conversion a bug might have gotten  introduced for deserialization. This PR fixes that as well as ban zero blob tx
ref: 
- https://github.com/ethereum/EIPs/pull/6863
=> tx: Fix the deserialization of blob tx and add no empty blobs validation

package-lock.json, packages/block/package.json, packages/blockchain/package.json, packages/client/package.json, packages/devp2p/package.json, packages/devp2p/src/dpt/dpt.ts, packages/devp2p/src/rlpx/ecies.ts, packages/devp2p/src/rlpx/rlpx.ts, packages/devp2p/src/util.ts, packages/ethash/package.json, packages/evm/package.json, packages/statemanager/package.json, packages/trie/package.json, packages/tx/package.json, packages/util/package.json, packages/util/src/account.ts, packages/util/src/constants.ts, packages/util/src/signature.ts, packages/vm/package.json
rebased https://github.com/ethereumjs/ethereumjs-monorepo/pull/2639
=> Update ethereum-cryptography from 1.2 to 2.0

packages/client/lib/miner/pendingBlock.ts, packages/client/lib/rpc/modules/engine.ts, packages/client/test/miner/pendingBlock.spec.ts
Add proofs to blobsbundle and consequently to getblobsbundle engine api call so that CL doesn't need to compute proof which ideally would be coming packaged in the network wrapper serialized tx
ref:
- https://github.com/ethereum/execution-apis/pull/392
=> client: add proofs to blobsbundle

packages/statemanager/test/checkpointing.account.spec.ts, packages/statemanager/test/checkpointing.storage.spec.ts
This PR expands the StateManager checkpointing test suites, both for account and for storage checkpointing, with some stronger emphasis on the storage tests.
Two test cases failing at the moment (one is a double failure due to 2 consecutive runs), one failure with directly reading a storage slot saved to cache, one other involving an empty/non-empty storage slot write.
Still needs investigation and fixes.
=> Statemanager: Expand Checkpointing Tests

package-lock.json, packages/block/karma.conf.js, packages/blockchain/karma.conf.js, packages/client/karma.conf.js, packages/common/karma.conf.js, packages/evm/karma.conf.js, packages/statemanager/karma.conf.js, packages/trie/karma.conf.js, packages/tx/karma.conf.js, packages/tx/package.json, packages/util/karma.conf.js, packages/util/package.json, packages/vm/karma.conf.js
Bump `@chainsafe/ssz` to `0.11.1`.
This allows for removal of `karma` aliasing needed with the previous version of the package. See https://github.com/ChainSafe/ssz/pull/318
=> Bump `@chainsafe/ssz` to `0.11.1`

packages/client/test/sync/txpool.spec.ts, packages/common/src/chains/goerli.json, packages/common/src/chains/mainnet.json, packages/common/src/chains/sepolia.json, packages/common/src/common.ts, packages/common/test/chains.spec.ts, packages/tx/src/baseTransaction.ts, packages/vm/test/api/EIPs/eip-3860.spec.ts, packages/vm/test/api/index.spec.ts
Shift the default hf to Shanghai 
(build on top of #2652 ), would be rebased once 2652 merges
=> common: Make Shanghai the default hardfork

packages/block/src/block.ts
While running devnet5 ethereumjs started crashing on restarts with the error on genesis init
because genesis was not shanghai, but being past shanghai time it, the blockchain's/dbmanager's common was shanghai which was being passed in opts, but along with hardforkByBlock opts which was correctly setting hardfork for the header, but failing for block hf validations as it was not using the new updated and properly set header's hardfork
This PR fixes the bug
pre-devent5 genesis
- https://github.com/ethpandaops/4844-testnet/blob/skylenet/prep-devnet-5/network-configs/devnet-5/genesis.json#L17
This PR is based off on
- https://github.com/ethereumjs/ethereumjs-monorepo/pull/2655
and hence should be merged after the above merges
=> common: Fix the block's fromValuesArray common refernces

packages/block/test/testdata/4844-hardfork.json, packages/client/devnets/4844-interop/config/genesis.json, packages/client/devnets/4844-interop/lighthouse/genesis.json, packages/client/devnets/4844-interop/lighthouse/setup.sh, packages/client/devnets/4844-interop/prysm/genesisGEN.json, packages/client/devnets/4844-interop/prysm/prysm.json, packages/client/test/sim/configs/sharding.json, packages/client/test/testdata/geth-genesis/eip4844.json, packages/common/src/utils.ts, packages/common/test/timestamp.spec.ts
from devnet5 onwards the `shardingForkTime` is renamed to `cancunTime` in genesis.json
This PR is build on
- https://github.com/ethereumjs/ethereumjs-monorepo/pull/2657
pls rebase and merge when #2657 is merged!
devnet 5 genesi: 
- https://github.com/ethpandaops/4844-testnet/blob/skylenet/prep-devnet-5/network-configs/devnet-5/genesis.json#L17
=> common: Rename shardingForkTime to cancunTime

packages/block/test/eip4844block.spec.ts, packages/client/devnets/4844-interop/tools/txGenerator.ts, packages/client/lib/rpc/modules/engine.ts, packages/client/test/miner/pendingBlock.spec.ts, packages/client/test/rpc/engine/getPayloadBodiesByHashV1.spec.ts, packages/client/test/rpc/engine/getPayloadBodiesByRangeV1.spec.ts, packages/client/test/rpc/engine/getPayloadV3.spec.ts, packages/client/test/rpc/eth/getTransactionReceipt.spec.ts, packages/client/test/rpc/eth/sendRawTransaction.spec.ts, packages/common/docs/enums/Hardfork.md, packages/common/src/chains/goerli.json, packages/common/src/chains/mainnet.json, packages/common/src/chains/sepolia.json, packages/common/src/eips/4844.json, packages/common/src/enums.ts, packages/common/src/hardforks/cancun.json, packages/common/src/hardforks/index.ts, packages/common/src/hardforks/sharding.json, packages/common/src/utils.ts, packages/evm/src/evm.ts, packages/evm/test/precompiles/14-pointevaluation.spec.ts, packages/evm/test/runCall.spec.ts, packages/tx/test/eip4844.spec.ts, packages/vm/test/api/runTx.spec.ts
With Cancun hf shaping up nicely, this PR updates the references of the hf to `Cancun` (corresponding CL hf `Deneb`)
=> common: Rename shardingForkDev hf to Cancun

packages/blockchain/src/blockchain.ts, packages/blockchain/src/db/manager.ts, packages/blockchain/test/util.ts, packages/ethash/src/index.ts
Switches the handling of uint8Arrays nested inside JSON objects put in the DB to store as hex strings since LevelDB incorrectly converts these uint8Arrays to nested JSON objects and reassembling the Uint8Array is slower than converting to and from hex strings.
=> Fix handling of nested uint8Arrays in JSON in DB

packages/client/lib/miner/miner.ts, packages/client/lib/miner/pendingBlock.ts, packages/client/lib/rpc/modules/eth.ts, packages/client/lib/service/txpool.ts, packages/client/test/miner/pendingBlock.spec.ts
Currently ethereumjs can pack more than allowed blobs into a block which causes block rejection by the CL.
This is rectified by enforcing the allowed blobs limit while picking transactions for building a block.
TODO:
=> client: Limit blobs as per the maxDataGasPerBlock for block building

package-lock.json, packages/client/bin/cli.ts, packages/client/lib/config.ts, packages/client/lib/execution/vmexecution.ts, packages/client/lib/types.ts, packages/trie/package.json, packages/trie/src/db/checkpoint.ts, packages/trie/src/trie/trie.ts, packages/trie/src/types.ts, packages/trie/test/db/checkpoint.spec.ts, packages/trie/test/index.spec.ts
This PR adds a permanent Node cache to the Trie checkpoint DB class which increases client block execution in particular and repetitive trie reads in general.
Cache design is extremely simple since trie node keys are unique, so there is no need for this back-and-forth related to checkpointing, since there is no risk to overwrite and old entry and therefore accidentally introduce a wrong key. I tested this with longer client sync ranges and there were no problems.
It is also "by design" that reverted node entries are kept in the cache, since this might help to mitigate repeated revert-attacks with the same attack setup, always re-reading the same accounts/slots e.g. and then revert.
I in-between planned to activate this LRU cache by default, since in most cases there should be no …
=> Trie/Client: Add permanent Trie Node Cache + Client Integration

packages/statemanager/src/cache/account.ts, packages/statemanager/src/cache/storage.ts
Replace `OrderedMaps` in account and storage `diffCache` with pure JS maps.  Appears to have a small performance gain (as well as readability improvements).
Can use a script like this to validate performance:
```
import { Address } from '@ethereumjs/util'
import { randomBytes } from 'crypto'
import { createAccount } from '../../test/util'
import { AccountCache } from './account'
import { CacheType } from './types'
const samples = 10000
const accountCache = () => {
const cache = new AccountCache({ type: CacheType.LRU, size: 10000 })
for (let x = 0; x < samples; x++) {
const address = Address.fromPrivateKey(randomBytes(32))
const account = createAccount(undefined, 1n)
cache.get(address)
cache.put(address, account)
if ((x ^ 10) === 0) {
cache.checkpoint()
}
if ((x ^ 20) === 0) { …
```
=> Use JS maps in cache

package-lock.json, packages/client/bin/cli.ts, packages/client/lib/client.ts, packages/client/lib/config.ts, packages/client/lib/execution/execution.ts, packages/client/lib/execution/vmexecution.ts, packages/client/lib/rpc/modules/eth.ts, packages/client/lib/service/ethereumservice.ts, packages/client/lib/service/fullethereumservice.ts, packages/client/lib/types.ts, packages/client/package.json, packages/client/test/cli/cli-libp2p.spec.ts, packages/client/test/cli/cli-sync.spec.ts, packages/client/test/integration/beaconsync.spec.ts, packages/client/test/integration/fullsync.spec.ts, packages/client/test/integration/lightsync.spec.ts, packages/client/test/integration/merge.spec.ts, packages/client/test/integration/miner.spec.ts, packages/client/test/rpc/eth/getTransactionByHash.spec.ts, packages/client/test/rpc/eth/syncing.spec.ts, packages/client/test/rpc/helpers.ts, packages/client/test/service/fullethereumservice.spec.ts
Ok, this PR now starts with some low-level things to ease respectively improve (aka: speed up) "execution mode", so to catch up with execution if things are behind.
It does so by:
- Allowing to disable transports (actually by updating the Yargs version, `--transports` didn't work as expected before)
- Allowing to completely disable sync (`syncMode` option also renamed to `sync` since easier to write, new option `none`, so now: `--sync=full` (normally not used), `sync=none`)
So this allow to run the client with:
```shell
npm run client:start -- --transports --sync=none
```
Haven't explicitly tested execution speed-up, since at the end it doesn't really matter for this PR, think it's generally good to have at least these possibilities from above, independtly from the purpose. Should help …
=> Client short-term "Execution Mode" Mitigations

packages/tx/src/legacyTransaction.ts
When preparing Ethereum data for RLP encoding, you must convert all values to either byte arrays or lists.  Scalar values (positive integers) are converted to byte arrays by using the fewest bytes possible to represent the value in big endian format.  The canonical form of any scalar value prepped for RLP encoding is that any leading `0` bytes stripped.  In the case of `0`, this means that the only byte (`0x00`) is stripped and you are left with an empty array.
Most of the values in this code are properly 0-stripped using `bigIntToUnpaddedBuffer`.  Unfortunately, it appears that the `chainId` was added without stripping leading zeros.  In most cases this doesn't matter, but if someone is running a chainId 0 blockchain and they want to EIP-155 encode their transaction, the previous code …
=> tx: Fix EIP-155 transaction encoding on chain ID 0.

package-lock.json, packages/block/README.md, packages/block/package.json, packages/block/src/block.ts, packages/block/test/from-rpc.spec.ts, packages/block/test/mockProvider.ts, packages/client/test/net/peer/libp2pnode.spec.ts, packages/client/test/net/peer/libp2ppeer.spec.ts, packages/client/test/net/peerpool.spec.ts, packages/client/test/net/server/libp2pserver.spec.ts, packages/devp2p/test/dns.spec.ts, packages/evm/package.json, packages/statemanager/test/ethersStateManager.spec.ts, packages/tx/README.md, packages/tx/package.json, packages/tx/src/transactionFactory.ts, packages/tx/test/fromRpc.spec.ts, packages/tx/test/mockProvider.ts, packages/util/src/index.ts, packages/util/src/provider.ts, packages/util/test/provider.spec.ts
This PR, when complete, will replace the `fromEthersProvider` static constructors in `block` and `tx` with a more generalized `fromJsonRpcProvider` constructor that will take the URL string for a JSON-RPC provider and then fetch the corresponding block or tx from the provider using native `fetch` or `http` request and will also remove the` micro-ftch` dependency which requires several polyfills in a browser/webpack context (i.e. `zlib-browserify`,`https-browserify`, and `stream-http`).
=> Migrate `fromEthersProvider` to `fromJsonRpcProvider` constructors

packages/client/bin/cli.ts, packages/client/karma.conf.js, packages/client/lib/config.ts, packages/client/lib/execution/execution.ts, packages/client/lib/execution/vmexecution.ts, packages/client/lib/service/fullethereumservice.ts, packages/client/lib/sync/beaconsync.ts, packages/client/lib/sync/fullsync.ts, packages/client/lib/types.ts, packages/client/lib/util/index.ts, packages/statemanager/src/stateManager.ts, packages/statemanager/test/stateManager.account.spec.ts, packages/statemanager/test/statemanager.spec.ts, packages/trie/src/trie/trie.ts, packages/trie/test/trie/checkpoint.spec.ts
Memory optimizations for the client and in general, can either be directly merged or used as a base for additional pushes, don't really care, what fits better.
=> Client Memory Optimizations

packages/client/bin/cli.ts
It may take client a little while to fully start and bootstrap its services (especially if there are pending blocks to be executed). If SIGINT/CTRL + C comes before that, client may end up in an unclean shutdown
This PR hooks up shutdown handler as soon as client is started, and also makes sure client is properly started before initiating a clean shutdown:
PS: Build on top of client memory optimizations PR and is pointing to that branch
- https://github.com/ethereumjs/ethereumjs-monorepo/pull/2675
So pls rebase and merge afterwards 2675 is merged and with the base branch of this PR updated to `develop-v7`
=> client: Fix unclean shutdown scenario where SIGINT may come before client fully started

packages/blockchain/src/blockchain.ts, packages/client/lib/execution/vmexecution.ts, packages/client/lib/util/debug.ts
On further debugging and testing another case of `vmHead` corruption was observed:
1. client was executing 749796-749896 range but got an interrup signal and 749890 failed
2. next time client started vmHead was already updated to 749896 and execution started from block 749897 which obviously would fail
The synopsis of the issue:
In vmExecution  iterator, block error was being ignored leading to incorrect vmHead forward movement. So the right thing to do was to throw error. 
However in blockchain,  iterator head was not being properly saved to last successfully executed if `onBlock` callbacks errored. 
This PR addressed both the issues and also moves out iterator error handling out side of the vm iterator callback for further simplicity.
=> blockchain: Save iterator head to last successfuly executed even on errors

packages/client/test/sim/4844-devnet-5.md, packages/client/test/sim/4844.md, packages/client/test/sim/4844devnet5.spec.ts, packages/client/test/sim/sharding.spec.ts, packages/client/test/sim/simutils.ts, packages/tx/src/baseTransaction.ts
A blob tx gen utility for seeding devnet5 (or subsequent devnets/testnests with blobs)
how to run:
1. Clone the repo set to branch `develop-v7` and run `npm i` with nodejs `18` installed and latest npm version
2. Run the blob gen utility (replace PRIVATE_KEY with a funded account private key and RPC_URL with an authenticated rpc url):
```typescript
cd packages/client
PRIVATE_KEY=ae557af4ceefda559c924516cabf029bedc36b68109bf8d6183fe96e04121f4e RPC_URL=https://rpc.lodestar-ethereumjs-1.srv.4844-devnet-5.ethpandaops.io npm run tape -- test/sim/4844devnet5.spec.ts
```
It runs with current chainId of `4844001005`, if you want to override pass `CHAIN_ID=` env param in above command
currently it posts 2 txs, but that can be modified with another env variable `NUM_TXS`
You can manipulate the fees …
=> client: Add 4844 devnet5 blob post utility

packages/evm/src/interpreter.ts
While matching op code trace of ethereumjs with the geth it was observed that ethereumjs's gasCost logs were incorrect w.r.t the actual gas used by the opcode.
This was happening because the dynamicFee should be the one to be logged which is the actual gas consumed by the opcode 
Post this the gasCost mismatch diff with geth greatly reduced and the `0` gasCost entries disappeared from the trace
=> evm: Fix the gasCost logs in op code trace

packages/trie/README.md, packages/trie/docs/classes/Trie.md, packages/trie/test/index.spec.ts
This PR updates old references to the deleteFromDB trie constructor arg, which was replaced in favour of `useNodePruning` in #2203
=> trie: update references to old deleteFromDB constructor arg

package-lock.json, packages/statemanager/src/ethersStateManager.ts
Updates the `ethersStateManager` to use the newly implemented `storageCache` instead of the custom JS Map we were using before.
=> Use `storageCache` in `ethersStateManager`

packages/client/bin/cli.ts, packages/client/lib/logging.ts, packages/client/lib/types.ts, packages/client/test/logging.spec.ts
Most if not all clients have this as default policy:
- info logs on stdout
- debug logs on file with filerotate
The default enabling of debug logs help in retrospective debugging even if the user forgets to enable logging. This PR enables the same and fixes a previous issue of `--logFile true` not working which according to help should have logged to `ethereumjs.log`
=> client: Enable default debug logging to file

eslint/package.json, package-lock.json
This PR provides a tentative fix for the issue below that a user has run into.
```
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path D:\Workspace\ethereumjs-monorepo\eslint/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'D:\Workspace\ethereumjs-monorepo\eslint\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```
=> eslint: add eslint package.json

packages/blockchain/src/blockchain.ts, packages/common/src/common.ts, packages/common/src/eips/4399.json, packages/common/src/hardforks/chainstart.json, packages/common/test/hardforks.spec.ts, packages/evm/src/opcodes/codes.ts, packages/evm/src/opcodes/functions.ts, packages/evm/src/opcodes/gas.ts, packages/evm/test/opcodes.spec.ts, packages/vm/test/util.ts
Deprecation cleanup work for the upcoming breaking releases.
Will track the changes in the following list:
- Common: remove deprecated `nextHardforkBlock()`, `isNextHardforkBlock()` and `isHardforkBlock()` methods
- Blockchain: remove deprecated `getHead()` method
- EVM: rename SHA3 opcode -> KECCAK256
- EVM: rename DIFFICULTY opcode to PREVRANDAO post Merge
=> Monorepo: Deprecation Cleanup Work

packages/tx/src/baseTransaction.ts, packages/tx/src/eip1559Transaction.ts, packages/tx/src/eip2930Transaction.ts, packages/tx/src/eip4844Transaction.ts, packages/tx/src/legacyTransaction.ts, packages/tx/test/eip1559.spec.ts, packages/tx/test/typedTxsAndEIP2930.spec.ts
While sharing a block via json with @acolytec3 it was noticed that jsons didnt have type info in many instances, althrough one could interpret the json type via other fields, but a more verbose `type` can certainly help in easy identification. 
This PR aims to add normalized base transaction json fields in every toJson as well as removes some serialization redundancy of these common fields
Also fixes `versionedHashes` serialization which didn't have prefixed 0x
=> tx: Normalize toJson for different tx types

packages/statemanager/test/ethersStateManager.spec.ts, packages/tx/src/fromRpc.ts, packages/tx/src/transactionFactory.ts, packages/tx/test/fromRpc.spec.ts, packages/tx/test/json/v0tx.json
In https://github.com/ethereumjs/ethereumjs-monorepo/pull/2613 I "solved" decoding the optimism system txs wich v=0, but forgot that EIP2930 or EIP1559 have 50% chance to have v=0 as well. If we then set v=undefined, then these txs are suddenly unsigned while they clearly are. Test included.
Also renames `fromRPCTx` -> `fromRPC` in line with the Block lib.
=> tx: ensure rpc txs are correctly decoded for v=0

packages/client/lib/rpc/modules/engine.ts, packages/client/test/rpc/engine/newPayloadV3VersionedHashes.spec.ts
Post blob tx conversion to RLP, CL's commitments check via versioned hashes is now passed over to EL with new payloads having the computed CL versioned hashes.
Implements:
- https://github.com/ethereum/execution-apis/pull/407
This PR implements the same
Depends on 
- https://github.com/ethereumjs/ethereumjs-monorepo/pull/2708
and should be merged (post rebase) after #2708 is merged
=> client: Extend newPayloadV3 for blob versioned hashes checks

package-lock.json, packages/evm/package.json
Updates `rustbn.js` to v0.3.0 and removes a hack in `node_modules` required to pass in hex strings.
=> Update `rustbn.js` to latest

docker/docker-compose.yml
Running `docker-compose up` was resulting with `Unknown argument: datadir` because `datadir` should be spelled as `dataDir` for `@ethereumjs/client v0.7.1`.
=> fix unknown argument error

packages/wallet/package.json
Solves https://github.com/ethereumjs/ethereumjs-monorepo/issues/2731 Updated dependencies of ethereum-cryptography to v2.0.0
=> Updated  ethereum-cryptography to ^2.0.0

packages/blockchain/src/types.ts, packages/client/src/execution/vmexecution.ts, packages/client/test/execution/vmexecution.spec.ts, packages/client/test/rpc/helpers.ts, packages/vm/src/runBlock.ts
On the 4844 devnet5 a weird error was noticed:
1. on new payload the client runs `vmExecution.runWithoutSetBlock` first and 
2. then on fcU once the block is part of canonical chain it runs `vmExecution.run` which runs block in an iterator loop
Run on 1. gives `VALID` execution while 2nd fails with `invalid state root`
This PR aims to solve it:
Synopsis of the issue: the vmExecution's `run` and `runWithoutSetHead` can end up running the same block one after another leading to state manager's incorrect caches
This PR updates `clearCache` flag in runBlock if such a scenario comes up during client execution.
PS:
the issue is resolved with this diff which might give an idea about where the problem could be i.e. by running the block again in the `vm` copy of vmexecution
```diff
--- …
```
=> client: Fix double runs of the block execution

packages/vm/test/tester/config.ts, packages/vm/test/util.ts
This small update ensures we can run tests which have an alias, plus EIP numbers, in our test runner.
Example to run the TSTORE tests:
```
cd ./packages/vm
npm run test:blockchain -- --fork=Paris+1153 --dir=../EIPTests
```
Without this PR you are unable to run the tests, since test runner converted `Paris+1153` to `Merge` before and will thus run the Merge tests, and not the `Merge+1153` tests which are the TSTORE tests.
=> vm/tests: ensure tests with aliases run with eip configs

packages/client/src/net/peer/peer.ts, packages/client/src/net/peerpool.ts, packages/client/src/net/protocol/boundprotocol.ts, packages/client/src/net/server/rlpxserver.ts, packages/client/src/service/ethereumservice.ts, packages/client/test/net/server/rlpxserver.spec.ts, packages/client/tsconfig.prod.cjs.json, packages/devp2p/src/rlpx/rlpx.ts
This fixes a memory leak in the client being triggered when a peer is banned who is then sending continued messages to our client. These messages are the not answered but added to the `messageQueue` in `BoundProtocol`. If the other client is staying connected and continues to send messages (which happens in practice) `messageQueue` is growing indefinitely.
I have tested that the functionality both triggers and is not breaking anything by adding `console.log()` output to both the `server.ban()` method in the client and the then executed `rlpx.disconnect()` method in devp2p, see screenshot above, and then waiting for a respective event to trigger during client run.
I have also added a general reasonable guard for `messageQueue` to generally avoid this list to grow without bounds.
Ready for …
=> Client: Fix PeerPool Memory Leak

packages/block/src/types.ts
This adds a missing 4844 txData type to the block `transactions` type
=> block: add missing tx type

packages/client/src/miner/miner.ts, packages/client/src/miner/pendingBlock.ts, packages/client/src/net/protocol/ethprotocol.ts, packages/client/test/miner/pendingBlock.spec.ts, packages/vm/src/buildBlock.ts
makes sure that a block is not build with missing blobs (i.e. from non network wrapper tx)
TODO:
~~- [ ] ensure same in gossip~~ TO be dealt in a different PR after discussion
=> vm: Discard blob txs with missing blobs for block building

packages/blockchain/src/consensus/clique.ts, packages/blockchain/src/consensus/ethash.ts, packages/blockchain/src/utils.ts, packages/blockchain/test/util.ts, packages/client/src/blockchain/chain.ts, packages/client/src/config.ts, packages/client/src/sync/fetcher/accountfetcher.ts, packages/client/src/sync/fetcher/blockfetcherbase.ts, packages/client/src/sync/fetcher/bytecodefetcher.ts, packages/client/src/sync/fetcher/storagefetcher.ts, packages/client/src/util/parse.ts, packages/client/src/util/rpc.ts, packages/client/test/integration/util.ts, packages/statemanager/src/ethersStateManager.ts, packages/tx/src/eip1559Transaction.ts, packages/tx/src/eip4844Transaction.ts
This PR removes ~15 instances of `any` typecasting when unnecessary, by either replacing them with more precise typecasting or removing them completely.
=> monorepo: remove instances of `any` typecasting 

packages/tx/src/baseTransaction.ts, packages/tx/src/eip1559Transaction.ts, packages/tx/src/eip2930Transaction.ts, packages/tx/src/eip4844Transaction.ts
Addresses the issue that was brought up in this comment: https://github.com/ethereumjs/ethereumjs-monorepo/pull/2767#discussion_r1226359471
=> tx: remove default hardfork from tx classes

packages/block/test/eip4844block.spec.ts, packages/block/test/from-beacon-payload.spec.ts, packages/client/test/miner/pendingBlock.spec.ts, packages/common/src/eips/4844.json
ref to updated devnet 6 specs:
- https://github.com/ethereum/EIPs/pull/7154
TODO:
=> common: update the blob target and limit to 3/6 respectively

packages/client/src/rpc/modules/engine.ts, packages/client/test/rpc/engine/newPayloadV3VersionedHashes.spec.ts
Another discovery from devnet-6 test runs:
The verifying of excessDataGas/4844 validations were not fully happening in new payload because of requirement of parent, which in our normal flow would happen once we do a putBlock into chain (which happens in fcU update)
This PR performs those validations
=> client: fix new payload 4844 validations

packages/client/src/execution/level.ts, packages/trie/src/db/checkpoint.ts, packages/trie/src/trie/trie.ts, packages/util/src/db.ts, packages/util/src/mapDB.ts, packages/util/test/mapDB.spec.ts
The current implementation of the `copy` function of the `DB` interface does not create a new underlying db but rather reuses the same db of the original object being copied. This PR renames the `copy` function to `shallowCopy` in order to reflect this behavior and make it's name more intuitive and less confusing.
=> util: Rename mapdb copy function

packages/vm/package.json
Fixes the `test:API` script so it picks up all tests in the `test/api` directory.
=> Fix `npm run test:API` script

config/cli/ts-build.sh
Adds a step in the build process for adding `assert {type: "json"}` to our JSON imports in the ESM build outputs
=> Add json type assertions to ESM post build fixes

packages/vm/test/retesteth/transition-child.cts, packages/vm/test/retesteth/transition-child.ts, packages/vm/test/retesteth/transition-cluster.cts
WIP. And this is likely temporary since if we switch tests to `import x from foo.js` then it will likely start to fail too.
=> Fix retesteth runner

packages/blockchain/src/blockchain.ts, packages/common/src/types.ts, packages/common/src/utils.ts
To test latest hivecancun tests (@ https://github.com/ethereum/hive/commits/fb7ea843fb3935cd49197597a0454691b6a58820 ) : 
```
git remote add spencer-tb git@github.com:spencer-tb/hive.git
git fetch spencer-tb
git checkout fb7ea843fb3935cd49197597a0454691b6a58820
```
Or branch: [hive-cancun-devnet7](https://github.com/spencer-tb/hive/compare/hive-cancun-devnet7)
Run hive:
```
./hive --sim pyspec --sim.limit "pyspec/cancun" --client ethereumjs --docker.output
```
(limits to Cancun tests, remove `sim.limit` to run all pyspec tests since there are also shanghai -> cancun fork tests)
Example command to filter one test and get more output:
```
./hive --sim pyspec --sim.limit "pyspec/cancun/eip4844_blobs/blob_txs/blob_tx_attribute_calldata_opcodes/003-fork=Cancun-tx_gas=500000-single_byte-opcode=C …
```
=> Common: Fix genesis parsing for 4844

package-lock.json, packages/client/src/rpc/modules/debug.ts, packages/evm/package.json, packages/evm/src/precompiles/06-ecadd.ts, packages/evm/src/precompiles/07-ecmul.ts, packages/evm/src/precompiles/08-ecpairing.ts, packages/util/src/bytes.ts, packages/util/test/bytes.spec.ts
This PR adds an extra guard to the proxy `hexToBytes` from `ethereum-cryptography`. That method supports both prefixed and unprefixed hex strings. The new (deprecated) `unprefixedHexToBytes` now explicitly only accepts unprefixed hex strings.
(Tests seem to pass locally so ready for review)
Follow up of #2845
=> util/bytes: make unprefixedHexToBytes specific

packages/block/test/header.spec.ts, packages/common/test/hardforks.spec.ts, packages/common/test/timestamp.spec.ts, packages/evm/test/precompiles/0a-pointevaluation.spec.ts, packages/evm/test/runCall.spec.ts, packages/statemanager/test/proofStateManager.spec.ts, packages/statemanager/test/stateManager.account.spec.ts, packages/statemanager/test/statemanager.spec.ts, packages/tx/test/eip4844.spec.ts, packages/tx/test/transactionFactory.spec.ts, packages/vm/test/api/EIPs/eip-2930-accesslists.spec.ts, packages/vm/test/api/index.spec.ts, packages/wallet/test/index.spec.ts
This PR fixes several errors that were showing up when running `npm run tsc --workspaces`. Likely a side-effect of some of the recent changes.
=> monorepo: fix tsc errors

packages/evm/src/evm.ts, packages/evm/src/types.ts
Note: static `create` will be removed if we remove mcl-wasm
=> evm: rename EVMOpts -> EVMCreateOpts

packages/evm/src/evm.ts, packages/evm/src/types.ts
The original PR #2861 changed `EVMOpts` -> `EVMCreateOpts` (in two places, for both the constructor EVM as the argument type for `runCall` and `runCode`)
Now, the constructor argument for EVM is `EVMCreateOpts`. The runtime arguments are now `EVMRunCallOpts` and `EVMRunCreateOpts`, which have a base type which it extends: `EVMRunOpts`.
@holgerd77 If wanted I can also revert the `EVMCreateOpts` (so EVM constructor argument type) back to `EVMOpts`. (But, I think this type name is slightly more clear)
=> evm/types: rename EVMCreateOpts -> EVMRunOpts

packages/common/src/common.ts, packages/util/src/constants.ts, packages/util/src/internal.ts
Replaces one default export with a named export (to help with bundler compatibility) and also adds two missing file extensions to internal imports to `util/bytes`
=> Fix imports

package-lock.json, packages/statemanager/examples/browser.html, packages/statemanager/src/ethersStateManager.ts, packages/statemanager/test/ethersStateManager.spec.ts, packages/statemanager/test/testdata/providerData/mockProvider.ts
Updates the `EthersStateManager` API and caching logic:
1. Updates `putAccount` to match `DefaultStateManager` API for deleting an account where `account` parameter is not provided
2. Updates `revert` logic to revert the storage cache and clear the `contractCache`
3.  Adds new tests to validate `revert` logic changes
4. Updates `MockProvider` API to deal with ethers `JsonProviderRpc` batched request logic
=> Update `EthersStateManager` 

.github/workflows/browser.yml, config/eslint.cjs, packages/client/.eslintrc.cjs, packages/common/test/utils.spec.ts, packages/devp2p/src/dns/dns.ts, packages/evm/package.json, packages/evm/test/eips/eip-5656.spec.ts, packages/genesis/.eslintrc.cjs, packages/genesis/.eslintrc.js, packages/genesis/src/genesisStates/goerli.ts, packages/genesis/src/genesisStates/mainnet.ts, packages/genesis/src/genesisStates/sepolia.ts, packages/genesis/src/index.ts, packages/genesis/test/index.spec.ts, packages/util/test/genesis.spec.ts, packages/vm/.eslintrc.cjs
Three things this PR does:
- Turns on the `import/extensions` rule in `eslint` for all packages except `client` and `vm` where we are still running a lot of CJS code (i.e. the entire `client` package and the test runner in `vm`).
- Fix `eslint` setup in the new `genesis` package so it actually runs and fixes various lint issues identified there.
- All lint fixes identified by this new rule
- Pulls in browser CI fixes from #2824
=> Update eslint config with file extensions rule

packages/genesis/src/index.ts, packages/genesis/test/index.spec.ts, packages/vm/test/api/genesis.spec.ts
This PR fixes a small inconsistency with the genesis package API I discovered while writing release notes. So the example I added as a test now would break before, because the `getGenesis()` API would give either `GenesisState` or `null` while the other `genesisState` input APIs in VM and Blockchain would take `GenesisState` or `undefined`.
This didn't play well together on the type level and so the example would break.
PR fixes this.
=> VM/genesis: Fix small genesis API inconsistency

packages/client/src/blockchain/chain.ts, packages/client/src/config.ts, packages/client/src/execution/vmexecution.ts, packages/client/src/rpc/modules/engine.ts, packages/client/test/rpc/engine/forkchoiceUpdatedV1.spec.ts, packages/client/test/rpc/engine/getPayloadV1.spec.ts, packages/client/test/rpc/engine/getPayloadV3.spec.ts, packages/client/test/rpc/engine/newPayloadV1.spec.ts, packages/client/test/rpc/engine/newPayloadV2.spec.ts, packages/client/test/rpc/engine/newPayloadV3.spec.ts, packages/client/test/rpc/engine/withdrawals.spec.ts
fix and optimize the block execution for engine's new payload and fcUs, supersedes https://github.com/ethereumjs/ethereumjs-monorepo/pull/2787
- chain head was being used for getting `vmHead` instead of the actual `vm` head
- optimize and correct checks if the parent(s) have been executed (track and use `executedBlocks` ) 
- recursively find parents would only find just 1 parent, `vmHead` hash should have been used as its used to find parents till `vmHead`
- add `executedBlocks` map in engine for easy figuring out what has been executed (rather than checking `stateRoot` in state manager because a bad block can be formed with previously executed `stateRoot` which would of course be declared valid) ,
- and better pruning of `executedBlocks` and `remoteBlocks` based on `finalized` and `vm` …
=> client: improve new payload and fcu block executions

packages/client/src/rpc/modules/engine.ts
for devnet-8
- https://github.com/ethereum/execution-apis/pull/425
=> client: add shouldOverrideBuilder flag for getPayloadV3

packages/block/README.md, packages/blockchain/CHANGELOG.md, packages/blockchain/README.md, packages/client/libp2pBrowserBuild/net/package.json.browser.deps, packages/client/package.json, packages/common/README.md, packages/devp2p/CHANGELOG.md, packages/devp2p/README.md, packages/ethash/README.md, packages/evm/CHANGELOG.md, packages/evm/README.md, packages/evm/package.json, packages/statemanager/README.md, packages/trie/README.md, packages/tx/README.md, packages/util/README.md, packages/vm/CHANGELOG.md, packages/vm/README.md, packages/vm/package.json
Follow-up on #2876 
Small release clean-up round including an additional EVM RC.2 release (+ upstream version updates) since RC.1 was broken (missing StateManager dependency).
=> Small RC1 Release Cleanup Round

packages/client/src/rpc/modules/engine.ts, packages/client/src/rpc/validation.ts, packages/client/test/rpc/engine/getPayloadV3.spec.ts, packages/client/test/rpc/engine/newPayloadV3.spec.ts, packages/client/test/rpc/engine/newPayloadV3VersionedHashes.spec.ts
pending tasks to make client devnet 8 compatible
- fcu v3
- change validations of newpayload v3 and make them 1-1
Could have further changes depending on the acceptance of 
- https://github.com/ethereum/consensus-specs/pull/3454
=> client: apply engine api changes for devnet 8

packages/client/test/integration/fullsync.spec.ts
The `fullsync` integration test routinely timeouts so experiments with extending that test timeline to see if this resolves the issue.
=> Extend fullsync test timeout

packages/client/test/sim/snapsync.md
Update instructions for running tests to use vitest instead of tape.
=> Update instructions for running snap sync sim tests

packages/client/src/net/protocol/boundprotocol.ts
This PR fixes a hive test (on top of #2935 which fixes another related timeout problem) where this happens:
There are two clients. These both gets fed messages and it is necessary that upon creating new blocks the peers have exchanged all messages. The block builder client (1) has a race condition without this PR. Here is what happens:
Client (1) gets multiple `NewPooledTransactionHashes` (5 in total, over 5 messages). Therefore, client (1) requests 5 `GetPooledTransactions`. However, at some point client (1) is already requesting a pooled tx without getting a response, and then queries a new `GetPooledTransactions`. Prior to this PR this is not possible because there is only ONE request possible per devp2p message type. This PR has a temporary fix: we now create a Lock for every message …
=> client: add support for multiple same-type messages over devp2p

packages/block/src/block.ts, packages/block/src/header.ts
The problem this fixes is that we first validate the blob transactions (this calls into fake_exponential) and then validate the excess blob gas. This is problematic, because if the excess blob gas check is incorrect it calls with very large numbers into fake_exponential, essentially an infinite loop.
This also optimizes the blob gas price calculation: this is constant, but we calculated it for each blob tx before.
=> Fix block validation order for EIP4844

packages/trie/src/node/util.ts, packages/trie/src/proof/range.ts, packages/trie/src/trie.ts
This PR makes a few minor improvements to the trie library util types.
- Improves the `isRawNode` util into a typeguard, which removes the need for typecasting in some instances.
- Slightly simplifies the logic of the `lookupNode` and `decodeNode` methods
=> trie: improve util types and handling

packages/devp2p/src/ext/kbucket.ts
in the kbucket implementation the dontSplit attribute of KBucketNode is typed as bool, but was checked wit "!== undefined" which always was true. This caused KBucket.add to never split the leaf node and therefore kept the kbucket as a single level tree with a maximum of _numberOfNodesPerKBucket entrys in total.
tiny modification with huge impact :D
=> fixed kademlia kbucket add

packages/common/src/utils.ts
Fixes: 
`./hive --sim "ethereum/engine" --client ethereumjs --sim.parallelism 16 --sim.limit="engine-cancun/Request Blob Pooled Transactions"`
If fork is at timestamp genesisTimestamp then this fork is supposed to be active at timestamp = 0 and not participate in the forkHash calculation of the devp2p/ETH STATUS message.
See also:
https://github.com/hyperledger/besu/issues/5744
https://github.com/ethereum/go-ethereum/pull/27895
https://eips.ethereum.org/EIPS/eip-6122
=> common: handle forkHash on timestamp == genesis timestamp

packages/devp2p/src/protocol/eth.ts
Currently, we always construct DEBUG messages on devp2p/ETH even if we are not debugging. This PR ensures these strings are only built when actually debugging. (Slight optimization)
=> DevP2P: ETH: only create DEBUG msgs if debugging

packages/common/src/utils.ts, packages/common/test/hardforks.spec.ts
This PR:
- Adds forkHash tests for fork configs where a fork is scheduled at exactly the genesis block time (this should not change forkHash as discovered by hive, see: https://github.com/ethereumjs/ethereumjs-monorepo/pull/2959)
- Adds the `nonce` field to required Geth fields (otherwise one gets a non-descriptive error)
- Makes the "missing fields" error message more descriptive
=> common: add forkHash tests

packages/client/src/miner/pendingBlock.ts
Lighthouse seems to have an optimization where they send a fcU before updating head as well as after updating head. this seems to result into two calls with different parentBeaconBlockRoot (which is the CL head on which proposal is being build) 
Since we have not been using parent beacon block root for uniqueness of payload being build, we were returning same payload if to second fcU call (which has an updated parent beacon block root). 
This was leading to invalid evaluation of the block hash later in new payload where the correct parent beacon block root supplied by the CL is injected into payload
This PR attempts to fix the same
=> client: include parent beacon block root for proposal payload uniquness

packages/trie/benchmarks/index.ts
One of the imports are broken in the trie benchmark files. This change fixes it.
=> Fix broken import

packages/evm/src/evm.ts, packages/vm/src/runTx.ts
Removes some cosmetic `0x` duplication that was leftover when `bytesToHex` was changed to produce prefixed hex strings.
Before fix --
`vm:tx Running tx=0x6143c89384b58f92fceda500e24e3ffe89a30c5441620fd1f3234a98ebc8a8d4 with caller=0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b gasLimit=3972796 to=0x095e7baea6a6c7c4c2dfeb977efac326af552d87 value=100000 data=`**0x0x00**` +0ms`
After fix --
`vm:tx Running tx=0x6143c89384b58f92fceda500e24e3ffe89a30c5441620fd1f3234a98ebc8a8d4 with caller=0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b gasLimit=3972796 to=0x095e7baea6a6c7c4c2dfeb977efac326af552d87 value=100000 data=`**0x00**` +0ms`
=> Clean up logging in vm/evm

packages/client/bin/cli.ts, packages/client/src/client.ts, packages/client/src/net/server/rlpxserver.ts
Fixes #2983 as well as adds an additional layer of error handling to the client top-level `run` function for errors thrown in eventemitter functions (that normally bypass the `run().catch...` call).
You can test the fix for #2983 by starting geth with default settings and then try to start our client with same defaults.  You will observe an error message like `Server error - EADDRINUSE...` or something indicating that geth is already listening on port 30303.  
On master branch, once this error occurs, you will not be able to shut down the client using Ctrl + C because the client startup function hangs mid promise and never resolves.  This handles the error gracefully and starts the client up.  Oddly enough, the client seems to be able to use the port in contention and still be able to …
=> Add error handling for async errors in client

packages/common/src/chains.ts
on request of eirgon the cancun has been unscheduled from holesky for now 
Ref
-  https://github.com/eth-clients/holesky/pull/68
=> common: unschedule Cancun for holesky

packages/tx/src/baseTransaction.ts, packages/tx/src/capabilities/eip1559.ts, packages/tx/src/capabilities/eip2930.ts, packages/tx/src/capabilities/generic.ts, packages/tx/src/eip1559Transaction.ts, packages/tx/src/eip2930Transaction.ts, packages/tx/src/eip4844Transaction.ts, packages/tx/src/legacyTransaction.ts
=> tx: consolidate generic tx capabilities

packages/client/bin/cli.ts, packages/client/src/config.ts, packages/client/src/execution/vmexecution.ts, packages/client/src/types.ts, packages/evm/src/evm.ts, packages/evm/src/interpreter.ts, packages/evm/src/logger.ts, packages/evm/src/precompiles/index.ts, packages/evm/src/types.ts, packages/vm/src/runBlock.ts, packages/vm/src/runTx.ts, packages/vm/src/types.ts, packages/vm/src/vm.ts, packages/vm/test/tester/config.ts
This PR adds the feature for an EVM profiler. It features, once enabled, tracking:
- The amount of calls, the time it takes, and the gas it consumes for each opcode
- The same "inside" the precompiles
For precompiles we have the special case that the gas there is not tracked as in normal EVM calls, but instead depends upon what precompile is called. If a precompile is called, the "inner" gas used by that precompile (so without the overhead of the initial CALL opcode to the precompile) is tracked.
The VM gets extra options: `profilerOpts`, which can `reportProfilerAfterBlock` and `reportProfilerAfterTx`. Note that if a profiler is reported, the profiler in the EVM is cleared, so you cannot use both options.
EVM itself has an extra option as well, the `profiler` (should rename this to …
=> Add EVM profiler

packages/trie/src/trie.ts
```
if (this.root() === this.EMPTY_TRIE_ROOT ... ) 
```
```
if (equalsBytes(this.root(), this.EMPTY_TRIE_ROOT)  ... ) 
```
=> trie: use equalsBytes for root check

packages/trie/test/trie/trie.spec.ts
Test coverage for `trie.checkRoot` was at 0%.
This brings coverage to 100%
=> trie: test coverage for 'checkRoot'

packages/client/bin/cli.ts, packages/vm/src/runBlock.ts, packages/vm/src/runTx.ts, packages/vm/src/vm.ts
PR includes some small improvements to the VM block/tx profiler UX to better locate on what blocks/txs profiler is applicable and has been running.
Additionally `reportAfterTx` option has been fixed to now propagate correctly to the EVM, since before the nullish coalescent operator chaining was not working correctly and the option omitted. This also affects the `--vmProfileTxs` CLI option in the client.
=> VM: Small Profiler UX improvements / Fix client reportAfterTx option propagation to EVM

packages/statemanager/src/stateManager.ts, packages/statemanager/test/stateManager.account.spec.ts, packages/statemanager/test/stateManager.code.spec.ts, packages/statemanager/test/stateManager.storage.spec.ts
This PR handles the scenario when size 0 is provided for account or storage cache sizes in the StateManager by then just disabling the cache.
This is generally an optimization which makes sense, also to avoid a somewhat weird "cache initialized but never used and all functions called" scenario.
Beyond this allows for directly passing through 0 values for the `--accountCache` and `--storageCache` options in client.
Also quick side note: the additional state runs in SM are very very fast and not noticeable and I think it generally makes sense to add this case to a broader test run scenario, since it is something we will commonly use and set up the SM cache with.
=> StateManager: deactivate storage/account caches for cache size 0

packages/trie/src/trie.ts
Followup to #2962 (shelved)
This takes the frist step towards simplifying and improving `trie.findPath()`.
While the logic is fundamentally the same, this refactors `findPath` without the `async-promise-executor` API, and uses the `async/await` syntax directly to achieve the same result.  The `resolve` and `reject` calls have been replaced with `return` and `throw` respectively.
=> trie:  Rewrite findPath without async-promise-executor

packages/statemanager/src/cache/storage.ts, packages/statemanager/src/ethersStateManager.ts, packages/statemanager/test/ethersStateManager.spec.ts
`npm run coverage`  on the `statemanager` package showed no coverage for the `dumpStorage` or `clearContractStorage` methods.
**`dumpStorage`** should return a `StorageDump` object, representing the current state of the storage trie for an account as a key/value map.  Like calling `getContractStorage` for all of the storage keys in an account at once.
I included a few lines of code in the `ethersStateManager.spec.ts` to cover `dumpStorage` (as well as `clearContractStorage`) , but they did not pass as expected, because `dumpStorage` was only looking in `this._storageCache._lruCache`, and not in `this._storageCache._orderedMapCache`
**(For context -- `ethersStateManager.getContractStorage()` uses whichever cache type is available)**
----
This PR adds a method to the `StorageCache` class: …
=> ethersStateManager: dumpStorage fix / test

packages/trie/src/trie.ts
`trie.put(key, null)` 
and
`trie.put(key, Uint8Array.from([])`
both should (and do) delete the value for that key: 
https://github.com/ethereumjs/ethereumjs-monorepo/blob/e2dc88bab0cdb073ee3dbc1154959cd718634527/packages/trie/src/trie.ts#L194-L198
--
However, `Null` is left out of the type options for the value paremeter:
`async put(key: Uint8Array, value: Uint8Array, skipKeyTransform: boolean = false): Promise<void>`
The `official` trie tests actually do use `null`  as a value.  The reason the test does not throw a Type error is that the `null` values are wrapped in a variable with type `any`
Since PUT does not actually accept `Null` values outright, users are forced to use empty Uint8Arrays, or `as any` to access this part of the implementation.
----
This PR adds `| null` as a type …
=> Trie: make NULL available as type option for put value

packages/block/package.json, packages/blockchain/package.json, packages/common/package.json, packages/ethash/package.json, packages/evm/package.json, packages/rlp/package.json, packages/statemanager/package.json, packages/trie/package.json, packages/tx/package.json, packages/util/package.json, packages/vm/package.json
This follows up to [] and []
Enables DEBUG variable in "coverage" test scripts.  By just including the "ethjs" master debug variable, the `if (this.DEBUG) ...`  conditionals present in `DefaultStateManager` et al. will be included in the coverage test.  
Added to  the coverage script in all packages, event though not all packages have DEBUG features yet, and not all packages that do have a debugger have implemented this `if (this.DEBUG) ...` pattern yet.
=> DEBUG coverage

package-lock.json, packages/block/src/index.ts, packages/client/package.json, packages/client/src/sync/skeleton.ts, packages/client/test/sim/beaconsync.md, packages/client/test/sim/beaconsync.spec.ts, packages/client/test/sim/configs/mainnet.json, packages/client/test/sim/mainnet.spec.ts, packages/client/test/sim/simutils.ts, packages/client/test/sim/single-run.sh, packages/client/test/sim/snapsync.md, packages/client/test/sync/fetcher/reverseblockfetcher.spec.ts, packages/client/test/sync/skeleton.spec.ts
some improvements for more robust backfill + beacon sync sim
=> client: some skeleton improvements from observations on devnet syncs

package-lock.json, packages/statemanager/package.json
Hi I am using hardhat with yarn berry.
I met this error a few days ago whenever i try to compile and test. 
```
Error: @nomicfoundation/ethereumjs-statemanager tried to access @nomicfoundation/ethereumjs-trie, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
Required package: @nomicfoundation/ethereumjs-trie
Required by: @nomicfoundation/ethereumjs-statemanager@npm:2.0.2 (via <my-repository-path>/.yarn/cache/@nomicfoundation-ethereumjs-statemanager-npm-2.0.2-5465bc8cbc-3ab6578e25.zip/node_modules/@nomicfoundation/ethereumjs-statemanager/dist/)
```
it means that some packages are using as "dependencies" but these declared as "devDependencies".
i think this pr is a very tiny thing, but it would help for lots of yarn users 😂
=> StateManager: some devDependencies move to dependencies

packages/evm/src/memory.ts, packages/evm/test/memory.spec.ts
This is a small performance optimization improving `MLOAD` and `MSTORE` performance by 10-20%.
Performance results (always last block):
cd ../evm && npm run build && cd ../client && npm run client:start -- --sync=none --vmProfileBlocks --executeBlocks=962960-962971 (MLOAD 48, MSTORE 100 times)
MLOAD
New 2.8  2.7 2.8 2.8
Old. 2.65 2.8 2.7 2.5
MSTORE
New 1.85 1.8 1.9 1.8
Old. 1.65  1.8 1.7 1.75
cd ../evm && npm run build && cd ../client && npm run client:start -- --sync=none --vmProfileBlocks --executeBlocks=962960-962970 (MLOAD 1224, MSTORE 2550 times)
MLOAD
New 2.8 2.75 2.7 2.65
Old.  2.85 2.8 2.7 2.55
MSTORE
New 1.85 1.85 1.8 1.7
Old. 1.75. 1.7 1.7 1.65
Ok. So I would think that results are clear enough on this and we can take this in. Ready for review. 🙂 
We should nevertheless really …
=> EVM: Initialize memory with CONTAINER_SIZE bytes

packages/trie/README.md, packages/trie/examples/logDemo.ts, packages/trie/src/trie.ts, packages/trie/test/util/log.spec.ts
This introduces `debug` logging to the `Trie` class.
Like other packages, all `debug` calls will be wrapped inside of a conditional:
`if (this.DEBUG) { ... } `
`this.DEBUG` will be set to `true` only if the `ethjs` flag has been set in `process.env.DEBUG`
If active, the debugger will log with the namespace: `ethjs:Trie:`
The debugger is available by calling `this.debug(message: string, namespaces: string[])`
`trie.debug()`  will take 1 or 2 parameters.  The first being the string to be logged, the second being a list of added namespaces for that specific message.
So calling `trie.debug('Trie Created')`  will log 
> // **ethjs:trie:**  Trie Created
And calling `trie.debug('Adding value for key: 0xabcd', ['PUT'] )`  will log:
> // **ethjs:trie:PUT** Adding value for key: 0xabcd
----
Also …
=> Trie: Debug logging

packages/client/test/sync/fetcher/storagefetcher.spec.ts
This change refactors the snap storage fetcher tests over to using vi instead of td for mocking. It also increases coverage by testing a few cases.
=> Snap storage fetcher tests

packages/common/src/eips.ts, packages/common/src/hardforks.ts, packages/evm/src/evm.ts, packages/evm/src/interpreter.ts, packages/evm/src/opcodes/codes.ts, packages/evm/src/opcodes/functions.ts, packages/evm/src/types.ts, packages/evm/test/runCall.spec.ts
for devnet 9 (included in cancun) - https://github.com/ethereum/pm/issues/857
EIP https://eips.ethereum.org/EIPS/eip-7516
=> evm: add blobgasfee eip 7516

packages/evm/src/logger.ts, packages/vm/src/vm.ts
This PR adds an overall summary of the profiler: the amount of opcodes (calls), the total gas spent, the MGas/S, and the new column Blocks per Slot.
If Blocks per Slot is `>= 1` then we can execute one block within one beacon chain slot (12 seconds). If it is below, we are executing less than one block per slot, i.e. we cannot keep up with the chain because we are too slow.
This BpS is also added for each opcode: if it is below 1, it is too slow. (Note, that if the amount of calls is too low, think less than 10, this might not give a good indication if the opcode is too slow or not)
=> VM/EVM profiler: add summary, add Blocks per Slot normalized field

packages/statemanager/src/stateManager.ts
a small refactor to obtain account trie/storagetries and codedb for building state in snapsync PR
- https://github.com/ethereumjs/ethereumjs-monorepo/pull/3031
=> statemanager: small refactor to get storage objects for snapsync

packages/client/bin/cli.ts, packages/client/src/config.ts, packages/client/src/execution/vmexecution.ts, packages/client/src/types.ts
Followup for 
- https://github.com/ethereumjs/ethereumjs-monorepo/pull/3023
to enable running the client from previously unprefixed storage tries synced pre #3023
=> client: add a cli option for backward compatibility with non prefixed storage tries

packages/util/src/bytes.ts
This PR:
- Optimizes bytesToBigInt
This only optimizes bytes with length 1 and bytes with length 2 by caching those.
Here are the results: (bytesToBigInt)
```
0 22.67887508869171
0 22.8313969373703
1 38.06730806827545
1 105.89006400108337
2 49.631819009780884
2 120.36363506317139
3 133.02554297447205
3 135.36226105690002
4 149.31096291542053
4 152.2477569580078
```
The format is: first the length of the input byte, then the amount of ms to convert 1 million of those. The first entry is the optimized one (so with this PR), the second entry is current `master`. Note that for `1` byte length we go from 106 ms to 38 ms. For other byte lengths, the times are equal (so there is no performance loss or gain there).
Just for completeness, also "large" bytes:
```
31 635.5747010707855
31 …
```
=> util: optimize bytesToBigInt for 1-byte bytes

packages/statemanager/src/cache/storage.ts
This change simplifies some code from the `statemanager` storage cache.
=> Simplify Storage Cache Code

package-lock.json, packages/devp2p/package.json
The `vm` nightly tests started failing recently and the issue is because the `scanf` dependency recently released a point update (1.1.20 - notably the first one in 3 years) and it has some broken types in it.  Given that this dep is only used for parsing the ENR string and the underlying functionality should be static, makes sense to just pin to the previous version and leave it there for now.
=> Pin `scanf` dependency

package-lock.json, packages/devp2p/package.json, packages/evm/package.json, packages/statemanager/package.json
As noted in #3071, the `PrecompileInput` interface exposes a `_debug` property which is of type `debug`.  Since this `PrecompileInput` is be used when somebody is implementing a custom precompile, it makes sens to add the `debug` types to the production dependencies so Typescript can resolve these types.
It also updates the dependency version in two other packages where it is a `devDependency`.
=> Add `debug` types to `evm`

packages/client/src/config.ts, packages/client/src/rpc/modules/engine.ts, packages/client/test/rpc/engine/newPayloadV1.spec.ts
on devnet9 there is  a range of blocks 1700-2000 where blocks have txs ~1400+. This causes newpayload api to timeout for the CLs causing them to be stuck and/or retry the same blocks over and over again.
This PR, responds `SYNCING` to heavy blocks (for ethereumjs) which can then be independently executed while letting the CL sync moveforward.
tested on devnet-9 with lodestar leading to fast resolution of sync from genesis
=> client: make the newpayload execution of big blocks non blocking

packages/client/bin/cli.ts, packages/client/src/config.ts, packages/client/src/execution/vmexecution.ts, packages/client/src/miner/pendingBlock.ts, packages/client/src/rpc/modules/engine.ts, packages/client/src/types.ts, packages/client/test/rpc/engine/getPayloadV1.spec.ts
in cancun-engine hive tests, there are lots of `Invalid` scenario tests where the new payload evaluates to `INVALID` but we don't respond accordingly in fcU (rather end up throwing error instead of `INVALID` status)
this PR caches invalids and use it in fcU responses.
What scenario this PR changes/Fixes
- add invalid block cache populated in new payload and use it in fcu
- skip adding the payloads generated in getPayload to the chain without going through new payload
- add a cli option to run hive without engine pruning via `--pruneEngineCache false` as some tests require deep cache
- fix validHash lookup
- cache remoteblocks early in newpayload after successful block and parent block validations
TODO
From 69 failing cases 
this PR reduces to 61 failing cases
Requested some clarifications …
=> client: track and respond to invalid blocks in engine api and other hive engine-cancun fixes

packages/client/src/rpc/modules/engine.ts, packages/client/src/service/fullethereumservice.ts, packages/client/src/service/skeleton.ts, packages/client/test/rpc/helpers.ts, packages/client/test/sync/skeleton.spec.ts
on devnet9, because of some reasons skeleton was resetting the chain and these are the remedial fixes that have been deployed on the nodes there
BUILD on top of 
- https://github.com/ethereumjs/ethereumjs-monorepo/pull/3077
TODO
=> client: fix canonical reset of the chain by the skeleton

packages/client/src/rpc/modules/eth.ts, packages/client/test/cli/cli.spec.ts, packages/client/test/rpc/eth/coinbase.spec.ts, packages/client/test/rpc/helpers.ts
This change implements the `eth_coinbase` rpc endpoint. Also see the [JSON RPC API](https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_coinbase).
=> client: Add eth_coinbase RPC implementation

packages/client/bin/cli.ts, packages/client/test/cli/cli.spec.ts
Address #2938 
- Adds new default port settings for websocket RPC to avoid colliding with HTTP RPC defaults
- Adds new guards in CLI arg parsing to ensure that colliding port values aren't set between WS and HTTP RPCs
=> Guard against rpc port collisions

packages/client/README.md
This PR adds a mention and instructions related to using the lodestar quickstart repository, which seems to me like the easiest way to get our client running. 
Related to #3081
=> client: add lodestar quickstart to client readme

package-lock.json
This PR resolves a medium security postcss vulnerability: https://security.snyk.io/vuln/SNYK-JS-POSTCSS-5926692
=> monorepo: fix postcss vulnerability

README.md
Resolves #3051 by adding mention of the wallet package to the general README. 
Concerning the dependency graph, the wallet package only imports from util, which we never seem to mention in that graph, so I left that out.
=> monorepo: add wallet to readme

packages/common/src/chains.ts
Also see [Holesky DNS Network for Peer Discovery](https://github.com/eth-clients/holesky/issues/58)
=> Add holesky dns url to supported chains info

packages/client/bin/cli.ts, packages/client/bin/startRpc.ts, packages/client/src/types.ts, packages/client/src/util/rpc.ts, packages/client/test/util/rpc.spec.ts
This change modifies the cli `rpcDebug` option to allow for enabling only the `eth` or `engine` rpc module for log collection so that there is less noise during debugging. Also see #3101.
=> Change rpcDebug option to allow enabling/disabling specific rpc module logs

packages/vm/src/runTx.ts
If the gas limit of a tx is lower than the minimum gas limit (this consists of: tx upfront gas of 21000, the tx data cost, and optionally more gas needed for contract creation), previously we had this error message: `base fee exceeds gas limit`. This is confusing with EIP1559s base fee and is completely unrelated. This PR updates the error message.
=> vm: better error message to avoid confusion with EIP1559 base fee

packages/client/src/miner/pendingBlock.ts
Stumbled upon this one in a hive test.
I have explicitly checked client for more of these cases where we test for `!== undefined` but do not have the other check that it should also not be `null`. This was the only occurrence I could find.
=> Client: pendingBlock fix if FCU is called with withdrawals=null pre-cancun

package-lock.json
This resolves the issue described in this  [link](https://security.snyk.io/package/npm/browserify-sign/4.2.1?_gl=1%2a1i3azfz%2a_ga%2aMzMwNzM1ODM0LjE2OTg2MTQ3MDg.%2a_ga_X9SH3KP7B4%2aMTY5ODYxNDcwOC4xLjAuMTY5ODYxNDcwOC4wLjAuMA)
=> monorepo: fix browserify vulnerability

packages/client/src/rpc/modules/engine.ts
handle an edgecase noticed during holesky sync
=> handle an edge case in newpayload block execution

packages/vm/README.md, packages/vm/src/runTx.ts
This PR:
- Fixes the Readme example tx that was missing a gasPrice param
- Improves an error message that made it seem like pre-eip1559 transactions were providing an invalid maxFeePerGas param.
=> vm: add missing gasPrice param to readme example tx

packages/common/README.md, packages/evm/README.md, packages/evm/src/types.ts
This PR fixes a couple instances where EIP numbers linked to the wrong EIPs
=> common: fix readme eip links

packages/client/src/rpc/modules/engine.ts, packages/client/src/service/skeleton.ts
to avoid the chain being reset by getting interfered with sksleton's fill Canonicaland fcU's sethead's putblocks of executed blocks
now skeleton attempts blocking fill for the max number of  executed blocks which fcu wants to put via execution's setHead
This PR should fix the hive pytests failing because of this issue
ps:
this is a patch but a proper solution needs to happen at blockchain layer where blocks shouldn't reset the chain unless explicitly asked to or via a proper rule that they should extend the max height of the chain.
Also skeleton 's canonical block handling/tracking needs to be up streamed to the chain , but that could be a little more involved work to address separately
=> client: Patch fcu skeleton blockfill process to avoid chain reset

packages/evm/tsconfig.prod.cjs.json, packages/evm/tsconfig.prod.esm.json, packages/genesis/tsconfig.prod.cjs.json, packages/genesis/tsconfig.prod.esm.json
When trying to super-optimize hive, I noted that if you partially copy our monorepo and then try to build a package (all dependencies are in the folder) then for `evm` and `genesis` there are references to packages which are not used. I think we can remove those references?
=> tsconfig: fix references

packages/client/bin/cli.ts, packages/client/test/cli/cli.spec.ts
This finishes up the work identified in #3045 by adding complete typing to the `args` passed in the CLI.  No more `//@ts-ignore`
=> Finishes typing client opts

packages/vm/test/api/runBlock.spec.ts, packages/vm/test/api/runTx.spec.ts
This PR "un-nests" some nested `it` vitest tests. Nested `it` functions do not get executed, and therefore "silently pass".
=> vm: fix nested tests

packages/client/src/service/txpool.ts
During Holesky sync testing, an error was discovered resulting from an `undefined` value being passed into `handleAnnouncedTxHashes` while processing a `NewPooledTransactionHashes` message:
```
[11-06|17:23:48] INFO [ CL ] New chain head set (forkchoice update) number=262502 head=0x1380…4a8b finalized=0x4429…4727 response=VALID timestampDiff=9 mins
[11-06|17:23:48] DEBUG Forkchoice requested update to new head number=262503 hash=0xd124…b550
[11-06|17:23:48] DEBUG New skeleton head announced number=262503 hash=0xd124…b550 force=true
[11-06|17:23:48] DEBUG Beacon chain extended new head=262503 tail=257593 next=0xa15f…ff48
[11-06|17:23:48] DEBUG Writing SYNCING linked=true subchains=[tail=257593 head=262503 next=0xa15f…ff48] reset=false el=262502 hash=0x1380…4a8b
[11-06|17:23:48] DEBUG …
```
=> client: Return during handling NewPooledTransactionHashes message if txHashes is undefined

packages/verkle/src/util/crypto.ts
This PR improves the verkle cryptography helpers, notably:
- Extracting the computationally heavier `getStem` logic (which uses `pedersenHash`) from the `getTreeKey` (now renamed `getKey`) to avoid recomputing the stem again and again. 
- Minor renaming.
=> verke: update verkle crypto helpers

packages/util/src/bytes.ts
This fixes two things related to the new bytes-bigint helpers:
- Uses big "uints" rather than "ints" (that was the previous behavior, and fits with how we use those throughout)
- Instead of throwing when byte length is too small, pad with zeroes.
=> util: adjust byte bigint utils

packages/devp2p/src/dns/dns.ts, packages/devp2p/src/dpt/ban-list.ts, packages/devp2p/src/dpt/dpt.ts, packages/devp2p/src/dpt/server.ts, packages/devp2p/src/protocol/les.ts, packages/devp2p/src/protocol/snap.ts, packages/devp2p/src/rlpx/peer.ts, packages/devp2p/src/rlpx/rlpx.ts
This PR removes debug calls in the devp2p package if no DEBUG flag is set. This ensures that we do not create debug strings which we later throw away if no logger is attached. This was already the case in the eth protocol, but this is now package-wide. the only place where it is not added is in `assertEq` in `util.ts`
=> Remove debug loggers devp2p

packages/evm/src/index.ts
While working on #3167, I noticed that we do not export `EVMRunCallOpts` and `EVMRunCodeOpts` from the `evm` package even though these are the type definitions for the `evm.runCall` and `evm.runCode` public methods of the EVM.  This fixes that.
=> Add runCallOpts and runCodeOpts to `evm` exports

package-lock.json
This PR addresses the following issue: https://github.com/ethereumjs/ethereumjs-monorepo/security/dependabot/66
=> monorepo: address dependabot vuln 66

packages/evm/test/precompiles/01-ecrecover.spec.ts
This change aims to increase test coverage for the evm package `01-ecrecover` precompile.
=> Add test for ecrecover precompile

packages/util/src/bytes.ts, packages/util/test/bytes.spec.ts
This addresses an issue where an invalid hex (e.g. `'0x\x19Ethereum Signed Message:\n32')` ) wouldn't throw. 
We now validate that every parsing of hex to int (through parseInt in base 16) returns a valid int and not a NaN.
=> util: check that hex to byte conversion is valid in hexToBytes

packages/util/src/bytes.ts
This PR optimizes hexToBytes.
**NOTE**: I also changed `unprefixedHexToBytes` to use this, because we call `unprefixedHexToBytes` in `toBytes` in case we convert a BigInt to Bytes! 
To test:
```typescript
import { hexToBytes as hexToBytesCrypto } from 'ethereum-cryptography/utils'
import { hexToBytes, padToEven } from '../src'
const allHexChars = 'aabbccddeeffAABBCCDDEEFF00112233445566778899'
const storageSlotMax = '0x' + ('ff').repeat(32)
const cases = ['0x', '0xaA', storageSlotMax, '0x' + allHexChars, '0x' + allHexChars.repeat(32)]
const iter = 1_000_000
const oldHexToBytes = (hex: string): Uint8Array => {
if (typeof hex !== 'string') {
throw new Error(`hex argument type ${typeof hex} must be of type string`)
}
if (!/^0x[0-9a-fA-F]*$/.test(hex)) {
throw new Error(`Input must be a …
```
=> util: optimize hexToBytes

packages/statemanager/examples/browser.html, packages/trie/src/trie.ts
The `statemanager` package browser example has two errors when it's run. The first error comes from referencing `process` in the trie package:
```
trie.ts:105 Uncaught (in promise) ReferenceError: process is not defined
at new Trie (trie.ts:105:18)
at new DefaultStateManager (stateManager.ts:200:23)
at run (browser.html:19:34)
at browser.html:31:9
```
The second error results from using `hexStringToBytes` instead of `hexToBytes`. This change fixes both of these issues so that the example successfully runs in the browser.
=> statemanager: Fix statemanager Browser Example

packages/common/src/chains.ts, packages/common/test/hardforks.spec.ts
updating the schedule as discussed in ACD today 
see 
- https://github.com/ethereum/execution-specs/pull/860
- https://github.com/ethereum/EIPs/pull/8051
=> common: schedule cancun for testnets

packages/util/src/provider.ts
Example was previously passing in the full verbose json-rpc request which wasn't necessary
=> fix: Fix fetchJsonRpc example

packages/evm/test/runCall.spec.ts
This updates the `CALLCODE` test added in #3194 with clearer execution results (and mirrors a new test we're proposing to add to the execution-api-tests).
=> Update callcode test 

packages/common/src/crc.ts
Use permalink in `crc.js` reference to avoid future breakage of link.
=> Use permalink to avoid future breakage of link

packages/client/src/rpc/index.ts
Noticed this was missing while reading client code
=> chore: Add missing jsdoc to client

packages/client/bin/cli.ts, packages/client/test/util/wasmCrypto.spec.ts, packages/common/src/types.ts, packages/devp2p/src/dpt/message.ts, packages/devp2p/src/rlpx/ecies.ts
This adds additional cryptographic primitives from `@polkadot/wasm-crypto`, mainly for use in devp2p.  Partially addresses #3246
=> Additional `wasm-crypto` replacements in devp2p

packages/rlp/benchmarks/index.ts, packages/rlp/package.json, packages/rlp/src/index.ts, packages/rlp/tsconfig.benchmarks.json
Improve performance in the inner _decode function by avoiding copying of the remainder.
In the case that the final remainder is returned to the user (ie: stream=true), it is copied before returning.
Results in ~10-30x speedup
benchmarks:
before:
```
decode - list of small numbers x 3,985 ops/sec ±4.57% (42 runs sampled)
decode - list of large numbers x 3,522 ops/sec ±9.29% (32 runs sampled)
decode - list of small buffers x 2,558 ops/sec ±2.94% (41 runs sampled)
decode - list of large buffers x 0.34 ops/sec ±42.70% (5 runs sampled)
```
after:
```
decode - list of small numbers x 50,158 ops/sec ±0.33% (96 runs sampled)
decode - list of large numbers x 50,496 ops/sec ±0.44% (93 runs sampled)
decode - list of small buffers x 46,721 ops/sec ±0.29% (92 runs sampled)
decode - list of large …
```
=> perf: improve rlp.decode

packages/tx/src/baseTransaction.ts, packages/tx/src/eip1559Transaction.ts, packages/tx/src/eip2930Transaction.ts, packages/tx/src/eip4844Transaction.ts, packages/tx/src/legacyTransaction.ts, packages/tx/test/eip1559.spec.ts, packages/tx/test/eip4844.spec.ts, packages/tx/test/legacy.spec.ts, packages/tx/test/typedTxsAndEIP2930.spec.ts
This PR adds `addSignature` method. It is essentially the old `protected _processSignature` method.
This allows users to add raw values of the signature, without having to use `tx.sign` (where the pkey is necessary). This is, for instance, handy for hardware wallets.
Please take care reviewing the Legacy transactions, since those are somewhat exceptional.
Ref: https://github.com/ethereumjs/ethereumjs-monorepo/discussions/3229
=> tx: add `addSignature` method

packages/client/src/sync/fetcher/trienodefetcher.ts, packages/client/src/util/rpc.ts, packages/client/test/sync/fetcher/trienodefetcher.spec.ts, packages/client/test/util/rpc.spec.ts
Also fixes the same error, thrown during sync from the `checkFiilter` method in `client/src/util/rpc.ts`.
- ### `trieNodeFetcher.store` 
- A possible `undefined` was ignored with a `!` and an `as string`.
- Fixed by assigning an empty string in place of the possible `undefined` string.
- ### `util/rpc.ts -- checkFilter(method: string, filterStringCSV: string)`
- Function expects a string value for `filterStringCSV`, but can potentially be fed an `undefined` 
- This probably happens from the same `as string` issue above, or the same bug somewhere else
- Fixed by checking for `undefined` and treating it the same as an empty string.
Running the script from the Issue with these two fixes resulted in the elimination of that error, and allowed the `sync` process to run smoothly.
=> client: Check for undefined pathStrings

packages/client/test/integration/beaconsync.spec.ts, packages/client/test/integration/client.spec.ts, packages/client/test/integration/fullethereumservice.spec.ts, packages/client/test/integration/fullsync.spec.ts, packages/client/test/integration/lightsync.spec.ts, packages/client/test/integration/merge.spec.ts, packages/client/test/integration/miner.spec.ts, packages/client/test/integration/peerpool.spec.ts, packages/client/test/integration/pow.spec.ts, packages/client/test/miner/miner.spec.ts, packages/client/test/net/peerpool.spec.ts, packages/client/test/net/protocol/rlpxsender.spec.ts, packages/client/test/net/server/rlpxserver.spec.ts, packages/client/test/rpc/util/CLConnectionManager.spec.ts, packages/client/test/service/fullethereumservice.spec.ts, packages/client/test/service/lightethereumservice.spec.ts, packages/client/test/sim/beaconsync.spec.ts, packages/client/test/sync/fetcher/blockfetcher.spec.ts, packages/client/test/sync/fetcher/fetcher.spec.ts, packages/client/test/sync/fetcher/headerfetcher.spec.ts, packages/client/test/sync/fetcher/reverseblockfetcher.spec.ts, packages/client/test/sync/lightsync.spec.ts, packages/client/test/sync/sync.spec.ts
This PR addresses the issue of "nesting" in Vitest test designs, as well as issues regarding test assertions inside of event callbacks.
1. Test Nesting:
- The update to vitest v1.x.x introduces stricter rules around nested tests.
- "Nesting" refers to a test case within a test case
- *describe* inside of *describe*
- *it* inside of *it*
**The solution for this is usually to break apart the nested test cases into separate test suites**
i.e.
```ts
describe('All the tests', () => {
it('test 1', () => {
it('test 1a', () => {
assert(...)
})
it('test 1b', () => {
assert(...)
})
})
it('test 2', () => {
assert(...)
})
})
```
would be refactored to:
```ts
describe('test 1', () => {
it('test 1a', () => {
assert(...)
})
it('test 1b', () => {
assert(...)
})
})
describe('test 2', () => {
it('test …
```
=> Client: fix test nesting and other vitest issues

packages/common/src/chains.ts, packages/common/test/hardforks.spec.ts
as discussed in today's Feb 8 ACD, cancun confirmed for mainnet
ref: 
- https://github.com/ethereum/consensus-specs/pull/3597
- https://github.com/ethereum/EIPs/pull/8173
and this here confirms the forkhash
https://discord.com/channels/595666850260713488/745077610685661265/1205157653047808071
=> common: schedule cancun for mainnet

package-lock.json, packages/block/CHANGELOG.md, packages/block/package.json, packages/blockchain/CHANGELOG.md, packages/blockchain/package.json, packages/client/CHANGELOG.md, packages/client/package.json, packages/common/CHANGELOG.md, packages/devp2p/CHANGELOG.md, packages/devp2p/package.json, packages/ethash/CHANGELOG.md, packages/ethash/package.json, packages/evm/CHANGELOG.md, packages/evm/package.json, packages/genesis/CHANGELOG.md, packages/genesis/package.json, packages/rlp/CHANGELOG.md, packages/statemanager/CHANGELOG.md, packages/statemanager/package.json, packages/trie/CHANGELOG.md, packages/trie/package.json, packages/tx/CHANGELOG.md, packages/tx/README.md, packages/tx/package.json, packages/util/CHANGELOG.md, packages/vm/CHANGELOG.md, packages/vm/package.json, packages/wallet/CHANGELOG.md
Hotfix releases following #3261 with new releases for the already published versions adding a missing `debug` dependency to the `@ethereumjs/trie` package.
Additionally some README and CHANGELOG additions I forgot to commit before pushing, not necessary for the releases itself to be merged, can be taken in afterwards (or at any time).
=> Hotfix Releases (Missing Trie debug dependency)

packages/statemanager/src/stateManager.ts, packages/trie/src/trie.ts, packages/trie/src/util/readStream.ts, packages/trie/test/stream.spec.ts
This change fixes an import error that is coming up in webpack browser builds resulting from a nodejs-specific import being made in the trie package as a result of the readable-stream refactor done in #3231. See https://github.com/ethereumjs/ethereumjs-monorepo/pull/3231#discussion_r1486061100.
=> Remove nodejs import from trie.ts

packages/trie/src/trie.ts, packages/trie/src/types.ts
Users of the `@ethereumjs/trie` library will see this error when using `trie.findPath` in their tooling, specifically when writing a function which returns the result of `trie.findPath`:
> Return type of public method from exported class has or is using private name 'Path'.ts(4055)
This happens because the `Path` interface was not previously exported.  Users were unable to import it directly from the Trie library to declare a return type for their functions.  The Typescript compiler would also be unable to properly infer the return type for the user function, because the expected return type `Path` could not actually be found from the outside.
Fix:
`interface Path {...} ` > `export interface Path {...}`
=> trie: export "Path" interface

packages/block/examples/4844.ts, packages/block/test/eip4844block.spec.ts, packages/block/test/from-beacon-payload.spec.ts, packages/client/bin/cli.ts, packages/client/devnets/4844-interop/tools/txGenerator.ts, packages/client/test/miner/pendingBlock.spec.ts, packages/client/test/rpc/engine/getPayloadV3.spec.ts, packages/client/test/rpc/engine/kaustinen2.spec.ts, packages/client/test/rpc/engine/newPayloadV3VersionedHashes.spec.ts, packages/client/test/rpc/eth/getBlockByNumber.spec.ts, packages/client/test/rpc/eth/getTransactionReceipt.spec.ts, packages/client/test/rpc/eth/sendRawTransaction.spec.ts, packages/common/examples/initKzg.ts, packages/evm/test/precompiles/0a-pointevaluation.spec.ts, packages/tx/examples/blobTx.ts, packages/tx/examples/initKzg.ts, packages/tx/test/eip4844.spec.ts, packages/util/src/kzg.ts, packages/vm/test/api/EIPs/eip-4844-blobs.spec.ts, packages/vm/test/api/runTx.spec.ts, packages/vm/test/tester/index.ts
Follow-up on #3294 
This is a small API optimization for the KZG initialization. We can make the `trustedSetupPath` in Util optional while remaining backwards compatiblity.
Then `initKZG(kzg, '')` with this relatively expressionless `''` can be shortened to `initKZG(kzg)`.
=> Small KZG API Optimization

packages/client/test/sync/fetcher/fetcher.spec.ts
Closes #3279 
TODO
Note: the client test seems to rely upon the internal timing of the NodeJS timers. I think if we make this longer (I made it 100 times longer) then we are ok. (Although this raises the question if we should take a deeper look if we can improve this test)
=> Fix node versions

packages/client/bin/cli.ts
`npm run client:start -- --unlock 0x...`
fails with
`TypeError: Cannot read properties of undefined (reading 'createInterface')`
=> Client: fix `readline` library import

packages/util/src/provider.ts
The ts-doc example code block was not closed with ` ``` `, as a result the [docs page](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/util/docs/README.md#fetchfromprovider) is wrongly rendered.
I just fixed it by adding the missing ` ``` ` 👍
=> Fix ts-doc typo

packages/client/src/config.ts, packages/client/test/rpc/helpers.ts, packages/common/src/eips.ts, packages/evm/src/opcodes/EIP2929.ts, packages/evm/src/opcodes/functions.ts, packages/evm/src/opcodes/gas.ts, packages/statemanager/src/statelessVerkleStateManager.ts
followup of 
- https://github.com/ethereumjs/ethereumjs-monorepo/pull/3343
test and fix issues against the next iteration of verkle kaustinen5 as a stateless client
How to run:
1. clean the client datadir (`/data/k6data`)  and start the client  providing where to save payload of invalid blocks (`/data/k6data/invalidblocks`):
`npm run client:start:ts --  --ignoreStatelessInvalidExecs /data/k6data/invalidblocks  --dataDir /data/k6data --network kaustinen6 --rpcEngine --rpcEngineAuth false --logLevel warn`
the loglevel is kept warn so that only failures so unexpected warns/errors show up to reduce noise while syncing
2.  clean the lodestra quickstart datadir's lodestar folder (here `k6data/lodestar` and run the following:
`/setup.sh --dataDir k6data --network kaustinen6 --justCL`
to start …
=> common: configure kaustinen6 network

packages/client/test/integration/beaconsync.spec.ts
Currently the nightly Node 20 tests are failing, see e.g. [here](https://github.com/ethereumjs/ethereumjs-monorepo/actions/runs/8776976521/job/24081258740), the beacon sync integration tests are timing out:
This is an attempt to fix, ready to be merged (I would not want to create an extra PR proof-of-success test setup, unreasonable effort).
There is a specific test case named in the failing test run, but since tests are async might not be directly attributable, so I just increased timeouts for all tests.
=> Client: Fix Node 20 Nightly Test Runs

packages/client/src/execution/vmexecution.ts
When I just tested the client on the ESM build with `npm run client:start -- --execution=false` I realized that the execution flag is ignored and execution started nevertheless.
This is likely since we have various execution entrypoints atm and it is likely that at least one gets triggered in an non-expected context.
This small PR adds a better guard in the execution `run()` method directly to avoid this kind of scenarios. Should be safe to merge since the `--execution` flag is used with very much a clear intention and so this cannot have side effects on beacon sync or whatsoever on normal runs.
=> Client: Better --execution Flag Guard

packages/evm/src/opcodes/gas.ts
address a pending change of ignoring precompiles for some target access events
=> evm: ignore precompile addresses for some target access events

packages/client/bin/cli.ts, packages/client/src/execution/vmexecution.ts, packages/client/src/service/fullethereumservice.ts, packages/client/test/rpc/engine/preimages.spec.ts, packages/client/test/rpc/helpers.ts, packages/client/test/testdata/geth-genesis/kaustinen2.json, packages/client/test/testdata/geth-genesis/kaustinen6.json, packages/common/src/chains.ts, packages/common/src/enums.ts, packages/common/src/hardforks.ts, packages/common/src/utils.ts, packages/evm/src/evm.ts
shifts verkle to osaka to prepare ethjs for electra devnets
tested kaustinen6 network sync, working as before
=> common: add osaka hardfork and shift verkle to osaka

packages/block/src/block.ts, packages/block/src/header.ts, packages/blockchain/src/blockchain.ts, packages/client/src/miner/miner.ts, packages/evm/src/evm.ts, packages/evm/src/opcodes/EIP2929.ts, packages/evm/src/opcodes/functions.ts, packages/evm/src/opcodes/gas.ts, packages/tx/src/eip1559Transaction.ts, packages/tx/src/eip4844Transaction.ts, packages/vm/src/buildBlock.ts, packages/vm/src/runBlock.ts, packages/vm/src/runTx.ts, packages/vm/test/api/runTx.spec.ts
This change removes some unnecessary explicit boolean comparisons where `isActivatedEIP` is called in order to make the code cleaner and more consistent.
=> Remove unnecessary boolean comparisons when using isActivatedEIP

packages/block/src/block.ts, packages/block/src/types.ts, packages/client/src/rpc/modules/engine/engine.ts, packages/client/src/rpc/modules/engine/util/newPayload.ts, packages/client/test/net/peer/rlpxpeer.spec.ts, packages/client/test/sync/txpool.spec.ts, packages/common/src/types.ts, packages/util/src/bytes.ts, packages/util/test/types.spec.ts, packages/vm/test/api/EIPs/eip-3540-evm-object-format.spec.ts, packages/vm/test/api/runBlock.spec.ts
This PR reverts some updates that had been made to `string` in #3348  and #3357, where string types were updated to `PrefixedHexString` when that was relevant, but this can lead to breaking changes in certain contexts. I've reverted what seemed like the most obvious common usages (e.g. block or common types that can be used externally). Instead of actually reverting to `string`, I updated the types to `PrefixedHexString | string` so that we can easily eventually remove `string` fully. I've also added TODO's above each of these instances so we can quickly retieve these instances and do that eventually.
=> monorepo: revert and adjust some prefixedHexTypes

packages/block/src/block.ts, packages/blockchain/src/blockchain.ts, packages/blockchain/src/consensus/ethash.ts, packages/blockchain/src/db/helpers.ts, packages/blockchain/src/db/manager.ts, packages/blockchain/test/blockValidation.spec.ts, packages/blockchain/test/index.spec.ts
fixes the block body parsing and removes the body save optimization making the body load simple enough
tested kaustinen6 network and confimed working (so in general all post merge networks) as well as mainnet pow first few thousand blocks
=> block: fix the block body parsing as well as save/load from blockchain

packages/blockchain/src/db/manager.ts, packages/blockchain/test/blockValidation.spec.ts, packages/blockchain/test/index.spec.ts
handle nil blockbodies for backward compatibility
validated things working fine for kaustinen6 as well as mainnet pow few thousand blocks
=> blockchain: handle nil blockbodies for backward compatibility

packages/common/src/eips.ts, packages/common/src/hardforks.ts, packages/vm/test/api/EIPs/eip-2935-historical-block-hashes.spec.ts
test the 2935 contract code as per the eip
- https://eips.ethereum.org/EIPS/eip-2935
and update history save address, however old address is till overriden for kaustine6 (tested and verified) 
its likely that the code and hence address will be modified at which point the address and the code for testing will be updated
=> common: add spec test for 2935 contract code and update history storage address

packages/evm/src/interpreter.ts, packages/util/src/account.ts
some issues discorved and fixed while running/debugging block `123836` of kaustinen6
=> util,evm: cleanup and fix some verkle related issues

packages/vm/src/vm.ts
- Move it to an instance method. There shouldn't be any issues with it being an instance method since the underlying event emitter is still per object.
- Make it more typesafe by taking keyof Events rather than string
- TODO meant to do this pr to master not vitest-update
=> chore: Small cleanup to vm._emit

packages/block/src/block.ts, packages/block/src/from-beacon-payload.ts, packages/block/src/types.ts, packages/client/src/rpc/modules/engine/types.ts, packages/client/src/rpc/modules/engine/validators.ts, packages/client/src/rpc/validation.ts, packages/client/test/rpc/engine/newPayloadV4.spec.ts, packages/util/src/requests.ts
it has been decided to not accept this engine api change:
- https://github.com/ethereum/execution-apis/pull/544
so the CLs have to rename the field from receipts to request now even for devnet0
=> util,block: rename deposit receipt to deposit request

packages/vm/src/buildBlock.ts
stateRoot was collected before requests were accumulated which actually changes the state. so the build blocks would have the wrong stateroot
this pr fixes the same
tested on electra with lodestar integration
=> vm: fix the gathering of stateroot only after requests have been accumulated

packages/client/src/rpc/modules/eth.ts, packages/client/test/rpc/eth/getTransactionCount.spec.ts
This updates the response handler for `eth_getTransactionCount` to support the `pending` block option.  This includes pending transactions currently in the local transaction pool in the transaction count.
This is needed to allow our client to work with the [tx fuzzer](https://github.com/MariusVanDerWijden/tx-fuzz/)
=> Add support for `pending` in `getTransactionCount`

packages/common/src/types.ts, packages/common/src/utils.ts, packages/common/test/utils.spec.ts
pick deposit contract address from genesis.json config which is specified in this way:
```json
{
"config": {
"chainId": 3151908,
"homesteadBlock": 0,
"eip150Block": 0,
"eip155Block": 0,
"eip158Block": 0,
"byzantiumBlock": 0,
"constantinopleBlock": 0,
"petersburgBlock": 0,
"istanbulBlock": 0,
"berlinBlock": 0,
"londonBlock": 0,
"mergeNetsplitBlock": 0,
"terminalTotalDifficulty": 0,
"terminalTotalDifficultyPassed": true,
"shanghaiTime": 0,
"cancunTime": 0,
"depositContractAddress": "0x4242424242424242424242424242424242424242",
"pragueTime": 1715694670
}
}
```
=> common: parse deposit contract address from geth genesis for chain config

packages/evm/src/opcodes/gas.ts, packages/statemanager/docs/README.md, packages/statemanager/src/accessWitness.ts, packages/statemanager/src/statelessVerkleStateManager.ts, packages/statemanager/test/statelessVerkleStateManager.spec.ts, packages/verkle/src/types.ts, packages/verkle/src/util/keys.ts, packages/verkle/test/keys.spec.ts
This PR renames code keccak to codehash as suggested by @acolytec3
=> verkle: rename code keccak

packages/evm/src/opcodes/functions.ts
We did not have the extcodesize > 0 check in AUTH which should invalidate the signer.
To test: download https://github.com/ethereum/execution-spec-tests/files/15330588/fixtures_develop.tar.gz
Untar the blockchain tests into `ethereum-tests` for instance in a Devnet0 dir.
Then from VM:
`npm run test:blockchain -- --fork=Prague --dir=../Devnet0`
=> evm: fix eip3074 AUTH check

packages/client/src/rpc/modules/eth.ts, packages/client/test/rpc/eth/getTransactionReceipt.spec.ts
While running `assertoor` tests in kurtosis, we identified a bug in our code where we were not returning a `status` field as part of the response from `eth_getTransactionReceipt`.  This PR brings our code into line with the [spec](https://ethereum.github.io/execution-apis/api-documentation/)
=> Fix tx status in `eth_getTransactionReceipt`

packages/vm/test/api/EIPs/eip-2935-historical-block-hashes.spec.ts
update the test with new proposed bytecode and deployment  configs
ref: 
- https://github.com/ethereum/EIPs/pull/8596
Note: this test setup can/will be used to test various flavours of the 2935 contract as well as can be used as inspirations for other system contracts
=> vm: updated 2935 tests with the new proposed bytecode and corresponding config

packages/client/bin/cli.ts, packages/client/src/types.ts
This PR allows multiple files to be passed in as an input for the `--loadBlocksFromRlp` CLI parameter in the `client` which will allow the hive `consensus` tests to be run.
=> Add support for multiple sources of rlp blocks

packages/verkle/src/util/bytes.ts, packages/verkle/test/util/bytes.spec.ts
This change helps increase test coverage of the `verkle` package bytes helper by adding some unit tests.
=> verkle: Add tests for verkle bytes helper

package-lock.json, packages/evm/package.json, packages/vm/package.json
This updates the `mcl-wasm` dependency from 1.4.0 to 1.5.0 to adress a browser build issue due an included Node.js native `crypto` import as also described here https://github.com/herumi/mcl-wasm/issues/35.
Ready to be merged if tests pass!
=> EVM/VM: Update mcl-wasm Dependency (Esbuild Issue)

package-lock.json, packages/evm/.gitignore, packages/evm/package.json, packages/evm/vite.config.ts
Adds a recomended setup for measuring bundle size.
- Uses vite because the repo is already using vitest
- Uses `safest` option for the most conservative worst case tree shaking
- Adds a visualizer for visualizing bundle size
Run `npm run visualize:bundle` to vie a visualization of bundle for evm package
To test a specific import modify the index.ts to only export that import
=> feat: Add bundle visualizer

package-lock.json
This fixes these two npm audit high-severity issues:
- https://github.com/advisories/GHSA-3h5v-q93c-6h6q
- https://github.com/advisories/GHSA-grv7-fg5c-xmjg
=> monorepo: npm audit fix

package-lock.json, packages/client/package.json, packages/statemanager/package.json, packages/verkle/package.json, packages/verkle/src/node/baseVerkleNode.ts, packages/verkle/src/node/types.ts, packages/verkle/src/verkleTree.ts, packages/verkle/test/verkle.spec.ts
This makes several small updates to `verkle` preparing for implementation of `trie.push`
- Update `VerkleTrie` class to use output from `verkleCrypto.serializeCommitment` as db key for root node instead of `ROOT_DB_KEY` (serialized commitment is needed for the verkle state root when we start creating block execution proofs)
- Update `findPath` test to use `verklenode.hash` instead of the partial path as the db key (to ensure that we can find nodes from previous state roots and not overwrite them everytime a node at a given partial path changes)
- Update `findPath` test to use result from `findPath` when inserting a new node into the trie.  This gives a cleaner example of how `trie.put` should work 
- Updates `verkle-cryptography-wasm` to v0.4.5
=> Use node hash as db key

packages/block/src/from-beacon-payload.ts, packages/block/test/eip7685block.spec.ts, packages/client/src/rpc/validation.ts, packages/util/src/requests.ts, packages/util/test/requests.spec.ts, packages/vm/src/requests.ts
for devnet 1 of prague (spec: https://notes.ethereum.org/@ethpandaops/pectra-devnet-1)
ref: - https://github.com/ethereum/execution-apis/pull/549
=> util: rename withdrawal request's  validatorPublicKey to validatorPubkey

packages/block/src/from-beacon-payload.ts, packages/client/test/rpc/engine/newPayloadV4.spec.ts, packages/common/src/eips.ts, packages/evm/src/evm.ts, packages/evm/src/opcodes/functions.ts, packages/vm/test/api/EIPs/eip-2935-historical-block-hashes.spec.ts
for devnet 1 of prague (spec: https://notes.ethereum.org/@ethpandaops/pectra-devnet-1)
eip 2935 got added with `set` leading to bytecode change as well as got broken down into two parts with `BLOCKHASH` reading from state moved to 7709 to be activated in verkle (without changing the BLOCKHASH window)
- https://eips.ethereum.org/EIPS/eip-7709
- https://eips.ethereum.org/EIPS/eip-2935
=> common: update eip 2935 as per latest devnet1 spec and add related eip 7709

packages/vm/src/runBlock.ts, packages/vm/test/api/EIPs/eip-2935-historical-block-hashes.spec.ts
remove the backfill of the last 256 hashes as it is already removed from the eip following  kenya discussions
=> vm: remove backfill of block hashes on 2935 activation

packages/evm/src/evm.ts, packages/vm/test/tester/config.ts
This PR
- Updates `ethereum-tests` to https://github.com/ethereum/tests/releases/tag/v14.0
- This includes a back-and-forth conversation with Dimitry about some tests (one should not be in the release and we skip them now)
- Implements and adds https://eips.ethereum.org/EIPS/eip-7610 (note, have not added this to Common since this is always allowed by default - the situation has not happened on mainnet so we can safely allow it always from Chainstart)
=> update tests to v14

packages/vm/src/types.ts, packages/vm/src/vm.ts, packages/vm/test/api/index.spec.ts
I was a bit shocked when I wanted to integrate the new `bls` EVM option into the client [here](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/client/src/execution/vmexecution.ts#L180) (e.g.) that we still have got this ugly DevEx in place that a full fledged EVM needs to be passed over to the VM, even if only a tiny setting or boolean flag should be adjusted (so this then draws this need in to re-provide a full round set of statemanager, blockchain, common,... to align with the VM).
This PR solves this, by just chaining over the EVM options. Should have no side effects, I thought through (and provided with tests) a couple of scenarios, especially regarding blockchain, statemanager, common.
So, if these three *are* provided to `evmOpts` (for whatever reasons), one …
=> VM: EVM Opts Chaining for better DevEx

packages/verkle/src/node/leafNode.ts, packages/verkle/src/node/types.ts, packages/verkle/src/node/util.ts, packages/verkle/src/verkleTree.ts, packages/verkle/test/leafNode.spec.ts, packages/verkle/test/verkle.spec.ts
Adds `trie.del` as a simple extension of `trie.put`
- Adds a new `trie.del` function which wraps `trie.put`
- Add special handling in `trie.put` for the deleted leaf value
1. If no leaf node exists at the specified key (i.e. `findPath` returns no leaf node), return early (since you can't delete a value in a leaf node that doesn't exist)
2. Writes the special `VerkleLeafNodeValues.Deleted` when inserting the value into the leaf node.
=> Add `trie.del`

packages/client/src/rpc/modules/debug.ts, packages/client/test/rpc/debug/getRawBlock.spec.ts, packages/client/test/rpc/debug/getRawHeader.spec.ts, packages/client/test/rpc/debug/getRawReceipts.spec.ts, packages/client/test/rpc/debug/getRawTransaction.spec.ts, packages/client/test/rpc/helpers.ts
Implements 4 JSON-RPC methods in the `debug` namespace.
- debug.getRawBlock
- returns an RLP-encoded block
- debug.getRawHeader
- returns an RLP-encoded header
- debug.getRawReceipts
- retuns an array of EIP-2718 binary-encoded receipts from a block
- debug.getRawTransaction
- returns the bytes of a transaction
=> RPC: implement debug_getRaw...  methods  

packages/block/package.json, packages/blockchain/package.json, packages/common/package.json, packages/devp2p/package.json, packages/ethash/package.json, packages/evm/package.json, packages/genesis/package.json, packages/rlp/package.json, packages/statemanager/package.json, packages/trie/package.json, packages/tx/package.json, packages/util/package.json, packages/verkle/package.json, packages/vm/package.json, packages/wallet/package.json
I've now read a bit on side effects [here](https://sgom.es/posts/2020-06-15-everything-you-never-wanted-to-know-about-side-effects/) and have gotten some base feeling for potential situations.
My overall stance here is that it is...
Putting something in the global scope which then constitutes the state for some other library is generally a pattern we try to fully avoid. And if something is passed on via an object (`Common` being the most prominent one), this is then no problem again. The one thing which might came closest is this global KZG initialization we had before we discoverd ourself that this bad (also for other reasons) and where we switched to this `Common.customCrypto`-encapsuled way of passing things around. If I understand side effects correctly I would also think that the …
=> Monorepo: Set sideEffects to false for all Packages

packages/common/src/hardforks.ts, packages/vm/src/requests.ts, packages/vm/test/util.ts
This PR solves some bugs in https://github.com/ethereum/execution-spec-tests/releases/tag/devnet-1%40v1.3.0
Note: some bugs were in the state runner itself, others were in the VM, mainly the one in `requests.ts`.
A question we might have to answer here is if our 7702 txs are too strict on loading values, for instance an `yParity` of `0x00` will not be accepted (leading zeros in the hex string) and neither will a `v` value (old alias for `yParity`).
This solves both the state and blockchain tests.
Note: also ensures the correct EIPs are on Prague's common
=> Fix Prague test runner

packages/client/src/rpc/modules/eth.ts, packages/client/test/rpc/eth/getBlockReceipts.spec.ts
**Returns the receipts of a block by number, hash, or tag**
tested by `hive` in **ethereum/rpc-compat**:
Before: **Fail 24/90**
After: **Fail 16/90**
=> RPC: implement eth_getBlockReceipts

packages/client/src/rpc/modules/eth.ts, packages/client/src/rpc/types.ts
To run, setup local hive with EthereumJS
1. Ensure in hive, `clients/ethereumjs` has a cloned `ethereumjs-monorepo`
2. Ensure that in `clients`, you rename `Dockerfile.local` to `Dockerfile`
3. To run: `./hive --sim ethereum/rpc --client ethereumjs --sim.limit rpc-compat`
Before: 16/90 failed, after: 13/90 failed
Side note: in order to run EthereumJS in hive with TS-node from the source, change `ethereumjs-local.sh`:
`ethereumjs="node /ethereumjs-monorepo/packages/client/dist/esm/bin/cli.js"`
To
`ethereumjs="tsx /ethereumjs-monorepo/packages/client/bin/cli.ts"`
And ensure that in `Dockerfile` (the renamed `Dockerfile.local`) you install `tsx`:
```
RUN npm i -g ts-node
RUN npm i -g tsx
```
**Failing tests overview**
- `eth_call/call-callenv` - the test expects us to return 0 on the …
=> Client: fix more hive RPC-Compat tests

packages/common/src/common.ts, packages/common/src/eips.ts, packages/common/src/hardforks.ts, packages/common/src/types.ts, packages/vm/test/api/EIPs/eip-2935-historical-block-hashes.spec.ts
This change is inspired by #3448 and refactors the following files by removing any description string fields and instead including them as comments to reduce code size:
* `eips.ts`
* `hardforks.ts`
=> common: move description string from being an object field to a comment

packages/common/src/common.ts, packages/common/src/types.ts, packages/common/test/customChains.spec.ts, packages/vm/test/api/EIPs/eip-2935-historical-block-hashes.spec.ts
Closes https://github.com/ethereumjs/ethereumjs-monorepo/issues/3505
This PR expands the types in Common such that one can override params in hardforks.
An example is given in the 2935 test on how to use it.
=> Common: allow overriding params

packages/block/src/types.ts, packages/client/src/rpc/modules/debug.ts, packages/client/src/rpc/modules/eth.ts, packages/common/src/types.ts, packages/util/src/bytes.ts
This PR addresses one of the points from #3216, namely:
- Go through the bytes module, and related functions that accept both PrefixedHexString | string as types, and restrict the type to only accept PrefixedHexString.
=> refactor: restrict PrefixedHexString types

package-lock.json, packages/blockchain/examples/clique.ts, packages/blockchain/package.json, packages/blockchain/src/blockchain.ts, packages/blockchain/src/consensus/casper.ts, packages/blockchain/src/consensus/ethash.ts, packages/blockchain/src/consensus/index.ts, packages/blockchain/src/constructors.ts, packages/blockchain/src/index.ts, packages/blockchain/src/types.ts, packages/blockchain/test/blockValidation.spec.ts, packages/blockchain/test/clique.spec.ts, packages/blockchain/test/customConsensus.spec.ts, packages/blockchain/test/pos.spec.ts, packages/blockchain/test/reorg.spec.ts, packages/blockchain/test/util.ts, packages/client/bin/cli.ts, packages/client/src/blockchain/chain.ts, packages/client/test/integration/merge.spec.ts, packages/client/test/integration/miner.spec.ts, packages/client/test/integration/util.ts, packages/vm/examples/run-blockchain.ts, packages/vm/package.json, packages/vm/test/api/buildBlock.spec.ts, packages/vm/test/tester/runners/BlockchainTestsRunner.ts
This PR moves to a more flexible consensus layout for blockchain allowing for an optional `consensusDict` to be passed in where all consensus objects which should be used for consensus validation must be present.
This basic setup allows for full tree shaking regarding Clique and Etash code and it will - step 2 - also allow to remove the Ethash dependency.
Since we are now in a Proof-of-Stake world where consensus validation is the exception the PR also moves to having consensus validation deactivated by default. Semantics of the `consensusValidation` flag is "merged" with the `consensusDict` object ("consensus" and "consensus validation" is basically the same), this allows for a substantial simplification on otherwise useless "combinations" (this and that object passed, but …
=> Blockchain: More Modern and Flexible Consensus Layout / Tree Shaking Optimization

packages/client/src/ext/jwt-simple.ts
Closes https://github.com/ethereumjs/ethereumjs-monorepo/issues/3508
It seems we changed `jwt-simple` internally. `jwt-simple` is now edited (internally) to support decoding/encoding unpadded payload bytes. 
This fixes CL <-> EL communication with Grandine. I also tested this (before and after) on Prysm, and the communication works.
=> Ensure EthJS and Grandine talk

packages/verkle/src/node/util.ts, packages/verkle/test/leafNode.spec.ts
Following confirmation from @gballet [here](https://github.com/ethereum/go-verkle/issues/440), updating our code to always apply the leaf marker on touched values in the trie.
=> Apply leaf marker on all touched values

packages/client/src/config.ts
Updates ENGINE_NEWPAYLOAD_MAX_TXS_EXECUTE constant to 200.
This fixes the failing eip-6110 hive test brought to our attention in the chat.
=> client: ENGINE_NEWPAYLOAD_MAX_TXS_EXECUTE constant

packages/client/src/execution/vmexecution.ts, packages/client/src/rpc/modules/debug.ts, packages/client/test/rpc/eth/estimateGas.spec.ts, packages/client/test/rpc/eth/getBalance.spec.ts, packages/client/test/rpc/eth/getBlockTransactionCountByNumber.spec.ts, packages/client/test/rpc/eth/getCode.spec.ts, packages/client/test/rpc/eth/getTransactionCount.spec.ts, packages/client/test/rpc/txpool/content.spec.ts, packages/common/src/interfaces.ts, packages/evm/src/evm.ts, packages/evm/src/interpreter.ts, packages/evm/src/journal.ts, packages/evm/src/types.ts, packages/statemanager/src/rpcStateManager.ts, packages/statemanager/src/simpleStateManager.ts, packages/statemanager/src/stateManager.ts, packages/statemanager/src/statelessVerkleStateManager.ts, packages/vm/src/types.ts, packages/vm/src/vm.ts, packages/vm/test/api/EIPs/eip-4895-withdrawals.spec.ts, packages/vm/test/api/customChain.spec.ts, packages/vm/test/util.ts
This PR refactors and simplifies the `StateManager` interfaces located in `Common`. Especially the double structure with the more generic `StateManagerInterface` and the inheriting `EVMStateManagerInterface` turned out to be too inflexible and more and more non-EVM methods had been added there over the years, since one could not "escape the inheritance structure".
After some discussion of some more complex solutions (multiple interfaces, by case API definitions citing the various interfaces needed), this PR now goes for a more simple solution, which nevertheless should suit the practical needs. The two interfaces are unified again, and instead not so central functionality is made optional (`getProof()`, `dumpStorage(),..). This allows to free the various state manager implementations from …
=> StateManager: Interface Refactor/Simplification

packages/client/src/rpc/helpers.ts, packages/client/src/rpc/modules/eth.ts, packages/client/test/rpc/eth/call.spec.ts
Updates to satisfy `hive` **rpc-spec** tests.
Adds an optional `data` field to the type `RpcError`:
```
RpcError = {
code: number
message: string
trace?: string
data?: string
}
```
per `hive` tests: **eth_call/call-revert-abi-error** and **eth_call/call-revert-abi-panic**
when `eth_call` reverts, it should return an error object:
```ts
{ code: 3,
data: <executionResult>,
message: <error message> }
```
This change to `eth_call` fixes these 2 failing hive tests:
```ts
if (execResult.exceptionError !== undefined) {
throw {
code: 3,
data: bytesToHex(execResult.returnValue),
message: execResult.exceptionError.error,
}
}
```
=> RPC: add data field to RpcError / eth_call error

packages/common/src/utils.ts
In #3518, we removed almost all of the TTD related logic in the code base and with that tightened up what we accept in our parsing of geth genesis parameters.  This caused an issue with Hive where the hive genesis parameters would provide a nonzero TTD but still expecting that merge would be at genesis (since the difficulty of the genesis block is higher than the provided TTD).  This adjusts our logic to compare genesis block difficulty vs TTD to accomodate this quirk in hive.
=> Adjust ttd checks in `parseGethParams`

packages/statemanager/src/rpcStateManager.ts, packages/statemanager/src/stateManager.ts, packages/trie/examples/createFromProof.ts, packages/trie/examples/logDemo.ts, packages/trie/examples/proofs.ts, packages/trie/src/constructors.ts, packages/trie/src/proof/index.ts, packages/trie/src/proof/range.ts, packages/trie/src/trie.ts, packages/trie/test/proof.spec.ts, packages/trie/test/proof/range.spec.ts, packages/trie/test/trie/secure.spec.ts, packages/trie/test/util/asyncWalk.spec.ts, packages/trie/test/util/log.spec.ts, packages/verkle/src/verkleTree.ts
This change aims to provide more detail in the naming of the now standalone proof functions in the Verkle and Merkle datastructures:
The following functions have been renamed in Merkle-Land:
* `createProof` -> `createMerkleProof`
* `updateFromProof` -> `updateTrieFromMerkleProof`
* `verifyProof` -> `verifyMerkleProof`
The following functions have been renamed in the still experimental and under development Verkle-Land:
* `createProof` -> `createVerkleProof`
* `verifyProof` -> `verifyVerkleProof`
The statemanager wrapper function `verifyProof` remains unchanged since keeping it general will allow for a Merkle or Verkle backend.
=> Proof function renaming

packages/block/test/eip4844block.spec.ts, packages/client/test/execution/vmexecution.spec.ts, packages/common/src/chains.ts, packages/common/src/common.ts, packages/common/test/chains.spec.ts, packages/common/test/customChains.spec.ts, packages/vm/test/api/index.spec.ts
This change addresses issue #3562 by updating the default hardfork from Shanghai to Cancun.
=> Update default hardfork

packages/client/src/rpc/modules/admin.ts, packages/client/test/rpc/admin/peers.spec.ts
Addresses #3565
Adds a new `admin_peers` function that mirrors the functionality of the geth RPC endpoint as described [here](https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-admin#admin_peers)
=> Add `admin_peer` RPC endpoint

packages/blockchain/src/consensus/ethash.ts, packages/client/src/rpc/modules/admin.ts
Spotted two instances where `as any` typecasting could be removed
=> monorepo: type cleanup

packages/statemanager/src/rpcStateManager.ts, packages/util/src/provider.ts
This PR adds the `string[]` type to the rpcParams type, as it is a valid param in some contets, notably the eth_getProof JSON-RPC second param.
=> util: add string[] type to rpcParams type

packages/client/README.md, packages/client/bin/cli.ts
This change does two things:
* clean up the Prometheus metrics server documentation for the client
* adds a default case of returning a `404` not found response in the case of navigating to an unkown/unhandled route
=> Prometheus cleanup

packages/devp2p/examples/simple.ts, packages/vm/examples/run-blockchain.ts, packages/vm/examples/run-solidity-contract.ts, packages/vm/examples/vmWithGenesisState.ts, scripts/examples-runner.ts
The examples test runner tries to run each example in a package, and if one of them throws, the `npm run examples` will fail (and will also throw on CI). However, some examples have `process.exit`, if this is hit, the process exits with a successful code and any errors which might have thrown *could* be discarded (depending if the error gets handled first, or the `process.exit`)
=> Example test runner: make script more readable / ensure examples do not `process.exit`

packages/block/test/difficulty.spec.ts, packages/client/test/rpc/eth/sendRawTransaction.spec.ts, packages/common/src/common.ts, packages/common/test/chains.spec.ts
=> Common: Deep-Copy Fix

packages/block/README.md, packages/block/examples/1559.ts
This change updates the `block` package documentation with new breaking changes from #3550. 
While working on this change, it was discovered that the `block` package README uses code examples that are not being embedded from source example files from the examples folder. These examples need to be moved into their own executable files and embedded into the README with `npm run examples:build`. This will be done in a followup PR.
=> Update block docs with header renamings

packages/trie/README.md
This change update the trie package README to use the updated standalone functions instead of old static constructors that were refactored in #3515.
=> Trie static constructors doc updates

packages/verkle/src/constructors.ts, packages/verkle/src/index.ts, packages/verkle/src/verkleTree.ts, packages/verkle/test/verkle.spec.ts
ref issue: #3560
**VerkleTree:**
moves state `VerkleTree.create` to 'constructors.ts' 
renames it to `createVerkleTree`
=> verkle: extract static constructor

packages/evm/src/evm.ts, packages/evm/test/transientStorage.spec.ts
Fixes a Transient Storage [EIP 1153](https://eips.ethereum.org/EIPS/eip-1153) bug related to not clearing Transient Storage after creating a contract at tx-level. Thanks @yann300 :smile:
=> Ensure TransientStorage cleanups after Tx-level contract creation

package-lock.json, package.json
This ports over a fix I have already applied on #3643 on `maintenance-v8` fixing a bug for platform-specific dependencies not being included in a `package-lock.json` file, resulting in an...
```shell
Error: Cannot find module @rollup/rollup-darwin-arm64. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
```
... error when running the `npm run visualize:bundle` command on Mac OS (+ potentially other linux machines?).
Fix is applied along [this comment](https://github.com/npm/cli/issues/4828#issuecomment-2328919455), the wider thread/issue directly deals with the core issue.
=> Monorepo: Fix platform-Specific Dependencies npm CLI Bug

config/tsconfig.json
When running typescript's typecheck (npm run `tsc`), some internal errors from node_modules show up, which is a blocker to eventually adding this to the CI. This options skips node_modules internal typechecking
=> monorepo: skip typecheck for node modules

packages/blockchain/src/consensus/clique.ts, packages/client/src/sync/fetcher/accountfetcher.ts, packages/client/src/sync/fetcher/blockfetcher.ts, packages/client/src/sync/fetcher/blockfetcherbase.ts, packages/client/src/sync/fetcher/bytecodefetcher.ts, packages/client/src/sync/fetcher/fetcher.ts, packages/client/src/sync/fetcher/headerfetcher.ts, packages/client/src/sync/fetcher/reverseblockfetcher.ts, packages/client/src/sync/fetcher/storagefetcher.ts, packages/client/src/sync/fetcher/trienodefetcher.ts, packages/devp2p/src/rlpx/peer.ts, packages/statemanager/src/statelessVerkleStateManager.ts
This change checks for the `ethjs` rail guard to be active for logging to be activated in the `client` and `devp2p` packages. This makes them consistent with the rest of the packages that abide by the guard rail, as discussed in #3634.
In order to test this, one can try running `DEBUG='ethjs,*' npm run client:start:dev2` and comparing it's log output to running `DEBUG='*' npm run client:start:dev2`. 
In a followup PR, the documentation of the monorepo packages that support logging will be updated with logging instructions/details.
=> Make logging consistent

packages/block/src/types.ts, packages/client/src/sync/fetcher/blockfetcher.ts
This PR:
- Fixes the BlockBytes type in Block (note: `RequestBytes` and `RequestsBytes` (plural!!) is a mistake hard-to-miss, maybe we should think of better naming for those types to avoid these kind of mistakes?)
- Ensures that BlockBodies now take the Requests sent with the BlockBodies response used to create the relevant blocks.
Will keep this at draft, will test (or someone else) later on devnet-3 if this fixes the issue where we report that clients are not sending us BlockBodies. So please only merge if this has been tested!
=> client/block: ensure BlockBodies requests get properly propagated

packages/statemanager/README.md, packages/statemanager/examples/fromProofInstantiation.ts
This change includes updates to the `statemanager` package `README` and follows from breaking updates in #3629 & #3672.
=> Statemanager doc update

package-lock.json, package.json, packages/client/package.json, packages/statemanager/package.json, packages/util/src/verkle.ts, packages/verkle/package.json, packages/verkle/test/proof.spec.ts
Fixes the VM nightly jobs
1) Pins vitest to 2.1.0 so we don't get point update mismatches
2. Update `verkle-cryptography-wasm` and the corresponding interface so it's no longer broken
=> Pin vitest deps

packages/evm/vitest.config.browser.mts
I somehow messed up updating the tests to v14.1, seems like we still are on v14.0, this should fix the nightly tests.
I think I pushed the wrong version in https://github.com/ethereumjs/ethereumjs-monorepo/pull/3633
I checked locally, this should fix the nightly tests.
To test: 
`git submodule update --recursive`
`npm run test:blockchain -- --fork=Istanbul --test=wrongRLPGenesis_Istanbul`
`npm run test:blockchain -- --fork=Istanbul --test=lastblockhashException_Istanbul`
This runs 0 tests (which is expected, since these "faulty tests" are now removed)
=> update ethereum tests to v14.1

packages/trie/src/node/branch.ts, packages/trie/src/node/extension.ts, packages/trie/src/node/extensionOrLeafNodeBase.ts, packages/trie/src/node/leaf.ts, packages/trie/src/trie.ts, packages/trie/src/types.ts, packages/trie/src/util/nibbles.ts
This PR resolves #3704 by:
- Renaming the Node class to the more accurate `ExtensionAndLeafNodeBase` class and making it abstract.
- Removing the `encodeKey` method from the extension and leaf node classes as they were not used
- Adding RawExtensionNode and RawLeafNode types
- Removing the EmbeddedNode type and replacing it with the `NodeReferenceOrRawNode` type
- Adding a `BranchNodeBranchValue` type that fits the types of the values of the _branches of the branch node class.
=> trie: improve node typings and class architecture 

packages/vm/DEVELOPER.md, packages/vm/test/t8n/README.md, packages/vm/test/t8n/t8ntool.ts
Fixes a bug in t8ntool filler where we create empty coinbase accounts
=> t8n: do not create empty coinbase account from SpuriousDragon on state.reward == 0

packages/client/src/config.ts, packages/client/src/rpc/modules/engine/engine.ts, packages/client/src/rpc/modules/engine/types.ts, packages/client/src/service/txpool.ts, packages/client/test/miner/pendingBlock.spec.ts, packages/client/test/rpc/engine/getPayloadV3.spec.ts, packages/client/test/rpc/eth/sendRawTransaction.spec.ts, packages/client/test/rpc/helpers.ts
ref: 
- https://github.com/ethereum/execution-apis/pull/559
TODO: add to spec test
=> client: add getBlobsV1 to the client to support CL blob import

packages/vm/test/t8n/t8ntool.ts, packages/vm/test/util.ts
Fixes https://github.com/ethereum/execution-spec-tests/issues/883
Correctly sets the `excessBlobGas` in case no current excess blob gas is provided by the environment, by calculating the `excessBlobGas` based upon the parent header.
=> t8ntool: fix setting correct extraBlobGas

packages/util/src/units.ts, packages/util/test/units.spec.ts
This change adds a `Units` class in the `util` package with two conversion functions in it:
```
static ether(amount: number | bigint): bigint 
static gwei(amount: number | bigint): bigint
```
Also see #1397, most importantly [this](https://github.com/ethereumjs/ethereumjs-monorepo/issues/1397#issuecomment-2401861664) comment for more details.
=> Add Units class for conversions

package-lock.json
This fixes a high-severity issue that was flagged by npm. 
More details [here](https://github.com/advisories/GHSA-gcx4-mw62-g8wm)
=> monorepo: npm audit fixes 

package-lock.json, packages/tx/package.json, packages/tx/test/t9n.spec.ts
This PR adds T9N test support, to decode tx rlps and then verify:
- the sender
- the hash
- the intrinsic gas (the minimal gas limit the tx has to pay, covering data fee / access lists / tx base fee (21k in most cases, higher when creating contracts))
Or:
- If the RLP is invalid, the tx creation aborts
Runs tests of `ethereum-tests/TransactionTests`.
This currently only allows to consume the tests, not to fill them.
See: https://github.com/ethereum/go-ethereum/tree/master/cmd/evm#transaction-tool
=> Add T9N (TransactionTool) test consumption 

packages/mpt/test/trie/trie.spec.ts
Expands getValueMap tests by also testing startKey / limit params
=> mpt: expand getValueMap tests

packages/tx/vitest.config.browser.mts
Adds an edit to the `tx` browser test config to skip `t9n` tests in browser and fix browser tests **again**
=> Skip t9n in browser

.github/workflows/build.yml, .github/workflows/devp2p-build.yml
This change is a followup on #3376 and looks into remaining codecov issues:
=> Further troubleshoot current codecov CI issues

package-lock.json, packages/genesis/package.json, packages/genesis/test/index.spec.ts
This PR removes the mpt dev dependency from the genesis package.json. It was only used for one check in a test, and it leads to a circular dependency that was spotted by @holgerd77 . If we want to do that root check, we can always port some tests over to another package, but I suspect that this sort of very common stateRoot check is covered by many other tests already.
=> genesis: remove mpt devdep

packages/client/test/integration/miner.spec.ts, packages/client/test/sim/simutils.ts
Cleanup item from #3750
This replaces the current `miner` integration test with one that uses the inline client setup from the `test/sim/simutils` instead of complicated mocks.
=> Use `inlineclient` in miner integration tests

packages/client/README.md
This PR adds a new testnet section to the client readme, with an example of how to run the kaustinen6 testnet.
=> client: add kaustinen6 testnet instructions in client readme

packages/client/README.md
This adds a Kaustinen6 reference to the client verkle docs section
=> client: docs link to kaustinen6 ref

packages/blockchain/src/blockchain.ts, packages/common/src/types.ts, packages/common/src/utils.ts, packages/util/src/constants.ts
Adds the request hash to the genesis block to enable running tests on hive: `consume engine` and `consume rlp`.
Using the following hive branch [spencer-tb@prague-devnet-4-ethjs](https://github.com/spencer-tb/hive/tree/prague-devnet-4-ethjs) run either of:
```bash
./hive --sim 'ethereum/eest/consume-block-rlp' --client-file configs/prague.yaml --docker.output --client ethereumjs --docker.nocache .
./hive --sim 'ethereum/eest/consume-engine' --client-file configs/prague.yaml --docker.output --client ethereumjs --docker.nocache .
```
Note the keccak256 of the empty requests should account for the type prefixing, hence why:
```
KECCAK256_RLP_RH == 0x6036c41849da9c076ed79654d434017387a88fb833c2856b32e18218b3341c5f
```
and not the default `0x56e8...`.
=> packages: add requests hash to genesis block

packages/statemanager/src/statefulVerkleStateManager.ts, packages/vm/src/runBlock.ts
This PR extracts 4 verkle-related adjustments that were done in this PR : https://github.com/ethereumjs/ethereumjs-monorepo/pull/3716 . These are required to pass postState checks and eip-6800 tests
=> vm: verkle adjustments

package-lock.json, package.json
This PR fixes the high severity issues reported by NPM by manually resolving puppeteer-core
(which was the root cause of these issues) to a more recent, patched version.
There are still low-severity issues (related to cookie-handling) which should not be a concern for us, and can't be fixed easily right now as we would have to downgrade vitest-browser to 1.6.0 (we're on 2.1.0). I think we should rather wait for them to get this fixed.
=> monorepo: fix npm high severity issues

package-lock.json, packages/client/src/rpc/modules/admin.ts, packages/client/src/rpc/validation.ts, packages/client/test/rpc/admin/addPeer.spec.ts
This change provides an implementation for `admin_addPeer` as a part of the work being done in #3781 in order to integrate, develop, and provide an ethereumjs repl console. This work also relates to #1114 and increasing JSON-RPC API coverage.
=> Implement admin_addPeer

packages/client/package.json, packages/ethash/package.json, packages/rlp/package.json
This simplifies the coverage runs by removing the c8 tool usage and directly use the in-build vitest coverage functionality.
Beside being simpler goal is to reactivate coverage reporting for certain packages.
=> Monorepo: Simplify coverage Command & Reactivate Reporting

packages/util/src/verkle.ts, packages/util/test/verkle.spec.ts
Rewrites `chunkifyCode` with help from robots based on the reference implementation in EIP-6800
=> Rewritten chunkifyCode

packages/client/src/rpc/modules/debug.ts, packages/client/test/rpc/debug/verbosity.spec.ts
This change provides an implementation for debug_verbosity to allow for setting the verbosity level of the client logger as a part of the work being done in #3781  in order to integrate, develop, and provide an ethereumjs repl console. This work also relates to #1114  and increasing JSON-RPC API coverage.
=> Implement debug_verbosity

packages/common/src/eips.ts, packages/common/src/hardforks.ts, packages/tx/src/capabilities/legacy.ts, packages/tx/src/params.ts, packages/vm/src/runTx.ts, packages/vm/test/api/EIPs/eip-7623.spec.ts, packages/vm/test/t8n/t8ntool.ts
Implements EIP 7623 https://github.com/ethereum/EIPs/blob/da2a86bf15044416e8eb0301c9bdb8d561feeb32/EIPS/eip-7623.md
EEST ref: https://github.com/ethereum/execution-specs/pull/966/files
WIP, need to write tests and currently not sure about this implementation. (Added blocked, don't merge in devnet-5 spec PR https://github.com/ethereumjs/ethereumjs-monorepo/pull/3807)
=> Implement EIP 7623: calldata cost increase

package-lock.json, packages/common/src/common.ts, packages/common/src/hardforks.ts, packages/common/src/interfaces.ts, packages/evm/src/chunkCache.ts, packages/evm/src/evm.ts, packages/evm/src/interpreter.ts, packages/evm/src/opcodes/functions.ts, packages/evm/src/opcodes/gas.ts, packages/evm/src/params.ts, packages/evm/src/stemCache.ts, packages/evm/src/types.ts, packages/evm/src/verkleAccessWitness.ts, packages/evm/test/verkle.spec.ts, packages/statemanager/src/statefulVerkleStateManager.ts, packages/verkle/src/node/util.ts, packages/vm/package.json, packages/vm/src/params.ts, packages/vm/src/runBlock.ts, packages/vm/src/runTx.ts
This PR extracts some verkle work from #3716 so that the other PR can remain scoped on running verkle tests.
=> evm: verkle testing extraction

packages/client/src/rpc/helpers.ts, packages/client/src/rpc/modules/admin.ts, packages/client/src/rpc/modules/eth.ts, packages/client/src/rpc/modules/net.ts, packages/client/src/rpc/modules/txpool.ts, packages/client/src/rpc/modules/web3.ts, packages/client/src/rpc/types.ts, packages/client/src/rpc/validation.ts, packages/client/test/rpc/debug/setHead.spec.ts
Add unit tests for PR: [Implement debug_setHead #3811](https://github.com/ethereumjs/ethereumjs-monorepo/pull/3811)
* Add more unit tests for the `setHead` function
* Add `RPCMethod` as the return type for the middleware function.
* Add the missing name parameters to the function definition comments.
=> client: Add more unit tests for setHead function

packages/common/src/interfaces.ts, packages/evm/src/evm.ts, packages/evm/src/interpreter.ts, packages/evm/src/opcodes/functions.ts, packages/evm/src/opcodes/gas.ts, packages/evm/src/verkleAccessWitness.ts, packages/vm/src/runBlock.ts, packages/vm/src/runTx.ts
This PR aims to simplify the verkle access witness method interface by focusing on the actual explicit actions (read/writing different parts of an account) rather than abstract methods (like "create a contract"). This ends up with DRY-er code and makes it eaiser to parse what is going on.
=> evm: simplify verkle access witness methods

packages/common/src/common.ts, packages/evm/src/evm.ts, packages/evm/src/opcodes/EIP2929.ts, packages/evm/src/opcodes/gas.ts, packages/statemanager/src/statefulVerkleStateManager.ts, packages/vm/src/runBlock.ts, packages/vm/src/runTx.ts
This PR extracts some Verkle-related updates and fixes from #3716:
- Adds a systemVerkleAccessWiness to the EVM class.
- Adds a codeHash read access when creating a contract (for collision checking)
- Adds conditions that skips some accesses when interacting with system contracts and precompiles, as specified by the EIP-4762 EIP.
- Clarifies and fixes code chunk handling in the statefulVerkleStateManager
- Adjusts some miner/account reward logic so that it uses the systemVerkleAccessWitness and not the tx-level verkleAccessWitness, and skips access witness for miner when reward is 0
=> evm: verkle updates

package-lock.json, package.json, packages/client/src/logging.ts
**Problem** 
The VM nightly jobs are currently failing because of a dependency mismatch related to `typedoc` v0.26.
**Solution**
- This PR updates `typedoc` to v0.27 which resolves the dep mismatch.
- Updated package-lock
- Fixed a logger typing issue related to a point release in Winston logger used in the client
=> Fix `vm nightly` CI job

packages/blockchain/src/blockchain.ts, packages/blockchain/src/helpers.ts, packages/client/bin/cli.ts, packages/client/src/util/index.ts
When running `./hive --sim rpc --sim.limit rpc-compat --client ethereumjs --docker.output ethereumjs`, the `rpc-compat` tests it is noticed that the initial blocks fail to import and the client immediately exits. This PR will fix this problem. It also fixes finding the correct package.json file to extract the client version.
The main change is in the blockchain package, which now correctly sets the default value of the requestsHash in case it is not provided for the genesis block. If this is not done (or the incorrect value is used), the blockhash of the genesis block will be different and therefore the blockchain is configured to run a different chain.
=> Client: fix version logging and hive block imports

packages/block/src/params.ts, packages/evm/src/params.ts, packages/evm/src/precompiles/0b-bls12-g1add.ts, packages/evm/src/precompiles/0c-bls12-g1msm.ts, packages/evm/src/precompiles/0d-bls12-g2add.ts, packages/evm/src/precompiles/0e-bls12-g2msm.ts, packages/evm/src/precompiles/0f-bls12-pairing.ts, packages/evm/src/precompiles/10-bls12-map-fp-to-g1.ts, packages/evm/src/precompiles/11-bls12-map-fp2-to-g2.ts
(mini cleanup PR)
Besides cleaning up, this PR also ensures dynamic gas values for 2537 are read from common, not specifically pointing to EIP-2537 (for future possible price updates)
I noticed that some params in common appear to be unused. CoPilot helped me, had to tweak the script but got this:
```bash
grep -ohP '(\w+):' packages/*/src/params.ts | sed 's/:$//' | sort | uniq > all_params.txt
grep -r -ohP "param\('\K[^']+" packages/**/src --include \*.ts | sort | uniq > used_params.txt
comm -23 all_params.txt used_params.txt > unused_params.txt
cat unused_params.txt
```
Note: this outputs a lot of `*Gas`, these are still used, but EVM indexes those by `opcode.name + "Gas"` and not explicit hardcoded strings. 
NOTE: this also gives false positives, since this does not check the …
=> Remove unused params from common

.github/workflows/node-versions.yml, packages/client/test/rpc/websocket.spec.ts
This removes Node 18 from the Node versions run by the Node Nightly ci jobs (since only 18 is failing and it's been deprecated and we no longer officially support it).
Also rewrites `client/test/rpc/websocket.spec.ts` so the test should be less flaky.
=> Fix broken Node Nightly CI jobs

package-lock.json, package.json
Updates `vitest` and related deps to the latest version to address a [security vulnerability](https://github.com/ethereumjs/ethereumjs-monorepo/security/dependabot/90).
=> Update vitest to latest

packages/common/src/chains.ts
This PR fixes the problem on Pectra's Holesky fork where the deposit address differs from the mainnet deposit address. This means that deposit logs for EIP-6110 are not picked up and will therefore yield the incorrect requestsHash.
=> Common: fix deposit address for sepolia and holesky

config/cspell-ts.json, packages/era/src/e2store.ts, packages/era/src/era.ts, packages/era/src/types.ts, packages/era/test/era.spec.ts
This adds support for the `era` format which contains `SignedBeaconBlock` and `BeaconState` objects.
Note, this currently only support era files from `deneb` and later since the underlying SSZ types from `micro-eth-signer` are limited to deneb types.
=> Add era file support

config/cspell-ts.json, package-lock.json, packages/era/README.md, packages/era/package.json, packages/era/src/e2store.ts, packages/era/src/era.ts, packages/era/src/snappy.ts, packages/era/src/types.ts, packages/era/src/types/snappy-stream.d.ts, packages/era/test/era.spec.ts
Adds SSZ types for `Phase0`,  `Altair`, `Bellatrix`, and `Capella`  `BeaconState` types to `era` package to support the various Beacon State objects across forks.
Also, updates the README.md with basic usage for the `era` file format
=> Add altair and bellatrix states to era

packages/binarytree/src/binaryTree.ts, packages/binarytree/test/binarytree.spec.ts
This PR fixes an issue where updates to the tree would get skipped when the tree was already partially filled.
=> binarytree: fix updated value in non empty tree bug

packages/vm/src/requests.ts
Fixes the problem on Sepolia where the contract code does not match mainnet/holesky code. On Sepolia other logs (likely ERC20 related) are emitted and these should thus NOT be included in a deposit log. 
TODO: 
- ~~Fix log decoding in supplied test. Deposit logs stay empty.
[sepolia_extraneous_log (1).json](https://github.com/user-attachments/files/19087319/sepolia_extraneous_log.1.json)~~ Outdated test file
New test file which passes: [sepolia_extraneous_log.json](https://github.com/user-attachments/files/19089473/sepolia_extraneous_log.json)
=> vm: filter eip6110 logs based on topic

packages/binarytree/src/binaryTree.ts, packages/evm/src/binaryTreeAccessWitness.ts, packages/evm/src/evm.ts, packages/evm/src/index.ts, packages/evm/src/interpreter.ts, packages/evm/src/message.ts, packages/evm/src/opcodes/EIP2929.ts, packages/evm/src/opcodes/functions.ts, packages/evm/src/opcodes/gas.ts, packages/evm/src/types.ts, packages/vm/src/runBlock.ts, packages/vm/src/runTx.ts
Various fixes related `binarytree` and `StatefulBinaryStateManager`
- Updated `evm`/`vm` to use the correct state manager if EIP 7864 is active
- Add `BinaryTreeAccessWitness` as optional property on `EVM`
- Fix bug in `createBinaryProof` where the whole key (instead of just the stem) was being passed to `findPath`
=> Binary Tree cleanup

package-lock.json, package.json, packages/client/src/net/server/rlpxserver.ts, packages/client/test/net/peer/rlpxpeer.spec.ts, packages/client/test/net/peerpool.spec.ts, packages/client/test/net/server/rlpxserver.spec.ts
This PR:
- Reolves #3913 by fixing bundle generation. It probably just broke because the required dependency was removed by this commit
[080ad6fa70fc091f#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L60)](https://github.com/ethereumjs/ethereumjs-monorepo/commit/42a8eb454d3b1878e73def85080ad6fa70fc091f#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L60)
- Upgrade non-eslint related dependencies from the root package json
- Removes the puppetteer core resolution, the issue related to the broken peer dependency seems to have disappeared through upgrading whatever package used it.
=> monorepo: fix bundling and upgrade non-eslint deps

packages/ethash/test/miner.spec.ts
Ethash tests do not run on a PR push, but they do run in the nightly runs which fail https://github.com/ethereumjs/ethereumjs-monorepo/actions/runs/13937007049. The eslint update https://github.com/ethereumjs/ethereumjs-monorepo/commit/5b81492d5fe6f70ab8f597b667beae28162b7b78 has shown that the test has been wrong the entire time: without `await`ing the method, it will return a `Promise`, which is truthy (so `.ok` is fine, which was before the commit/PR above). However, it is not equal to `true` (so `isTrue` will throw) which is why the nightly tests now fail.
The question is: why is this not caught by the linter? It is clearly a floating promise.
To test (this is not done on CI) one can test it locally to `npm run test` in the ethash package.
=> Fix Ethash tests

config/eslint.config.mjs, packages/rlp/eslint.config.mjs, packages/rlp/src/errors.ts, packages/rlp/src/index.ts, packages/util/src/errors.ts
This should be minimal impact, definitions of EthereumJSError is now in RLP, and re-exported from util. Also added the linter rules to RLP. 
Let's see if this works. It will slightly increase the RLP package size because we have the EthereumJSError definition but this is (obviously) less impact than making RLP depend on util.
=> RLP: Move EthereumJSError form util to RLP and start using EthereumJSError in RLP

packages/statemanager/src/simpleStateManager.ts
Jsdoc was kinda confusing since this is the ethereumjs/statemanager package. This replaces it with a link to the generated docs
=> Small jsdoc improvement to SimpleStateManager

packages/tx/src/capabilities/eip2930.ts, packages/tx/src/capabilities/eip7702.ts, packages/tx/src/capabilities/legacy.ts
This PR fixes the gas calculation in 7702. 
It also removes the `extraCost` param from the legacy `getDataGas`, this param has no use, one can just add the `extraCost` to whatever the method returns. 
This PR now passes https://github.com/ethereum/execution-spec-tests/releases/tag/pectra-devnet-6%40v1.0.0
Side note: we need a CI job or a tool which allows us to run these tests on the CI. The CI currently does not run the latest Prague tests.
=> Fix 7702 gas calculation

packages/tx/examples/setEOATx.ts, packages/tx/src/7702/tx.ts, packages/tx/src/constants.ts, packages/tx/src/index.ts, packages/tx/src/types.ts, packages/tx/src/util/authorization.ts, packages/tx/src/util/index.ts, packages/tx/test/util/authorization.spec.ts, packages/vm/src/runTx.ts
=> EIP 7702 authority list signing utilities

config/vitest.config.coverage.istanbul.mts, config/vitest.config.coverage.mts
Small config change to limit coverage reporting to only include the `src` folders from packages. Previously also `examples` and `scripts` had been included, which distorts the overall coverage results (see screenshot).
After:
=> Limit Coverage to src Folders

packages/block/src/types.ts
Make `totalDifficulty` field optional in the `JSONRPCBlock` type.
This field is a leftover from pre-merge days and is not even listed as part of the [execution API spec for blocks](https://github.com/ethereum/execution-apis/blob/main/src/schemas/block.yaml) any longer.  We don't use it internally in any of the constructors so there's no reason to require it in the input.
=> Remove `totalDifficulty` from `JSONRPCBlock` type required fields

packages/common/src/utils.ts
Adds the Osaka hard fork to `common/utils`. Required to run `consume engine` EOF tests in hive.
=> chore: add osaka hf to utils

packages/tx/src/capabilities/eip7702.ts, packages/tx/test/transactionRunner.spec.ts
Our current transaction tester is wrong, it passes tests where it should fail. This updates the test runner.
Here are also some txs to test for 7702 (generated with EEST). To run, place the contents of this zip in `ethereum-tests` and then change the lines in `transactionRunner.spec.ts` from
```
fileFilterRegex,
undefined,
'TransactionTests',
)
```
to
```
fileFilterRegex,
undefined,
'txs',
)
```
[txs.zip](https://github.com/user-attachments/files/19480417/txs.zip)
=> Tx: fix transaction tester

packages/block/src/consensus/clique.ts, packages/client/bin/utils.ts, packages/client/test/util/wasmCrypto.spec.ts, packages/common/src/types.ts, packages/common/test/customCrypto.spec.ts, packages/tx/CHANGELOG.md, packages/tx/src/1559/tx.ts, packages/tx/src/2930/tx.ts, packages/tx/src/4844/tx.ts, packages/tx/src/7702/tx.ts, packages/tx/src/legacy/tx.ts, packages/tx/src/util/authorization.ts, packages/tx/test/eip1559.spec.ts, packages/tx/test/eip4844.spec.ts, packages/tx/test/typedTxsAndEIP2930.spec.ts, packages/util/CHANGELOG.md, packages/util/src/signature.ts, packages/util/test/signature.spec.ts, packages/vm/test/api/EIPs/eip-7702.spec.ts, packages/vm/test/api/runBlock.spec.ts
Updates `@ethereumjs/util` `ecsign` method:
- Does not add 27 anymore to the recovery bit. This is a weird quirk from legacy txs where the recovery bit (unprotected) is 27 or 28
- Remove the `chainId` property of ecsign (this is used nowhere in our libraries, the place where it *could* have been used is the tx package: legacy txs with EIP-155 protection. It is handled within the package already (so util does not take care of this logic))
=> util/tx: change ecsign to not add 27 to `v` value

packages/client/src/sync/fetcher/fetcher.ts, packages/client/test/sync/fetcher/fetcher.spec.ts
At the RC releases PR https://github.com/ethereumjs/ethereumjs-monorepo/pull/3886 which only updated package.jsons, changelogs, readmes and package-lock, for some reason when running client in `tsx` mode (so `npm run client:start:ts`) the Fetcher `client/src/sync/fetcher/fetcher.ts` would throw:
```
TypeError: Cannot read properties of undefined (reading 'pipes')
at Readable.pipe (node:internal/streams/readable:670:13)
at BlockFetcher.write (/home/jochem/Documents/ejs/ethereumjs-monorepo/packages/client/src/sync/fetcher/fetcher.ts:500:8)
at BlockFetcher._fetch (/home/jochem/Documents/ejs/ethereumjs-monorepo/packages/client/src/sync/fetcher/fetcher.ts:519:12)
at BlockFetcher.fetch (/home/jochem/Documents/ejs/ethereumjs-monorepo/packages/client/src/sync/fetcher/fetcher.ts:552:32)
at …
```
=> client: fix new tsx behavior which overwrites (?) fields of subclasses

config/README.md, config/vitest.config.mts, packages/binarytree/package.json, packages/block/package.json, packages/blockchain/package.json, packages/client/package.json, packages/client/vitest.config.unit.ts, packages/common/package.json, packages/common/src/common.ts, packages/devp2p/package.json, packages/era/package.json, packages/ethash/package.json, packages/evm/package.json, packages/genesis/package.json, packages/mpt/package.json, packages/rlp/package.json, packages/statemanager/package.json, packages/tx/package.json, packages/util/package.json, packages/verkle/package.json, packages/vm/package.json, packages/vm/vitest.config.ts, packages/wallet/package.json
This updates our package.json to provide an entry point at `typescript` that can be specified with a `NODE_OPTIONS="--conditions=typescript"` node option and updates our internal execution scripts and vitest to use these entry points.  This allows us to run our code/tests with sources updated but without having to rebuild all packages when we run code from internal packages.
- Switches the exports map in each `package.json` to this
```json
"exports": {
".": {
"import": {
"typescript": "./src/index.ts",
"default": "./dist/esm/index.js"
},
"require": "./dist/cjs/index.js"
}
},
```
So that we have a special `typescript` condition that you can specify in `NODE_OPTIONS` as described above.  In doing so, it will then resolve the imports from `src/index.ts` instead of the compiled Javascript …
=> Use `src/**/*.ts` when developing locally

packages/block/README.md, packages/blockchain/README.md, packages/common/README.md, packages/devp2p/README.md, packages/ethash/README.md, packages/evm/README.md, packages/mpt/README.md, packages/rlp/README.md, packages/statemanager/README.md, packages/tx/README.md, packages/util/README.md, packages/vm/README.md
README updates for `block` and `blockchain`
- Removes long outdated explanations for `Buffer` -> `Uint8Array` and `Bigint` migrations (removed from all package readme where applicable)
- Removes old explanations for deprecated version changes that aren't applicable anymore
- Streamlines explanations around genesis state data
=> `Bigint` and `Buffer` conversion comment cleanups in READMEs

packages/common/src/chains.ts
Small PR to add the Prague hardfork timestamp from [EIP-6700](https://eips.ethereum.org/EIPS/eip-7600) and the fork hash, before we forget before releases. 🙂 
Fork hash has been taken from a Nethermind [PR](https://github.com/NethermindEth/nethermind/pull/8502/files) and confirmed with the following code:
```ts
c = new Common({ chain: Mainnet })
const fh = c.forkHash(Hardfork.Prague, hexToBytes('0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3'))
console.log(fh)
```
Ready for review and merge.
=> Common: Add Mainnet Prague Timestamp & ForkHash

packages/client/src/util/vkt.ts
This PR removes an unnecessary empty array initialization that was pointed out by @jochem-brouwer  in https://github.com/ethereumjs/ethereumjs-monorepo/pull/3973#discussion_r2041248173 but that had not addressed before the PR got merged.
=> util: remove unnecessary empty array assignment

Dockerfile
This change updates the dockerfile to use the same client folder path naming used in the other ethereumjs dockerfiles on hive in order to stay consistent with naming patterns.
=> Update Dockerfile WORKDIR path

packages/devp2p/README.md, packages/era/README.md, packages/evm/README.md, packages/tx/README.md, packages/vm/README.md
=> Doc Updates: Yet another round (EVM / VM / Other)

packages/ethash/package.json
This PR fixes #4005 by adjusting the ethash npm run test script so that it consider the global timeout specified in the ethash package.
This seems to be the culprit for both node20 and node22 (aside from some irregular client tests failing)
=> fix: nightly node tests

packages/statemanager/src/statefulVerkleStateManager.ts, packages/statemanager/src/statelessVerkleStateManager.ts, packages/vm/src/runBlock.ts, packages/vm/src/runTx.ts
This modifies our usage of `StatelessVerkleStateManager` in `vm` to import it only as a type so it does not get included in a bundle where the `StatelessVerkleStateManager` isn't actually used
=> Convert `StatelessVerkleStateManager` usage to type in `vm`

packages/block/README.md, packages/evm/README.md, packages/mpt/README.md, packages/statemanager/README.md, packages/tx/README.md, packages/vm/README.md
This PR adds some highlight section for our core packages at the beginning of the README docs.
=> Add README Package Highlights

packages/evm/src/eof/container.ts, packages/evm/src/eof/errors.ts, packages/evm/src/eof/verify.ts, packages/evm/src/errors.ts, packages/evm/src/opcodes/functions.ts, packages/evm/src/opcodes/gas.ts
This PR:
- Makes the EVMErrorMessage singular (EVMErrorMessages -> EVMErrorMessage)
- Renames EOFError to EOFErrorMessage to be consistnet with the above. 
The convention would then be: 
- Error messages live under an enum-like const/type that is named `XYZErrorMessage`
- Error classes or wrappers are named `XYZError` (e.g. EVMError)
- These error classes may have a message property that is then typed as `XYZErrorMessage`
=> evm: consistent error message names

packages/e2store/README.md
=> Improve e2store README

packages/e2store/README.md, packages/e2store/examples/e2hs.ts, packages/e2store/examples/era.ts, packages/e2store/examples/era1.ts, packages/e2store/package.json
- Creates `examples` directory.
- Adds examples scripts
- era
- era1
- e2hs
- Updates README with code section links to examples
- should auto populate README with `npm run examples:build`
- Fixes `npm run examples` scripts in package.json
=> e2store: examples directory and README update

.github/workflows/static-build.yml, packages/ethash/README.md, packages/genesis/README.md, packages/rlp/README.md, packages/wallet/README.md
This change:
* Renames the static-build workflow to include all packages being covered
* Fixes all action badge links
=> Rename static build ci job

packages/client/test/integration/miner.spec.ts, packages/client/test/integration/pow.spec.ts, packages/client/test/logging.spec.ts, packages/client/test/miner/pendingBlock.spec.ts, packages/client/test/rpc/debug/verbosity.spec.ts, packages/client/test/rpc/engine/newPayloadV1.spec.ts, packages/client/test/rpc/engine/newPayloadV2.spec.ts, packages/client/test/rpc/helpers.ts, packages/client/test/sim/beaconsync.spec.ts, packages/client/test/sync/fetcher/reverseblockfetcher.spec.ts, packages/client/test/sync/skeleton.spec.ts, packages/client/test/sync/txpool.spec.ts
This change is a followup to #3967 and aims to remove all non-essential logger usage in the client tests, [as mentioned by @holgerd77](https://github.com/ethereumjs/ethereumjs-monorepo/pull/3967#pullrequestreview-2764473155).
=> Logger usage removal in client tests

packages/block/examples/4844.ts, packages/evm/examples/4844.ts, packages/tx/examples/blobTx.ts, packages/vm/examples/vmWith4844.ts
All of our EIP-4844 examples are still using `shanghai` and manually activating EIP 4844.  This is no longer necessary as of Cancun so this updates the examples accordingly.
=> Update 4844 examples to cancun

config/cspell-ts.json, packages/client/src/miner/pendingBlock.ts, packages/client/test/rpc/engine/newPayloadV4.spec.ts
while debugging peerdas lighthouse was doing getpayload retries which was returning incomplete response on retry
=> client: fix getpayloadv4 to return execution requests as well on retry

CODE_OF_CONDUCT.md, README.md, packages/binarytree/README.md, packages/block/README.md, packages/blockchain/README.md, packages/common/README.md, packages/devp2p/README.md, packages/e2store/README.md, packages/ethash/README.md, packages/evm/README.md, packages/genesis/README.md, packages/mpt/README.md, packages/rlp/README.md, packages/statemanager/README.md, packages/testdata/README.md, packages/tx/README.md, packages/util/README.md, packages/verkle/README.md, packages/vm/README.md
This PR udates the footers on the README files to get the outdated ReadTheDocs documentation out there, it also ports the code of conduct over from there into the monorepo and links to this new ported file.
=> Update README EthereumJS Footers

packages/client/src/sync/fullsync.ts, packages/common/src/common.ts
Responding to a TODO found in `client/sync/fullsync.ts` regarding `common.nextHardforkBlockOrTimestamp`
> // TODO: Do something about super-ugly nextHardforkBlockOrTimestamp() method
---- 
This PR attempts to make this method a bit less ugly with:
- simplified logic
- more explicit merge hf handling
- more consistent type handling
- improved documentation
=> common: improve ugly method

packages/tx/src/1559/tx.ts, packages/tx/src/2930/tx.ts, packages/tx/src/4844/tx.ts, packages/tx/src/7702/tx.ts, packages/tx/src/legacy/tx.ts, packages/tx/src/util/internal.ts, packages/tx/test/base.spec.ts, packages/tx/test/util.spec.ts
This change addresses two `TODO`s from the codebase:
* Move the test for `valueBoundaryCheck()` from `base.spec.ts` which should hold tests that test the base transaction functionality, into a more appropriately named file, `util.spec.ts` for the helper function being tested
* Improve the method name by making it more specific
=> valueBoundaryCheck chores

packages/tx/README.md, packages/tx/examples/ledgerSigner.mts
Updates the "Signing with a hardware or external wallet" example in the tx package documentation to use the current API.
Fixes #3989
=> Fix outdated hardware wallet signing example

packages/common/src/common.ts, packages/common/test/benchmark/common.bench.ts
This updates how `_mergeParamsCache` and `_buildParamsCache` function to remove the spread operator which was recreating the params cache object each time we update the params cache (which happens a bunch of time in the course of instantiating a `common` instance ). 
This gives a roughly 6-8x performance improvement in this particular code segment.
=> Improve `paramsCache` updates

packages/common/src/enums.ts, packages/common/src/hardforks.ts, packages/common/src/utils.ts, packages/common/test/gethGenesis.spec.ts, packages/evm/src/evm.ts
do we want to add static bpo hardforks or inject them dynamically?
so:
1. have bpo1, bpo2,..bpo5 hardforks added in code and populate/update their dicts. this will allow configuring blobschedule for these hardforks for devnets,
2. inject bpo1, bpo2... hardforks based on parsing the blobschedule (and then we also maintain a default blobschedule objects in our chains as well which we use to inject these hardforks)
so ethereumjs view is:
1. if its a normal fork treatment affecting forkid then we will add 5 bpo forks statically to the code (and we will add more later when the need arises).,
2. if its not a normal fork treatment, then we will allow dynamic specification of bpos in blobsschedule
since it seems that there is desire for changing forkid with bpo forks, and 1. is simpler to …
=> common: add 5 bpo hardforks for blobSchedule specification

packages/util/src/bytes.ts
This fixes the VM nightly tests like [this](https://github.com/ethereumjs/ethereumjs-monorepo/actions/runs/17225705048/job/48869724463) to have the nightly tests running reliably and so to prepare for moving more test runs over to nightly.
The `package-lock.json` file is updated as well since this was necessary to re-trigger the error locally, indicating that the error was prevented on PRs still due to the cache not yet taking in the latest version from ESLint (so but it would have propagated to PRs anyhow at some point).
Will admin merge, a quick look would nevertheless be nice!
=> Fix VM Nightly CI

.github/workflows/block-build.yml, .github/workflows/blockchain-build.yml, .github/workflows/browser.yml, .github/workflows/build.yml, .github/workflows/client-build.yml, .github/workflows/common-build.yml, .github/workflows/devp2p-build.yml, .github/workflows/evm-build.yml, .github/workflows/examples.yml, .github/workflows/lint.yml, .github/workflows/lockfile.yml, .github/workflows/mpt-build.yml, .github/workflows/noCompile.yml, .github/workflows/node-versions.yml, .github/workflows/rlp-ethash-genesis-wallet-build.yml, .github/workflows/spellcheck.yml, .github/workflows/statemanager-build.yml, .github/workflows/tx-build.yml, .github/workflows/typecheck.yml, .github/workflows/util-build.yml, .github/workflows/verkle-build.yml, .github/workflows/vm-build.yml, .github/workflows/vm-nightly-test.yml, .github/workflows/vm-pr.yml
Updates actions/checkout@v4 to actions/checkout@v5 across CI workflows.
Upgrade to actions/checkout@v5 for improved performance and stability.
Reference:
Latest version: https://github.com/actions/checkout/releases/tag/v5.0.0
=> Update GitHub Actions

packages/vm/DEVELOPER.md
Nothing fancy just fixed a outdated link:
https://github.com/ethereum/tests/tree/develop/BlockchainTests/GeneralStateTests - outdated
https://github.com/ethereum/tests/tree/develop/docs/test_types/TestStructures/GeneralStateTests - new
=> docs: update outdated GeneralStateTests link

packages/common/src/hardforks.ts, packages/vm/test/api/t8ntool/t8ntool.spec.ts
This PR removes all EOF EIPs from the Osaka HF definition and generally levels the EIP inclusions by only leave the still relevant EIPs.
First run is to see what the tests will do, eventually needs an additional update.
=> Osaka EIP "Plainification" (EOF out!)

packages/evm/src/precompiles/05-modexp.ts
Follow-up on #4071 
The gas cost formula update for [EIP-7883](https://eips.ethereum.org/EIPS/eip-7883) was not yet fully correct (or there was an EIP update in between, not sure, but anyhow).
This PR applies two fixes and a few simplifications/clean-ups. This fixes the remaining 70 failing tests from the EEST Osaka tests.
(best to review commit-by-commit)
=> EIP-7883 Fixes

packages/client/test/rpc/engine/getPayloadV5.spec.ts
This fixes a small EIP-7826 (tx gas limit cap) related client test to get the nightly tests going again.
Will admin-merge, no production code touched.
=> Small Nightly Test Fix
