ethereumjs/ethereumjs-monorepo

lib/precompiled/01-ecrecover.js, package.json
This also fixes ecrecover in browsers and removes secp256k1 as a dependency for ethereumjs-vm.
=> Use ecrecover() from ethereumjs-util in the ecrecover precompiled contract

lib/runTx.js
Good for running `eth_call`'s in the provider engine and the testrpc in cases where the address specified has zero balance. `eth_call`'s are free, and in other ethereum implementations run just fine, and don't error when the sender doesn't have enough Ether.
=> Add option to skip balance check.

lib/runCode.js
as per README.md:
- `exception` - a `boolean`, whether or not the contract encountered an exception
=> fixed boolean logic to match the spec fixes #48

README.md
=> Fix doc for 0/1 exception attr of runCode callback

lib/hooked.js, package.json, tests/hooked.js
This is a helper for creating a vm with modified state lookups
this should be made obsolete by a better public API for StateManager
```js
var vm = createHookedVm({
enableHomestead: true,
}, {
fetchAccountBalance: function(addressHex, cb){ ... },
fetchAccountNonce: function(addressHex, cb){ ... },
fetchAccountCode: function(addressHex, cb){ ... },
fetchAccountStorage: function(addressHex, keyHex, cb){ ... },
})
vm.runTx(txParams, cb)
```
=> add hooked-vm utility and test

lib/opFns.js
Creating a PR for @dbrock's commit that adds some tasty debugging information.
comments appreciated -- maybe instead of reporting a string as an error we can use a more structured object
=> add location information to `invalid JUMP' errors

lib/index.js
Breaking change. I think it makes sense.
=> Since trie/blockchain is optional, move it into opts in the constructor

lib/runTx.js
Otherwise it can end up with negative gas usage.
=> Issue proper early warning if base fee exceeds gaslimit

README.md, lib/opFns.js, lib/runCode.js
This fixes https://github.com/ethereumjs/ethereumjs-vm/issues/113.
It also updates the README to correctly document the `suicides` variable, which was [already](https://github.com/ethereumjs/ethereumjs-vm/blob/d2713ce43816417f67611cdd84f7ebe9d3f97ddb/lib/runTx.js#L177-L18) an `Object` and not an `Array`. And it removes the `runState.suicideTo` variable since that information is already in `suicides`.
This change was tested by manually adding the [ZeroValue_SUICIDE_OOGRevert.json](
https://github.com/ethereum/tests/blob/3b90fbfaf0b6180be9276bbd050ac2475b95d949/BlockchainTests/GeneralStateTests/stZeroCallsRevert/ZeroValue_SUICIDE_OOGRevert.json) test file to `node_modules/ethereumjs-testing/tests/BlockchainTests`, in lieu of the pending test runner update …
=> fix selfdestruct revert bug

lib/constants.js, lib/opFns.js, lib/opcodes.js, lib/runCode.js
The first commit prevents `runState.gasLimit` from going negative and failing the test case [call_OOG_additionalGasCosts1](https://github.com/ethereum/tests/blob/e8ba92a9e20a252d215cbc95d314eba22b1d79c5/src/GeneralStateTestsFiller/stCallCodes/call_OOG_additionalGasCosts1Filler.json) under Homestead.
The second commit fixes the [shallowStack_d10g0v0_Homestead](https://github.com/ethereum/tests/blob/cffb263d6c9075e1396e72d5d8febc21329b6600/src/GeneralStateTestsFiller/stStackTests/shallowStackFiller.json#L42) test case, which executes the bytecode `0x60010b600055`:
```
[1] PUSH1 0x01 
[2] SIGNEXTEND 
[4] PUSH1 0x00 
[5] SSTORE 
```
and should throw an OOG due to a stack underflow.
The third commit fixes some failing edge cases in the …
=> Fix homestead [WIP]

.travis.yml, circle.yml
VMTests use Frontier gas costs, which means they fail if run in a VM using EIP150 gas costs. ethereumjs-vm would need conditional fork logic to continue passing the VM tests.
=> dont run testVM on CI

package.json
This solves an issue which causes `npm run testBlockchain` to fail under node8
=> increase maximum stack size for testBlockchain

README.md, tests/BlockchainTestsRunner.js, tests/tester.js
VM tests are disabled since they use Frontier gas costs, and ethereumjs-vm doesn't support historical forks.
=> debug flag for Blockchain test post state; disable VM tests

CHANGELOG.md, README.md, lib/opFns.js, lib/runCode.js, lib/runTx.js, lib/stateManager.js, package.json
* This is the working branch for remaining features in Spurious Dragon.
* If you'd like to help, check out ethereumjs/ethereumjs-lib on Gitter.
* Please be careful when pushing changes to this branch, especially if it reverts the work of others. If you aren't sure what to do next, ask in Gitter!
=> Spurious Dragon Working Branch

README.md
Current links points to markdown files which does not exists, changed for a link to the ethereumjs-block and ethereumjs-account repositories.
=> fix Block and Account links in README.md

lib/cache.js, lib/runTx.js
This fixes a bug introduced in [0b9e9a](https://github.com/ethereumjs/ethereumjs-vm/commit/0b9e9a340a608cd97c5d36e9d7b50d6c3f8a97ce) that was causing [examples/run-transaction-complete](https://github.com/cdetrio/ethereumjs-vm/blob/fix-cache-del/examples/run-transactions-complete/index.js) to fail with:
```
address created: 692a70d2e424a56d2c6c27aa97d1a86395877b3a
----running tx-------
/ethereumjs-vm/examples/run-transactions-complete/index.js:74
createdAddress = results.createdAddress
^
TypeError: Cannot read property 'createdAddress' of undefined
```
=> null address check before deleting account from trie

README.md, examples/run-transactions-simple/README.md, examples/run-transactions-simple/index.html, examples/run-transactions-simple/index.js
fix #149 and fix run-transactions-simple example
=> support npm run build command and fix run-transactions-simple example

lib/runCall.js
here is more details about the issue https://github.com/indutny/bn.js/issues/147
=> replace toBuffer => toArrayLike

lib/opFns.js
=> VM speedup by using in-place bn.js operators

lib/opcodes.js
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-141.md
Since all unknown OP code will fallback to `INVALID` pseudo instruction
https://github.com/ethereumjs/ethereumjs-vm/blob/master/lib/opcodes.js#L156
and `runCode` already handle the `opName === 'INVALID'` case, 
https://github.com/ethereumjs/ethereumjs-vm/blob/master/lib/runCode.js#L119
it's a 2 lines patch
Do i need to enable or write certain test cases to test this?
=> EIP-141: Designated INVALID instruction

lib/fakeBlockChain.js, lib/opFns.js
=> Fix some broken opcodes due to JS number issues

lib/index.js, lib/opFns.js, lib/runBlock.js, lib/runCall.js, lib/stateManager.js
The point of this is to avoid double serialisation. Currently bn.js is serialised to a Javascript Array which is then ported into a Javascript Buffer. After this change it is directly serialised into a Buffer.
=> Replace Buffer.from(bn.toArray()) with bn.toArrayLike(Buffer)

lib/opFns.js
It is handled above in the `if (diff < 0)`.
=> BLOCKHASH reading past genesis is handled elsewhere, so handle actual errors)

lib/runBlock.js
It is a best practice to pass an error object to a callback instead of a string.
~In this pull request I updated standard (to catch this errors in the future) and removed an unnecessary `return` statement (reported by `standard`).~
=> proper error objects on callbacks

lib/opFns.js, lib/runCode.js
=> Some smaller cleanups (mostly regarding calls)

tests/tester.js
This started failing when the tests submodule was updated.  Remove it from tests until the cause can be identified and fixed.
=> disable 'randomStatetest643'

.travis.yml, README.md, circle.yml, package.json, tests/tester.js
This reintegrates the blockchain tests to be run on travis builds (leaving ``BlockchainTests/GeneralStateTests``).
PR should be merged also on travis build failure since blockchain tests are failing for other reasons atm and this is just a basis for testing/fixing this.
=> Reintegrate blockchain tests

lib/opFns.js
This fixes test case `Call50000_identity`.
=> Avoid double-callbacks in CALL

package.json, tests/tester.js
This goes hand-in-hand with https://github.com/ethereumjs/ethereumjs-testing/pull/11
=> add support for specifying tests repo path as a command line argument

lib/opcodes.js, tests/GeneralStateTestsRunner.js, tests/tester.js
squashed https://github.com/ethereumjs/ethereumjs-vm/pull/170 with authorship retained.
=> add --jsontrace flag for state tests

package.json
These tests take too long.  I suggest we disable them automatically.
=> Disable GeneralStateTests suite in Blockchain tests

README.md, utils/diffTestOutput.py
This PR contains a script which takes two files containing TAP output from blockchain/state tests and produces concise diff of the differences between them.
Here is an example that compares the differences between the master branch and https://github.com/jwasinger/wip/metropolis (the work-in-progress branch for Byzantium implementation):
```
curl https://gist.githubusercontent.com/jwasinger/6cef66711b5e0787667ceb3db6bea0dc/raw/0740f03b4ce90d0955d5aba1e0c30ce698c7145a/gistfile1.txt > output-wip-byzantium.txt
curl https://gist.githubusercontent.com/jwasinger/e7004e82426ff0a7137a88d273f11819/raw/66fbd58722747ebe4f7006cee59bbe22461df8eb/gistfile1.txt > output-master.txt
python diffTestOutput.py output-wip-byzantium.txt output-master.txt
```
Results:
```
Diff of failed tests:
< …
```
=> Utility Script to produce diff of test output between runs

package.json, tests/util.js
Small PR to improve the test output:
1) Output the account address when using ``--debug`` flag with blockchain tests:
```
ok 7 correct balance
ok 8 correct nonce
ok 9 correct balance
ok 10 correct nonce
ok 11 correct balance
not ok 12 correct nonce
```
This greatly improves assignment of the error messages.
2) Downgrade ``tape`` dependency to fixed version to remove useless stacktrace output in ``tape`` greater ``4.6.3``. This change is already also included in ``wip/metropolis`` branch by @cdetrio, should be no problem to integrate on rebasing though.
=> Test output improvements

README.md, package.json, tests/tester.js
This PR adds the ability to test against custom-generated state tests.  The argument `--customStateTest` is used to specify the relative path of a file containing a custom test.
This PR is necessary for implementing trace equivalence testing and fuzz testing with EthereumjsVM.
Depends on changes in https://github.com/ethereumjs/ethereumjs-testing/tree/test-from-source
=> Add support to test a custom state test

CHANGELOG.md, package.json
Accidentally bungled the 2.3.0 release and because npm doesn't allow re-publishing, I am bumping the version to 2.3.1
=> Bump version to 2.3.1

lib/opFns.js
=> Add shortcut for empty memload/memstore

lib/precompiled/06-ecadd.js, lib/precompiled/07-ecmul.js, lib/precompiled/08-ecpairing.js, package.json
These changes checks for empty values returned by rustbn (depends on ethereumjs/rustbn.js#5 )
=> Avoid rustbn exceptions, check for empty values

README.md, tests/tester.js
This should largely help to bring failing tests from the skip lists under control. PR shouldn't also be too problematic since existing behavior of running tests with currently existing arguments stays the same.
The PR splits the existing tests skip list into three separate lists:
- ``BROKEN``: for tests which should be fixed
- ``PERMANENT``: for tests skipped due to system specifics / design considerations
- ``SLOW``: for tests running slow (run from time to time)
At the same time two new testing CL args are introduced, ``skip`` for skipping tests from one or more of the lists and ``runSkipped`` for only run the skipped-list tests.
These can be used like this:
```
node tests/tester -s --skip=BROKEN,PERMANENT
node tests/tester -s --runSkipped=SLOW
```
This allows for scenarios like only …
=> Split test skip list into separate "Broken", "Permanent" and "Slow" skip lists

README.md, tests/tester.js
- Removes now passing tests
- Removes tests not existing any more
- Moves some tests from the ``BROKEN`` to the ``PERMANENT`` skip list (see comments in the code)
=> Update of the skipped tests lists

README.md
Usage example from the tests [here](https://github.com/ethereumjs/ethereumjs-vm/blob/master/tests/VMTestsRunner.js#L35-L41) :)
=> Change name of step event's gas key in docs

lib/runCall.js, tests/tester.js
Current exception in randomStatetest is because an assertion in the bn.js module, it checks that the number to be added is less than 0x4000000
https://github.com/indutny/bn.js/blob/master/lib/bn.js#L2129
These changes checks returnFee, if its greater than gasLimit set it as gasLimit + 1, this avoids BN assertion failure when returnFee is bigger than 0x4000000 and ending as an OOG exception as expected.
Closes https://github.com/ethereumjs/ethereumjs-vm/issues/195
=> Fixes randomStatetest643 exception

tests/GeneralStateTestsRunner.js
See: https://github.com/ethereum/tests/issues/249
=> Print state root after transaction completion when --jsontrace is specified

lib/opFns.js, lib/runCall.js, lib/runCode.js
Fixes #167. Depends on #175, #179, #186 and #188.
=> Rework memory expansion/access in opFns

lib/opFns.js
=> Restrict direct stack usage in opfns

lib/exceptions.js, lib/runCode.js
This helped find some of the bugs already fixed, though it may be useful in the future too.
=> Validate stack items after operations

lib/cache.js
Tests pass, so looks like the trivial workaround doesn't break anything below.
=> Fix #81 by checking it.value is valid

lib/opFns.js, lib/precompiled/01-ecrecover.js, lib/runCall.js, package.json
Fixes #156.
Still wrapping my head around the code, so any suggestions are welcomed. I just made sure the state tests were passing.
=> Update ethereumjs-util to 5.1.3

lib/runTx.js
Otherwise, the resulting trie is incorrect (because contents in the cache are not included if they are not flushed)
=> Emit tx log step after cache is flushed

lib/opFns.js, lib/precompiled/01-ecrecover.js, lib/precompiled/02-sha256.js, lib/precompiled/03-ripemd160.js, lib/precompiled/04-identity.js
=> Use bn.js eq and lt instead of cmp

README.md, lib/index.js
=> Support external statemanager in VM constructor

.travis.yml, README.md, package.json, tests/tester.js
=>  Run coveralls on travis

lib/runCall.js
Fixes #235. Split off #272.
Reason: https://github.com/indutny/bn.js/issues/176
=> Properly calculate totalgas for large return values

lib/runCode.js
To ensure those conditions still generate a valid step for `runStepHook` handler.
The initial checks otherwise prevent certain situations from generating steps (e.g. for trace output)
=> Move initial iterateVm checks to after step hook

README.md, lib/index.js, lib/runCall.js
I'm creating a real-time Solidity debugger runtime for an [Augur bounty](https://github.com/augurProject/augur-bounties#-bounty-2-portable-solidity-debugger).
To do this sanely, compiler optimization needs to be turned off for the developer to be follow a logical stepping process; otherwise it's possible for the compiler to optimize things away and cause unexpected behavior from a debugging perspective.
Unfortunately, turning off optimization can mean very large compiled contracts. [EIP 170](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-170.md) prevents contracts with more than `0x6000` bytes (or 24KB) from being created. The rationale for EIP 170 (as I interpreted it) was really to address scaling from a global perspective, however I can see it acceptable to allow users to ignore …
=> Add option to ignore EIP 170 for debugging purposes

README.md, lib/runTx.js
Fixes #283
Excerpt to #283 that this PR implements:
> I can see why we shouldn't change the reported gasUsed, because it's the amount of net gas that was removed from the sending account. However, ethereumjs-vm should at a minimum report the gasRefund to let callers know that additional gas may be needed to actually execute the transaction. I believe this proposal makes sense, but I'd love to talk alternatives if it's not quite right. I'm going to go ahead open a PR that implements this proposal.
=> Add Gas Refund to Transaction Results

lib/runCall.js, lib/stateManager.js
Fixes test RevertInCreateInInit for #272 as per eq. 79 of the yellow paper. I wasn't entirely sure if any explicit cleanup of the storage trie was required but the tests do indeed all pass now 🎉  
I've done the cleanup in `stateManager` to ensure all storage tries and the cache are maintained correctly. This makes the change a bit more verbose but hopefully a little bit more stable. I've also refactoring the common elements of `stateManager.putContractStorage()` and the new method `stateManager.clearContractStorage()` into a private method `_modifyContractStorage`.
=> Created contract accounts should have nonce 1 and storage empty

README.md, lib/index.js, lib/runCall.js
This PR is in support of the new/upcoming [Velma Solidity Debugger](https://github.com/SeesePlusPlus/velma), which is a real-time (rather than trace analyzer) Solidity debugger with supported [VS Code extension](https://github.com/SeesePlusPlus/vscode-velma-debug).
This PR introduces an option to the `new VM()` API called `emitNewContractEvents` (I am flexible with the name) which will emit an event named `newContract` (also open for name change) which provides a new contract's created address and it's deployment/creation bytecode (for reference/identification of the contract).
This event occurs immediately after the address is created for the new contract instance; this allows 3rd party libraries to know about the address before the constructor is executed. For example, this allows …
=> Add option to emit 'newContract' events

lib/exceptions.js, lib/runCode.js
This solves https://github.com/ethereumjs/ethereumjs-vm/issues/191 by throwing all programmatic errors not being internal errors of the VM (like ``OUT_OF_GAS``).
Behaviour can be tested by introducing a JS runtime error in ``opFn.js``, e.g. by adding:
```javascript
var test = toast - tee
```
as a first line in the ``ADD`` opcode and then run a state test encompassing this opcode in the stack:
```shell
node tests/tester.js -s --test='add11'
```
Behaviour before:
```shell
$ node tests/tester.js -s --test='add11'
TAP version 13
not ok 1 the state roots should match
---
operator: equal
expected: |-
'17454a767e5f04461256f3812ffca930443c04a47d05ce3f38940c4a14b8c479'
actual: |-
'3d0b7c83da4ae1c5eb6964cbfb1ffb248498ce6560113458ce7d963fff8cb449'
at: replenish …
```
=> Throw original error and terminate execution on programmatic errors

lib/index.js, lib/runBlock.js, lib/runBlockchain.js, lib/stateManager.js, tests/BlockchainTestsRunner.js
=> Some cleanup for stateManager

README.md, lib/index.js, lib/opFns.js, lib/precompiled/01-ecrecover.js, lib/precompiled/02-sha256.js, lib/precompiled/03-ripemd160.js, lib/precompiled/04-identity.js, lib/precompiled/05-modexp.js, lib/precompiled/06-ecadd.js, lib/precompiled/07-ecmul.js, lib/precompiled/08-ecpairing.js, lib/runBlock.js, lib/runCall.js, lib/runCode.js, lib/runJit.js, lib/stateManager.js, package.json, tests/BlockchainTestsRunner.js, tests/GeneralStateTestsRunner.js
**Summary**
This PR replaces the old ``common`` library with the new ``ethereumjs-common`` library and introduces two new VM options ``chain`` and ``hardfork``.
This will allow for the following:
- In-parallel development on future HF features
- Modular HF dev with separated PRs, no need for one big switch-over PR
- Parallel support of different HFs (necessary for client) at least from Byzantium onwards
- Easier release management on HF updates
**Note on API design**
The API extension for the moment has kept simple with either statically setting ``chain`` and ``hardfork`` or by default falling back to a ``mainnet`` ``byzantium`` setting - also for the sake of backwards compatibility. In the future this can be extended to allow the option to directly derive these settings from the …
=> Improve chain and fork support

lib/opFns.js, lib/opcodes.js, lib/runCode.js
Based on https://github.com/ethereum/EIPs/blob/master/EIPS/eip-145.md
=> Implement bitwise shifting

lib/index.js, lib/opFns.js, lib/runBlockchain.js, lib/runCode.js, lib/stateManager.js, tests/BlockchainTestsRunner.js
This is part of the broader discussion in #268 and #309 so readers should probably start there.
The basic premise is that `getBlockHash` should not be on `stateManager`. This is the only block property that is present on `stateManager` and it doesn't really fit. Removing this also means the ctor doesn't need to take a blockchain which simplifies the interface as per #268.
=> Remove blockchain from stateManager

.gitignore, package.json
According to the comments in #327, this PR replaces `istanbul` with `nyc` for test coverage.
=> From Istanbul to NYC

.circleci/config-blockchain-tests.yml, README.md
Solution is a bit more elegant than proposed in: https://github.com/ethereumjs/ethereumjs-vm/issues/337
This PR introduces a new CircleCI job ``run_blockchain_tests``. This job is ignored on regular PRs and only triggered (then skipping all the other test executing jobs) on a branch named ``run-blockchain-tests. Have only added this to the README docs.
Like this we can easily trigger test runs on Circle (we have to see once how long this will take though), we might even just keep a permanent ``run-blockchain-tests`` PR where tests are retriggered every now-and-then by rebasing.
Will also submit another PR named differently for a negative-test.
=> Easier triggering of BlockchainTests test runs on CircleCI

tests/api/fakeBlockChain.js, tests/api/runJit.js
This PR contains tests for `runJit` and `fakeBlockchain`. I bundled them together since the changeset was rather small.
=> API Tests for runJit and fakeBlockchain

package.json
The coverage command only runs the state tests, resulting in confusing reports for modules like `runBlock` and `runBlockchain`. This PR adds a `-c` flag to the test runner, which runs `cacheTest`, `bloomTest`, `gensishashes`, state tests, and the `bcTotalDifficultyTest` dir as a sample of blockchain tests.
It furthermore fixes `cacheTest` and `genesishashes` which were still using on `vm.trie` directly.
Update: The contents of this PR were [changed](https://github.com/ethereumjs/ethereumjs-vm/pull/327#issuecomment-416245590), refer to [discussion](https://github.com/ethereumjs/ethereumjs-vm/pull/327#issuecomment-416271023)
=> Include API tests in coverage

lib/cache.js, lib/opFns.js, lib/runCall.js, lib/runCode.js, lib/runTx.js, lib/stateManager.js
This is part of the broader discussion in #268 and #309 so readers should probably start there.
This PR simplifies the `stateManager` interface by removing the two-phase commit that is exposed by `stateManager`. In the old setup a contract account goes through an extra phase of commit/revert so as to cope with the consensus bug after EIP-161 (https://github.com/ethereum/EIPs/blob/master/EIPS/eip-161.md). The aim here was to reproduce a behaviour whereby a precompiled contract is considered touched even in the case where an OOG error occurs. The new implementation introduces an explicit touch of a precompiled contract in the case of an OOG error in `runCall` and more closely matches the implementation used in other evm implementations. It also simplifies the interface of `stateManager` …
=> Remove contract specific commit

.circleci/config.yml, lib/fakeBlockChain.js, lib/runBlockchain.js, tests/api/runBlockchain.js
This is part of the PR series for adding API tests to the vm:
* Adds `iterator` to `fakeBlockchain` to facilitate testing
* Fixes a minor issue for propagating errors in `runBlockchain`
* Adds tests for `runBlockchain`, considering the new API with `blockchain` moving out of `stateManager`.
=> API Tests for runBlockchain

package.json, tests/tester.js
This PR runs the VM on the latests tests, I've done a new ``ethereumjs-testing`` [v1.2.1]() release, also added some CHANGELOG entry on the updates on the testing repository.
I will close https://github.com/ethereumjs/ethereumjs-vm/pull/305, since this brings not enough value with minimal changes and three commits to rebase this and bring this in order.
We can nevertheless reference this here for going back to the notes already done on some test results.
=> [WIP] Run with the latest tests (ethereumjs-testing v1.2.1)

package.json
PR to run the VM against the latests ``ethereumjs-testing`` release [v1.2.2](https://github.com/ethereumjs/ethereumjs-testing/releases/tag/v1.2.2).
=> Run with the latest tests (ethereumjs-testing v1.2.2)

README.md
Thanks to https://github.com/tenthirtyone for catching this.
This fixes a typo that 0x6000 is 24k and not 2k.
See https://github.com/trufflesuite/ganache-cli/pull/571 for details.
=> Fix readme typo for EIP-170 (2k -> 24k)

lib/runTx.js, tests/api/runBlockchain.js, tests/api/runTx.js, tests/api/utils.js
This PR is part of the [series](https://github.com/ethereumjs/ethereumjs-vm/pull/315) for adding API test coverage. It:
- Adds tests for `runTx.js`
- Modifies `lib/runTx.js` to add two validation checks. Furthermore it moves the check for `populateCache` flag to the beginning of function.
- A test Related to `populateCache` fails. I'm not sure if the test case makes sense. I assumed `runTx` should run even when `populateCache` is false, the difference being that no cache is utilized. However, `runTx` fails because it tries to use cache nevertheless.
- Moves `createGenesis` utility to `utils.js` file.
=> Add runTx API tests

lib/fakeBlockChain.js, lib/stateManager.js, tests/api/index.js, tests/api/stateManager.js, tests/api/utils.js
This PR is part of the [series](https://github.com/ethereumjs/ethereumjs-vm/pull/315) for adding API test coverage. It:
- Adds tests for `index.js`
- Adds basic tests for `stateManager.js`
=> Add API tests for index, stateManager

lib/bloom.js, lib/opFns.js, lib/runBlockchain.js, lib/runCall.js, lib/stateManager.js, tests/util.js
This PR updates a few of the JSDoc comments that were incorrectly listing the arguments of the functions they were documenting.
=> Update JSDoc comments to add missing parameters

lib/hooked.js, lib/stateManager.js, package.json, tests/api/index.js, tests/api/stateManager.js
``ethereumjs-util`` update to ``v6.0.0`` as preparation for https://github.com/ethereumjs/ethereumjs-vm/pull/329.
=> Update of ethereumjs-util to v6.0.0

package.json
Run the VM on the latests tests included in ``ethereumjs-testing`` [v1.2.3](https://github.com/ethereumjs/ethereumjs-testing/releases/tag/v1.2.3).
The new tests should now be on a greater part ready to be used for Constantinople testing, especially new ``SSTORE`` gas price calculations are now included through a complete test refill (consistency/accuracy not confirmed though yet).
=> Run with the latest tests (ethereumjs-testing to v1.2.3)

lib/opFns.js, lib/runCode.js, package.json, tests/constantinopleSstoreTest.js, tests/tester.js
Depends on ethereumjs/ethereumjs-common#27.
Closes #354
I wasn't sure about the best way to test this PR since there aren't any EIP-1283 tests yet in ethereum/tests, so I created my own tests in ``tests/constantinopleSstoreTest.js`` until official tests are available. These tests are currently not being run in circleci. Ideas?
=> EIP 1283 SSTORE

package.json
Run with the latest tests from ``ethereumjs-testing`` [v1.2.4](https://github.com/ethereumjs/ethereumjs-testing/releases/tag/v1.2.4).
This is fixing various blockchain tests, see release notes for details.
=> Run with the latest tests (ethereumjs-testing to v1.2.4)

tests/BlockchainTestsRunner.js
This adds the usage of the new ``sealEngine`` parameter from the new blockchain test format (see this PR https://github.com/ethereum/tests/pull/533 over on the tests repo).
This should both fix currently failing blockchain tests due to not comparing to PoW-related params (``mixHash``, see [this](https://github.com/ethereum/tests/pull/533) comment e.g.) any more and at the same time significantly speed up blockchain test runs (we might be able to directly include these in the normal CI runs now, will do another blockchain test run after merge for getting the execution time).
=> Added usage of sealEngine to blockchain tests

lib/index.js, lib/opFns.js, lib/runBlock.js, lib/runCall.js, lib/runCode.js, lib/runTx.js, lib/stateManager.js, tests/api/runBlock.js, tests/api/runTx.js
This is part of the broader discussion in #268 and #309 so readers should probably start there.
One of the goals of defining and simplifying the `stateManager` interface is to allow others to implement their own underlying storage infrastructure which may or may not include caching. The current implementation exposes the cache both through direct accesses by the vm and through the `warmCache` method on `stateManager`. The existence of the cache is also exposed by the `populateCache` option on a couple of the vm methods. This PR acts to remove these in order to allow us to in future hide the existence of the cache from the vm entirely.
The change essentially removes the options, and modifies synchronous cache accesses, which assume the account has been preloaded, to instead operate against …
=> Remove explicit direct cache interactions

lib/stateManager.js, tests/api/stateManager.js, tests/api/utils.js
This PR fixes three currently failing blockchain tests:
- "OOGStateCopyContainingDeletedContract",
- "suicideCoinbase",
- "RecallSuicidedContractInOneBlock"
These started failing with https://github.com/ethereumjs/ethereumjs-vm/pull/147
The PR implements changes that are required for [EIP-158](https://github.com/ethereum/eips/issues/158). EIP-158 requires that accounts evaluated as empty be deleted.
With #147, we started checking if accounts were empty, in `runTx.js` by calling `stateManager.accountIsEmpty`. This in turn calls `stateManager.getAccount` which calls `cache.getOrLoad`.
The call to `cache.getOrLoad` is problematic because if it cannot find an account in the cache, it will add one to the cache. (Either the one it finds in the merkle tree / `cache.trie` or a new one.) However, …
=> Stop adding account to cache when checking if it is empty.

docs/index.md, lib/index.js, lib/opcodes.js, lib/runCode.js, tests/api/freeLogs.js
Some tools for debugging and creating coverage reports of contracts relay on adding events before compiling and testing, this is approach was proven to work on the solidity-coverage project https://github.com/sc-forks/solidity-coverage
By doing this, they elevate the cost of all the calls, and they can't cover views and pure functions, because the EVM will throw when those functions try to emit an event.
This _emitFreeLogs_ option allows instantiating an EVM instance without this limitation, enabling any contract to emit an unlimited quantity of events without modifying the block gas limit, and also to emit events during STATICCALLS.
**Note:**
Like _allowUnlimitedContractSize_, this (emitFreeLogs) option should only be used when debugging, any transaction calling the LOG opcode when this …
=> Add emitFreeLogs option - Used for debugging/coverage

lib/opcodes.js, tests/api/freeLogs.js
Error originated in #378 
Behavior:
Once the codes constant changed, the flag persisted until the VM was re-imported.
Desired:
New instances should always have false by default.
Added test case, should charge normal gas if flag is not set
=> Fix freeLogs, don't modify codes constant

lib/runBlock.js, tests/api/runBlock.js
This fixes the test GasLimitHigherThan2p63m1. `runBlock` should fail when the supplied block has a gas limit higher than `2^63 - 1` but currently this validation doesn't occur.
I ran into one of the failing blockchain tests from #338 whilst doing work on #376. The above test now passes but what I find odd is I can't find a reference to this in an EIP or in the yellow paper. I can see this exact logic present in `cpp-ethereum` and `go-ethereum` though so I thought I'd throw this out there. It might be the constant is better in `ethereumjs-common` but I left it in here for now; quite happy to update this if desired.
=> Fix failing blockchain test GasLimitHigherThan2p63m1

lib/opFns.js
This fixes the `BLOCKHASH` opcode which is essentially broken. Fixes the following blockchain tests:
* randomStatetest218BC
* randomStatetest240BC
* randomStatetest255BC
* randomStatetest331BC
* randomStatetest34BC
* randomStatetest35BC
* randomStatetest403BC
* randomStatetest431BC
* randomStatetest432BC
* randomStatetest598BC
* randomStatetest65BC
* BLOCKHASH_Bounds
* blockhashNonConstArg
* blockhashTests
=> Fix blockhash opfn

lib/opFns.js, lib/opcodes.js, lib/runCall.js
Depends on https://github.com/ethereumjs/ethereumjs-util/pull/146.
Closes #356.
=> EIP 1014 CREATE2

tests/tester.js
Just tested the tests marked as broken in the skipped tests list in ``tester.js``.
The following tests are passing now and can be reactivated:
```
'CreateHashCollision', // impossible hash collision on generating address
'RecursiveCreateContracts',
'createJS_ExampleContract', // creates an account that already exsists
'CreateCollisionToEmpty', // temporary till fixed (2017-09-21)
'TransactionCollisionToEmptyButCode', // temporary till fixed (2017-09-21)
'TransactionCollisionToEmptyButNonce', // temporary till fixed (2017-09-21)
'RevertDepthCreateAddressCollision', // test case is wrong
'randomStatetest642', // BROKEN, rustbn.js error
```
Last test still failing is one test from ``ecmul_0-3_5616_28000_96``.
=> Reactivated fixed tests from skipped broken tests list

docs/index.md, lib/cache.js, lib/index.js, lib/opFns.js, lib/runBlock.js, lib/runCode.js, lib/runTx.js, lib/stateManager.js, tests/api/index.js, tests/api/runBlock.js, tests/api/runBlockchain.js, tests/api/stateManager.js, tests/genesishashes.js
This is part of the broader discussion in #268 and #309 so readers should probably start there.
This PR removes all direct accesses, from the VM functions, to the `cache` and `trie`  properties of `stateManager`. This is essentially done by replacing calls to these properties to the equivalent   `stateManager` functions.
There are potentially two more controversial change here. The first is the removal of the  `loadCompiled` method on the VM. This method is unused internally and undocumented. It is problematic to keep this function as it interferes with checkpoint/commit structure used in `stateManager`. My assumption is that if someone desires this functionality they would interact with the `stateManager` directly prior to instantiating the vm. The second is the change of the `step` …
=> Remove vm accesses to stateManager trie and cache

lib/stateManager.js, tests/api/index.js, tests/api/runBlock.js, tests/api/stateManager.js
Now that the `vm` doesn't access the `cache` or `trie` directly (#376) these can be safely renamed to make them private. This PR is part of a long line of `stateManager` changes; see #309 and #268 for details.
=> Make stateManager cache and trie private

package.json, tests/tester.js
Running the latest tests ``v6.0.0-beta.2`` from ethereumjs-testing [v1.2.5](https://github.com/ethereumjs/ethereumjs-testing/releases/tag/v1.2.5).
=> Updated tests to v6.0.0-beta.2 (v1.2.5)

lib/opFns.js, lib/runCall.js, lib/runCode.js, lib/runTx.js, lib/stateManager.js, lib/storageReader.js, tests/api/storageReader.js
This PR is based on discussions in #268 and simplifies the `stateManager` interface used by the VM by removing dependencies on the following methods:
* `getAccountBalance`
* `putAccountBalance`
* `copy`
As per the discussion in #268 the balance methods have been removed as they are superfluously supported by both `ethereumjs-account` and by `stateManager`.
The dependency on the `copy` was introduced by #367 but this method in it's current form would be very difficult to document for an external interface. I've therefore removed this usage replacing it with a `storageReader` class which provides the necessary original value lookup caching.
=> StateManager interface simplification

lib/opFns.js, lib/opcodes.js
=> EIP 1052 EXTCODEHASH

lib/opFns.js
Fixes test TouchToEmptyAccountRevert3 on Constantinople.
Once #326 is merged this should mean all the tests now pass 🎉
=> Reset selfdestruct on revert

lib/stateManager.js
StateManager used `Buffer.from(address, 'hex')` to cast genesis state addresses to buffer, which returns empty after addresses were padded with `0x` in https://github.com/ethereumjs/ethereumjs-common/pull/33, resulting in some of the `runBlock` API tests failing.
=> Fix casting genesis state addresses to buffer

tests/cacheTest.js, tests/util.js
Follow-up to #319
This replaces usages of `sha3` missed in the `tests/` directory with the correct `keccak256`.
=> Replace usages of sha3 with keccak256

docs/index.md, lib/runCode.js
If a user modifies memory like shrinking and growing,
he also needs access to this property to reflect memory size changes.
~~This is needed to properly inject/modify the memory in the `step` event.
In my special case, I need to modify the `memoryWordCount` to properly
reflect changes.~~
~~Also, for other scenarios in the future, it might be necessary to have
the ability to have full access to the `runState` object.~~
=> runCode: Add `memoryWordCount` to the `step` event object.

lib/index.js, package.json, tests/api/index.js
Fixes https://github.com/ethereumjs/ethereumjs-vm/issues/411
=> Bugfix for opts.state overwrite

lib/stateManager.js, tests/api/runBlock.js, tests/api/stateManager.js
Fixes #417 
Clears the `stateManager` cache after setting the state root such that stale values are not returned. 
There's an additional problem whereby the empty trie root is apparently not included in the `merkle-patricia-tree` even when this is constructed empty. An additional check has been added to prevent this causing an error in `setStateRoot`, though I wonder if this should instead be changed in the `merkle-patricia-tree`.
=> Clear stateManager cache after setStateRoot

lib/cache.js
Uses `async.nextTick` to defer calling the callback in two `cache` async functions. Tested manually, but wasn't sure how best to write tests for such an issue. Happy to add tests if anyone has an idea.
Fixes #421.
=> Fix mixed sync/async funcs in cache

lib/bloom/index.js
Converts Bloom to an es6 class, and moves it to a directory to have it as a separate module.
My thinking is to structure the VM as multiple modules which contain most of the code, and in the root directory (`lib/`) have code that connects these individual modules together. This should also ease our way into a monorepo (if we decided to go for it). Bloom was a low-hanging fruit, I'll create an issue to discuss how to structure the rest of the code.
Bloom is used only internally, and is not exposed, so this shouldn't be a breaking change.
=> Convert Bloom to es6 class

lib/hooked.js
There is no field "cache" in stateManager, it is called "_cache"
=> fix typo: stateManager._cache

lib/bloom/index.js
Fixes #332 
Using the types that are expected in `utils.keccak256`, which is what `add` and `check` uses to process to params
=> Update API doc types for Bloom filter methods 

.gitignore, tests/BlockchainTestsRunner.js, tests/GeneralStateTestsRunner.js
Fix #390 
`stateManager.trie` should be `stateManager._trie` instead. I have also included a change to surface error message in test, as the testrunner was swallowing the error message, making it difficult to debug failing test.
=> Change stateManager.trie to stateManager._trie in GeneralStateTestsRunner

lib/runCode.js, lib/vm/memory.js, lib/vm/opFns.js, package.json, tests/api/vm/memory.js, tests/tester.js
This PR:
- Introduces the `Memory` class used for evm memory manipulation
- Removes `memStore` and `memLoad` and moves the logic to opcode handlers. The goal is to increase verbosity and reduce code hidden in utility functions
- In some opcodes, it reduces copy gas before attempting memory write
- The test cases `ExtCodeCopyTargetRangeLongerThanCodeTests` and `codeCopyZero` which were skipped previously have been fixed and are no longer skipped
- This is part of the same effort as in #424 and #431.
Similar to before, `offset` and `length` are cast from `BN` to normal JS numbers, which means if they're bigger than 53 bits `BN` throws an exception. Gas limit should probably cap how bug `offset` and `length` can become, but it might be better to address this issue somehow in future. The only …
=> Refactor memory manipulation in evm

package.json, tests/tester.js
Main trigger for this was that ``coverage`` was still running on ``Byzantium`` and so coverage was inaccurate since e.g. the new opcodes were not shown yet as covered.
I also updated the ``testBlockchain`` command to run on ``Petersburg``.
=> Complete switch to Petersburg on tests | Fix coverage

lib/vm/opFns.js, tests/tester.js
Fixes the case where `outLength` in `CALL` is longer than the actual data returned, which resulted in the difference being overwritten with zeros. This fixes the `CallIdentity_6_inputShorterThanOutput` test case.
=> Fix longer output than return length in call opcode

lib/precompiled/05-modexp.js
This PR attempts to fix #214. I tried to use `BN.mont` explicitly, but got some weird result:
`new BN(1).toRed(BN.mont(new BN('64', 16))).fromRed()` which I thought should return `0x1`, actually returns `0x18`! Not sure if this is a bug or intended?
Should I do benchmarks to make sure this is actually more performant?
~~Update: It's running out of heap memory on `modexp_37120_37111_1_1000000`~~
=> [WIP] Use BN reduction context in modexp precompile

tests/GeneralStateTestsRunner.js, tests/tester.js
This PR fixes the failing `ecmul_0-3_5616_28000_96` test case. You might notice that the fix is not done in code, but in the test suite. I noticed that the tx is not being executed at all, because the tx sender doesn't have enough balance, but I was puzzled why then this invalid test is failing. I found an explanation in https://github.com/PegaSysEng/pantheon/pull/106. Here's a summary:
A requirement of the test harness is that if a test is invalid and the coinbase account is empty, it should be dropped from the state. This is mainly for state tests, as in blockchain tests, an invalid tx is simply rejected.
It might be a good idea to verify this nevertheless.
=> Fix ecmul_0-3_5616_28000_96

karma.conf.js, tests/api/index.js, tests/api/runBlock.js, tests/api/runBlockchain.js, tests/api/state/stateManager.js, tests/api/state/storageReader.js, tests/api/utils.js
=> [WIP] Fix browser test issues

lib/index.js
This PR converts VM to a es6 style class. I also dropped `VM.deps`, as I wasn't sure what purpose it's serving, and why users can't require the libraries themselves. If there's a good reason why it's there let me know so I can add it back in.
=> Convert VM to es6 class

lib/state/promisified.js
One of the main sources of asynchrony in VM is the state manager. This wrapper allows us to slowly shift towards promises without having to modify the whole codebase at once. E.g. a new part that's being modernized could wrap its `stateManager` like this:
```javascript
const state = new StateManager()
const pstate = new PStateManager(state)
await pstate.getAccount(addr)
```
This is a temporary class and will have to be deleted when the whole codebase has transitioned to promises.
(Will be merged into #479)
=> [v4] Add promisified wrapper for stateManager

lib/evm/eei.js, lib/evm/loop.js, lib/evm/opFns.js
Async opcode handlers now return a promise instead of accepting a callback as argument.
(To be merged into #479)
=> Promisify async opcode handlers

lib/evm/loop.js, lib/index.js, lib/runTx.js, tests/api/runTx.js
Promisifies the internals of runTx by introducing an async method `_runTx` which `runTx` calls. For now most of the code which was in `runTx` is inside `_runTx` as is, without breaking them into separate methods. I'm thinking of abstracting some common patterns (between `runTx`, `Interpreter` and `runBlock`) e.g. updating an account's balance in future.
(To be merged into #479)
=> Promisify runTx internals

lib/runBlock.js, tests/api/runBlock.js
This PR:
- Rewrites `runBlock` internals with promises and async/await syntax
- It re-structures the code somewhat and breaks it into different methods
- One of my goals has been to reduce shared global state, and rather have methods that explicitly get some parameters and return results, and to reduce the region where side-effects happen. As such, most of the methods don't have side-effects (don't modify the block or state).
- I've also re-ordered some parts of the code where it doesn't change the logic to get closer to the above goals.
- This won't be the final state for `runBlock` and (similar to `runTx`) is the first iteration.
Some side note: Currently the types we have are very heavy and serve multiple purposes. E.g. `ethereumjs-block` contains RLP serialization/deserialization of …
=> Rewrite runBlock internals with async/await

lib/state/stateManager.ts, tests/api/state/stateManager.js
Previous to this PR copying a `StateManager` always returned one with a `Common` object set to `mainnet` and `byzantium` (see #524). Now the `Common` object is passed when copying a `StateManager`.
=> Pass the Common object when copying a StateManager

lib/index.ts, tests/api/index.js
Previous to this PR copying a VM always returned one with a `Common` object set to `mainnet` and `Petersburg`. It now passes the chain and hardfork info when copying it.
=> Accept a Common object when constructing the VM and pass it when copying it

tests/BlockchainTestsRunner.js
blockchain tests don't need to generate the gensis state as they come with their own `pre` world state. Avoiding this extra generation resulted in the duration of `npm run testBlockchain` going from 17m down to 2m on my local machine :grin: 
This is done via a trick: `runBlockchain` generates the genesis state when current state root doesn't match with the genesis state's root. So I manually manipulate `vm._common.genesis().stateRoot` to avoid generating the state.
I checked the source code, and this shouldn't have a side-effect (`common.genesis().stateRoot` doesn't seem to be used elsewhere). But still this is a trick and ideally `runBlockchain` would accept an option to disable generating genesis state (which would be a breaking change because it changes the parameter ordering, so I …
=> Avoid generating genesis state in blockchain test runner

lib/evm/eei.ts, lib/evm/interpreter.ts, lib/evm/loop.ts, tests/GeneralStateTestsRunner.js
While reviewing the codebase some calls to `Object.assign` caught my attention, as I suspected that they may be hiding some type errors. 
I replaced them with object literals using the spread operator (i.e. `{ ...obj }`) and normal field assignments to check if that was the case.
My suspicion turned out to be right, and I found two type errors in `Interpreter#runLoop`:
1. If `Loop#run` returned an exception, `null` was set as the result's `gasRefund` and `selfdestruct` fields.
2. The result's `runState` didn't type.
I tried to fix them, but I'm not familiar enough with the codebase as to be sure that my changes are correct.
For 1, I replaced the `null`s with the default values used to initialize those fields.
For 2, I made  `LoopResult#runState` non-optional, as I didn't find any instance …
=> Replace Object.assign calls and fix type errors

README.md, lib/index.ts, package.json, tests/api/evm/precompiles/06-ecadd.js, tests/api/evm/precompiles/07-ecmul.js, tests/api/evm/precompiles/08-ecpairing.js, tests/api/istanbul/eip-1108.js, tests/api/istanbul/index.js
Addresses https://github.com/ethereumjs/ethereumjs-vm/issues/539.
~WIP, first push to run the tests against `ethereumjs-common` [v1.2.1](https://github.com/ethereumjs/ethereumjs-common/releases/tag/v1.2.1).~
I think for the time of Istanbul development we should fix the common dependency version (have done this here) to have more predictable Istanbul behavior since EIPs might change and we don't want to do major version bump for every change here over on the `Common` side.
=> Istanbul Draft EIP-1108 Support

docs/README.md, docs/classes/statemanager.md, docs/classes/vm.md, docs/classes/vmerror.md, docs/enums/error.md, docs/interfaces/execresult.md, docs/interfaces/interpreterresult.md, docs/interfaces/runblockopts.md, docs/interfaces/runblockresult.md, docs/interfaces/runcallopts.md, docs/interfaces/runcodeopts.md, docs/interfaces/runtxopts.md, docs/interfaces/runtxresult.md, docs/interfaces/statemanageropts.md, docs/interfaces/txreceipt.md, docs/interfaces/vmopts.md, lib/bloom/index.ts, lib/evm/eei.ts, lib/evm/interpreter.ts, lib/evm/loop.ts, lib/evm/memory.ts, lib/evm/stack.ts, lib/state/cache.ts, lib/state/stateManager.ts
Regarding the names of `Interpreter` and `Loop`:
I think `Interpreter` makes more sense for `Loop` as it reads the bytecode and executes the opcodes. For the current `Interpreter`, the closest concept that comes to my mind is `StateTransition` or `TxExecutor` or `MessageRunner` or something of the like. Another alternative is simply `EVM` which is very general and vague. But I'm hoping others chime in here and come up with better names :)
=> Use typedoc syntax instead of jsdoc, add docs

CHANGELOG.md, package.json
Ok, have compiled down a first version of release notes 😄, this is still WIP though.
=> New release v4.0.0-beta.1

README.md, examples/run-solidity-contract/index.ts, examples/run-transactions-complete/index.ts, lib/evm/eei.ts, lib/evm/evm.ts, lib/evm/interpreter.ts, lib/evm/precompiles/01-ecrecover.ts, lib/evm/precompiles/02-sha256.ts, lib/evm/precompiles/03-ripemd160.ts, lib/evm/precompiles/04-identity.ts, lib/evm/precompiles/05-modexp.ts, lib/evm/precompiles/06-ecadd.ts, lib/evm/precompiles/07-ecmul.ts, lib/evm/precompiles/08-ecpairing.ts, lib/evm/precompiles/index.ts, lib/evm/precompiles/types.ts, lib/runBlock.ts, lib/runTx.ts
This is a WIP that simplifies the `ExecResult` type.
The changes I made so far are:
* Always use VMError, and not directly `ERROR`.
* Unified `ExecResult` and `PrecompileResult`.
* Moved `OOGResult` to `evm.ts`
* Renamed `EVMResult#vm` to `EVMResult#execResult`
Each of them is implemented in separate commits, so we can pick/discard whatever we want.
=> ExecResult simplification

lib/index.ts
This PR adds some doc to the VM about how/when the state is modified. It also documents how `AsyncEventEmitter` behaves wrt event handlers' exceptions.
=> Document VM methods' state modifications behavior

lib/state/stateManager.ts, tests/api/state/stateManager.js
=> Validate storage keys' length and improve doc

CHANGELOG.md, package.json
Still a bit unsure with the release process, but after some back-and-forth thinking it occurred to me that actually both TS respectively promsify updates (block, merkle tree, eventually blockchain as well) are breaking changes here due to the objects being able to be passed from the outside on the VM API.
So likely we will have to make a follow-up v5.0.0 release along with these anyhow (which is also no big deal I think, if necessary so be it). So we might as well just wait for both to be finalized and published to then at least have just one necessary breaking release on the VM, and we can/should then just do the v4 release just now, have this out and go on.
Let me know what you think and eventually approve if you go along.
=> New release v4.0.0

lib/evm/eei.ts, lib/evm/opFns.ts, lib/evm/opcodes.ts, tests/api/istanbul/eip-1344.js
Implements [EIP-1344](https://eips.ethereum.org/EIPS/eip-1344), closes #569. See #501 for discussion
=> Add CHAINID opcode for istanbul (eip-1344)

lib/runTx.ts
https://github.com/ethereumjs/ethereumjs-vm/commit/519a07646d4bd892c2427548fb79d6fa259d99b6#diff-f5570026bc45fa69b273a873ea7ab1c4R93 caused an unintended breaking change by changing the output of the error strings.
Also, I couldn't test this because I couldn't figure out how to get things working. I also couldn't push without adding `--no-verify` due to the linter not working out of the box (something about `ethereumjs-config-format` not available).
=> fix: tx error strings should not contain multiple consecutive whitespace characters

lib/evm/opcodes.ts, lib/index.ts
This PR includes 2 modifications:
- It removes the `dynamic` field from opcode info (fixes #573)
- It moves `CHAINID` opcode to an istanbul-specific list of opcodes and on instantiation of the VM updates the list of opcodes if HF is istanbul. This change is necessary for #581, and it can later on be generalized to every HF (as per discussion in #543). Another possible improvement is to store the list of opcodes in the VM instead of a global variable in `opcodes.ts`.
=> Maintain separate list of opcodes for Istanbul

lib/evm/eei.ts, lib/evm/opFns.ts, lib/evm/opcodes.ts, tests/api/istanbul/eip-1884.js
I just added a basic test case to see `SELFBALANCE` works. It should be tested more thoroughly when Istanbul tests are merged into `ethereumjs-testing`.
Fixes #579
=> Add EIP-1884 support for Istanbul

lib/evm/interpreter.ts, lib/evm/opcodes.ts, lib/evm/precompiles/09-blake2f.ts, lib/index.ts
Fixes #591, also related to #543
Instead of having a global list of opcodes in the `opcodes.ts` file, this PR sets this list as a property of the VM instance to avoid problems when two VM instances with different HFs are created.
I also made each opcode to be an object instead of a list. Objects are typed easily and are more flexible.
Note: If the Common instance of a VM instance is modified after construction, the list of opcodes will be out-dated.
=> Make list of opcodes property of VM instance

README.md, lib/evm/evm.ts, lib/evm/interpreter.ts, tests/api/events.js
This is a WIP PR, as I'm not sure about
1. Where to document this
2. Where to test it. Should I create a new file in `tests/api`?
Closes #574
=> Emit events before and after executing a message

lib/evm/evm.ts, lib/evm/interpreter.ts, lib/index.ts, lib/runBlock.ts, lib/runTx.ts, lib/state/promisified.ts, tests/api/runBlock.js, tests/api/runBlockchain.js, tests/api/runTx.js
This PR implements two performance optimizations. See #598 for more info.
=> Cache calls to promisify present in hot paths

README.md, lib/index.ts
=> Improve the VM's events' docs

lib/index.ts, lib/state/promisified.ts
Just a small PR responding to some comments from @holgerd77 in #600
=> Add an explanation on why we cache promisifyed functions

lib/evm/eei.ts, lib/evm/evm.ts, lib/evm/opFns.ts, lib/runTx.ts
To be merged into #607
Fixes #611
=> Store refund counter in EVM

package.json, tests/api/bloom.js, tests/api/istanbul/eip-1884.js, tests/api/istanbul/eip-2200.js
Upgrades to ethereumjs-util v6.2.0 and fixes failing test cases as described in #619.
=> Upgrade to ethereumjs-util v6.2.0

.circleci/config.yml, package.json
The main reason for this PR is to quickly identify what are the failing tests, instead of skimming through the thousands of lines in the test output.
This PR makes some changes on how tests are ran, so we can take advantage of test analysis and reporting by circleCI. Lifecycle additions:
1. Test commands got a `| tee -a results.tap` suffix. It gets `stdout` and `stderr` from tests, print them out to CI log and save them to a file, which is required for the following step.
2. The package `tap-xunit` converts the original tap format to [xunit](https://xunit.net/docs/format-xml-v2).
3. CircleCI reads that xml and produce a nice output and feed the tests metadata to their Insights platform.
Related: 
- [tape reporters](https://github.com/substack/tape#pretty-reporters)
- [xunit …
=> Test reporting improvements on CircleCI interface

lib/index.ts
Found an outdated param definition for `cb` in `runBlockchain` which was removed when promisified in https://github.com/ethereumjs/ethereumjs-vm/pull/546
=> chore: remove outdated cb param definition

examples/run-transactions-complete/index.ts
I was trying to recreate https://github.com/ethereumjs/ethereumjs-vm/issues/234 however it looks like the example code has since been updated and the output looked good to me.
I did find that the output for the contract balance was blank like so:
```
-------results-------
nonce: 01
balance in wei:
stateRoot: 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
codeHash: a6db6bcd1c3757abef01cdf587304df3698a3b1e6b93667fbe87072d261ee7e1
---------------------
```
It seemed strange so digging in it looks like `createdAccount.balance.toString('hex')` outputs a blank string on zero, so this PR outputs a more friendly `0`.
=> fix: properly output zero balance in examples/run-transactions-complete

.github/labeler.yml, .github/workflows/labeler.yml
Adds a PR labeler for the new monorepo package format thanks to [actions/labeler](https://github.com/actions/labeler).
See it in action with the 2 open PRs here: https://github.com/ryanio/ethereumjs-vm/pulls
closes #629
=> Add PR labeler for packages

.github/workflows/vm-coverage.yml, .github/workflows/vm-lint.yml, .github/workflows/vm-nightly-test.yml, .github/workflows/vm-test.yml
Adds caching of `node_modules` for faster gh action runs.
See how a cache hit looks [here](https://github.com/ethereumjs/ethereumjs-vm/pull/628/checks?check_run_id=348087266).
Note: we don't have a `package-lock.json` file in this repository so I am hashing `package.json` as the cache key instead (also what happens in current `.circleci`). @alcuadrado likes not having a `package-lock.json`  "as it forces us and the CI to experience the libraries as users would."
@evertonfraga suggested we run a nightly job without caching to catch any potential issues that may happen when an in-range dependency update breaks the build or tests, so I added `vm-nightly-test.yml` that runs without any caching.
Also accidentally missed running gh actions on `pull_request` so this PR includes that.
=> github actions: cache deps, run nightly test

CHANGELOG.md, README.md, docs/classes/statemanager.md, lib/state/stateManager.ts
While updating the links across the 6 repos for the migration, I bumped into these different formats for EIP links. As they does not impact the migration, I decided to update them now.
> **Preferred Citation Format [1]**
> The canonical URL for a EIP that has achieved draft status at any point is at https://eips.ethereum.org/. For example, the canonical URL for EIP-1 is https://eips.ethereum.org/EIPS/eip-1.
[Reference](https://github.com/ethereum/EIPs/blob/af677b348da866d41a58d8948a89d0b00d410e2b/README.md#preferred-citation-format).
=> Changes EIP links to preferred citation format

lib/evm/opcodes.ts, lib/index.ts, tests/api/index.js, tests/api/opcodes.js
When adding support for Istanbul opcode changes in https://github.com/ethereumjs/ethereumjs-vm/pull/582, I had taken an approach that was prone to errors when adding new hardforks, and this has happened. Muir Glacier doesn't inherit the opcode changes from istanbul.
I think it's still open how to approach opcode info for HFs, but for now I've changed the condition in `getOpcodesForHF` to apply istanbul changes to every HF gte Istanbul. Also added tests.
This needs to be released soon as it affects evm execution in Muir Glacier.
=> Fix getOpcodesForHF for when HF > istanbul

.github/workflows/vm-test.yml, package.json, tests/BlockchainTestsRunner.js, tests/GeneralStateTestsRunner.js, tests/tester.js, tests/util.js
The HF comparison error fixed in https://github.com/ethereumjs/ethereumjs-vm/pull/647 by @s1na was one of the most severe bugs in recent times, it actually makes the whole MuirGlacier pretty much unusable (this needs a bug fix release ASAP).
I am actually still amazed that this could slip through, this might need some further postmortem analysis. One major reason is actually the lack of consensus tests for the MuirGlacier HF.
This PR allows the VM to be tested with the MuirGlacier HF setting by falling back to the Istanbul tests. I also did some cleanup of the fork configuration in the test runner so to have a better distinction between the fork names/aliases used in the VM and the test runner.
I tested this with the pre #647 state of the VM (so what was actually released as the …
=> Run Consensus Tests on MuirGlacier

lib/evm/eei.ts, lib/evm/evm.ts, lib/evm/interpreter.ts
`DELEGATECALL` and `CALLCODE` call the code of contract B in the context of contract A. So that the environment's address is still A, but B's code is being executed. I need a reliable way of knowing which contract's code is being executed atm so I added `codeAddress` to the `step` event.
=> Add codeAddress to step event

karma.conf.js, package.json, tests/api/state/stateManager.js, tests/util.js
This PR:
1. Adds `tests/api/state/stateManager.js` back to karma.
1. Skips slow test when running in karma: `should generate the genesis state root correctly for mainnet`
1. Modifies test `should generate correct genesis state root for all chains` to `should generate the genesis state root correctly for all other chains` (since mainnet is already tested prior).
1. Runs karma in both headless Firefox and Chrome for increased browser coverage.
1. Removes unneeded `karma-detect-browsers`.
Closes #465
=> Add State Manager API tests to karma

package.json
This little change aims to allow cross-package tests using TypeScript + Lerna.
It solves the problem below, in the monorepo context:
=> Running API tests with ts-node

package.json
This commit fixes broken repository's package installation on Node v12 (#661).
1. Package `level` updated to version 6.0.0.
=> Fix Node v12 repo installation issue

packages/vm/docs/README.md, packages/vm/docs/modules/_state_cache_.md, packages/vm/typedoc.js
In the vm `state/cache.ts` has `@ignore` and had no documentation generated for it, so this PR removes the empty file by adding it to the `exclude` in `typedoc.js`.
=> Remove empty doc

.github/workflows/blockchain-lint.yml, .github/workflows/labeler.yml
This PR switches to using [Periodic Labeler](https://github.com/paulfantom/periodic-labeler) as a workaround for actions from forks lacking write access which renders [actions/labeler](https://github.com/actions/labeler) useless.
=> Fix PR Labeler

packages/vm/lib/index.ts, packages/vm/tests/api/index.js
This is the solution for #650 issue. What has been done:
1. Method `VM#init()` is added.
3. Method `VM.create()` is added.
2. Property `VM#isInitialized` is added.
3. Methods `VM#runBlockchain()`, `VM#runBlock()`, `VM#runTx()`, `VM#runCall()` and `VM#runCode()` are updated.
=> Add initialization method to prevent race conditions

.github/ISSUE_TEMPLATE/general.md, .github/ISSUE_TEMPLATE/package--ethereumjs-account.md, .github/ISSUE_TEMPLATE/package--ethereumjs-block.md, .github/ISSUE_TEMPLATE/package--ethereumjs-blockchain.md, .github/ISSUE_TEMPLATE/package--ethereumjs-common.md, .github/ISSUE_TEMPLATE/package--ethereumjs-tx.md, .github/ISSUE_TEMPLATE/package--ethereumjs-vm.md, README.md
This PR addresses some scattered changes.
The baseline of issue organization of a monorepo is to identify which package the issue relates to. GitHub issue templates help with that, in a way that users can choose the package from a list, and its corresponding label will be added upon issue creation.
[A simplified live example](https://github.com/evertonfraga/ethereumjs-vm/issues/new/choose):
Displayed in Twitter, Chat applications, sometimes on search results. Example:
Added to README.
<p align="center">
</p>
Closes #716.
=> Issue creation fitted to monorepo standards; README changes

packages/vm/lib/evm/evm.ts, packages/vm/lib/exceptions.ts, packages/vm/tests/api/runTx.js
**Revival of #676** 
Includes review fixes by @evertonfraga 
Addresses #672.
Have made a minimal reproduction of #672 at [cgewecke/checkpoint-repro][1]. It runs two transactions vs. ganache-core:
+ the first overflows an account balance and errors as expected with `Value overflow`
+ the second fails with `Cannot get state root with uncommitted checkpoints`, indicating that the previous tx has left the vm in an unresolved state.
This happens because the balance overflow error is thrown directly from `evm._executeCall` and `evm._executeCreate` without being handled via the revert/commit steps in the method which calls them ([evm.executeMessage][2])
PR
+ returns `Value overflow` exceptions as part of the vm result (instead of throwing), similar to the way contract creation address collisions …
=> Handle balance overflow as evm exception

codecov.yml
Aims to solve some false negative coverage tests, by setting a threshold to 1%.
Finishes one task at https://github.com/ethereumjs/ethereumjs-vm/issues/723
=> coverage: setting threshold to 1%

packages/tx/examples/custom-chain-tx.ts, packages/tx/examples/transactions.ts, packages/tx/src/transaction.ts, packages/tx/test/api.ts
This PR simply gets rid of the deprecated `new Buffer(…)` statements, in favor of `Buffer.from(…)`.
**How to validate it**
Test suite should not fire any warning.
Example of warning: https://github.com/ethereumjs/ethereumjs-vm/runs/572001912?check_suite_focus=true#step:5:17
=> Handles new Buffer() deprecation

packages/vm/lib/evm/interpreter.ts, packages/vm/lib/evm/opcodes.ts
> Recreated PR #659 
I've rewritten Opcodes creation logic what simplified Interpreter and made Opcode object itself easier to use and more informative.
1. Added new Opcode class with fields `code` and `fullName`. Class field `fullName` created for opcodes like PUSH, JUMP, etc. which have similar names. Now this name is calculated only once. Classes are what V8 optimizer loves to use for faster function optimization. Also I protect it from accidental changes with Object.freeze call, so it could be passed anyway without creating of a duplicate. The interface now looks like this:
```ts
class Opcode {
readonly code: number
readonly name: string
readonly fullName: string
readonly fee: number
readonly isAsync: boolean
// ...
}
```
2. Added createOpcodes factory into `lib/evm/opcodes.ts`. It …
=> Refactor opcodes

packages/vm/lib/runTx.ts, packages/vm/lib/state/cache.ts, packages/vm/lib/state/stateManager.ts, packages/vm/tests/api/istanbul/eip-1884.js, packages/vm/tests/api/istanbul/eip-2200.js, packages/vm/tests/api/state/stateManager.js
This PR is a quick fixup that removes the `await` in several `for await...of` loops that were in my latest promisification effort (#719). @kumavis [noted](https://github.com/ethereumjs/ethereumjs-vm/pull/719#discussion_r414815928) `for await` is for async iterators and thus is unneeded in these contexts.
=> Remove unneeded `for await`s

.github/workflows/vm-nightly-test.yml
This PR fixes the currently failing nightly blockchain test by adding a missing `actions/checkout@v1` step and making sure the lerna cmds run on root.
=> Fix nightly vm blockchain test

packages/common/src/chains/goerli.json, packages/common/src/chains/kovan.json, packages/common/src/chains/mainnet.json, packages/common/src/chains/rinkeby.json, packages/common/src/chains/ropsten.json, packages/common/src/hardforks/berlin.json, packages/common/src/hardforks/index.ts, packages/common/tests/hardforks.ts
Part of #736
+ [Berlin Meta: EIP 2070][1]
+ reference PR [ethereumjs-common 51][2]
[1]: https://eips.ethereum.org/EIPS/eip-2070
[2]: https://github.com/ethereumjs/ethereumjs-common/pull/51
=> Add common boilerplate for Berlin hardfork

packages/vm/package.json, packages/vm/tests/BlockchainTestsRunner.js, packages/vm/tests/config.js
This is a test run of the updated [v1.3.1](https://github.com/ethereumjs/ethereumjs-testing/releases/tag/v1.3.1) consensus tests referencing a state of `ethereum/tests` in a pre-Berlin HF state. Check is mainly for a first impression on how the tests behave.
See v7.0.0 pre-Berlin HF release PR https://github.com/ethereum/tests/pull/687 on the `ethereum/tests`repo for hints on what has changed there and what tests have been added.
[ DO NOT MERGE ]
=> Update to ethereumjs-testing v1.3.1 (pre-Berlin HF release) / Fix test runs

packages/common/docs/README.md, packages/common/docs/classes/_index_.common.md, packages/common/docs/interfaces/_types_.bootstrapnode.md, packages/common/docs/interfaces/_types_.chain.md, packages/common/docs/interfaces/_types_.chainstype.md, packages/common/docs/interfaces/_types_.genesisblock.md, packages/common/docs/interfaces/_types_.genesisstatestype.md, packages/common/docs/interfaces/_types_.hardfork.md, packages/common/docs/modules/_genesisstates_index_.md, packages/common/docs/modules/_index_.md, packages/common/docs/modules/_types_.md, packages/common/src/chains/goerli.json, packages/common/src/chains/kovan.json, packages/common/src/chains/mainnet.json, packages/common/src/chains/rinkeby.json, packages/common/src/chains/ropsten.json, packages/common/src/index.ts, packages/common/src/types.ts, packages/common/tests/hardforks.ts, packages/common/tests/testnet.json
As per https://github.com/ethereumjs/ethereumjs-vm/pull/755#discussion_r431622116, this PR removes old unused fields `consensus` and `finality`.
Please see [this commit](https://github.com/ethereumjs/ethereumjs-vm/pull/758/commits/e8c831b626c9408b4f9473bd3e18704dbb34fe03) for a clean diff prior to rebuilding docs.
=> common: remove old fields `consensus` and `finality`

packages/common/README.md, packages/common/docs/classes/_index_.common.md, packages/common/src/hardforks/berlin.json, packages/common/src/hardforks/byzantium.json, packages/common/src/hardforks/chainstart.json, packages/common/src/hardforks/constantinople.json, packages/common/src/hardforks/dao.json, packages/common/src/hardforks/homestead.json, packages/common/src/hardforks/istanbul.json, packages/common/src/hardforks/muirGlacier.json, packages/common/src/hardforks/petersburg.json, packages/common/src/hardforks/spuriousDragon.json, packages/common/src/hardforks/tangerineWhistle.json, packages/common/src/index.ts
As per https://github.com/ethereumjs/ethereumjs-vm/pull/758#pullrequestreview-423472672, this PR removes old unused fields `casper` and `sharding`.
=> common: remove old fields `casper` and `sharding`

packages/common/package.json, packages/common/src/chains/goerli.json, packages/common/src/chains/kovan.json, packages/common/src/chains/mainnet.json, packages/common/src/chains/rinkeby.json, packages/common/src/chains/ropsten.json, packages/common/src/index.ts, packages/common/tests/hardforks.ts
This PR adds forkhash support to the `Common` library in preparation for `eth/64` support for the `devp2p` library as outlined in https://github.com/ethereumjs/ethereumjs-devp2p/issues/55.
It does so by adding a new `Common.forkHash()` method which either returns the `forkHash` for a HF from a chain file or calculates via the newly added internal `_calcForkHash()` function.
I didn't add a `Common.forkHashes()` method yet as proposed [here](https://github.com/ethereumjs/ethereumjs-devp2p/issues/55#issuecomment-638896891). I am not completely sure about the output format.
Such a method can be added later if needed along the integration work on the devp2p library.
Fork hashes hardcoded in the chain files are validated with the `_calcForkHash()` function in the tests.
=> Add forkhash support to Common library

scripts/ts-interface-diff.sh
My goal is to quickly inspect what interfaces have changed since the packages' latest release. This is specially useful for releases.
Instead of going over `diff` for the source files (which would be chaotic), I chose to perform `diff` on the `.d.ts` files. They are generated at build time, therefore not part of this repo, so I can't use `git` to compare such files.
The `ts-interface-diff.sh` script downloads the latest published package, and compares the `.d.ts` files recursively to the ones found in the local `dist` directory, printing the diff to `stdout`. I made it generic enough to be used with any other package, so feel free to test it elsewhere, if you want.
Basic instructions on the script file itself.
1. make sure to have dist files for the package you want to inspect
```sh
npm i …
```
=> tooling: adding script to inspect TS interface diffs

README.md, package.json
Basic docs, showing how to quickly get started.
Please let me know your wishlist for these docs, as I will grow them in the following days.
=> Adds documentation for a smooth onboarding

packages/account/package-lock.json, packages/account/package.json, packages/account/src/index.ts, packages/account/test/index.spec.ts, packages/block/package-lock.json, packages/block/package.json, packages/block/src/block.ts, packages/vm/examples/run-blockchain/index.ts, packages/vm/examples/run-solidity-contract/index.ts, packages/vm/lib/index.ts, packages/vm/lib/runBlock.ts, packages/vm/lib/state/cache.ts, packages/vm/lib/state/stateManager.ts, packages/vm/package-lock.json, packages/vm/package.json, packages/vm/tests/BlockchainTestsRunner.js, packages/vm/tests/GeneralStateTestsRunner.js, packages/vm/tests/api/index.js, packages/vm/tests/api/runBlock.js, packages/vm/tests/api/state/cache.js, packages/vm/tests/api/state/stateManager.js, packages/vm/tests/tester.js, packages/vm/tests/util.js
This PR:
* Updates `merkle-patricia-tree` to v4
* Moves account trie-related methods to StateManager: `getCode`, `setCode`, `getStorage`, `setStorage`
* this was a suggestion from @s1na since he believes the vm was the only consumer of these methods
* Removes various unneeded `promisify`s
=> Update merkle-patricia-tree to v4, move account trie-related methods to StateManager

packages/vm/lib/evm/opcodes.ts, packages/vm/tests/api/runCall.js
Closes #543 
Some notes: I also have grouped pre-byzantium opcodes (homestead, that's `DELEGATECALL`), but `homestead` is not supported by the VM yet.
I have included a very simple test which obviously does not test all cases.
Also per the issue: I think that any gas cost changes should either:
1) should be read every time from the opcode call from common (think about `SLOAD`, `BALANCE`, etc.) 
2) if the call price is fixed (`SLOAD` for instance always charges the same amount of gas) then we should use the `fee` attribute of the opcode and change this fee if the gas price changes (ideally reading this once from common)
I tend to encourage us to use (2) since this does a single call to common for these constant-priced opcodes. (1) keeps calling common every time we use the opcode, though …
=> [VM] group opcodes based upon hardfork

packages/common/src/index.ts, packages/common/tests/hardforks.ts
Related to https://github.com/ethereumjs/ethereumjs-devp2p/pull/82
This PR adds the following methods to the `Common` library together with associated tests:
- `nextHardforkBlock()` - Returns the next HF block for a HF provided or set
- `isNextHardforkBlock()` - Some convenience additional utility method, matching the existing `hardforkBlock()` / `isHardforkBlock()` method setup
- `hardforkForForkHash()` - Returns the data available for a HF given a specific forkHash
All functions are triggered by needs of the Eth64 implementation, but will likely - especially the first two next-HF-block functions also be useful in other contexts, e.g. for switching the HF setting on the client along block download.
=> New utility methods for Common (loosely connected to Eth64 implementation)

packages/common/src/hardforks/byzantium.json, packages/common/src/hardforks/chainstart.json, packages/common/src/hardforks/constantinople.json, packages/common/src/hardforks/homestead.json, packages/common/src/hardforks/istanbul.json, packages/common/src/hardforks/tangerineWhistle.json, packages/vm/lib/evm/opFns.ts, packages/vm/lib/evm/opcodes.ts
Closes #803 
This PR moves all gas base fees to Common. It also disables checks within the opcodes to see if the opcode is available. These opcodes are not available if VM has a Common defined before the hardfork which introduced this opcode. See `getOpcodesForHF` [here](https://github.com/ethereumjs/ethereumjs-vm/blob/a44f7f0f34af6a3435b02b6da5171089ccac03e5/packages/vm/lib/evm/opcodes.ts#L283). 
Also started adding the right fee values for `ChainStart` and `TangerineWhistle` so this also introduces some work to support ChainStart/TangerineWhistle again! 😄  Related issue: #652 
This only makes `opcodes.ts` slightly less typesafe by calling `createOpcodes` in `getOpcodesForHF`.
=> [VM/Common] move gas base fees to Common

.github/workflows/vm-nightly-test.yml
Somehow this got messed up — probably in one of my recent refactors.
Related: #809
=> ci: Fixes scheduled slow tests for VM

packages/vm/lib/evm/eei.ts, packages/vm/lib/evm/evm.ts, packages/vm/lib/evm/opFns.ts, packages/vm/lib/index.ts, packages/vm/lib/runTx.ts, packages/vm/lib/state/cache.ts, packages/vm/lib/state/interface.ts, packages/vm/lib/state/stateManager.ts, packages/vm/package.json, packages/vm/tests/api/state/stateManager.js, packages/vm/tests/config.js
Initial push on `TangerineWhistle` support, I would assume that only the changes from [EIP-161](https://eips.ethereum.org/EIPS/eip-161) need to be separated for this to work.
Initial test run:
```shell
1..1096
```
Feel free to pick things up and continue on this.
=> TangerineWhistle HF Support

CHANGELOG.md, package.json
Hey @holgerd77,
I noticed that `ethereumjs-blockchain` had a tilde (`~`) dependency on `ethereumjs-util`, which meant that it didn't get any benefit from the backports you released today.
@evertonfraga already fixed this on `master`, but that change will only land in `@ethereumjs/blockchain` and not `ethereumjs-blockchain`, I created the `blockchain/4.x` the branch here and backported the fix. The branch names follow the new conventions, as instructed by Everton.
As this change is tiny, I also made the preparation of the new release here.
I think this should be the latest backport needed, but will rescan the dependency trees in search for more `~` dependencies.
=> Use the latest ethereumjs-util v6 in a new patch version of ethereumjs-blockchain

package-lock.json, packages/blockchain/package.json, packages/blockchain/src/index.ts, packages/blockchain/test/index.ts, packages/ethash/package.json, packages/ethash/src/index.ts, packages/ethash/test/block.spec.ts, packages/vm/lib/runBlockchain.ts, packages/vm/package-lock.json, packages/vm/tests/api/runCode.js, packages/vm/tests/api/state/stateManager.js, packages/vm/tests/util.js
=> Remove async dependency

scripts/check-dependencies.js
This PR adds a script that can be used to ensure that the dependencies of all the packages use the same versions. This is important to avoid duplicated dependencies.
I imported it as is from Buidler, so it may be a bit more strict than what we'd want here. Some very opinionated things are:
1. It ensures that every package has exactly the same version requirement, ignoring `semver` semantics at all. This could be relaxed, to only prevent incompatible version requirements, but IMO it's not worth the effort and may lead to less than ideal situations.
2. It ensures that every `peerDependency` is also declared as `devDependency` with the exact same version requirement.
I haven't set it up in the CI. The script is super fast, and doesn't require installing the dependencies, so it could be run …
=> Add a script to lint dependencies

packages/common/src/hardforks/berlin.json, packages/vm/lib/evm/interpreter.ts, packages/vm/lib/evm/opFns.ts, packages/vm/lib/evm/opcodes.ts, packages/vm/lib/evm/stack.ts, packages/vm/lib/exceptions.ts, packages/vm/lib/index.ts, packages/vm/package.json, packages/vm/tests/api/berlin/eip-2315.js, packages/vm/tests/api/evm/stack.js
#737 
Implements [EIP-2315][1] which introduces three new opcodes and a subroutine "return stack" to help separate control flow logic from computational operations on the main VM stack. This provides some efficiency benefits and is convenient for static analysis tools that require clear control flow semantics.
A detailed analysis of the EIP can be found at [ethereum-magicians here][2]
[2]: https://ethereum-magicians.org/t/eip-2315-simple-subroutines-for-the-evm-analysis/4229
[1]: https://eips.ethereum.org/EIPS/eip-2315
+ Added tests include the EIP examples plus a couple from the besu and geth implementations.
+ Have made the Stack class's overflow threshold configurable because the return stack's maximum height is spec'd at 1023 (1 less than normal)
(In draft pending updates to the …
=> Implement EIP-2315: subroutines

.github/workflows/vm-build.yml, .github/workflows/vm-pr.yml, package-lock.json
This PR:
* Runs `git stash` before github-action-benchmark
* Runs benchmarks on PRs
* Updates the root package-lock.json
=> Benchmark ci fixes

packages/vm/lib/evm/interpreter.ts, packages/vm/lib/evm/memory.ts, packages/vm/tests/api/evm/memory.js
=> Make `memory.ts` use Buffers instead of Arrays

packages/vm/CHANGELOG.md, packages/vm/README.md, packages/vm/lib/evm/interpreter.ts, packages/vm/lib/evm/opFns.ts, packages/vm/lib/index.ts, packages/vm/lib/runBlock.ts
Updated changelog/readme/docs of VM.
Some general remarks: it would be helpful if we would also review PRs on their documentation: if any external feature is added or changed, the docs should be updated (I found a few inconsistencies or errors). The same goes with the changelog: I had to go back to January this year to figure out what was changed or not. It would be helpful if we have some kind of procedure for this (such as adding items to an unreleased version paragraph in the changelog).
=> VM docs v5

packages/account/CHANGELOG.md, packages/vm/CHANGELOG.md
This PR adds UNRELEASED release notes for the `account` library and adds some more prose to the `VM` release notes for better readability and guidance on breaking changes building upon the additions from #846.
=> Account UNRELEASED release notes / Some more prose on VM release notes

README.md, package.json
Since `lerna clean` [does not remove the root `node_modules`](https://github.com/lerna/lerna/issues/1304), this PR adds project script `npm run clean` to remove root and package `node_modules` directories, useful before running `npm i` for a fresh install.
=> Add clean script

README.md
Dependencies are in fact moved to the root `node_modules`. 
The only hoist <=> symlink relation is with the executables, which are still linked from `packages/node_modules/.bin/script`, now to the root `node_modules`.
=> Fixing hoisting documentation

packages/block/karma.conf.js
If you guys recall reading The Pragmatic Programmer, you'll immediately know what I'm doing :)
Let's quarantine the FF issue to a single branch, so its side-effects do not affect orthogonal PRs. Until we fix the root cause, we can't guarantee correctness of our code in FF (Blink) engine anyway, so it at least do not affect every other PR build (including master).
=> Temporarily disabling FF karma testing on Block

packages/vm/lib/evm/opFns.ts, packages/vm/lib/runTx.ts, packages/vm/lib/state/interface.ts, packages/vm/lib/state/stateManager.ts, packages/vm/tests/api/runCall.js, packages/vm/tests/api/runTx.js
This PR fixes two bugs in the VM which appeared when we ran mainnet blocks in #853
They both have to do with Istanbul SSTORE gas calculation: the first fixes that the storage cache is only wiped after a block (if two txs write the same storage, then this slot is cached and there are some gas refunds which you get in the VM which should not happen). The second is checking if the slot has the same value; they can have the same value, but due to wrongly padded Buffers the VM thinks that the values are different. (i.e. the buffers `0x01` and `0x0001` are semantically in the VM the same value, but the Buffers are obviously not equal).
=> VM Bugfixes

packages/block/karma.conf.js
This PR will be a sandbox of some different approaches to make FF + Karma work on our CI properly.
Measures:
Hypothesis:
Cleanup:
Note: The commits will be squashed at the end, so the history will be clean.
=> Fixes Karma Firefox test inconsistency

packages/block/src/header.ts, packages/common/src/eips/EIP2537.json, packages/common/src/index.ts, packages/common/tests/eips.ts, packages/common/tests/params.ts, packages/vm/lib/evm/evm.ts, packages/vm/lib/evm/precompiles/index.ts, packages/vm/lib/index.ts, packages/vm/package.json, packages/vm/tests/BlockchainTestsRunner.js, packages/vm/tests/GeneralStateTestsRunner.js, packages/vm/tests/api/EIPs/EIP2537-BLS-tests.js, packages/vm/tests/api/index.js
Follow-up on #856 and #863 
This PR moves EIP integration from the VM to Common to be able to spawn EIP implementations across different libraries touched (as currently possible along hardfork lines). Upon this base integration it updates the EIP2537 integration in the VM.
The Common integration is hopefully somewhat future proof. I already added an additional check for `minimumHardfork` requirements where Common initialization will throw if not met (EIP2537 is currently set to chainstart, let me know if this is too low for some reasons).
Not yet integrated is a possible EIP dependency, e.g. when one EIP depends on one or several others. This could be implemented by adding a parameter `EIPdependencies` or the like to the `EIP*.json` files. Since this comes with some mild extra complexity …
=> Move EIP Integration to Common

packages/common/src/eips/index.ts, packages/common/src/index.ts, packages/common/src/types.ts, packages/common/tests/eips.ts, packages/common/tests/params.ts, packages/vm/CHANGELOG.md, packages/vm/README.md, packages/vm/lib/evm/precompiles/0a-bls12-g1add.ts, packages/vm/lib/evm/precompiles/0b-bls12-g1mul.ts, packages/vm/lib/evm/precompiles/0c-bls12-g1multiexp.ts, packages/vm/lib/evm/precompiles/0d-bls12-g2add.ts, packages/vm/lib/evm/precompiles/0e-bls12-g2mul.ts, packages/vm/lib/evm/precompiles/0f-bls12-g2multiexp.ts, packages/vm/lib/evm/precompiles/10-bls12-pairing.ts, packages/vm/lib/evm/precompiles/11-bls12-map-fp-to-g1.ts, packages/vm/lib/evm/precompiles/12-bls12-map-fp2-to-g2.ts, packages/vm/lib/evm/precompiles/index.ts, packages/vm/lib/index.ts, packages/vm/tests/BlockchainTestsRunner.js, packages/vm/tests/GeneralStateTestsRunner.js, packages/vm/tests/api/EIPs/EIP2537-BLS-tests.js, packages/vm/tests/api/index.js
This PR updates the new `eips` option in Common and VM to use type `number` instead of `string`.
The primary reasons discussed were for dev ex brevity (less bulky), and better long term performance (iterating and comparing numbers should be faster than strings).
=> Index `eips` by `number` instead of `string`

.github/workflows/vm-nightly-test.yml
Ideally, the cache should go after `npm install`, so it would generate/use cache based on hashes of the updated `package-lock.json` files.
- Decided to remove cache read/write altogether, so we guarantee no cache for empty keys are being created, or that it is using wrong cache keys
I'm making an `package-lock.json` audit, which I'll document and make use recommendations.
=> ci: Updated slow test files

README.md, packages/account/README.md, packages/block/README.md, packages/blockchain/README.md, packages/common/README.md, packages/tx/README.md, packages/vm/README.md
We don't use the [standard](https://github.com/standard/standard) command anymore. It was replaced by ESLint and Prettier.
=> docs: removing standard badge

packages/vm/tests/config.ts, packages/vm/tests/tester.ts
This PR (should) fix the nightly CI runs.
This PR fixes the amount of state tests which is based upon [this nightly run](https://github.com/ethereumjs/ethereumjs-vm/actions/runs/269725216). It also explicitly does a test in case we pass "0" tests to expected tests (I think this is more clean than not explicitly testing here).
=> vm tests: fix state tests count

packages/vm/lib/state/stateManager.ts, packages/vm/tests/api/state/stateManager.spec.ts
Closes #875 
Had a bit of a wrong understanding here, storage slot values should be stripped of leading zeros, which is now enforced in `putContractStorage`. Since putting >32 bytes storage values is not possible in EVM, this is now also disallowed. If we strip leading zeros this means that any zero-byte will immediately be detected as "delete value", both in StateManager but also in MPT, which is nice.
=> VM: Strip zeros when putting contract storage in StateManager

.github/workflows/vm-build.yml, .github/workflows/vm-pr.yml, packages/vm/developer.md
This PR:
* Disables `comment-always` to reduce verbosity of comments on commits with normal benchmark results.
* The gh action will make an alert comment on the commit if any of the runs exceeds the default 200% threshold as compared to the last run on master.
* Adds documentation link to benchmark [github page](http://ethereumjs.github.io/ethereumjs-vm/dev/bench/).
* Stores max 30 commits of historical benchmark data for master branch.
=> Benchmark action improvements (disables comment-always)

packages/block/src/block.ts, packages/block/src/header.ts, packages/block/src/types.ts, packages/block/test/block.spec.ts, packages/common/CHANGELOG.md, packages/common/README.md, packages/common/src/index.ts, packages/common/tests/chains.ts, packages/tx/CHANGELOG.md, packages/tx/src/types.ts, packages/tx/test/api.ts, packages/vm/CHANGELOG.md, packages/vm/lib/index.ts, packages/vm/tests/api/index.spec.ts
This PR updates the default HF to Istanbul in preparation for the v5 release.
=> Update HF to Istanbul

packages/block/CHANGELOG.md, packages/blockchain/CHANGELOG.md, packages/common/CHANGELOG.md, packages/ethash/CHANGELOG.md, packages/tx/CHANGELOG.md, packages/vm/CHANGELOG.md
Completion of the CHANGELOG files for the various libaries in preparation for the VM v5 release.
Dates on latest included merges are added to the commit messages, so some last PRs can be added upon the final release PRs (or - better - along eventually following feature PRs).
Updates here will be kept in sync with the TODO list from #907 upon pushes.
=> CHANGELOG Completion for VM v5 Release

package-lock.json, packages/block/package.json, packages/block/src/header.ts, packages/block/src/types.ts, packages/blockchain/package.json, packages/ethash/package.json, packages/tx/package.json, packages/tx/src/transaction.ts, packages/tx/src/types.ts, packages/vm/lib/state/stateManager.ts, packages/vm/package.json
This small PR bumps `ethereumjs-util` to [v7.0.7](https://github.com/ethereumjs/ethereumjs-util/releases/tag/v7.0.7):
* Updates vm `accountIsEmpty` check
* Imports `AddressLike` and `bnToHex`
=> Update ethereumjs-util to v7.0.7

packages/block/package.json, packages/blockchain/package.json, packages/blockchain/tsconfig.browser.json, packages/common/package.json, packages/common/tsconfig.browser.json, packages/ethash/package.json, packages/tx/package.json, packages/vm/package.json, packages/vm/tsconfig.browser.json
Addresses [leftover review comment][3] from #913/886. 
Follows pattern established in [merkle-patricia-tree 117][1]. 
Per [clarifying comment][2] there:
> Web bundlers just use the browser version when resolving requires/imports. Then they pass those versions to the rest of the toolchain, like uglify
There are 4 packages with browser builds:
+ block
+ common
+ ethash
+ tx
[1]: https://github.com/ethereumjs/merkle-patricia-tree/pull/117#issue-412233007
[2]: https://github.com/ethereumjs/merkle-patricia-tree/pull/117#issuecomment-622572455
[3]: https://github.com/ethereumjs/ethereumjs-vm/pull/886#discussion_r501610246
=> Add browser field to package.json's of modules with browser builds

.github/workflows/vm-pr.yml, packages/vm/lib/evm/opcodes/EIP1283.ts, packages/vm/lib/evm/opcodes/EIP2200.ts, packages/vm/lib/evm/opcodes/functions.ts, packages/vm/lib/evm/opcodes/util.ts
Thanks for the contribution, @jochem-brouwer!
Closes #928 and fixes nightly builds.
=> Fix Constantinople tests 

packages/block/CHANGELOG.md, packages/block/src/block.ts, packages/block/src/header.ts, packages/vm/tests/util.ts
This PR updates the `BlockHeader` factory methods to make the `BlockOptions` param optional.
=> BlockHeader: Make BlockOptions param optional

packages/blockchain/package.json, packages/blockchain/test/reorg.ts, packages/blockchain/test/util.ts, packages/vm/tests/BlockchainTestsRunner.ts, packages/vm/tests/config.ts
Closes #879 
This PR cherry-picks from #895 and does:
- Adds a specific (big) reorg test in the Blockchain
In this test, we create two chains: one chain which has a low difficulty and another one which has a higher difficulty, but this chain is actually **1 block behind** the other chain. This is possible due to the difficulty formula: if time since last block > 18 seconds, decrease the difficulty, if it is < 9 seconds, increase the difficulty. Block number is thus not a good identifier to find the "best chain" (which has the highest sum of difficulties, i.e. the Total Difficulty). In practice, this test first writes 65 blocks to the chain. Then it puts all the blocks in (64 blocks) which have a higher total difficulty: this thus **re-orgs 65 blocks**. Without any necessary change this …
=> Blockchain: Add reorg test + do not skip any reorg test in VM

packages/block/CHANGELOG.md, packages/block/src/header.ts, packages/block/src/types.ts, packages/block/test/block.spec.ts, packages/blockchain/test/index.ts, packages/blockchain/test/util.ts, packages/tx/CHANGELOG.md, packages/vm/CHANGELOG.md
Cherry-picked from #895 
It is (recently) not allowed anymore to edit params like `difficulty` in Header. In order to currently set the (right) difficulty in header (i.e. the canonical difficulty) then one has to create a mock Header and then call `canonicalDifficulty` on this mock Header. Then, one can create a new `Header` with the difficulty as returned by this `canonicalDifficulty` call.
It doesn't make a lot of sense to create a mock header.  We want to "just set it to the correct value".
This PR:
- Adds `calcDifficultyFromHeader` as a `BlockOption`. If this is defined, then this `Header` will be used to calculate the difficulty; any existing difficulty will be overwritten to this new, correct, value. Suggestion by @holgerd77 👍 
- Change tests in `blockchain` to use this new method. …
=> Block: add methods to calculate difficulty of a consecutive header/block

packages/block/CHANGELOG.md, packages/block/src/block.ts, packages/block/src/header.ts, packages/block/src/types.ts, packages/block/test/block.spec.ts, packages/block/test/header.spec.ts, packages/tx/CHANGELOG.md, packages/tx/src/transaction.ts, packages/tx/src/types.ts, packages/tx/test/api.ts
=> New freeze option to deactivate block, tx freeze / Fix block options passing

packages/blockchain/CHANGELOG.md, packages/blockchain/src/db/constants.ts, packages/blockchain/src/db/helpers.ts, packages/blockchain/src/db/manager.ts, packages/blockchain/src/index.ts, packages/blockchain/test/index.ts, packages/blockchain/test/reorg.ts, packages/blockchain/test/util.ts, packages/vm/examples/run-blockchain/index.ts, packages/vm/lib/index.ts, packages/vm/tests/BlockchainTestsRunner.ts, packages/vm/tests/api/index.spec.ts, packages/vm/tests/api/runBlockchain.spec.ts, packages/vm/tests/api/utils.ts
WIP. Cherry-picked from #895 and builds upon #927 
Closes #690 
This PR aims to:
- Fix concurrency issues when using the Blockchain (getters/setters now all wait)
- Document the library
- Make variable names more correct
- Make the library more readable (more docs, some (unnecessary?) recursion removed)
Also security:
- Genesis block should be put in the Blockchain constructor to prevent accidentally wiping the Genesis block from the DB / Tracking a completely other network (!)
- This also means that **putGenesis** is now not possible anymore. You set Genesis in constructor and it cannot change after that.
- Safe `static` constructor which throws if the `init` method throws
=> Blockchain concurrency and safety improvements

packages/block/src/block.ts, packages/block/src/header.ts, packages/block/test/block.spec.ts, packages/block/test/mockchain.ts
This PR: 
- Makes `blockchain` parameter mandatory in `validate` methods of `Block` and `BlockHeader`
- Adds `validateData` method to `Block`
- ~~Hoists the `extraData` check to the constructor of `BlockHeader`~~
Rationale:
If you called `validate` in `BlockHeader` without a `blockchain`, the **only check** which is being done is checking that `extraData.length` is within the current bounds of the maximum `extraData`. This can give consumers the false idea that the header is correct, but the method does practically nothing.
Validate is now explicitly used to `validate` against the parent `BlockHeader` (or `Block`). There is an additional function in `Block` which has the logic which does not need `blockchain` in case a consumer does have a block but no access to a blockchain. (We cannot …
=> Block: make blockchain mandatory in validation methods

packages/block/CHANGELOG.md, packages/block/src/block.ts, packages/block/src/header.ts, packages/block/test/block.spec.ts, packages/blockchain/CHANGELOG.md, packages/blockchain/src/index.ts, packages/blockchain/test/index.ts, packages/blockchain/test/reorg.ts, packages/blockchain/test/util.ts, packages/common/CHANGELOG.md, packages/common/src/chains/goerli.json, packages/common/src/chains/kovan.json, packages/common/src/chains/mainnet.json, packages/common/src/chains/rinkeby.json, packages/common/src/chains/ropsten.json, packages/common/src/index.ts, packages/common/tests/chains.ts, packages/tx/src/transaction.ts, packages/vm/examples/run-blockchain/index.ts, packages/vm/tests/BlockchainTestsRunner.ts, packages/vm/tests/api/index.spec.ts, packages/vm/tests/api/runBlockchain.spec.ts, packages/vm/tests/api/utils.ts
This PR provides some ground for a future PoA support, see #689. I am doing this now since I hope that this will allow us for a future PoA feature addition without the need for another major release respectively introducing breaking changes. I have done some reading along on the Clique PoA [EIP-225](https://eips.ethereum.org/EIPS/eip-225) and I think this should get a solid enough structural setup with this PR which should allow for non-breaking integration (by adding signer validation on PoA chains along an activated `Blockchain.validateConsensus` setting), this might benefit from some validation though.
The PR introduces code parts to now throw on `Block` or `Blockchain` validation triggers on setups which we just don't support yet (validate blocks on 'goerli') or which doesn't make …
=> Structural Preparations for PoA Support

package-lock.json, packages/block/.eslintrc.js, packages/blockchain/.eslintrc.js, packages/common/.eslintrc.js, packages/ethash/.eslintrc.js, packages/tx/.eslintrc.js, packages/tx/CHANGELOG.md, packages/tx/src/transaction.ts, packages/vm/.eslintrc.js, packages/vm/package-lock.json, packages/vm/tests/api/runBlock.spec.ts
This PR is more of a suggestion and a base for discussion than a concrete PR. It changes the `tx` constructor to directly make use of the `TxData` interface object instead of taking in the separate values. I came here after further thinking about class inheritance on Tx along reviewing the `Object.freeze` issue https://github.com/ethereumjs/ethereumjs-vm/issues/940 from @cgewecke and generally having another look at the tx constructor we have right now.
I think with this change it becomes a lot easier and will be cleaner for people to subclass the tx class - e.g. when they want to add their own tx values they can just build upon the current interface infrastructure and extend the `TxData` interface instead of squeezing in their own values in the subclass constructor respectively generally …
=> Tx Constructor Restructuring

.github/workflows/vm-pr.yml, package.json
As promised, this PR disables most of the hardfork specific tests, to favor job concurrency. 
It can be easily reverted, by un-commenting those lines.
=> ci: disabling most of the hardfork-specific tests

packages/block/README.md, packages/blockchain/README.md, packages/common/README.md, packages/ethash/README.md, packages/tx/CHANGELOG.md, packages/tx/README.md, packages/vm/README.md
This PR fixes some inconsistencies within the README files discovered while browsing through the repository after having done the `beta.2` releases.
Changes are mostly header updates and headline hierarchy corrections, also some small rewrites.
The eventually somewhat unusual (or: not so commonly spotted) subtitle formatting is a table header without a body and renders like the following:
=> Small Release/README Fixes

packages/tx/package.json, packages/vm/package.json
This PR fixes #952 issue to remove vulnerable dependencies from EthereumJS libraries.
|  | Found | Fixed |
|--|--|--|
| deps | 0 | 0 |
| dev-deps | 0 | 0 |
|  | Found | Fixed |
|--|--|--|
| deps | 0 | 0 |
| dev-deps | 0 | 0 |
|  | Found | Fixed |
|--|--|--|
| deps | 0 | 0 |
| dev-deps | 0 | 0 |
|  | Found | Fixed |
|--|--|--|
| deps | 0 | 0 |
| dev-deps | 0 | 0 |
|  | Found | Fixed |
|--|--|--|
| deps | 0 | 0 |
| dev-deps | 9 | 9 |
- Removed redundant [contributor](https://www.npmjs.com/package/contributor) package. Reason: dependency is not in use.
|  | Found | Fixed |
|--|--|--|
| deps | 0 | 0 |
| dev-deps | 144 | 0 |
=> Audit dependencies and clean up dependency tree

packages/blockchain/CHANGELOG.md, packages/blockchain/docs/README.md, packages/blockchain/docs/classes/_db_helpers_.dbop.md, packages/blockchain/docs/classes/_db_operation_.dbop.md, packages/blockchain/docs/classes/_index_.blockchain.md, packages/blockchain/docs/enums/_db_operation_.dbtarget.md, packages/blockchain/docs/interfaces/_index_.blockchaininterface.md, packages/blockchain/docs/interfaces/_index_.blockchainoptions.md, packages/blockchain/docs/modules/_db_cache_.md, packages/blockchain/docs/modules/_db_constants_.md, packages/blockchain/docs/modules/_db_helpers_.md, packages/blockchain/docs/modules/_db_manager_.md, packages/blockchain/docs/modules/_db_operation_.md, packages/blockchain/src/db/manager.ts, packages/blockchain/src/index.ts, packages/blockchain/test/index.ts
Intended to be included in the `rc.1` release.
Addresses comment from @jochem-brouwer from here https://github.com/ethereumjs/ethereumjs-vm/issues/923#issuecomment-726891053 to make `Blockchain._getTd()` public. Function is renamed to `getTotalDifficulty()` for better clarity, CHANGELOG entry has been added and the blockchain docs rebuild.
=> Public Blockchain.getTotalDifficulty() method

.github/workflows/vm-pr.yml, .gitmodules, packages/tx/test/testLoader.ts, packages/vm/tests/testLoader.ts
This is the implementation of regular and extended VM State and Blockchain tests. It took lots of research and testing to have a concise code. The focus is on maintainability :)
On an ordinary PR, these tests will be fired:
But `vm-state-extended` and `vm-blockchain-extended` will be skipped.
All workflows running after adding the special label `type: test all hardforks` will have tests for all hardforks. Analogously, if the label is removed, the extended tests will not run anymore.
How it can be improved in the future:
- use YAML includes to reuse some code.
- If having `vm-state-extended` and `vm-blockchain-extended` on the checks start to bother you guys, there's an alternative: create one job with a script that outputs the matrix variables, just like I did with the `node-versions.yml` …
=> On-demand testing for VM State and Blockchain

packages/block/CHANGELOG.md, packages/block/package.json, packages/blockchain/CHANGELOG.md, packages/blockchain/package.json, packages/common/CHANGELOG.md, packages/common/package.json, packages/ethash/CHANGELOG.md, packages/ethash/package.json, packages/tx/CHANGELOG.md, packages/tx/package.json, packages/vm/CHANGELOG.md, packages/vm/package.json
Part of #907 
Final release series 🎉   for the VM v5 and other monorepo libraries following #958 
Note: I first wondered if I should just point to the beta and RC release notes in the CHANGELOG or do aggregated new release note entries. Already had a tendency towards the new release notes version also for the sake of user friendliness on reading when the decision was taken from me when I further realized that some sections from the extensive `beta.1` release notes actually had to be rewritten and not just appended together to continuedly make sense. The damage (if there is any) from redundancy should be very limited in this case I would say.
=> Final releases

packages/vm/lib/index.ts, packages/vm/lib/runBlock.ts, packages/vm/tests/BlockchainTestsRunner.ts, packages/vm/tests/api/runBlock.spec.ts, packages/vm/tests/api/utils.ts
This PR adds an option to make the VM automatically switch to the right hardfork in `runBlock`.
=> VM: add selectHardforkByBlockNumber option

packages/vm/lib/index.ts, packages/vm/tests/BlockchainTestsRunner.ts, packages/vm/tests/api/runBlock.spec.ts, packages/vm/tests/api/utils.ts
Fixes the default value of the `selectHardforkByBlockNumber` as pointed out by @holgerd77 in #966.
=> VM: fix selectHardforkByBlockNumber default value

packages/client/lib/net/peer/peer.ts, packages/client/lib/net/protocol/boundprotocol.ts, packages/client/lib/net/protocol/ethprotocol.ts, packages/client/lib/net/protocol/flowcontrol.ts, packages/client/lib/net/protocol/lesprotocol.ts, packages/client/lib/service/fullethereumservice.ts, packages/client/lib/sync/fullsync.ts, packages/client/lib/sync/lightsync.ts, packages/client/test/integration/fullethereumservice.spec.ts, packages/client/test/net/protocol/boundprotocol.spec.ts, packages/client/test/sync/fullsync.spec.ts
This PR is an attempt at resolving the challenge with dynamically adding methods to `BoundProtocol` from `EthProtocol` and `LesProtocol`.
This PR adds the interfaces `EthProtocolMethods` and `LesProtocolMethods` to assist in the type safety, since a class dynamically adding types to itself is not yet supported in typescript.
Side note: I’m not entirely sure why the methods were being added in both lowerCamelCase and UpperCamelCase, so I just opted for the lowerCamelCase method naming to reduce duplication, as that was what was being used around the code base.
Resolves one part of #975.
=> client: type BoundProtocol messages

packages/vm/lib/runCall.ts, packages/vm/lib/runCode.ts, packages/vm/lib/runTx.ts
This PR resolves #530 by using the vm's common for default blocks created in `runCall` and `runCode`. It also updates some of the code to prefer using the nullish coalescing operator.
=> Use vm's common when creating default blocks in `runCall` and `runCode`

packages/blockchain/src/index.ts, packages/blockchain/test/index.ts, packages/vm/README.md, packages/vm/lib/runBlock.ts, packages/vm/lib/runTx.ts
Related: #960 
This PR introduces some handy things: `afterBlock` and `afterTx` now get access to which block/tx is finished. Blockchain `iterator` gets an optional parameter which specifies how many blocks should (at most) be ran. It also adds a `setHead` method which allows updating the head of a certain tag, and this is saved in the DB. Related issue: #691.
=> Blockchain client requests

packages/client/lib/net/peer/libp2ppeer.ts, packages/client/lib/net/peer/rlpxpeer.ts, packages/client/lib/net/protocol/boundprotocol.ts, packages/client/lib/net/protocol/ethprotocol.ts, packages/client/lib/net/protocol/lesprotocol.ts, packages/client/lib/net/protocol/protocol.ts, packages/client/lib/net/protocol/rlpxsender.ts, packages/client/lib/net/server/libp2pserver.ts, packages/client/test/integration/fullethereumservice.spec.ts, packages/client/test/net/peer/libp2ppeer.spec.ts, packages/client/test/net/peer/rlpxpeer.spec.ts, packages/client/test/net/protocol/boundprotocol.spec.ts, packages/client/test/net/protocol/rlpxsender.spec.ts, packages/devp2p/src/eth/index.ts
This PR integrates the ETH/64 protocol from the latest devp2p `master` into the client. This is tested with ETH/64 only to exclude the possibility that ETH/63 is taking over all the load (ETH/62 has been removed since it is reaching EOL anyhow).
=> Integrate ETH/64 Protocol into Client

packages/common/src/chains/goerli.json, packages/devp2p/src/eth/index.ts, packages/devp2p/src/rlpx/rlpx.ts
This PR does the following:
- Fixes a severe devp2p bug not sending the `nextForkBlock` correctly on ETH.sendStatus() msg
- Improves RLPx disconnect reason debug output
- Updates Goerli bootnodes
=> Client Network Improvements

packages/tx/src/transaction.ts, packages/tx/test/api.ts, packages/vm/tests/api/runTx.spec.ts
This PR fixes `tx.isSigned()` as reported in #1041. It ensures that `v,r,s` aren't initialized in the constructor if undefined.
In writing some extra test cases, I also found the same bug in `fromValuesArray` that would initialize `v,r,s` to `BN(0)` if missing, so that is also fixed.
=> Fix isSigned returning true for unsigned txs

packages/trie/src/checkpointDb.ts, packages/trie/src/checkpointTrie.ts, packages/trie/src/db.ts, packages/trie/src/secure.ts, packages/trie/test/checkpointDb.spec.ts, packages/trie/test/db.spec.ts, packages/vm/tests/BlockchainTestsRunner.ts
This PR: 
- Seperates the DB used by `BaseTrie` and the extended DB used by `CheckpointTrie` (and `SecureTrie`) into two DBs; the base `DB` and the `CheckpointDB`. 
- All checkpoint operations are cached into memory. This makes reverting operations very easy (just throw away the latest cache) and also does not write to disk (so less I/O operations)
=> Trie: cache CheckpointTrie in memory

packages/devp2p/src/rlpx/peer.ts
This PR fixes a critical devp2p bug where peer data processing stays in an endless while loop on retrieval of malformed data, code change should be relatively self-explanatory, so if an error is thrown "early enough" before the data is consumed the loop will be executed ever and ever again (while the peer is disconnected anyhow).
Stumbled upon this in the client where the following error has been hammered out in an endless fashion on some malformed peer data:
```shell
ERROR [01-19|18:55:59] AssertionError [ERR_ASSERTION]: should have valid tag: c9994806780c34bf140355955ad1d2f5aeb38a61cea495379a435931d8bf7e6e / 176a38c21a95454505a8d05627c9975ce84673da8903b33fe48b80b082595cc0
at new AssertionError (internal/assert/assertion_error.js:447:11)
at Object.assertEq …
```
=> Devp2p: fix a peer data processing bug

packages/blockchain/src/index.ts, packages/blockchain/test/index.ts, packages/client/lib/sync/fullsync.ts, packages/vm/lib/index.ts, packages/vm/lib/runBlockchain.ts
My own client (blockchain) DB is currently in a state where block execution is not further done due to a somewhat inconsistent db state. In the client this gets noticeable by the execution messages not further showing up, there are only the block import logs displayed.
I could identify the root cause of the no-execution behavior: in the `Blockchain` iterator function there is no [block found](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/blockchain/src/index.ts#L769) in the DB following the current iterator head. Therefore no blocks are executed. I have no idea though how and when the blockchain DB got into this state. I do know though that I've been there (in this state) a couple of times before with block execution stopping.
This PR is approaching this on a low …
=> Client: Warning on not possible further block execution

README.md, packages/block/README.md, packages/blockchain/README.md, packages/client/README.md, packages/common/README.md, packages/devp2p/README.md, packages/ethash/README.md, packages/trie/README.md, packages/tx/README.md, packages/vm/README.md
Fixes all codecov badges that broke after the repository renaming. There are several other badges referencing the old repo, but they leverage the automatic redirect that GH provides, so that's fine for now.
=> Fixes codecov badges after repo renaming

packages/block/src/block.ts, packages/client/lib/blockchain/chain.ts, packages/client/lib/net/server/rlpxserver.ts, packages/client/lib/sync/execution/execution.ts, packages/client/lib/sync/execution/vmexecution.ts, packages/client/lib/sync/fullsync.ts, packages/client/lib/sync/sync.ts, packages/client/test/blockchain/chain.spec.ts, packages/client/test/integration/fullethereumservice.spec.ts, packages/client/test/integration/peerpool.spec.ts, packages/client/test/integration/util.ts, packages/devp2p/src/rlpx/peer.ts
This PR targets to fix the latest (obvious) client sync errors, specifically:
- Two common peer errors just indicating a disconnect ("Unknown forkhash", "Invalid type") are added to the list of ignored RLPxServer errors, 7c58eeb and 0d64db5
- A safeguard is added to avoid "socket already destroyed" errors in the devp2p peer module (haven't seen this error on quite an amount of blocks syncing after adding this change, this might need some final confirmation respectively some further observation though), 05059c8
- Block validation on client blockchain is activated, this should avoid getting into inconsistent state DB states when malformed blocks are received and at least partially solve #1066 
Will keep this as "WIP" for another hour or up to half a day, should be open for review soon …
=> Client: Fix Sync Bugs and Error Messages

packages/block/src/block.ts, packages/block/src/header.ts, packages/block/src/types.ts, packages/block/test/clique.spec.ts, packages/block/test/header.spec.ts, packages/blockchain/src/db/manager.ts, packages/blockchain/src/index.ts, packages/client/lib/blockchain/chain.ts, packages/client/lib/net/protocol/ethprotocol.ts, packages/client/lib/net/protocol/lesprotocol.ts, packages/client/lib/sync/execution/vmexecution.ts, packages/client/lib/sync/fetcher/blockfetcher.ts, packages/tx/src/transaction.ts, packages/tx/src/types.ts, packages/tx/test/api.ts, packages/vm/README.md, packages/vm/lib/evm/eei.ts, packages/vm/lib/evm/evm.ts, packages/vm/lib/runBlock.ts, packages/vm/lib/runTx.ts, packages/vm/lib/state/stateManager.ts, packages/vm/tests/api/runBlock.spec.ts
I think we can safe us from a load of problems when the `Common` instance in block and tx is just copied over. After months of thinking about this I am pretty much sure this is the right thing to do. Both txs and blocks just DO have a certain HF state - and if this is attached to an outer `Common` which - e.g. in the case of our client with `chainCommon` - might move on or change, this will lead to consistency problems if the respective Tx or Block objects are still around.
PR was triggered when running the client on Rinkeby which broke at bloke 55 with:
This is now fixed with this PR - as always replaced by another error though (`Invalid receipt trie`). Original root cause was the block being executed on the wrong HF though.
I think these `Common`-copy-fix can go in as a bug fix, this …
=> Block, Tx: always copy Common on instantiation / Fix HF consistency bugs

packages/client/bin/cli.ts, packages/client/lib/config.ts, packages/client/lib/sync/execution/vmexecution.ts, packages/client/lib/util/debug.ts, packages/vm/lib/runTx.ts
Fixing #1090 
I will actually not start working on new consensus bugs without adding a new meaningful debug tool. 😂
This one from this first commit 8d0afb7 is actually super-handy: it adds a new CLI option (mainly for internal usage, but of course also can be leveraged by consumers) `debugCode` which generates a dynamic script on a VM block execution failure. 
So this can be run with:
```shell
npm run client:start -- --network=rinkeby --debugCode
```
Script looks something like this and will be logged out to the console:
```typescript
/**
* Script for locally executing a block in the EthereumJS VM,
* meant to be used from packages/vm directory within the
* https://github.com/ethereumjs/ethereumjs-monorepo repository.
*
* Block: 14182
* Hardfork: spuriousDragon
*
* Run with: …
```
=> Client, VM -> Rinkeby: Fix consensus error on block 14182 (invalid receipt trie)

packages/vm/lib/evm/eei.ts, packages/vm/lib/evm/evm.ts
=> VM -> Mainnet: fix Frontier consensus bug along CREATE with not enough gas (WIP)

packages/client/lib/sync/execution/vmexecution.ts, packages/vm/lib/evm/opcodes/codes.ts
Closes #1090. Cherry-picked from #1094.
Very nasty bug. There are two problems:
(1) Client does not update the opcodes of VM when we change hard forks. In practice, some stuff happens though: if we update a context variable which we were already using (like tx data gas cost for nonzero data) then this is used (as we dynamically fetch this from the current Common). However, if a HF introduces new opcodes, then these are not added to VM and are thus not accessible. 
(2) We never updated TangerineWhistle gas cost changes in the first place. If you instantiate a Common with Chainstart, then switch to TangerineWhistle, and even called `_updateOpcodes()` before, then gas costs are *not* updated in the VM.
(Side note: also weird that tests did not cover this. On the other hand, there are not …
=> VM/Client: fix HF switching. Fix TangerineWhistle update bug.

packages/vm/examples/.gitignore, packages/vm/examples/run-solidity-contract/contracts/Greeter.sol, packages/vm/examples/run-solidity-contract/index.ts, packages/vm/examples/run-solidity-contract/package.json
This PR:
* replaces `ethereumjs-abi` (deprecated) with `@ethersproject/abi` (closes #1098)
* upgrades `solc` version
* fixes some new warnings for contract:
* upgrades solidity version
* adds SPDX-License-Identifier
* removes visibility identifier from constructor (public is default)
---
To test, `cd` into `packages/vm/examples/run-solidity-contract` and run `npm i && npm run example`
The output should look like this:
```
> run-solidity-contract@ example /Users/rg/dev/ethereumjs-monorepo/packages/vm/examples/run-solidity-contract
> ts-node index.ts
Account: 0xbe862ad9abfe6f22bcb087716c7d89a26051f74c
Set account a balance of 1 ETH
Compiling...
Compiled the contract
Deploying the contract...
Contract address: 0x61de9dc6f6cff1df2809480882cfd3c2364b28f7
Greeting: Hello, World!
Changing …
```
=> VM: Update run-solidity-contract example

packages/blockchain/src/index.ts
This PR adds some logic to `blockchain._putBlockOrHeader` where if a header is passed in then it will only validate the header and not the entire block since the additional data needed would be missing (txs, uncles). This was discovered when trying to sync the client on rinkeby in light mode.
=> Blockchain: if passed header only validate header

packages/block/package.json, packages/client/package.json, packages/trie/CHANGELOG.md, packages/trie/README.md, packages/trie/package.json, packages/trie/src/baseTrie.ts, packages/vm/package.json
MPT release with the new checkpointing mechanism and other CI and docs related changes (see CHANGELOG).
Please notice that I reverted a `Trie.setRoot()` -> `Trie._setRoot()` rename (introduced by myself) from https://github.com/ethereumjs/merkle-patricia-tree/pull/125 and switched to deprecating instead. This seemed to dangerous to me on retrospective regarding introducing a breaking change. Have instead added to #1024.
=> MPT: New Release v4.1.0

packages/vm/examples/run-solidity-contract/README.md
This PR updates the readme instructions for `run-solidity-contract`  removing the old `npm run build:dist` step since the monorepo packages are now automatically built post-install following `npm i` on root.
=> Update run-solidity-contract readme instructions

packages/common/src/eips/2315.json, packages/common/src/index.ts, packages/common/tests/eips.spec.ts
This PR adds a new method `Common.isActivatedEIP()`. This method is meant to replace manual calls like `this._vm._common.eips().includes(2929)` (see e.g. [here](https://github.com/ethereumjs/ethereumjs-monorepo/pull/1124/files#diff-5989b042ba2babcc01da3488dea79edfec7ea66c41dde9d04cf6332d204fae2dR276)) which will break once such an EIP moves to a HF.
After merging all these calls - particularly in the VM - should be replaced with the functionality from here.
Note that the current terminology around the term "active" in the `Common` library is very unfortunate (I once introduced myself). Other methods like `activeHardforks()` take "active" as "being a part of the chain" - if activated or not. I therefor for now used the terminology "activated" to differentiate here at least a bit. I will …
=> Common: Add new isActivatedEIP() method

.github/workflows/vm-pr.yml, packages/common/src/hardforks/berlin.json, packages/vm/lib/evm/evm.ts, packages/vm/lib/evm/opcodes/EIP2929.ts, packages/vm/lib/evm/precompiles/05-modexp.ts, packages/vm/lib/index.ts, packages/vm/lib/runTx.ts, packages/vm/package.json
This PR is to get an in-between overview on where we are with the berlin test runs - still excluding EIP-2718 and EIP-2930 - PR is branched off from #1124.
@jochem-brouwer feel free to merge this one in if useful or we can otherwise merge post #1124 merge, as you like.
=> VM, Common: updated EIP checks / added EIP-2565, EIP-2929 to Berlin HF

packages/block/package.json, packages/blockchain/package.json, packages/trie/package.json, packages/tx/package.json, packages/tx/src/transactionFactory.ts, packages/vm/benchmarks/util.ts, packages/vm/lib/evm/opcodes/EIP1283.ts, packages/vm/lib/evm/opcodes/EIP2200.ts, packages/vm/lib/evm/opcodes/EIP2929.ts, packages/vm/lib/evm/precompiles/01-ecrecover.ts, packages/vm/lib/evm/precompiles/02-sha256.ts, packages/vm/lib/evm/precompiles/03-ripemd160.ts, packages/vm/lib/evm/precompiles/04-identity.ts, packages/vm/lib/evm/precompiles/05-modexp.ts, packages/vm/lib/evm/precompiles/06-ecadd.ts, packages/vm/lib/evm/precompiles/07-ecmul.ts, packages/vm/lib/evm/precompiles/08-ecpairing.ts, packages/vm/lib/evm/precompiles/09-blake2f.ts, packages/vm/lib/evm/precompiles/0a-bls12-g1add.ts, packages/vm/lib/evm/precompiles/0b-bls12-g1mul.ts, packages/vm/lib/evm/precompiles/0c-bls12-g1multiexp.ts, packages/vm/lib/evm/precompiles/0d-bls12-g2add.ts, packages/vm/lib/evm/precompiles/0e-bls12-g2mul.ts, packages/vm/lib/evm/precompiles/0f-bls12-g2multiexp.ts, packages/vm/lib/evm/precompiles/10-bls12-pairing.ts, packages/vm/lib/evm/precompiles/11-bls12-map-fp-to-g1.ts, packages/vm/lib/evm/precompiles/12-bls12-map-fp2-to-g2.ts, packages/vm/lib/evm/precompiles/types.ts, packages/vm/lib/evm/precompiles/util/bls12_381.ts, packages/vm/package.json
Fixes a TS compilation failure on install relating to ethereumjs-util 7.0.9. 
PR: 
+ removes @types/bn.js as a dependency everywhere
+ imports `bn.js` via ethereumjs-util everywhere (for clarity about its source)
Idea is:
+ bn.js [is not a direct dependency in any package][1] - it always comes from ethereumjs-util
+ @types/bn.js [is a direct dependency][2] of ethereumjs-util
+ monorepo should let ethereumjs-util manage the bn types
[1]: https://github.com/ethereumjs/ethereumjs-monorepo/search?p=1&q=bn.js
[2]: https://github.com/ethereumjs/ethereumjs-util/blob/b100d13f827a3d495d3de85f3e5d6756749b514f/package.json#L88
=> Remove @types/bn.js from block,blockchain,trie,tx,vm packages

packages/block/src/header.ts, packages/vm/lib/evm/precompiles/01-ecrecover.ts
Two more fixes when using ecrecover on large chain IDs:
- VM `ECRECOVER` precompile
- Block cliqueSigner() address recovery
=> VM, Block: large ChainID ecrecover fixes

packages/common/src/chains/goerli.json, packages/common/src/chains/mainnet.json, packages/common/src/chains/rinkeby.json, packages/common/src/chains/ropsten.json, packages/common/src/hardforks/berlin.json, packages/common/tests/eips.spec.ts, packages/common/tests/hardforks.spec.ts, packages/common/tests/params.spec.ts, packages/vm/lib/evm/opcodes/codes.ts, packages/vm/lib/index.ts, packages/vm/tests/api/EIPs/eip-2315.spec.ts, packages/vm/tests/api/opcodes.spec.ts
This is a simple PR which updates the `ethereum-tests` submodule to the `Berlin` release [8.0.0](https://github.com/ethereum/tests/releases/tag/8.0.0) with a removed `EIP-2315` HF. `EIP-2315` is also removed here in `Common` in the `berlin` HF definition file.
I originally also wanted to add the block numbers for `berlin` along this PR. But I don't trust these numbers yet since the `Ropsten` HF would be so close and there is no corresponding `go-ethereum` release out yet, see also https://github.com/ethereum/pm/issues/248#issuecomment-792573651.
=> Update ethereum-tests submodule to 8.0.0 / Remove EIP-2315 from berlin

.github/workflows/trie-build.yml, .github/workflows/vm-pr.yml
This PR applies a small fix to the trie benchmarks code for the conditional `auto-push` field. It also keeps a max limit of 30 previous runs of data, and upgrades the `checkout` step from v1 to v2.
=> Trie: fix benchmarks

package-lock.json, packages/client/README.md, packages/client/lib/rpc/index.ts, packages/client/lib/rpc/modules/admin.ts, packages/client/lib/rpc/modules/eth.ts, packages/client/lib/rpc/modules/net.ts, packages/client/lib/rpc/modules/web3.ts, packages/client/lib/rpc/types.ts, packages/client/lib/rpc/validation.ts, packages/client/package.json, packages/client/test/rpc/admin/nodeInfo.spec.ts, packages/client/test/rpc/eth/call.spec.ts, packages/client/test/rpc/eth/estimateGas.spec.ts, packages/client/test/rpc/eth/getBalance.spec.ts, packages/client/test/rpc/eth/getBlockByNumber.spec.ts, packages/client/test/rpc/eth/getBlockNumber.spec.ts, packages/client/test/rpc/eth/getCode.spec.ts, packages/client/test/rpc/eth/getStorageAt.spec.ts, packages/client/test/rpc/eth/getTransactionCount.spec.ts, packages/client/test/rpc/helpers.ts, packages/client/test/rpc/mockBlockchain.ts, packages/client/test/rpc/net/listening.spec.ts, packages/client/test/rpc/net/peerCount.spec.ts, packages/client/test/rpc/net/version.spec.ts, packages/client/test/rpc/validation.spec.ts
This PR adds new RPC methods:
1. `eth_getTransactionCount`
1. `eth_getBalance`
1. `eth_getCode`
1. `eth_getStorageAt`
1. `eth_call`
1. `eth_estimateGas`
For `eth_call` and `eth_estimateGas`, the code uses a copy of the vm as to not make any changes.
This PR also:
1. Adds new rpc input validators: `address`, `blockOption`, `transaction`
1. Adds basic tests for all rpc input validators
1. Improves the rpc test helper code
1. Improves some of the rpc and validator typedocs
=> Client: Add 6 new RPC methods

packages/block/src/block.ts, packages/block/src/types.ts, packages/client/lib/config.ts, packages/common/src/index.ts, packages/tx/.eslintrc.js, packages/tx/examples/ropsten-tx.ts, packages/tx/src/baseTransaction.ts, packages/tx/src/eip2930Transaction.ts, packages/tx/src/legacyTransaction.ts, packages/tx/src/transactionFactory.ts, packages/tx/src/types.ts, packages/tx/test/base.spec.ts, packages/tx/test/legacy.spec.ts, packages/tx/test/transactionFactory.spec.ts, packages/tx/test/transactionRunner.ts
This PR applies a few small fixes and improvements to the new tx library with EIP2718 and 2930 support:
* `AccessListEIP2930Transaction` - removes `asList` parameter in `raw()`, preferring to use `serialize()`
* `TransactionFactory` - for clarity, renames `fromRawData` to `fromSerializedData`
* For clarity, renames `_validateExceedsMaxInteger(validateCannotExceedMaxInteger)` to `_validateCannotExceedMaxInteger(values)`
* Renames internal usage of `fromRlpSerializedTx` to `fromSerializedTx`
* Introduces `common.copy()` for easier deep copy functionality.
=> Tx: Small fixes and improvements

packages/client/README.md, packages/client/bin/cli.ts, packages/client/lib/config.ts, packages/client/lib/util/parse.ts
This PR splits the CLI transports options for bootnodes and multiaddrs. Closes https://github.com/ethereumjs/ethereumjs-monorepo/issues/1069.
=> Client: split CLI transports options for bootnodes and multiaddrs

.github/workflows/trie-build.yml, packages/client/bin/cli.ts, packages/client/browser/index.ts, packages/client/lib/config.ts, packages/client/lib/net/server/libp2pserver.ts, packages/client/lib/net/server/rlpxserver.ts, packages/client/lib/net/server/server.ts, packages/client/test/net/server/libp2pserver.spec.ts
This PR ensures that we save the node key to disk. This is saved in the root directory of the current network. This way, we ensure that we will re-use the enode, such that we can quickly reconnect, or add our client as a bootnode. This would not be possible if it is not saved, since then our enode keeps changing every time we reboot the client.
=> Client: Save node key

packages/block/src/header.ts
PR removes a restriction introduced in #863 that disallows commons with custom genesis settings unless their hardforks are set to `chainstart`. 
This is blocking integration of the `block` module in the Hardhat testrpc because they set a custom common with special gas limits, chainId, etc as an initial step on launch, but need to run on arbitrary hardforks.
https://github.com/nomiclabs/hardhat/blob/579d44a105d6a8323d270ea55876c6694c212316/packages/hardhat-core/src/internal/hardhat-network/provider/utils/makeCommon.ts#L20-L42
Perhaps this restriction should be preserved but gated behind a flag - not sure. Am opening in the simplest form for further discussion.
=> Make genesis params settable for any hardfork in block headers

packages/client/lib/net/protocol/ethprotocol.ts, packages/client/lib/net/protocol/lesprotocol.ts, packages/client/lib/rpc/modules/admin.ts, packages/client/test/net/protocol/ethprotocol.spec.ts, packages/client/test/net/protocol/lesprotocol.spec.ts
This PR is a follow-up to #1150 that fixes some BN cases where toNumber should not be used in case of large number network ids like yolov3.
=> Client: small BN fixes

codecov.yml, packages/client/codecov.yml, packages/devp2p/codecov.yml, packages/trie/codecov.yml, packages/util/codecov.yml
This PR:
* Configures the threshold for the codecov `patch` status check to `5%` ([docs link](https://docs.codecov.io/docs/commit-status#patch-status))
* Removes duplicate `codecov.yml` files, preferring one at the top level of the monorepo
* Removes deprecated `base` property
=> codecov: configure threshold for patch status check

packages/tx/CHANGELOG.md, packages/tx/package.json
Replaces #1162 with just a version bump and changelog entry. As Holger noted in discord, the problem looks like a corrupted local build, so just need to publish a new `dist/`
> think this was because in some old version the file might have been named EIP2930Transaction.ts  in src  and TypeScript just didn't update the index.js  file on an update (eventually jochem-brouwer can confirm?).
=> New Tx 3.1.1 Release

packages/vm/tests/api/runTx.spec.ts, packages/vm/tests/api/utils.ts
I've switched from TxPool to access list generation for today. 😄 
On a first round I will add some tests to `runTx()` API tests and also clean up there a bit. On a first commit 4163c40 I've removed the existing `setup()` function, I am pretty sure that this is not doing anything useful (maybe some relic which was necessary on some old structure setup) and just bloating up the code. This is also confusing to read and hinders adding more flexible test setups directly by e.g. changing the `StateManager` or `Common`. Nevertheless pushing early here, so if I've overlooked something here let me know.
Generally I will see how far I will come, I think I'll give some tests some more space on a first round, generally in need I have the impression.
=> VM: Refactor runTx() API tests / add Typed Transaction tests

.github/workflows/e2e-tests.yml
The current E2E test seems to be failing randomly with a build error (from the target repo's own build script)
```
'dist/tokens/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48.json'
Error: ENOENT: no such file or directory, unlink 'dist/tokens/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48.json'
```
I don't think this is worth digging into because this target was POC and doesn't test much of the monorepo.
Will open a PR re-enabling when Hardhat has successfully integrated the new libraries - they have a huge test suite which touches most of the code here.
=> Temporarily disable e2e tests (due to intermittent failures)

packages/tx/src/types.ts, packages/util/src/address.ts, packages/util/src/bytes.ts, packages/util/test/address.spec.ts, packages/vm/examples/run-transactions-complete/index.ts, packages/vm/karma.conf.js, packages/vm/lib/runTx.ts, packages/vm/lib/state/interface.ts, packages/vm/lib/state/stateManager.ts, packages/vm/tests/api/runTx.spec.ts, packages/vm/tests/api/state/stateManager.spec.ts, packages/vm/tests/config.ts
Ok, here is the access list generation PR fixing #1152. This needs significantly more tests, but this should generally do what is expected. I just tried to generate the following super-simple access list with this:
```shell
{
gasUsed: <BN: 52f8>,
execResult: {
gasUsed: <BN: 0>,
exceptionError: undefined,
returnValue: <Buffer >,
gasRefund: <BN: 0>
},
bloom: Bloom {
bitvector: <Buffer 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ... 206 more bytes>
},
amountSpent: <BN: 2068e0>,
accessList: [
{
address: 'be862ad9abfe6f22bcb087716c7d89a26051f74c',
storageKeys: []
}
]
}
```
Which obviously is not enough yet. 😄  Functionality for more complex AL is there but should be manually tested or …
=> VM: Generate Access Lists in runTx()

packages/util/CHANGELOG.md, packages/util/src/account.ts, packages/util/test/account.spec.ts, packages/util/test/bytes.spec.ts
PR changes `isValidAddress`, `isValidChecksumAddress` and `isZeroAddress` to return `false` when given a non-hex-prefixed string (or non-string) input.
This proposal comes from a Hardhat integration [review discussion][1]. 
Basic idea is that it's unexpected behavior for boolean validators like this to throw. 
[1]: https://github.com/nomiclabs/hardhat/pull/1337#discussion_r600056630
=> Stop throwing when non-hex-prefixed addresses are passed to util `isValid..` methods

packages/block/src/header.ts, packages/block/test/clique.spec.ts, packages/vm/CHANGELOG.md, packages/vm/karma.conf.js, packages/vm/lib/buildBlock.ts, packages/vm/lib/index.ts, packages/vm/lib/runBlock.ts, packages/vm/tests/api/buildBlock.spec.ts, packages/vm/tests/api/runBlock.spec.ts
This PR adds `vm.buildBlock()` for building a block and adding transactions one at a time. 
It can be used like so:
```typescript
const blockBuilder = await vm.buildBlock({ parentBlock })
const txResult = await blockBuilder.addTransaction(tx)
const block = await blockBuilder.build()
```
It creates a checkpoint on the StateManager and modifies the state as transactions are run. The checkpoint is committed on `build()` or discarded with `revert()`.
Closes #1018.
This PR also:
* includes fixes for `runBlock` with `generate: true` by setting the header fields for gasUsed, logs bloom, receiptTrie, and transactionsTrie. (closes #1037)
* moves the tx receipt generation logic in `runBlock` to a function inside the same file called `generateTxReceipt`, which is then exported and used in …
=> VM: Add vm.buildBlock() and BlockBuilder API

packages/tx/src/baseTransaction.ts, packages/tx/src/eip2930Transaction.ts, packages/tx/src/legacyTransaction.ts
Fixes #1189 
Ok, this should do it, have tested on the console and can confirm that this fixes the bug.
Have also unified the default value setting along the road since this would otherwise generally be dangerous to introduce inconsistencies and hard-to-track bugs in the future which just occur on a single constructor or so.
I have done pretty atomic commits to allow for a careful review. I have done these single transitions pretty cautiously though.
=> Tx: fix AccessListEIP2930Transaction constructor bug with v=0

packages/block/src/types.ts, packages/tx/src/baseTransaction.ts, packages/tx/src/eip2930Transaction.ts, packages/tx/src/legacyTransaction.ts, packages/tx/src/transactionFactory.ts, packages/tx/test/eip2930.spec.ts, packages/vm/lib/buildBlock.ts, packages/vm/lib/runBlock.ts, packages/vm/lib/runTx.ts, packages/vm/lib/types.ts, packages/vm/tests/api/buildBlock.spec.ts, packages/vm/tests/api/runBlock.spec.ts, packages/vm/tests/api/runTx.spec.ts, packages/vm/tests/api/types.spec.ts
This PR:
* Adds `receipt` to `RunTxResult`
* Moves the tx receipt generation logic from `runBlock` to `runTx`
* Requested by @alcuadrado
* Fixes `BlockBuilder` to allow building a block with zero txs
* `AccessListEIP2930Transaction`: adds alias `type` for `transactionType` so it can be interpreted correctly when passed to `fromTxData`
* `TransactionFactory`: For extra safety, adds `toBuffer` on `txData.type` in case a 0x-prefixed hex string is passed in
* Adds types test from @alcuadrado to ensure that the actual objects can be safely used as their data types
* Adds test cases for legacy and access list transactions to `runBlock`
* `BlockBuilder`: Moves the `stateManager.commit` to after putting the block in blockchain in case it throws on validating
=> vm: add tx receipt to RunTxResult, allow BlockBuilder to build a block with zero txs

package-lock.json, packages/vm/lib/evm/eei.ts, packages/vm/lib/evm/evm.ts, packages/vm/lib/evm/interpreter.ts, packages/vm/lib/evm/opcodes/EIP1283.ts, packages/vm/lib/evm/opcodes/EIP2200.ts, packages/vm/lib/evm/opcodes/EIP2929.ts, packages/vm/lib/evm/opcodes/functions.ts, packages/vm/lib/evm/opcodes/util.ts, packages/vm/lib/runBlock.ts, packages/vm/lib/runTx.ts, packages/vm/lib/state/stateManager.ts
We are receiving complains from our users about the release candidate version we published running >6x slower than our previous version. 
The main difference between these versions is that the RC version uses v5, instead of v4, making it the first consumer of v5.
This performance regression is aligned with that @jochem-brouwer reported when experimenting with removing the traces and running the standard tests, so I instructed one of our users to remove them from their `node_modules`, and not only the performance regression was gone, but the test run actually faster.
This PR removes all the debug traces from the VM. I didn't remove them from other packages to keep the PR small, and because we don't use them, so it's not as urgent.
@holgerd77, do you think we can get this published today? …
=> Remove all the debug traces from the vm

packages/vm/tests/api/events.spec.ts
One of the tests in `events.spec.ts` intends to check that `EVMResult` is emitted after running a message, but the test was actually listening for the `beforeMessage` event. Changed the test to listen for `afterMessage`.
Also included a couple small copy-edits in an explanatory comment further down in the file.
=> VM: Small fixes in events spec file

packages/vm/lib/state/stateManager.ts, packages/vm/tests/api/state/stateManager.spec.ts
I recently noticed that `setStateRoot` had a direct buffer comparison:
`if (stateRoot === this._trie.EMPTY_TRIE_ROOT) {`
In practice this doesn't always work and should instead use `Buffer.equals()`. I added a spec test that fails without the provided fix.
This was also an opportunity to DRY (Don't-Repeat-Yourself) the code a bit.
=> StateManager: fix buffer comparison in setStateRoot

packages/vm/tests/api/runTx.spec.ts
Added a new test for default return values in `runTx.spec.ts` (testing the non-optional fields in `RunTxResult`).
I'm still getting my head wrapped around the code and testing practices for this project, so feedback is most definitely welcome.
=> VM: New test for runTX return values

packages/vm/tests/api/buildBlock.spec.ts, packages/vm/tests/api/runBlock.spec.ts, packages/vm/tests/api/utils.ts
This PR improves the test performance for `buildBlock.spec.ts` after seeing that it was running very slow in karma.
The bottleneck was `vm.stateManager.generateCanonicalGenesis()` which I was using to set up addresses with balances to use for txs. Instead I am now just adding balance to the specific accounts needed, which drastically reduced the execution time.
=> VM: Improve buildBlock test performance

packages/client/lib/net/peer/peer.ts, packages/client/lib/net/peerpool.ts, packages/client/lib/net/protocol/boundprotocol.ts, packages/client/test/integration/mocks/mockpeer.ts, packages/client/test/net/peerpool.spec.ts
Follow-up solution to initial ETH messages being lost, replaces #1236
=> Client: Simple message queue to handle unhandled ETH messages during handshake

packages/client/test/rpc/eth/call.spec.ts, packages/client/test/rpc/eth/estimateGas.spec.ts, packages/client/test/rpc/eth/getBalance.spec.ts, packages/client/test/rpc/eth/getCode.spec.ts, packages/client/test/rpc/eth/getStorageAt.spec.ts, packages/client/test/rpc/eth/getTransactionCount.spec.ts
Partially addresses #1227 for `eth` calls. In particular, added tests for unsupported `block` params (i.e. block !== `latest`). Hopefully will help out with the code coverage report.
=> Added client rpc eth tests for unsupported block params

packages/block/test/header.spec.ts, packages/block/test/poaMockchain.ts
Partially addresses #1232 - Add 3 new tests for error conditions in `header.ts` that are currently not covered.
=> Add test for header error conditions

packages/client/lib/service/lightethereumservice.ts, packages/devp2p/src/les/index.ts
This PR addresses two small fixes I noticed while using les in the client:
1. LightEthereumService: adds missing FlowControl param to LesProtocol init
2. devp2p: fixes txRelay typo in status string
=> Two small fixes (adds missing flow param to LesProtocol, fixes txRelay typo)

packages/common/src/eips/3541.json, packages/common/src/eips/index.ts, packages/vm/lib/evm/evm.ts, packages/vm/lib/exceptions.ts, packages/vm/lib/index.ts, packages/vm/tests/api/EIPs/eip-3541.spec.ts
Implements [EIP3541](https://github.com/ethereum/EIPs/blob/8aa8b36070c28808f32d1e6465e71e9d0f2b8d2f/EIPS/eip-3541.md). 
~~Verify that if we deploy 0xEF on 3541 activated commons we should consume all gas (this is most likely the case).~~ (confirmed on ACD)
=> Implement EIP3541

packages/block/src/header.ts, packages/common/src/eips/3554.json, packages/common/src/eips/index.ts, packages/common/src/hardforks/byzantium.json, packages/common/src/hardforks/chainstart.json, packages/common/src/hardforks/constantinople.json, packages/common/src/hardforks/muirGlacier.json, packages/common/tests/eips.spec.ts
This [EIP](https://eips.ethereum.org/EIPS/eip-3554) is scheduled for London (please note that the Eth1 spec is outdated, it points to an EIP where the writer is currently not available, so a new EIP was created).
This also cleanups some code in block where the delay logic was copied (>= Byzantium). It is now a parameter in Common.
=> Implement EIP3554

packages/trie/src/baseTrie.ts, packages/trie/test/index.spec.ts
Fixes #1210 
I am coming more and more to the conclusion that this might be the only change we need. We shouldn't comment out stuff (or remove) directly in the DB manager to let people the freedom to delete themselves if they wish, this is what would be expected from the direct DB class.
Some historical reference in between: `_formatNode` has been moved from `CheckpointTrie` to `BaseTrie` [here](https://github.com/ethereumjs/merkle-patricia-tree/commit/40b02ee1c84f5dcda7c1f295699b1244fdbaf22f#diff-a21bc7ca183ffb0c3fc3c310436fe3ceb155b33debfda6e132ae2afb42724a8e).
All Trie delete operations - both from `del()` and from `batch()` - are routed through this `_formatNode` method, so this should shield all possible high-level trie deletes.
I am unsure about the default setting of a potential …
=> Trie: new deleteFromDB option (default: false)

packages/block/src/header.ts, packages/block/test/block.spec.ts, packages/block/test/eip1559block.spec.ts, packages/block/test/testdata/eip1559baseFee.json, packages/client/test/rpc/eth/sendRawTransaction.spec.ts, packages/client/test/rpc/helpers.ts, packages/tx/src/eip1559Transaction.ts, packages/tx/src/eip2930Transaction.ts, packages/tx/src/legacyTransaction.ts, packages/tx/test/base.spec.ts, packages/tx/test/transactionFactory.spec.ts, packages/vm/tests/api/runBlock.spec.ts
This PR adds coverage for missed lines of code, mostly gathered from codecov check warnings from #1148.
=> tests: additional coverage

packages/vm/lib/buildBlock.ts, packages/vm/tests/api/buildBlock.spec.ts
This PR adds 1559 support to BlockBuilder by setting the new block's `baseFeePerGas` to `parentBlock.header.calcNextBaseFee()`
=> VM: add 1559 support to blockbuilder

.github/workflows/e2e-tests.yml
GH actions is still running this file `e2e-tests.yml` (#1172) and emailing errors on merge to master so this PR fully comments out the file.
=> ci: disable e2e-tests.yml completely

packages/block/package.json, packages/blockchain/package.json, packages/client/package.json, packages/common/CHANGELOG.md, packages/common/README.md, packages/common/docs/classes/index.default.md, packages/common/docs/modules/genesisstates.md, packages/common/package.json, packages/devp2p/package.json, packages/tx/CHANGELOG.md, packages/tx/README.md, packages/tx/docs/classes/basetransaction.basetransaction-1.md, packages/tx/docs/classes/eip1559transaction.default.md, packages/tx/docs/classes/eip2930transaction.default.md, packages/tx/docs/classes/legacytransaction.default.md, packages/tx/docs/classes/transactionfactory.default.md, packages/tx/docs/interfaces/types.accesslisteip2930txdata.md, packages/tx/docs/interfaces/types.feemarketeip1559txdata.md, packages/tx/package.json, packages/vm/CHANGELOG.md, packages/vm/package.json
Ok, a new round of releases integrating the latest EIP-1559 spec changes and updating on tx library usability and generally integrating user feedback. ~Still WIP, VM is still missing.~
I very much anticipate a relatively narrow cadence of follow-up releases in the next weeks on approaching the `london` HF (so at least every two weeks, eventually also more on a weekly basis), so no worry if some feature or fix hasn't made this yet in this release.
We generally should release here soon since there are features/fixes both HardHat and Web3.js are waiting for to integrate.
=> New Releases VM v5.4.1, Tx v3.2.1, Common v2.3.1

packages/block/src/header.ts, packages/tx/src/eip1559Transaction.ts, packages/tx/src/eip2930Transaction.ts, packages/tx/src/legacyTransaction.ts, packages/util/src/account.ts, packages/util/src/types.ts, packages/util/test/types.spec.ts
This PR renames `bnToRlp` to `bnToUnpaddedBuffer` to better describe its function (closes https://github.com/ethereumjs/ethereumjs-util/issues/284)
It also converts some uses of `unpadBuffer(toBuffer(bn))` to the function, and adds a test for it in the util package. `bnToRlp` is kept as a deprecated alias that can be removed in a future major version.
=> util: rename bnToRlp to bnToUnpaddedBuffer

packages/client/bin/cli.ts, packages/client/lib/config.ts, packages/client/lib/sync/execution/vmexecution.ts, packages/client/lib/sync/fetcher/blockfetcher.ts, packages/client/lib/sync/fetcher/blockfetcherbase.ts, packages/client/lib/sync/fetcher/fetcher.ts, packages/client/lib/sync/fetcher/headerfetcher.ts, packages/client/lib/sync/fullsync.ts, packages/client/lib/sync/lightsync.ts, packages/client/test/integration/fullsync.spec.ts, packages/client/test/integration/lightsync.spec.ts, packages/client/test/sync/fetcher/blockfetcher.spec.ts
Related: #1306 
Working branch to sync with the [Calaveras](https://github.com/ethereum/eth1.0-specs/blob/master/network-upgrades/client-integration-testnets/calaveras.md) network, also coming with some calaveras related improvements (feel free to directly push on this branch or in doubt make a PR towards the branch if you have got things to add).
First thing I added here is an official `maxPerRequest` CLI option, then we don't always have to monkey-patch if running with a `50` maxPerRequest setting doesn't work but can just run `npm run client:start -- --network=calaveras --maxPerRequest=1`.
The option should be generally useful (so: not just a monkey-patch-ease option 🙂) since it will be likely useful for peopel to play a bit with this, this will likely allow to get to somewhat higher …
=> Client: Calaveras Sync Improvements + Working Branch

packages/vm/CHANGELOG.md, packages/vm/src/buildBlock.ts
This PR allows the blockbuilder to set a customizable `baseFeePerGas` if set in the `headerData`.
This was requested by hardhat to let users manipulate the base fee to test e.g. varying edge cases.
=> blockbuilder: allow customizable baseFeePerGas

packages/block/src/header.ts
The Kovan block nonce is a hex string of 65 0s and our `block` package expects a nonce of 8 bytes in length so trying to sync Kovan with the `client` results in an error.  
```
INFO [07-06|11:00:47] Connecting to network: kovan
ERROR [07-06|11:00:47] Error: nonce must be 8 bytes, received 65 bytes
at BlockHeader._validateHeaderFields (/home/jim/development/ethereumjs-monorepo/packages/block/src/header.ts:323:13)
at new BlockHeader (/home/jim/development/ethereumjs-monorepo/packages/block/src/header.ts:267:10)
at Function.fromHeaderData (/home/jim/development/ethereumjs-monorepo/packages/block/src/header.ts:77:12)
at Function.fromBlockData (/home/jim/development/ethereumjs-monorepo/packages/block/src/block.ts:36:32)
at Function.genesis …
```
=> block: Add fix for kovan nonce

packages/block/src/block.ts, packages/blockchain/src/index.ts, packages/client/lib/net/peer/rlpxpeer.ts, packages/client/lib/net/protocol/boundprotocol.ts, packages/client/lib/net/protocol/ethprotocol.ts, packages/client/lib/net/protocol/lesprotocol.ts, packages/client/lib/service/fullethereumservice.ts, packages/client/lib/service/lightethereumservice.ts, packages/client/test/net/protocol/ethprotocol.spec.ts, packages/client/test/net/protocol/lesprotocol.spec.ts, packages/devp2p/examples/peer-communication-les.ts, packages/devp2p/src/les/index.ts, packages/devp2p/test/integration/les-simulator.ts
This PR fixes `devp2p/examples/peer-communication-les.ts` by upgrading to les v4.
Sample run:
```
➜  examples git:(les-v4) ✗ ts-node peer-communication-les.ts
Add peer: 52.169.42.101:30303 Geth/v1.10.2-unstable-aab35600-20210322/linux-amd64/go1.16.2 (les4) (total: 1)
Add peer: 159.89.28.211:30303 Geth/v1.10.5-unstable-10eb654f-20210623/linux-amd64/go1.16.5 (les4) (total: 2)
----------------------------------------------------------------------------------------------------------
block 8845079 received: 0a3040af08dc247ad9e4290285360b9af0d58b8363c8cd1f0e0832bb2f98630a (from 52.169.42.101:30303)
----------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------- …
```
=> devp2p/client: add les v3/v4

.github/workflows/client-build.yml, packages/client/package.json, packages/client/test/cli/cli.spec.ts
This PR adds a basic cli test that spins up the client, imports a block from a peer, and finishes.
The Github Action is specified with a matrix of `network` and `syncmode`.
=> client: add basic cli test

packages/common/src/chains/calaveras.json, packages/common/src/chains/goerli.json, packages/common/src/chains/kovan.json, packages/common/src/chains/rinkeby.json, packages/common/src/chains/ropsten.json, packages/common/tests/chains.spec.ts, packages/common/tests/hardforks.spec.ts
Per the comment here https://github.com/ethereumjs/ethereumjs-monorepo/pull/1329#issuecomment-872002349, this PR cleans up the "type 1" `null` HFs (i.e. the `dao` HF) when not applied to a particular chain.
Please note the change in `hardforks.spec.ts` still provides a valid test as long as `london` remains unimplemented for `kovan`. If and when `kovan` gets the London HF, that test will fail.
=> common: remove dao hardfork from chains when not applied

packages/client/CHANGELOG.md
This PR updates the client changelog with the changes since the last release on 2020-06-19. There were 3 pages of PRs to sort through *(phew)* I tried to compile a list of the most significant PRs and not necessarily *every one* of them.
Prep for #1365
=> client: update changelog

packages/client/lib/rpc/modules/eth.ts, packages/vm/CHANGELOG.md, packages/vm/src/runTx.ts, packages/vm/tests/api/EIPs/eip-1559-FeeMarket.spec.ts, packages/vm/tests/api/EIPs/eip-2930-accesslists.spec.ts, packages/vm/tests/api/EIPs/eip-3541.spec.ts, packages/vm/tests/api/buildBlock.spec.ts, packages/vm/tests/api/runTx.spec.ts
This PR fixes an [EIP1559](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1559.md) bug, where we checked:
```
assert signer.balance >= transaction.gas_limit * transaction.max_fee_per_gas
```
However, in the EIP, the call value is first deducted from the accounts' balance, and we should thus add this to the `transaction.gas_limit * transaction.max_fee_per_gas`.
This PR also fixes a bug where nonce values are not checked at runtime.
=> VM: fix EIP1559 bug to include tx value in balance check, fix nonce check

packages/vm/CHANGELOG.md, packages/vm/tests/BlockchainTestsRunner.ts
We are not running all checks which are expected in `ethereum/tests`; if there is a `transactionSequence` field, try to execute the transactions on top of the last header block. This would have caught our nonce check problem in the transactions (see #1372).
=> VM: add tests for wrong transactions

packages/vm/CHANGELOG.md, packages/vm/src/evm/eei.ts, packages/vm/src/evm/interpreter.ts, packages/vm/src/evm/opcodes/EIP1283.ts, packages/vm/src/evm/opcodes/EIP2200.ts, packages/vm/src/evm/opcodes/EIP2929.ts, packages/vm/src/evm/opcodes/functions.ts, packages/vm/src/evm/opcodes/util.ts, packages/vm/src/index.ts, packages/vm/src/runTx.ts, packages/vm/tests/BlockchainTestsRunner.ts
This PR fixes several internal vm TODOs:
* Fix `state` opt type, add deprecation notice
* Use `gasRefund` from `execResult`
* Remove unneeded `no-unused-vars`
* Add eei method `addStipend`
* Fix typo (`prej` -> `prev`)
* Remove `runState._common` and pass common directly to functions needed
* Replace `utils.getContractStorage` with `eei.storageLoad` and add new opt `original`
=> VM: fix several internal todos

packages/trie/CHANGELOG.md, packages/trie/src/baseTrie.ts
Small change to remove internal use of deprecated `setRoot` method in `trie` package
=> trie: remove use of deprecated setRoot

.github/workflows/block-build.yml, .github/workflows/blockchain-build.yml, .github/workflows/client-build.yml, .github/workflows/common-build.yml, .github/workflows/devp2p-build.yml, .github/workflows/e2e-hardhat.yml, .github/workflows/ethash-build.yml, .github/workflows/node-versions.yml, .github/workflows/trie-build.yml, .github/workflows/tx-build.yml, .github/workflows/util-build.yml, .github/workflows/vm-build.yml, .github/workflows/vm-nightly-test.yml, .github/workflows/vm-pr.yml, scripts/check-npm-version.sh
Thanks to @alcuadrado for [mentioning](https://github.com/ethereumjs/ethereumjs-monorepo/pull/1395#discussion_r687059092) that the latest version of `actions/setup-node` has [caching](https://github.com/actions/setup-node#caching-packages-dependencies) capabilities, this really simplifies our ci scripts!
=> ci: simplify dependency cache code

config/cli/clean-package.sh, config/cli/clean-root.sh, package.json, packages/block/package.json, packages/blockchain/package.json, packages/client/package.json, packages/common/package.json, packages/devp2p/package.json, packages/ethash/package.json, packages/trie/package.json, packages/tx/package.json, packages/util/package.json, packages/vm/package.json
Adds a step in `npm run clean` in the directory root to remove all the `tsbuild` caches so Typescript doesn't throw build errors due to not being able to find `ethereumjs` packages that haven't been built yet when running `npm run clean` and then `npm i`.
=> Remove tsbuild caches

packages/client/lib/client.ts, packages/client/lib/config.ts, packages/client/lib/net/peerpool.ts, packages/client/lib/rpc/modules/eth.ts, packages/client/lib/service/fullethereumservice.ts, packages/client/lib/sync/fetcher/blockfetcherbase.ts, packages/client/lib/sync/fetcher/fetcher.ts, packages/client/lib/sync/fullsync.ts, packages/client/lib/sync/lightsync.ts, packages/client/lib/sync/sync.ts, packages/client/test/client.spec.ts, packages/client/test/integration/fullsync.spec.ts, packages/client/test/integration/util.ts, packages/client/test/rpc/eth/syncing.spec.ts, packages/client/test/sync/fullsync.spec.ts, packages/client/test/sync/lightsync.spec.ts, packages/client/test/sync/sync.spec.ts
This PR intends to keep the fullsync-syncer syncing at the tip of the chain. (Note: current branch target is the YoloV3 branch)
- Add `enqueueTask` to `fetcher`. This allows one to manually enqueue a task, and possibly restart the fetcher
- Add an option to not destroy the fetcher when it has processed all tasks
- Optimize full sync: in case no peers are available, then wait 5 seconds and try again, to get a best peer (this possibly fixes the re-bootstrap at some points)
- Fullsync `sync` method never resolves.
- Enqueue new blocks when the best peer announces new blocks
This is very WIP. Here are some things which need to be resolved: 
Currently, it seems to randomly work for some blocks (when we are at tip of chain, i.e. on YoloV3, every 15 seconds it imports and executes a new block), …
=> Client: keep syncing at tip of chain

packages/client/lib/sync/fetcher/blockfetcher.ts
As mentioned [here](https://github.com/ethereumjs/ethereumjs-monorepo/pull/1176#issuecomment-900218077), the log messages regarding peers sending useless responses to `eth` protocol messages are moved from `warn` to `debug` to reflect that these are not items that our client is responsible for.
=> client: move missing headers/bodies message to correct log level

packages/devp2p/src/rlpx/peer.ts
Ok, I hope that this will bring substantially more transparency to this central part of the RLPx code base. This whole "when is it called into which `sendMessage()` function from what context" topic was one of the main sources of confusion before. I actually already figured this out 3-4 times repeatedly and for this PR had to do another 30 minutes of research. 😜
Apart from several documentation additions one core of this PR is the improved "Received ..." debug message. This was before *always* inserting `undefined` for all subprotocol (e.g. `ETH`) messages, where people stumbled upon on debugging several times. What makes it worse is that people *then* interpret respectively associate the message code wrongly. So for `undefined` cases one is intuitively looking at the RLPx message code …
=> Devp2p: RLPx send message code and debug improvements

packages/client/lib/util/parse.ts
Geth genesis parameters store the `gasLimit` as a hex string while our `Common` instance calls for a `number`.  It's only currently used in the [header constructor](https://github.com/ethereumjs/ethereumjs-monorepo/blob/3d9774defa21cc9ca3af9c188d4be60d9de8c246/packages/block/src/header.ts#L231-L231) which is incidentally passing the value directly to a `new BN` constructor which currently takes a string as a possible input type so no errors are occuring.  
This small change parses the gasLimit to a `number` to ensure we have type safety for any future use and also keeps Typescript from complaining if you happen to be importing geth genesis parameters that have been converted to our file format as the gas limit will now correctly be converted to an integer first.
=> client: parse gasLimit as number for type safety

packages/devp2p/src/rlpx/peer.ts
Fixes #1421
When we did the original devp2p v5 in #1399 to add snappy compression to inbound/outbound devp2p messages, we didn't add snappy compression to the `ping`/`pong` messages since I wrongly interpreted them as not having a body so therefore not needing snappy.  This proved incorrect as we are still RLP encoding an empty array for the body and this also needs snappy compression.  Geth will now maintain connection through the `ping`/`pong` process.
=> devp2p: add snappy compression to ping/pong

packages/vm/src/state/stateManager.ts, packages/vm/tests/BlockchainTestsRunner.ts, packages/vm/tests/GeneralStateTestsRunner.ts, packages/vm/tests/api/runBlock.spec.ts, packages/vm/tests/api/runBlockchain.spec.ts, packages/vm/tests/api/state/stateManager.spec.ts, packages/vm/tests/config.ts, packages/vm/tests/util.ts
Closes #1271.
In #1271, a contract is deployed with code 0x80, this 0x80 is the same as `RLP([])`, which is the empty trie. Thus, if we hash this (to get the codeHash) then we get the hash of the empty trie. This confuses StateManager, as now suddenly empty state roots point to `0x80`, which is an invalid node which we cannot decode. Therefore, there are two options:
(1) Hardcode that the empty trie hash is indeed an empty trie, if a code is requested then instead return 0x80
(2) prefix codeHashes
(2) is better (after a discussion with Geth). We currently only have one case (the code 0x80) where this runs into problems. However, Geth has reported that they also run into problems when using fast sync. If we at some point start to assume that if a BranchNode/ExtensionNode has an underlying …
=> VM: Make CodeHashes have a DB prefix in StateManager

config/cli/ts-build.sh
It wasn't obvious to me if there was any actual issue or not but I've been seeing this sort of error in the build logs for a while:
```sh
> @ethereumjs/vm@5.5.2 build:browser
> ../../config/cli/ts-build.sh browser
../../config/cli/ts-build.sh: 75: [: browser: unexpected operator
../../config/cli/ts-build.sh: 78: [: browser: unexpected operator
[Node build] Using tsconfig.prod.json
> tsc --build ./tsconfig.prod.json
```
The build script was showing errors in the console every time I ran `npm i` and looks like the issue is the `==` operator not being supported by the Bourne shell, per [this article](https://stackoverflow.com/questions/24464690/bash-scripting-unexpected-operator).  Small fix to resolve the error.
=> bug: fix comparison operator bug

packages/client/lib/net/protocol/ethprotocol.ts
Fixes issue where geth sends a `reqId` that is too big for the JS number type and the `ETH` handler in the synchronizer errors out, causing us to lose sync with a peer.
I've run this PR on goerli for 80000 blocks syncing from a fully synced geth clients and experienced no recurrences of it.
=> client: fix reqId overflow issue in ETH handler

packages/devp2p/README.md, packages/devp2p/src/dpt/server.ts, packages/devp2p/src/eth/index.ts, packages/devp2p/src/les/index.ts, packages/devp2p/src/rlpx/peer.ts, packages/devp2p/src/util.ts
This PR adds per-message debugging on the devp2p library for the ETH protocol as well as other protocols. This should hopefully significantly help us on a more targeted debugging along client development.
Per-Message debugging can be used as follows, see also the additions to the docs for more information:
```shell
DEBUG=devp2p:eth:BLOCK_HEADERS,devp2p:eth:GET_BLOCK_HEADERS npm run client:start
```
Example output:
=> Devp2p: Per-Message debugging for ETH and other protocols / Improved docs

.github/workflows/block-build.yml, .github/workflows/blockchain-build.yml, .github/workflows/client-build.yml, .github/workflows/common-build.yml, .github/workflows/devp2p-build.yml, .github/workflows/e2e-hardhat.yml, .github/workflows/ethash-build.yml, .github/workflows/trie-build.yml, .github/workflows/tx-build.yml, .github/workflows/util-build.yml, .github/workflows/vm-build.yml
This PR adds the new `develop` branch to the ci triggers.
The only one left would be the nightly test, do we also want to run this once a day on `develop`? Since `on.schedule` doesn't allow you to specify the branch (https://stackoverflow.com/a/58800550) I am thinking of adding a matrix of `branch: [master, develop]` to the nightly jobs if we do want to add it. Or we could do it less frequently like once every 3 days, or on every push to `develop`, but I think then I'll have to create a new workflow file to customize.
If we merge this commit into master then I think we would also have to do it on `develop` so it has the updated files. I can probably re-open the same PR to merge into `develop` afterwards? Not sure if that would confuse rebasing master onto develop in the future, advice …
=> ci: add develop branch

.vscode/settings.json
VSCode was always returning this error in our monorepo setup:
> `Parsing error: Cannot read file '/dev/ethereumjs-monorepo/tsconfig.json'.eslint`
This PR adds `.vscode/settings.json` with a `workingDirectories` configuration to fix. See [docs](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint).
I also added format-on-save for developer productivity and time saving. Now when you save your file it should auto format properly with our lint and prettier rules!
=> vscode: add eslint workingDirectories config and enable format-on-save

.github/workflows/client-build.yml, packages/util/src/account.ts
This PR adds a more explicit note on `toChecksumAddress()` that the usage of EIP-1191 is discouraged due to the lack of backwards compatibility to the existing checksum format.
On a side line it also tests the reactivation of the E2E hardhat tests which I have reactivated in the Actions tab and where a fixing PR has been submitted on the Hardhat side here https://github.com/ethereumjs/ethereumjs-monorepo/pull/1391 by @ryanio which should have solved the test-breaking issue.
=> Util: More explicit EIP-1191 checksum usage discouraged note / Client: remove Rinkeby from CLI test matrix

config/MONOREPO.md
This PR adds a note for Windows installation to the monorepo docs. See https://github.com/ethereumjs/ethereumjs-monorepo/issues/1460#issuecomment-916480558 for reference.
=> docs: add Windows installation note

packages/client/lib/sync/fullsync.ts
Fixes bug in the logic for determining if a `NEW_BLOCK` is already known to a given peer
=> client: Bug fix in logic for adding known blocks to peers

packages/client/lib/util/parse.ts
Fixes #1466.  
The source of the issue is that when a geth genesis file is provided to the client, the `parseGethParams` method is inserting hardforks into the chain parameters with null block numbers where the hardfork is not present in the geth file.  When a client tries to connect to another client using the same geth genesis file, if one client isn't fully synced and sends a forkhash that is a subset of the other, the issue causes an error in `_validateForkId` at [this point](https://github.com/ethereumjs/ethereumjs-monorepo/blob/6e6dfb8f4c813c8be4be23b3f5a627e3aa545835/packages/devp2p/src/eth/index.ts#L157-L157) if the hardfork with a null block number is follow a hardfork with a block number since the forkhash is computed for all hardforks that occur on a given block is [the …
=> client: Filter out forks with no block set in config

packages/client/lib/miner/miner.ts
When the miner is assembling a new block and the new block happens to be the EIP1559 block, the `assembleBlock` was failing since the `baseFeePerGas` param wasn't active since EIP1559 isn't technically active in the `common` instance of the miner at the point in time where it's assembling the EIP1559 fork block (i.e. `Common` thinks it's EIP1559 fork block - 1).  This looks up the `initialBaseFee` from `common.paramByEIP` instead of `common.param` to retrieve that initial value when executing on the EIP1559 fork block.  It also adjusts the gas limit in line with the logic [validateGasLimit](https://github.com/ethereumjs/ethereumjs-monorepo/blob/90fea3df7a07dd1b1af248a19e76ad56a5432b94/packages/block/src/header.ts#L520-L520).
=> client: Fix gas calculations on EIP1559 forkblock in miner

packages/client/bin/cli.ts, packages/client/lib/rpc/index.ts
This PR adds a JSON-RPC help for CLI which lists all currently implemented RPC methods and can be used with a new `--helprpc` CLI option.
This should be useful for users to get an overview on the currently implemented RPC methods, making it unnecessary to refer to the - often outdated - respective tracking issue currently still linked in the RPC docs).
Output looks like the following:
=> Client: add JSON-RPC help (`--helprpc`)

packages/vm/package.json, packages/vm/src/index.ts
util.promisify is supported since Node.js 8, there's no point in using a polyfill.
That polyfill also breaks in ESM environments so removing it would be helpful.
=> feat(vm): use promisify from node.js

packages/common/docs/classes/default.md, packages/common/src/index.ts, packages/tx/README.md
Adds new custom parameters for Optimism L2 to the `CustomChains` `enum` in Common.
=> Common: add custom params for Optimism L2

packages/block/test/difficulty.spec.ts, packages/block/test/testdata/difficultyArrowGlacier.json, packages/common/src/chains/mainnet.json, packages/common/src/eips/4345.json, packages/common/src/eips/index.ts, packages/common/src/hardforks/arrowGlacier.json, packages/common/src/hardforks/index.ts, packages/common/src/index.ts, packages/common/tests/hardforks.spec.ts, packages/vm/src/index.ts
This PR adds the arrow glacier HF, which delays the difficulty bomb.
Since we have no test cases, do not merge yet.
=> Add arrowGlacier HF

packages/blockchain/CHANGELOG.md, packages/blockchain/src/index.ts
Fixes #1552.  
This addresses an issue where our code currently uses the bn.js `toBuffer()` function in several places in the `Blockchain` library which then breaks in the browser context.  Changes this usage to `toArrayLike()` per the [bn.js docs](https://github.com/indutny/bn.js/#utilities) to fix compatibility issues with browserify and similar bundlers.
=> blockchain: Change toBuffer to toArrayLike for BNs

package-lock.json, packages/blockchain/CHANGELOG.md, packages/blockchain/package.json, packages/client/package.json, packages/client/test/cli/cli-rpc.spec.ts, packages/client/test/cli/cli-sync.spec.ts, packages/vm/package.json
This patch release contains a bug fix for using the blockchain package in a browser context with tools like browserify, see PR [#1566](https://github.com/ethereumjs/ethereumjs-monorepo/pull/1566).
=> blockchain: v5.5.1 release

.github/workflows/vm-build.yml, .github/workflows/vm-pr.yml, packages/vm/package.json
I noticed we were running `npm run test:API` twice in our ci since it is already run during `coverage:test`, so this PR dedupes it.
=> vm: dedupe ci step

packages/common/src/chains/kovan.json, packages/common/tests/hardforks.spec.ts
Adds Berlin and London hardforks to Kovan chain details in Common
Block numbers/fork hashes pulled from:
- Berlin - https://github.com/openethereum/openethereum/commit/392a909cb746b67bb985bb7e6da6e21dfdb4cb16
- London - https://github.com/openethereum/openethereum/pull/502
=> Common: Add berlin/london hardforks to kovan

README.md
At some point a general MIT license note sneaked in to the overall [monorepo README](https://github.com/ethereumjs/ethereumjs-monorepo). This is misleading and actually wrong since close to all libraries are `MPL-2.0` licensed (for historical reasons). This PR corrects that.
See also: #1580
=> Monorepo: Correct License Note

package-lock.json, package.json, packages/vm/DEVELOPER.md, packages/vm/package.json, packages/vm/scripts/formatTest.js, scripts/e2e-publish.sh
Part of the work for #1537.
VM: `tap-spec` hasn't been updated in 3 years and npm reports it as having a high vulnerability. I found a fork of `tap-spec` that was last updated 6 months ago and does not seem to have the same vulnerability. https://www.npmjs.com/package/@randomgoods/tap-spec
Monorepo: I found a workaround for `npm login` in the `e2e-publish` script, so `npm-auth-to-token` can also be removed now.
=> monorepo, vm: remove npm vulnerabilities

packages/tx/src/eip1559Transaction.ts, packages/tx/src/legacyTransaction.ts, packages/util/src/bytes.ts, packages/util/test/bytes.spec.ts, packages/vm/src/runTx.ts
Clean-up items from #1568 
- Add explanatory notes to `validateNoLeadingZeroes` method in `util`
- Clarify error message in VM related to EIP3607
- Clean up error message in `legacyTransaction` constructor related to integer overflow
- Add test to demonstrate `0x01` is valid RLP encoding (since leading zeroes only occur if there are leading zero bytes (e.g. `0x001` which translates to `Buffer<00 01>`
=> Ethtests 10.2 cleanup items

packages/client/examples/private-geth-network.md
Fixes a broken link in one of the examples for instantiating a client with custom network parameters
=> client: fix broken link in client example

packages/client/lib/logging.ts
This PR fixes `winston` error logging to properly output error messages along with their stack trace.
While we define the error format for each transport (console: with colors, log file: without colors), winston also needs a top level `format` defined or we get this weird behavior.
---
To test this PR, run `npm run client:start -- --dev` once then comment out ```removeSync(`${args.datadir}/devnet`)``` in `bin/cli.ts:578` and run `npm run client:start -- --dev` again.
Before this PR you should see:
```
INFO [12-06|11:55:48] Initializing Ethereumjs client version=v0.2.0 network=devnet
ERROR [12-06|11:55:48] (empty message)
```
With this PR:
```
INFO [12-06|11:59:22] Initializing Ethereumjs client version=v0.2.0 network=devnet
ERROR [12-06|11:59:22] Error: The genesis block in the DB has a …
```
=> client: fix error logging

packages/vm/src/evm/eei.ts, packages/vm/tests/api/runCall.spec.ts
This PR closes #1591. 
Note: currently, `ethereum-tests` has not yet released the tests relevant to this, so I ran these locally. 
```
cd ./packages/ethereum-tests/ && git branch && git log -n 4 && cd -
develop
* refund-tests
commit 658605b000855cec2ea546c4fdf07c442d9ee1d7 (HEAD -> refund-tests, origin/refund-tests)
Author: marioevz <marioevz@gmail.com>
Date:   Fri Dec 10 20:11:32 2021 +0000
Add Log + Contract Creation OoG
commit 96c5815807804879008b15ccedbf298aa8359f3b
Author: marioevz <marioevz@gmail.com>
Date:   Fri Dec 10 18:38:47 2021 +0000
Add proper check for self destruct refund on contract creation
commit 18e7f5535246272ee7ed7ff440162acbeeaedc7e
Author: marioevz <marioevz@gmail.com>
Date:   Fri Dec 10 18:25:33 2021 +0000
Add tests for refund checks on OoG contract creation
commit …
```
=> Finish EIP-2681

config/eslint.js, packages/block/test/eip1559block.spec.ts, packages/client/bin/cli.ts, packages/client/lib/net/protocol/ethprotocol.ts, packages/common/src/index.ts, packages/tx/test/base.spec.ts
This PR disables eslint's `no-extra-semi` rule since it gets in the way when a semicolon is needed, like when the line starts with an opening parenthesis. I found that prettier rules already exhaustively cover semi formatting.
=> eslint: disable no-extra-semi, remove overrides

packages/common/src/eips/3855.json, packages/common/src/eips/index.ts, packages/vm/src/evm/opcodes/codes.ts, packages/vm/src/evm/opcodes/functions.ts, packages/vm/src/index.ts, packages/vm/src/runCode.ts, packages/vm/tests/api/EIPs/eip-3855.spec.ts
https://eips.ethereum.org/EIPS/eip-3855
=> common/vm: add EIP-3855, PUSH0 instruction

packages/client/package.json, packages/client/webpack.config.js
Fix broken dependency in webpack where node's `constants` package isn't being polyfilled by webpack 5.
=> Add fallback for node constants

.github/workflows/block-build.yml, .github/workflows/blockchain-build.yml, .github/workflows/client-build.yml, .github/workflows/common-build.yml, .github/workflows/devp2p-build.yml, .github/workflows/e2e-hardhat.yml, .github/workflows/ethash-build.yml, .github/workflows/node-versions.yml, .github/workflows/trie-build.yml, .github/workflows/tx-build.yml, .github/workflows/util-build.yml, .github/workflows/vm-build.yml, .github/workflows/vm-nightly-test.yml, .github/workflows/vm-pr.yml, Dockerfile, package-lock.json, packages/block/package.json, packages/blockchain/package.json, packages/client/package.json, packages/client/test/cli/cli-rpc.spec.ts, packages/client/test/cli/cli-sync.spec.ts, packages/common/package.json, packages/devp2p/package.json, packages/devp2p/src/eth/index.ts, packages/trie/package.json, packages/tx/package.json, packages/util/package.json, packages/util/test/account.spec.ts, packages/vm/package.json, packages/vm/tests/api/runBlock.spec.ts
This PR upgrades the ci to run default on Node v16 since v12 will be EOL in April.
Node v16 includes npm v7 by default so we can remove the extra install step.
We still test Node v12 on a nightly basis thanks to @evertonfraga's `node-versions.yml` workflow that pulls and runs all active and LTS versions.
=> ci: upgrade node to v16

README.md, codecov.yml
This PR adds rlp to the root readme on master.
It also adds the carryforward option for the rlp flag since the coverage is not run on every pr or build (https://docs.codecov.com/docs/flags#carryforward-flags)
=> rlp: add to root readme

packages/util/package.json, packages/util/src/account.ts, packages/util/src/address.ts, packages/util/src/object.ts
`object.ts` makes use of the `assert` module. This is a Node API that's no longer polyfilled by Webpack 5.
Anyone who depends upon `ethereumjs-util/object` won't be able to upgrade their project to Webpack 5. Webpack will fail to build their project, citing that `assert` is missing. This also implies that anyone trying to use `ethereumjs-util` with Create React App 5 won't be able to either, since CRA5 uses Webpack 5.
Here's an example of folks in the Web3 community having trouble with this: https://github.com/solana-labs/wallet-adapter/issues/241
In this PR, rather than to include a full polyfill of `assert` for browsers (eg. https://github.com/ethereumjs/ethereumjs-monorepo/pull/1637) we boil the assertions down to regular `if` statements and thrown `Errors`.
```
cd packages/util
yarn …
```
=> Util: Remove `assert` in favor of simply throwing `Errors` to ensure compatibility with Webpack 5

packages/client/lib/rpc/modules/engine.ts, packages/client/test/rpc/engine/executePayloadV1.spec.ts
Engine Api spec for merge renamed few fields of the execution payload. This PR renames some of the fields which got skipped in the kintsugi branch.
Spec Reference: https://github.com/ethereum/execution-apis/releases/tag/v1.0.0-alpha.5
=> Rename coinbase to feeRecipient as per v1.0.0-alpha.5 spec

packages/common/README.md, packages/common/src/index.ts, packages/common/tests/chains.spec.ts, packages/common/tests/hardforks.spec.ts, packages/common/tests/params.spec.ts, packages/vm/README.md, packages/vm/src/index.ts, packages/vm/tests/api/index.spec.ts
Closes #1274
Removing `onlySupported` and `onlyActive` was pretty straightforward, but it took me a bit longer to work out how to move `supportedHardforks` to the `vm` package. When doing so, I realized we might not need to store `opts.supportedHardforks` in the VM instance (e.g. in `this._supportedHardforks`) at all, and instead it just becomes a check at time of instantiation. But I'm not sure if I'm missing something, so I left some potential changes commented out in `packages/vm/src/index.ts`. I can update it either way but wanted to get an initial review to see if I'm on the right track.
I also updated the Common and VM READMEs to reflect the respective changes.
=> Common, VM: Remove unused HF options from Common, move supportedHardforks to VM

packages/blockchain/package.json, packages/client/package.json, packages/devp2p/package.json, packages/devp2p/src/dpt/dpt.ts, packages/devp2p/src/dpt/server.ts, packages/devp2p/src/eth/index.ts, packages/devp2p/src/les/index.ts, packages/devp2p/src/rlpx/peer.ts, packages/devp2p/src/rlpx/rlpx.ts, packages/devp2p/src/util.ts, packages/vm/package.json
Updates debug package to 4.3.3
Also fixes some logic devp2p code that caused multiple debug messages.
=> Devp2p, Client: Fix duplicated debug messages

packages/client/lib/rpc/modules/eth.ts, packages/vm/src/state/index.ts, packages/vm/src/state/interface.ts
Part of #1533
(to be done towards `master` since generic and relevant for minor releases)
I had some doubts on the ProofStateManager for some time since this would add some additional complexity on the StateManager interface collection. Now I directly stumbled upon this on the start of trying to add a VerkleTrie StateManager.
So I wouldn't want (couldn't) implement this functionality in such a state manager. But then in these RPC code parts of the client I would need some somewhat ugly `any` casts (and then do this functionality check anyhow) to get this working.
So I think this is a somewhat more flexible and practical solution - to add these as optional methods to the generic interface. Then TypeScript knows that this functionality might be there (people who use this would as well) and …
=> VM, Client: Remove ProofStateManager interface

.github/workflows/block-build.yml, .github/workflows/blockchain-build.yml, .github/workflows/client-build.yml, .github/workflows/common-build.yml, .github/workflows/devp2p-build.yml, .github/workflows/e2e-hardhat.yml, .github/workflows/ethash-build.yml, .github/workflows/examples.yml, .github/workflows/node-versions.yml, .github/workflows/rlp-build.yml, .github/workflows/trie-build.yml, .github/workflows/tx-build.yml, .github/workflows/util-build.yml, .github/workflows/vm-build.yml, .github/workflows/vm-pr.yml
This PR adds a new feature recently added to GitHub Action workflows, concurrency: https://docs.github.com/en/actions/using-jobs/using-concurrency
This allows us to automatically cancel previous runs for the same PR, rather than manually doing it or waiting for the outdated runs to finish.
To test, I will push a commit right after this to ensure that the behavior works as expected.
=> ci: add concurrency

packages/vm/src/evm/interpreter.ts
Adds a check in the `interpreter` to skip the `_runStepHook` function if there are no `step` event listeners since this method's sole purpose is to create and emit the `step` event.  The `step` is only used in tests in our code base so this should produce some (likely minor) overall improvement in VM performance since this function is run on each step in VM execution.
=> vm: skip `_runStepHook` method if no step event listener

packages/vm/tests/util.ts
The `blockchain` test runner currently errors out at the end of the test run when you set the `--debug` if there are no failing tests.  This can be seen by running the below command on the current master branc.
` npm run tester -- --blockchain --file="dayLimitConstruction.json" --debug` and noting the output
```
ok 12 correct storage value
/home/jim/development/ethereumjs-monorepo/packages/vm/tests/util.ts:154
for (const hash of keyMap) {
^
TypeError: keyMap is not iterable
at TrieReadStream.<anonymous> (/home/jim/development/ethereumjs-monorepo/packages/vm/tests/util.ts:154:26)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
This PR resolves the issue by converting the `for property...of..keyMap` to a proper iterator using `Object.entries` to ensure that the …
=> vm: fix keyMap iterator in blockchain test runner

packages/vm/src/evm/evm.ts, packages/vm/tests/api/runTx.spec.ts
Bug caused in Kintsugi; https://explorer.kintsugi.themerge.dev/tx/0x1fb8a5ac000196a54dfe63dfda60542340b790a874b1d319b0aa834ef2ea1425/internal-transactions
The problem is this: `REVERT` opcode does not consume all gas and puts a "revert reason message" in the return buffer (accessible with `RETURNDATACOPY`). This return buffer is also used to return whatever code should be deployed when creating a contract. The problem is that we, in general, check that there is no exception error. If there is an exception error, most logic in `executeCreate` of `evm.ts` does not run.
However, this check is not done [here](https://github.com/ethereumjs/ethereumjs-monorepo/blob/68f714921094ee7c6941c9fbbf9aacaf24838706/packages/vm/src/evm/evm.ts#L399), to check if the code size is larger than the max code …
=> vm: Fix contract REVERT bug: upon creation, REVERT return data > maxCodeSize

packages/tx/test/transactionRunner.ts, packages/tx/test/types.ts
I noticed we are not using all hardforks on the tx ethereum/tests tests, so added them here.
=> Add latest hardforks to tx tests

packages/client/lib/util/parse.ts, packages/client/test/testdata/post-merge.json, packages/client/test/util/parse.spec.ts
We had a logic where if the london block was zero and the `baseFeePerGas` undefined, we would set the `baseFeePerGas` to `1000000000`, otherwise, it would be undefined, this would not allow us to set the `baseFeePerGas` on the genesis initialization when parsing it with geth format. Now this logic has been moved to the block package (It was done by Ryan a few weeks ago)
=> Client: Geth genesis parser minor fix

packages/util/package.json, packages/util/src/account.ts, packages/util/src/hash.ts, packages/util/src/signature.ts, packages/util/test/account.spec.ts
Two caveats:
1. Added @noble/secp256k1 directly because we forgot to export `recoverPublicKey` to e-c. I suggest to merge like this, and i'll do another PR after we release 1.0.1
2. isValidPrivate tests are failing: noble does not throw on any invalid private, `isValidPrivateKey` is always either true or false. What should I do?
Closes #1668
=> Util: Upgrade to ethereum-cryptography 1.0

config/eslint.js, config/tsconfig.browser.json, config/tsconfig.json, package-lock.json, packages/vm/src/evm/opcodes/functions.ts, packages/vm/src/evm/opcodes/util.ts, packages/vm/src/runCall.ts
- Downgrades ES target to ES2018 with specific library targets for `es2019.object` and `es2020.bigint` to address https://github.com/ethereumjs/ethereumjs-monorepo/issues/1729. 
- Fixes a couple of missed native bigint notation numbers left over from https://github.com/ethereumjs/ethereumjs-monorepo/pull/1671
- Dedups `expmod`/`exponentiation` (thanks @paulmillr !!!)
=> Target ES2018 + misc cleanup

packages/tx/src/baseTransaction.ts, packages/tx/src/eip1559Transaction.ts, packages/tx/src/eip2930Transaction.ts, packages/tx/src/legacyTransaction.ts, packages/tx/src/transactionFactory.ts, packages/tx/test/base.spec.ts, packages/tx/test/transactionFactory.spec.ts, packages/tx/test/typedTxsAndEIP2930.spec.ts
Fixes #1739
Remove deprecated method declarations and tests
* get transactionType()
* get senderR()
* get senderS()
* get yParity()
* tx.fromRlpSerializedTx()
* _unsignedTxImplementsEIP155()
* _signedTxImplementsEIP155()
* TransactionFactory.getTransactionClass()
=> Tx: Execute on deprecation notes

.github/workflows/node-versions.yml, packages/client/test/integration/fullsync.spec.ts, packages/client/test/integration/mocks/mockserver.ts
Closes #1736 
This was a weird race condition that sometimes passed and sometimes didn't on my local without any code changes.
By moving the localServer up in the destroy sequence it should execute it more reliably before the next test starts. I also replaced the setTimeout in `await new Promise` with `this.wait`
=> ci: fix client integration failure

packages/block/src/header.ts, packages/block/src/types.ts, packages/block/test/eip1559block.spec.ts
closes #1747 
Removes `bloom` and `baseFee` from `block` package
=> Block: deprecation tasks

packages/common/src/eips/3670.json, packages/common/src/eips/index.ts, packages/vm/src/evm/evm.ts, packages/vm/src/evm/opcodes/functions.ts, packages/vm/src/evm/opcodes/util.ts, packages/vm/src/index.ts, packages/vm/tests/api/EIPs/eip-3540-evm--object-format.spec.ts, packages/vm/tests/api/EIPs/eip-3540-evm-object-format.spec copy.ts, packages/vm/tests/api/EIPs/eip-3670-eof-code-validation.spec.ts
Implements EIP-3670 on top of EIP-3540 PR
https://eips.ethereum.org/EIPS/eip-3670
=> VM, Common: Add EIP-3670 (EOF - Code Validation)

packages/block/src/header.ts, packages/block/test/block.spec.ts, packages/common/src/index.ts, packages/common/tests/hardforks.spec.ts, packages/common/tests/mergePOS.spec.ts, packages/common/tests/params.spec.ts, packages/vm/src/runBlock.ts
closes #1674 
Summary of changes:
Removed methods:
- `hardforkIsActiveOnChain`
- `activeHardforks`
- `activeHardfork`
Modified methods:
- `paramByBlock`
- Original signature: `paramByBlock(topic: string, name: string, blockNumber: BNLike)`
- New signature: `paramByBlock(topic: string, name: string, blockNumber: BNLike, td?: BNLike)`
- `_getHardfork` (internal helper function)
- Returns `null` instead of throwing if HF does not exist on chain
=> Common, Block: remove and rename ambiguous active methods

package-lock.json, packages/client/bin/cli.ts, packages/client/bin/startRpc.ts, packages/client/lib/util/rpc.ts, packages/client/package.json
Motivation: While making getProof requests from the browser using web3, the requests were being rejected because of the enforced cors policy by the browser for the webpage.
This PR adds the ability to provide a cors string to the rpc api, `*` by default (i.e. no restrictions). Post this the browser was able to make the required requests to ethereumjs rpc server.
=> client - Add functionality to specify cors for rpc server

packages/client/test/miner/miner.spec.ts, packages/client/test/miner/pendingBlock.spec.ts, packages/vm/src/evm/eei.ts, packages/vm/src/state/interface.ts, packages/vm/src/state/stateManager.ts, packages/vm/tests/api/EIPs/eip-1559-FeeMarket.spec.ts, packages/vm/tests/api/EIPs/eip-3198-BaseFee.spec.ts, packages/vm/tests/api/state/stateManager.spec.ts
This PR reintroduces @emersonmacro's https://github.com/ethereumjs/ethereumjs-monorepo/pull/1369 on the `develop` branch, since we had accidentally introduced a breaking change in the stateManager interface on master. This led to issues with hardhat's custom statemanager implementation not having the method. We reversed the work on master in https://github.com/ethereumjs/ethereumjs-monorepo/pull/1390, and this PR now reintroduces it on `develop` as part of v6 breaking changes release (https://github.com/ethereumjs/ethereumjs-monorepo/issues/1717)
=> vm: reintroduce modifyAccountFields

packages/client/lib/util/rpc.ts
the kilnv2 payload sizes were throwing error on engine api, updated the size limit in the body-parse as per the bellatrix specs of 10MiB of gossip size.
=> client: increase json parser size

packages/client/.gitignore, packages/client/bin/cli.ts, packages/client/bin/startRpc.ts, packages/client/kiln/Dockerfile, packages/client/kiln/README.md, packages/client/kiln/docker-compose.ethereumjs.yml, packages/client/lib/client.ts, packages/client/lib/sync/fetcher/blockfetcherbase.ts, packages/client/lib/sync/fetcher/fetcher.ts, packages/client/lib/sync/fullsync.ts, packages/client/lib/sync/lightsync.ts, packages/client/lib/sync/sync.ts, packages/client/lib/sync/txpool.ts, packages/client/lib/util/index.ts, packages/client/lib/util/rpc.ts, packages/client/test/cli/cli-rpc.spec.ts, packages/client/test/sync/fetcher/blockfetcher.spec.ts, packages/client/test/util/rpc.spec.ts, packages/client/webpack.config.js
This PR 
- updates the Kiln public testnet instructions
- switches on the engine api auth on a separate port 8551 by default (as what how its expected in kiln public testnet). 
- Also allows to  opens a websocket connection (via `-ws` flag) for engine api seperately (on same port 8551 by default for engine, and 8545 by default for non engine)
plus a small refactoring.
=> client: Kiln public testnet update

packages/devp2p/src/protocol/eth.ts, packages/devp2p/src/protocol/les.ts, packages/devp2p/src/protocol/protocol.ts
Quick fix following up on https://github.com/ethereumjs/ethereumjs-monorepo/pull/1600#pullrequestreview-905465290, the main issue here was that the per-message debug logs were not prefixed with `devp2p` (so they were being output e.g. `eth:STATUS` rather than `devp2p:eth:STATUS`)
edit: I have also further consolidated the classes, moving _version and _send to the parent class
=> devp2p: fix per-message debug logging

packages/common/src/eips/1559.json, packages/common/src/eips/2315.json, packages/common/src/eips/2565.json, packages/common/src/eips/2718.json, packages/common/src/eips/2929.json, packages/common/src/eips/2930.json, packages/common/src/eips/3198.json, packages/common/src/eips/3529.json, packages/common/src/eips/3541.json, packages/common/src/eips/3554.json, packages/common/src/eips/3607.json, packages/common/src/eips/3675.json, packages/common/src/eips/3855.json, packages/common/src/eips/3860.json, packages/common/src/eips/4345.json, packages/common/src/eips/4399.json, packages/common/src/hardforks/berlin.json, packages/common/src/hardforks/istanbul.json, packages/common/src/hardforks/london.json, packages/common/src/hardforks/petersburg.json
Closes #1773
Have only updated the "status" fields, the rest are prettier formats.
(I wonder if we should open a separate PR to format all of our JSON and markdown files in the monorepo at once, the command from root would be: `npx prettier "**/*.{json,md}" --write`)
=> common: update status fields for EIPs and hardforks

packages/blockchain/src/db/operation.ts
When the database operation is `del`, `this.baseDBOp.value` is undefined instead of `Buffer`.
In the old code, when deleting a value, the value is deleted in the database but not in the cache, causing the next read value still exists (because `DBManager` always tries to load data from cache first)
BTW, I tried to add a test case for this fix, but to find out that neither `DBManager` nor `DBOp` has a test case, maybe this should be improved?
=> blockchain: fix updateCache

packages/client/lib/rpc/modules/eth.ts
This PR aims to add the `mixHash` attribute on the `JsonRpcBlock` type, the reason is that when running the tests against the hive, they query the latest block with `eth_getBlockByNumber` and then they parse that data with Geth lib, which expects mixHash to be in the object, otherwise the hash wont match, making the tests go red
=> Client: Mix hash added to JsonRpcBlock

packages/block/src/header.ts
This PR resolves https://github.com/ethereumjs/ethereumjs-monorepo/issues/1738
=> block: unify blockHeader constructor input shapes

packages/client/bin/cli.ts
This PR aims to add support to unlock the miner with a PK in a file in the CLI script, the reason for adding this change is that, in the Hive tests, we need to somehow unlock miner so we can produce new blocks; this is achieved by receiving the private key through the Hive environment variables
=> Client: Unlock miner with file pk

packages/client/lib/config.ts, packages/client/lib/net/peerpool.ts, packages/client/lib/net/server/server.ts, packages/client/lib/sync/fetcher/blockfetcher.ts, packages/client/lib/sync/fetcher/blockfetcherbase.ts, packages/client/lib/sync/fetcher/fetcher.ts, packages/client/lib/sync/fetcher/headerfetcher.ts, packages/client/lib/sync/fullsync.ts, packages/client/test/integration/peerpool.spec.ts, packages/client/test/integration/util.ts, packages/client/test/sync/fetcher/blockfetcher.spec.ts, packages/client/test/sync/fullsync.spec.ts
While running on kiln, some more issues of sync stalling were observed: https://github.com/ethereumjs/ethereumjs-monorepo/issues/1780
The trigger of the sync stall is when the fetcher adds block to blockchain and the blocks fetched are not linearly connected, it leads to issue. 
~~One of the issue was writer was being destroyed.  This PR removes that condition of the writer being destroyed on error  as well as improves the fetcher logging a bit for better debugging.~~
UPDATE: Figured out that the writer's call back `cb(error)` switches off the writer. In case such a thing happened, its better to return an error in `await fetch(..)` and let the sync loop try with a different peer if required.
This also fixes the behavior that other peers were never tried because `fetcher.fetch` was never …
=> client: Sync stall investigation improvements

packages/client/lib/execution/receipt.ts, packages/client/lib/rpc/modules/eth.ts, packages/client/test/rpc/eth/getLogs.spec.ts
Thanks to "Sea Monkey" in our discord, teku was calling eth_getLogs with an array of addresses (rather than a single address) and this is valid according to the spec, so this PR fixes our endpoint.
=> client: expand getLogs to accept array of addresses

packages/vm/src/evm/evm.ts, packages/vm/src/evm/interpreter.ts, packages/vm/src/evm/opcodes/eof.ts, packages/vm/src/evm/opcodes/util.ts, packages/vm/tests/api/EIPs/eip-3540-evm-object-format.spec.ts, packages/vm/tests/api/EIPs/eip-3670-eof-code-validation.spec.ts
This is some follow-up work on #1719 with some improvements and clean-ups on the tests, also meant as some additional implicit review by dealing with the code.
I removed some various redundand code parts in the test files and and did some (very few) test additions and/or modifications. One major change is that I moved the whole EOF logic into its own file, it very much feels to me that this is justified since this is some major new functionality, likely also with additions and evolutions in the future. Let me know if you are ok with how this is integrated.
Otherwise: again, work looks extremely solid, thanks Andrew - also Jochem - for these great PRs! 😄
=> VM: EIP-3450, EIP-3670 Improvements and Test Clean-Ups

packages/client/lib/net/peerpool.ts
This will redo a new bootstrap in the client along status checks to allow for connection re-pickup if the initial connection fails. Behavior is now also activated in non-discovery scenarios (as in Kiln where a single bootnode is used for connection).
This was requested in the chat since otherwise auto-starting a client is very much unreliable.
=> Client: Improve stalled Kiln startup

packages/client/lib/net/peerpool.ts, packages/client/lib/sync/fetcher/blockfetcher.ts, packages/client/lib/sync/fetcher/fetcher.ts, packages/client/lib/sync/fetcher/headerfetcher.ts, packages/client/lib/sync/fullsync.ts, packages/client/test/sync/fetcher/blockfetcher.spec.ts, packages/client/test/sync/fetcher/fetcher.spec.ts, packages/client/test/sync/fetcher/headerfetcher.spec.ts
This PR is follow up of #1781 and adds the followinf refinements
=> client: Fetcher reorg handling

packages/client/lib/rpc/modules/engine.ts, packages/client/lib/sync/txpool.ts, packages/client/test/rpc/helpers.ts
A few small fixes I've gathered:
* add rpc validation for new `engine_exchangeTransitionConfiguration`
* create separate type for test utils type StartRPCOpts
* TxPool: Was getting this error frequently in normal tx pool operation: `Error handling message (eth:NewPooledTransactionHashes): (intermediate value) is not iterable`. After disabling the error catch so I can find the affected lines throwing, this is what resulted:
```
const [_, txs] = await (peer.eth as EthProtocolMethods).getPooledTransactions({
^
TypeError: (intermediate value) is not iterable
at TxPool.handleAnnouncedTxHashes (/Users/rg/dev/ethereumjs-monorepo/packages/client/lib/sync/txpool.ts:372:22)
```
I solved the above by first capturing the variable, checking it is defined, then destructuring the array into `const [_, …
=> client: small fixes (txpool result not iterable, rpc validation for exchangeTransitionConfiguration)

packages/client/bin/cli.ts, packages/client/kiln/README.md, packages/client/lib/util/parse.ts
This PR is adding additional Kiln bootnodes from [here](https://config.kiln.themerge.dev/el/bootnodes). It also fixes a bug where comma-separated bootnodes passed on CLI have not been parsed correctly.
The whole input situation - so, what get's into this `parseMultiaddrs()` in what format from where - is generally a bit chaotic (and might benefit from some small refactoring at some point), so I stayed conservative and rather a bit over-cautious and very much limited the added condition on this very specific case, since I couldn't completely oversee eventual side effects.
=> Client: Bootnodes fix

packages/common/src/index.ts, packages/common/tests/chains.spec.ts
On the Common `copy()` method the event listeners from the original object persist also on the copied object. This has  unwanted side effects. I discovered this in the client where the Block instantiation with the chain common [here](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/client/lib/net/protocol/ethprotocol.ts#L138) causes the `hardforkUpdated` event to still get consumed by the original listeners added to `chainCommon` when fired on the copied Common in the new Block object when the [hardfork is set](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/block/src/header.ts#L260) in the constructor.
=> Common: Fixed Event Listener Take-Over on Common.copy()

packages/client/lib/blockchain/chain.ts, packages/client/lib/rpc/modules/engine.ts, packages/client/lib/rpc/util/CLConnectionManager.ts, packages/client/lib/sync/fullsync.ts, packages/client/test/rpc/engine/newPayloadV1.spec.ts
Working on some more logger improvements around the Merge.
- Clean-up on redundant fetcher shutdown and log messages
- Dedicated log note on first CL execution block to clearly differentiate from Merge block
- Continued preMerge and a one-time post Merge warning if no CL connection is available
Here is some screenshot:
Will continue still a bit also looking at the "CONNECTED" scenario and see what can happen and should get notifications there.
Work is targeted towards the latest multi-peer-fix branch from @g11tech (works like a charm! 🙏 🙂 🎉) and can be merged in there before or post PR-merge, everything fine for me.
=> Client: more Merge-related logger improvments

packages/client/lib/blockchain/chain.ts, packages/client/lib/rpc/modules/engine.ts, packages/client/lib/rpc/util/CLConnectionManager.ts, packages/client/lib/sync/fetcher/blockfetcher.ts, packages/client/lib/sync/fetcher/fetcher.ts, packages/client/lib/sync/fetcher/headerfetcher.ts, packages/client/lib/sync/fetcher/types.ts, packages/client/lib/sync/fullsync.ts, packages/client/test/rpc/engine/newPayloadV1.spec.ts, packages/client/test/sync/fetcher/blockfetcher.spec.ts, packages/client/test/sync/fetcher/headerfetcher.spec.ts, packages/vm/src/runBlock.ts
The way we were adopting/handling jobs wasn't multi-peer safe when the results were provided less than asked for, as any shifting of jobs were not being reflected in the next job being fetched  by some other peer for e.g.
This PR fixes that, and enqueues the job again (instead of shifting/adopting all other jobs) to fetch the remaining data:
Example log:
```
client:fetcher Job index greater than processed + max queue size, skip next job execution. +0ms
client:fetcher Requested blocks=24034-24051 from id=e9631196 address=10.244.0.164:30303 (received: 17 headers / 7 bodies) +23ms
client:fetcher Adopt start block/header number from remaining jobs (provided=40 expected=50) +6ms
client:fetcher Re-enqueuing job index=480 first=24041 count=10 partialResults=40 from peer id=e9631196 (reply …
```
=> client: Handle partial results in multi-peer safe manner

packages/client/lib/rpc/modules/engine.ts, packages/client/test/rpc/engine/forkchoiceUpdatedV1.spec.ts
This PR aims to validate that the safe head block exists in the chain. Fixing the test case from the Hive: [Unknown SafeBlockHash](https://hackmd.io/lKw1UArUSWu1_lOdbt3heQ#Full-Description-of-Test-Cases)
Implementation inspired from geth: https://github.com/ethereum/go-ethereum/blob/master/eth/catalyst/api.go#L168-L179
Also, this is the validation mentioned on [Forkchoice state specs](https://github.com/ethereum/execution-apis/blob/main/src/engine/specification.md#forkchoicestatev1)
edit: this PR will have conflicts with #1803 - I will take care of that once one of these two PRs got merged
=> Client: Validate block safe hash on ForkchoiceUpdated

packages/client/lib/rpc/modules/eth.ts, packages/client/test/rpc/eth/getBlockByNumber.spec.ts
This PR aims to make the `eth_getBlockByNumber` return an array of transactions when `true` is passed as the second parameter; also, it returns `input` instead of `data` and `gas` instead of `gasLimit` as this is what is expected based on the [JSON-RPC Specs](https://github.com/ethereum/execution-apis/blob/main/src/schemas/transaction.json#L141-L176)
=> Client: eth_getBlockByNumber method returns array of tx object when asked

packages/client/lib/rpc/modules/engine.ts, packages/client/test/rpc/engine/forkchoiceUpdatedV1.spec.ts
This PR aims to validate that the finalized block exists in the chain. Fixing the test case from the Hive: [Unknown SafeBlockHash](https://hackmd.io/lKw1UArUSWu1_lOdbt3heQ#Full-Description-of-Test-Cases)
Implementation inspired from geth: https://github.com/ethereum/go-ethereum/blob/master/eth/catalyst/api.go#L154-L167
Also, this is bullet number 6 from [fork choice update specs](https://github.com/ethereum/execution-apis/blob/main/src/engine/specification.md#specification-1)
=> Client: Validate finalized block hash on ForkchoiceUpdated 

packages/client/bin/cli.ts
Adds a new `--startBlock` parameter to the CLI that will rewind the blockchain and set the head to the specified block number and start syncing from that point.
=> client: Add new startBlock parameter to client

packages/client/lib/rpc/modules/engine.ts, packages/client/lib/rpc/util/CLConnectionManager.ts
This is adding more Merge logging improvements like adjusting connection loss status values, fixing CL connection status display on client startup and refactor especially the forkchoice update log to be able to also log along RPC responses and various head block properties (block number / timestamp right now).
PR also updates the synchronized-status-check to only trigger a an update on recent blocks with a close-to-present timestamp, so that this is both not permanently logged and (likely more important) also not triggering synchronized-status based client logic.
A bit in a rush right now, should be ready for review I guess.
=> Client: even more Merge logging improvements

packages/client/lib/rpc/modules/engine.ts, packages/client/test/rpc/engine/forkchoiceUpdatedV1.spec.ts
With this PR, I aim to tackle: `Latest block after reorg` from the [Hive tests](https://hackmd.io/lKw1UArUSWu1_lOdbt3heQ?view#Eth-RPC-Status-on-ForkchoiceUpdated-Events1). Which makes sure that `forkchoiceUpdated` method is able to reorg if a previous block was sent as `headBlockHash`
=> Client: Fcu handles if headBlockHash is an old block

packages/client/lib/execution/receipt.ts, packages/client/lib/net/protocol/ethprotocol.ts, packages/client/lib/rpc/modules/eth.ts, packages/client/lib/service/fullethereumservice.ts, packages/client/lib/util/debug.ts, packages/client/test/net/protocol/ethprotocol.spec.ts, packages/client/test/service/fullethereumservice.spec.ts, packages/vm/benchmarks/util.ts, packages/vm/src/buildBlock.ts, packages/vm/src/evm/eei.ts, packages/vm/src/evm/evm.ts, packages/vm/src/index.ts, packages/vm/src/runBlock.ts, packages/vm/src/runCode.ts, packages/vm/src/runTx.ts, packages/vm/src/state/interface.ts, packages/vm/src/types.ts, packages/vm/tests/api/EIPs/eip-1283-net-gas-metering.spec.ts, packages/vm/tests/api/EIPs/eip-2929.spec.ts, packages/vm/tests/api/EIPs/eip-3529.spec.ts, packages/vm/tests/api/buildBlock.spec.ts, packages/vm/tests/api/evm/precompiles/hardfork.spec.ts, packages/vm/tests/api/index.spec.ts, packages/vm/tests/api/istanbul/eip-2200.spec.ts, packages/vm/tests/api/runBlock.spec.ts, packages/vm/tests/api/runCall.spec.ts, packages/vm/tests/api/runCode.spec.ts, packages/vm/tests/api/runTx.spec.ts, packages/vm/tests/api/state/accountExists.spec.ts
This PR accomplishes VM breaking change tasks listed in #1717:
- Moved EVMResult.gasUsed to RunTxResult where it is added to there, and execResult.gasUsed remains the same
- Moved one level up to EVMResult, since it does not seem appropriate (or used) in execResult
=> vm, client: continuing v6 breaking changes

packages/util/src/account.ts, packages/util/src/bytes.ts, packages/util/src/types.ts, packages/util/test/bytes.spec.ts, packages/util/test/types.spec.ts
Addresses the below item from #1717
On the second item, in looking at the code, I'm not really sure it makes sense to merge `stripZeroes` and `bigIntToUnpaddedBuffer` as they do different things.  To my way of thinking, it makes much more sense to merge:
- `stripZeros`
- `unpadBuffer`
- `unpadArray`
- `unpadHexString`
@holgerd77 Any thoughts here since it looks like the second item was your recommendation?
=> util: move misplaced functions

packages/client/lib/execution/vmexecution.ts, packages/client/lib/rpc/modules/engine.ts, packages/client/lib/rpc/modules/eth.ts, packages/client/test/rpc/engine/forkchoiceUpdatedV1.spec.ts, packages/client/test/rpc/engine/newPayloadV1.spec.ts
This PR:
1. Fixes `eth_call` error when prysm calls deposit contract with `data: '0x621fd130'` (`get_deposit_count()`). The simulated tx was running into some `gasPrice` issues with `baseFeePerGas`, so I updated the code to use `vm.runCall` which should relax the tx requirements.
2. engine: Adds `remoteBlocks` to handle storing blocks with unknown parent in case `fcU` sets head to it when parent is later given to `newPayload`. Also adds a test for local coverage of this scenario.
3. More strictly follow spec when returning `SYNCING` ensure we return `latestValidHash: null`
=> client: fix eth_call, add remoteBlocks to engine

packages/common/README.md
This PR helps improve the Common README with usage examples to show when using `require` may be necessary, until we merge esm support.
Context: https://github.com/ethereumjs/ethereumjs-monorepo/issues/978#issuecomment-1089510235
=> common: add require examples to readme

packages/vm/src/runCall.ts
The `caller` parameter in `runCallOpts` is optional but causes the EVM to throw if not provided.  The upcoming docs on the `runCallOpts` that are in the `develop` branch indicate the message caller should default to the zero address if not provided in the message so this fix accounts for that design.
=> Set caller to zero address if not provided

packages/common/src/index.ts, packages/common/tests/customChains.spec.ts
Fixes a bug discovered in #1838
(open for everyone in the team to review of course)
=> Common: fixed non-option passing on custom() method

packages/client/bin/cli.ts, packages/client/lib/config.ts, packages/client/lib/service/fullethereumservice.ts, packages/client/lib/sync/fetcher/blockfetcherbase.ts, packages/client/lib/sync/fetcher/fetcher.ts, packages/client/lib/sync/fullsync.ts, packages/client/lib/sync/lightsync.ts, packages/client/lib/sync/sync.ts, packages/client/test/sync/fetcher/blockfetcher.spec.ts, packages/client/test/sync/fullsync.spec.ts, packages/client/test/sync/lightsync.spec.ts, packages/client/test/sync/sync.spec.ts
This PR refactors services, syncronizers and fetchers to make things cleaner for beacon sync
As discussed with @ryanio this is per syncronizer processing, so moved back to the fullsync as beacon sync will have its own. however also moved the event association with it as its better that syncronizer wires up/cleans its own events
Testing
=> client: refac services, syncronizers and fetchers for beacon sync

packages/client/bin/cli.ts
In the PR https://github.com/ethereumjs/ethereumjs-monorepo/pull/1858 @holgerd77  noticed that maxFetcherJobs was not being picked up.
this PR fixes the same.
Behavior on passing `--maxFetcherJobs=0`:
The fetcher keeps on regularly trying to enqueue jobs but to no avail :+1:
=> client: pass the maxFetcherJobs arg to the config

packages/vm/README.md
The links to the examples in the README file were broken.
=> Fix example links

packages/vm/README.md
Clicking on the "Running the VM in a browser" link was resulting in a 404 error.
This change adds the `.js` extension to the URL, fixing the issue.
=> Fix broken Readme link to run the VM in a browser

packages/client/lib/execution/vmexecution.ts, packages/client/lib/util/debug.ts, packages/trie/README.md, packages/trie/src/baseTrie.ts, packages/trie/src/checkpointDb.ts, packages/trie/src/checkpointTrie.ts, packages/trie/src/db.ts, packages/trie/src/secure.ts, packages/trie/src/verifyRangeProof.ts, packages/trie/test/index.spec.ts
Completes tasks in #1717:
extra:
=> trie: convert constructor to options interface, remove deprecated setRoot

packages/devp2p/package.json, packages/devp2p/test/integration/dpt-simulator.ts, packages/devp2p/test/integration/rlpx-simulator.ts, packages/devp2p/test/integration/util.ts
This PR removes the `async` dep from the devp2p integration tests.
I was getting some errors from the peer liveness check when the server closed too quickly so I added some 500ms delays before closing, not sure why I had this problem.
=> devp2p: remove `async` dependency from integration tests

packages/vm/src/evm/evm.ts, packages/vm/src/exceptions.ts, packages/vm/src/runCall.ts, packages/vm/src/runTx.ts, packages/vm/tests/api/runCall.spec.ts, packages/vm/tests/api/runTx.spec.ts
Fixes #1839 
This addresses the fact that `skipBalance` in `runTx` doesn't handle skipping balance checks correctly after the initial transaction options are parsed.  Now, if `skipBalance` is set to true and the calling account balance is less than the transaction cost (i.e. intrinsic gas + value), it sets the balance equal to the transaction cost so the transaction will not fail due to an account having an insufficient balance.
It adds similar logic in `runCall` that checks to verify that the account has sufficient balance for any value transferred in the call.
=> vm: Improve `skipBalance` logic

packages/blockchain/src/index.ts, packages/client/lib/execution/vmexecution.ts, packages/vm/src/runBlockchain.ts, packages/vm/tests/api/runBlockchain.spec.ts
Small task to finish #1754.
Removed 'void' as a return type for blockchain.iterator()
Adapted VM and Client methods that use the blockchain iterator
Also reinstate VM tests for blockchain.getIteratorHead()  that were a part of #1822
=> blockchain: fix iterator return type, reinstate tests

packages/client/lib/rpc/modules/eth.ts, packages/client/test/rpc/eth/getBlockByHash.spec.ts, packages/client/test/rpc/eth/getBlockByNumber.spec.ts, packages/client/test/rpc/mockBlockchain.ts
Fixes #1880 by adding additional fields to transaction bodies as specified by the [JSON-RPC spec](https://github.com/ethereum/execution-apis/blob/d011196297ef8464deeffaa965fe27f66c9a303e/src/schemas/transaction.json#L275)
=> client: add missing tx fields to getBlockByHash

packages/vm/tests/tester/runners/BlockchainTestsRunner.ts, packages/vm/tests/util.ts
If a blockchain test fails and we have the `--debug` flag on, we expect that we do `verifyPostConditions`: https://github.com/ethereumjs/ethereumjs-monorepo/blob/0b7cc1b15d1fd9d58e4ae7db794674c3af4da5ae/packages/vm/tests/tester/runners/BlockchainTestsRunner.ts#L171
However, this actually does not work. If the block is invalid and produces a different `stateRoot` than whatever we expect, then `runBlockchain` actually throws and the `verifyPostConditions` is never ran. 
This PR also updates the formatter such that it is easier to read what goes wrong. On a VM which I intentially made producing wrong output:
(Was done by adding this to `runBlock.ts`:)
If the tests contain the postConditions we can now very quickly figure out what goes wrong if a test files :smile:
=> VM/tests: ensure verifyPostConditions works

packages/client/lib/execution/vmexecution.ts, packages/trie/benchmarks/checkpointing.ts, packages/trie/benchmarks/index.ts, packages/trie/benchmarks/random.ts, packages/trie/src/baseTrie.ts, packages/trie/src/checkpointDb.ts, packages/trie/src/checkpointTrie.ts, packages/trie/src/db.ts, packages/trie/src/index.ts, packages/trie/src/secure.ts, packages/trie/test/checkpoint.spec.ts, packages/trie/test/checkpointDb.spec.ts, packages/trie/test/db.spec.ts, packages/trie/test/encoding.spec.ts, packages/trie/test/index.spec.ts, packages/trie/test/official.spec.ts, packages/trie/test/proof.spec.ts, packages/trie/test/rangeProof.spec.ts, packages/trie/test/secure.spec.ts, packages/trie/test/stream.spec.ts
Resubmission of https://github.com/ethereumjs/ethereumjs-monorepo/pull/1895 with squashed history and rebase on `develop`
=> refactor(trie): abstract database implementation with an interface

packages/client/lib/rpc/modules/engine.ts, packages/client/test/rpc/engine/forkchoiceUpdatedV1.spec.ts, packages/client/test/rpc/engine/newPayloadV1.spec.ts
The https://github.com/ethereum/execution-apis/pull/217 part of the v1.0.0-alpha.9 subsumes the INVALID_TERMINAL_BLOCK into INVALID response via  {status: INVALID, latestValidHash: 0x0000000000000000000000000000000000000000000000000000000000000000}
This PR implements the same.
=> client: Subsume engine's INVALID_TERMINAL_BLOCK into INVALID response

packages/tx/src/legacyTransaction.ts, packages/tx/test/legacy.spec.ts, packages/util/src/signature.ts, packages/util/test/signature.spec.ts, packages/vm/src/evm/precompiles/01-ecrecover.ts
=> Util: Allow `v` to be `0` or `1` for EIP1559 transactions

package-lock.json, packages/block/package.json, packages/blockchain/package.json, packages/client/CHANGELOG.md, packages/client/README.md, packages/client/package.json, packages/common/package.json, packages/devp2p/package.json, packages/ethash/package.json, packages/trie/package.json, packages/tx/CHANGELOG.md, packages/tx/package.json, packages/util/CHANGELOG.md, packages/util/docs/README.md, packages/util/docs/classes/BN.md, packages/util/docs/enums/TypeOutput.md, packages/util/docs/interfaces/rlp.List.md, packages/util/docs/modules/BN.md, packages/util/docs/modules/rlp.md, packages/util/package.json, packages/vm/CHANGELOG.md, packages/vm/package.json
Last round of `master` v5 releases according to #1926 before `develop` gets merged into `master`. The `master` state directly before will then be branched off as `v5-maintenance`.
Open for review. 🙂 
Feel free to directly push corrections and additions.
=> Last round of master v5 Releases

packages/blockchain/src/index.ts
Fixes #1930 
Triggered in the client in a reorg-like scenario on syncing a Clique consensus-based chain (Sepolia, Rinkeby,...)
=> Blockchain: Clique-recently-signed False Positive Fix

packages/vm/src/evm/opcodes/codes.ts, packages/vm/src/evm/opcodes/functions.ts, packages/vm/src/evm/opcodes/gas.ts, packages/vm/tests/api/EIPs/eip-3074-authcall.spec.ts
This updates the AUTHCALL EIP. Changes were made: https://github.com/ethereum/EIPs/pull/4967
=> Update EIP 3074 AUTHCALL

packages/blockchain/CHANGELOG.md, packages/blockchain/package.json, packages/client/CHANGELOG.md, packages/client/package.json, packages/vm/CHANGELOG.md, packages/vm/package.json
@ryanio made me aware that I had forgotten a release for the Blockchain library containing the last-minute fix from #1931.
This PR catches up on this, it also includes new releases for VM and Client so that the changes are surely applied.
PR is targeted towards `v5-maintenance` so that it doesn't interrupt the current (rebase and the like) processes.
=> Blockchain, VM, Client: New Bugfix Releases

package-lock.json, package.json, packages/vm/tests/api/EIPs/eip-3074-authcall.spec.ts
Clean-up items following on #1943 
- Removes `bigint-crypto-utils` dep from root `package.json`
- Fixes memory leak in EIP-3074 tests where [`common` isn't copied](https://github.com/ethereumjs/ethereumjs-monorepo/blob/4481cf2d3f69bc35be343e5ae6709434eb2add9d/packages/vm/tests/api/EIPs/eip-3074-authcall.spec.ts#L228) and the hardfork listener gets duplicated
=> develop clean-up items

packages/vm/src/eei/vmState.ts
I was using the StateManager's `clearWarmedAccounts` function and noticed that the jsdoc comment says that the function takes a `boolean`, but found this to be untrue. This PR removes that jsdoc comment.
=> chore: remove untrue jsdoc comment on `clearWarmedAccounts`

packages/block/test/difficulty.spec.ts, packages/block/test/testdata/dfGrayGlacier/difficultyGrayGlacier.json, packages/block/test/testdata/dfGrayGlacier/difficultyGrayGlacierForkBlock.json, packages/block/test/testdata/dfGrayGlacier/difficultyGrayGlacierMinus1.json, packages/block/test/testdata/dfGrayGlacier/difficultyGrayGlacierTimeDiff1.json, packages/block/test/testdata/dfGrayGlacier/difficultyGrayGlacierTimeDiff2.json, packages/common/src/chains/mainnet.json, packages/common/src/eips/5133.json, packages/common/src/eips/index.ts, packages/common/src/enums.ts, packages/common/src/hardforks/grayGlacier.json, packages/common/src/hardforks/index.ts, packages/common/tests/hardforks.spec.ts, packages/evm/src/evm.ts, packages/vm/src/types.ts, packages/vm/src/vm.ts
Adds support for GrayGlacier HF re: https://github.com/ethereumjs/ethereumjs-monorepo/issues/1960
Duplicated for v5-maintenance in https://github.com/ethereumjs/ethereumjs-monorepo/pull/1984
=> Master branch - Gray Glacier Support

packages/evm/README.md
Related to #2008, this removes duplicate examples from the EVM readme that really depend on the VM to execute so should remain solely in the `vm` package.
=> evm: Remove vm example links

packages/block/src/header.ts, packages/client/bin/cli.ts
Fixes two bugs related to consensus validation that were introduced when we merged #1959 
- Fixes handling of `extraData` in genesis parameters for `client` devnet start-up
- Moves location of `_consensusFormatValidation` in `block` constructor so that `extraData` can be correctly constructed for PoA blocks.
=> Fix consensus validation bugs

packages/common/src/chains/ropsten.json, packages/common/src/chains/sepolia.json
Add `td` values for `ropsten` and `sepolia`  as well as `mergeForkIdTransition` entries which will be provided later which is when the `forkHash` will change.
=> common: Update sepolia and ropsten configs for merge

packages/client/lib/config.ts, packages/common/src/chains/sepolia.json
This PR adds Sepolia DNS discovery config to Common and DNS discovery activation to the client which solves the Sepolia initial sync connection problem.
For context see the [discv4-dns-lists](https://github.com/ethereum/discv4-dns-lists) repo and the [bootnode config](https://github.com/ethereum/go-ethereum/blob/master/params/bootnodes.go#L108) from Go Ethereum.
=> Common, Client: Sepolia DNS config and activation

package-lock.json, packages/block/package.json, packages/blockchain/package.json, packages/client/bin/cli.ts, packages/client/bin/startRpc.ts, packages/client/lib/execution/vmexecution.ts, packages/client/lib/rpc/index.ts, packages/client/package.json, packages/devp2p/package.json, packages/ethash/package.json, packages/evm/package.json, packages/evm/src/evm.ts, packages/statemanager/package.json, packages/trie/package.json, packages/tx/package.json, packages/util/package.json, packages/vm/package.json, packages/vm/src/runBlock.ts, packages/vm/src/types.ts
Various fixes and improvements to enable ethereumjs sync sepolia
WIP
~~- [ ] Replace kiln sync instructions with sepolia sync instructions~~ separate PR to tackle this
=> Miscellaneous fixes/improvements for evm, client, consensus and crypto

packages/evm/src/evm.ts, packages/evm/tests/runCall.spec.ts
Fixes #2009 
In `generateAddress`, we are not currently checking if the `FROM` account's nonce is 0 (i.e. an unused account) which leads to the error documented in #2009.  In practice, this should only ever occur if someone is making a direct call to `evm.runCall` independent of a running instance of the `VM` since the `FROM` account's nonce is incremented in `runTx` and you can't initiate a contract deployment from a non-existent account in an actual blockchain context.
=> evm: Add check for zero nonce in create

packages/statemanager/src/stateManager.ts, packages/trie/README.md, packages/trie/package.json, packages/trie/src/proof/range.ts, packages/trie/src/trie/node/branch.ts, packages/trie/src/trie/node/extension.ts, packages/trie/src/trie/node/leaf.ts, packages/trie/src/trie/secure.ts, packages/trie/src/trie/trie.ts, packages/trie/src/types.ts, packages/trie/test/index.spec.ts, packages/trie/test/proof.spec.ts, packages/trie/test/proof/range.spec.ts, packages/trie/test/trie/secure.spec.ts, packages/util/src/constants.ts
Keccak256 is the default hash algorithm for Ethereum, I use blake2b256 in my case. It's would be better that the underlying package supports customizing the hash algorithm rather than forking it.So I added the package level configurable hash function, by default it's keccak256.
=> Trie: allow customizing hash algorithm

packages/devp2p/src/protocol/eth.ts, packages/devp2p/src/protocol/index.ts, packages/devp2p/src/protocol/les.ts, packages/devp2p/src/protocol/protocol.ts, packages/devp2p/src/protocol/snap.ts, packages/devp2p/src/rlpx/peer.ts, packages/devp2p/test/integration/index.ts, packages/devp2p/test/integration/snap-simulator.ts, packages/devp2p/test/integration/util.ts
=> DevP2P: add snap protocol

packages/blockchain/README.md
Adds some new verbiage and links around custom consensus.  Fixes one item from #2032
=> blockchain: add documentation for custom consensus

packages/client/lib/config.ts, packages/client/lib/execution/vmexecution.ts, packages/client/lib/sync/beaconsync.ts, packages/client/lib/sync/skeleton.ts, packages/client/lib/sync/sync.ts, packages/client/test/sync/beaconsync.spec.ts, packages/client/test/sync/fetcher/reverseblockfetcher.spec.ts, packages/client/test/sync/skeleton.spec.ts
Handle few recovery and reorg scenarios to make beacon sync more robust
plus a small refac for better code clarity
@holgerd77 we can target this for `v5 maintenance` if we want, although we can also skip it as beacon sync is relatively new.
=> client: Make beacon sync more robust

packages/common/src/chains/goerli.json
Set goerli merge ttd to 10790000
Reference: https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/paris.md
=> common: Set goerli merge ttd to 10790000

packages/client/lib/rpc/modules/eth.ts, packages/client/test/rpc/eth/call.spec.ts
client: allow eth_call without to for testing contract creation 
Allows contract creation via eth_call without providing `to`.
Closes #1987
=> client: allow eth_call without to for testing contract creation

packages/block/src/types.ts, packages/client/test/integration/merge.spec.ts, packages/client/test/integration/miner.spec.ts, packages/common/README.md, packages/common/src/chains/goerli.json, packages/common/src/chains/ropsten.json, packages/common/src/chains/sepolia.json, packages/common/src/common.ts, packages/evm/README.md, packages/tx/README.md, packages/tx/src/baseTransaction.ts, packages/vm/src/types.ts, packages/vm/tests/tester/config.ts
set the default hard fork to merge
Closes #2015
=> common: set the default hard fork to merge

packages/common/src/chains/sepolia.json
Update `mergeForkIdTransition` hardfork schedule
Reference: https://github.com/ethereum/execution-specs/pull/564
=> common: Update the mergeForkIdTransition hardfork schedule for sepolia

packages/client/bin/cli.ts, packages/client/lib/config.ts, packages/client/lib/net/peer/peer.ts, packages/client/lib/net/peer/rlpxpeer.ts, packages/client/lib/net/protocol/index.ts, packages/client/lib/net/protocol/protocol.ts, packages/client/lib/net/protocol/rlpxsender.ts, packages/client/lib/net/protocol/snapprotocol.ts, packages/client/lib/service/fullethereumservice.ts, packages/client/lib/sync/index.ts, packages/client/lib/sync/snapsync.ts, packages/client/test/net/peer/rlpxpeer.spec.ts, packages/client/test/service/fullethereumservice.spec.ts, packages/devp2p/src/protocol/eth.ts, packages/devp2p/src/protocol/snap.ts, packages/devp2p/src/rlpx/peer.ts
This PR will enable fetching snap data for accounts,storage,codeby using the devp2p interface exposed in the PR: https://github.com/ethereumjs/ethereumjs-monorepo/pull/1883.  
Currently this PR is pointing to #1883, but when that gets merged, this PR will be updated to pointing master. This is so we can leverage the devp2p work being done in 1883 while independently developing some client capabilities with regard to consuming and fetching snap data (and get some early feedback)
`snap` protocol availability in the peer:
```typescript
[05-18|16:28:57] DEBUG Peer connected: id=e9631196 address=10.244.0.112:30303 transport=rlpx protocols=eth,snap inbound=false 
[05-18|16:28:57] DEBUG Found full peer: id=e9631196 address=10.244.0.112:30303 transport=rlpx protocols=eth,snap inbound=false …
```
=> client: Add client protocol and synchronizer for snap sync
