ethereumjs/ethereumjs-monorepo

lib/runTx.js

just a quick one -- no additional tests fail (5 blockchain tests already failing at time of PR)

clean - run tx

---

dist/ethereumjs-vm.js
lib/index.js
lib/opFns.js
lib/runCall.js
lib/runCode.js
lib/runJit.js

This pull request renames a few typos in variable naming and code comments.
A new browser build was also created. I am not sure if this is required of code changes. If not, I can remove that specific commit.

Renamed precompile typo

---

lib/opFns.js
lib/stateManager.js

**breaking change**
proposal here https://github.com/ethereumjs/ethereumjs-vm/issues/30
Not tested b/c tests are broken

state manager - handle rlp encoding for contract storage

---

README.md

update runTx + runCall to reflect the current flow

readme -  Internal Structure - update

---

lib/opFns.js
lib/precompiled/01-ecrecover.js
package.json
tests/util.js

Gets stuff working on Windows.

Change package dependencies. Renamed pads to setLength

---

.travis.yml
lib/cache.js

Wrap all red-black tree inserts/updates into a function that checks for node existence before insertion, which was the cause of this issue: https://github.com/ethereumjs/testrpc/issues/35
Submitting a PR to get Travis started running all the tests. I'm currently running all of them on my machine now, but it'll be awhile.

Fix a slimy cache bug

---

lib/index.js
lib/runCall.js
lib/runCode.js

Enable homestead feature set by passing an options object to `new VM()`.

Enable homestead

---

lib/index.js

... and avoid the subsequent once-off gas costs (25000) when calling them

Introduce activatePrecompiles option to create state for precompiled contracts

---

lib/opcodes.js

doesnt seem to be in use -- no opcodes have the 'async' flag
@wanderer please confirm

opcodes - rm unused 'async' property

---

lib/opcodes.js
package.json

\*G* need this in order to release a new version of dapple

fix opcode typo and bump ethereumjs-account version

---

lib/opFns.js
lib/runCode.js

Ensure stack width

---

lib/index.js

Let's try this again after #108.
See https://github.com/ethereumjs/ethereumjs-vm/blob/master/lib/index.js#L31

Fix VM.copy() again

---

lib/opFns.js
lib/runCall.js
package.json
tests/tester
tests/util.js

Do not deduct value multiple times when using DELEGATECALL

---

.travis.yml
README.md
circle.yml
package.json
tests/tester.js

I just found that you are looking for contributors on Reddit and want to start getting used to the codebase, this is my first attempt

Some nits and minor improvements

---

package.json

replaces https://github.com/ethereumjs/ethereumjs-vm/pull/145

revert ethereumjs-util to 4.5.0

---

README.md
lib/opFns.js
lib/opcodes.js
lib/runCall.js
lib/runCode.js
lib/runTx.js

spec: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-6.md
The only API left is `suicideRefundGas` in params.json, change it will break the test

EIP-6: Rename SUICIDE opcode

---

CHANGELOG.md

Hi,
these are some release notes which can be used for EIP 150 and Spurious Dragon releases, or merged together if done in one release.
Cheers
Holger

Draft for release notes for upcoming EIP150/Spurious Dragon release(s)

---

CHANGELOG.md
README.md

Hi,
just made a short new pull request to reflect the combined release (and with updated date(s)).
Cheers
Holger

Updated changelog to reflect combined 2.2.0 release

---

lib/opFns.js

Use memStore in makeCall

---

lib/opFns.js
lib/runCode.js

Strange that tests never catch this..

OOG should not be negative, but result in 0 gas left

---

CHANGELOG.md
circle.yml
package.json

Pre-byzantium release with tightened dependencies for keeping Homestead version of library installable for some time.

[Pre-Byzantium Release] v2.2.2

---

README.md
tests/GeneralStateTestsRunner.js
tests/tester.js

For specifying data, gas limit and value indices to use when running a state test

Add support for --data --gas --value command line arguments in state tests

---

lib/opFns.js

Update allocated memory word count only if allocation was successful

---

lib/precompiled/01-ecrecover.js
lib/precompiled/02-sha256.js
lib/precompiled/03-ripemd160.js
lib/precompiled/04-identity.js
lib/precompiled/05-modexp.js
lib/precompiled/06-ecadd.js
lib/precompiled/07-ecmul.js
lib/precompiled/08-ecpairing.js

I don't remember which test triggered this, but had a case where this was helpful.

Assert that data is passed to precompiles

---

lib/fakeBlockChain.js
lib/runBlockchain.js

Had this in a local branch for a while, need to verify first.

Fix fakeblockchain

---

.travis.yml
CHANGELOG.md
package.json

Also switched back to Node 6 for testing, should work now again.

[Release] New release v2.3.2

---

lib/stateManager.js

Fixes https://github.com/ethereumjs/ethereumjs-vm/issues/225 (replaces https://github.com/ethereumjs/ethereumjs-vm/pull/236)

remove redundant push to stateManager.touched

---

tests/util.js

`dumpState` is a utility function that can be used when debugging VM state test failures.  This PR adds output of account storage to `dumpState`

Add storage dump to 'dumpState'

---

circle.yml

Run the same tests on CircleCI as on travis

---

tests/GeneralStateTestsRunner.js

catch errors passing state tests

---

lib/opFns.js

Optimise BYTE to only use bn.js

---

.circleci/config.yml
.travis.yml

Can be merged if Coveralls activates and runs through.

Migrate coveralls from Travis to CircleCI

---

.gitignore
CHANGELOG.md
README.md
package.json

Will leave this open for 24h and then do a release tomorrow.

New release v2.4.0

---

.circleci/config.yml
README.md

This PR adds the new API test suite to the CircleCI build. It also updates the README build badge to reflect the latest build from CircleCI, since Travis is now deactivated.

Add API tests to CircleCI / Update README badge

---

lib/opFns.js
lib/runCode.js

This PR fixes three small typos in comments.

Fix typos in comments

---

lib/opFns.js

Also removes the need of a negation.

Reorder EXP code to match other opcodes

---

CHANGELOG.md
README.md
docs/index.md
lib/index.js
package.json

Petersburg. 🎊
Thanks again @danjm! 😄

New release v2.6.0 (Petersburg/Goerli)

---

tests/api/state/stateManager.js

Relates to #449 
Add unit test for `StateManager.dumpStorage()`

Add test for StateManager.dumpStorage

---

CHANGELOG.md
README.md
package.json

Already prepared the release notes for ``v3.0.0``, feel free to comment everyone.

New release v3.0.0

---

lib/evm/opcodes.js

Update misleading comments for opocde to reflect recent changes.
Signed-off-by: Hyung-Kyu Choi <hyungkyu.choi@gmail.com>

Update misleading comments for opocde

---

lib/evm/opFns.js

Fixes #260.
Had this in a local branch for a while, need to verify first.

Optimize signextend

---

.babelrc

Remove .babelrc

---

examples/run-blockchain/index.js

When I run example/run-blockchain, I found in the final result, new header is different from what is expected, e.g.
```
shenghu$ node examples/run-blockchain/
--- Finished processing the BlockChain ---
New head: 0x7285abd5b24742f184ad676e31f6054663b3529bc35ea2fcad8a3e0f642a46f7
Expected: 0x117545e24e3d1e1836bb92e3d6f3e77ac5b2ecd171a535830bf9b5afb8f522e5
```
The new head is that of genesis block, while it is expected to add another block. So I referred to the test codes and make this fix. Please review to see if I'm correct or not.

New head should be the same as expected when running example/run-blockchain

---

lib/evm/eei.ts
lib/evm/interpreter.ts

Just a small PR adding some doc to a type I found difficult to understand.

Improve selfdestruct maps doc

---

lib/state/stateManager.ts

Fix StateManager#copy's doc

---

lib/index.ts

Improve activatePrecompiles doc

---

examples/run-blockchain/index.ts
examples/run-code-browser/index.js
examples/run-solidity-contract/index.ts
examples/run-transactions-complete/index.ts
tests/VMTestsRunner.js

This PR supersedes #588 
Thanks @hugo-dc for your work on this.

Rename some missing return to returnValue

---

.github/workflows/vm-coverage.yml
.github/workflows/vm-lint.yml
.github/workflows/vm-test.yml
README.md
developer.md
karma.conf.js

Incrementally adds Github Actions. See tab `Checks`.

Add github actions

---

lib/runBlock.ts

A pretty simple change, just passing forward some options that should be there.

Support in runBlock runTx options

---

.github/workflows/account-lint.yml
.github/workflows/account-test.yml
.github/workflows/block-lint.yml
.github/workflows/block-test.yml
.github/workflows/blockchain-lint.yml
.github/workflows/blockchain-test.yml
.github/workflows/common-lint.yml
.github/workflows/common-test.yml
.github/workflows/labeler.yml
.github/workflows/tx-lint.yml
.github/workflows/tx-test.yml
.github/workflows/vm-lint.yml
.github/workflows/vm-test.yml
.gitignore
README.md
packages/account/README.md
packages/block/README.md
packages/blockchain/README.md
packages/common/README.md
packages/tx/README.md
packages/vm/README.md

This PR:
1. Normalizes workflow names
1. Runs workflows on PRs
1. Sets labeler to run on schedule so it can process forks (https://github.com/actions/labeler/issues/12#issuecomment-525762657)
1. Shortens workflow `node-version` to an array for brevity
1. Updates README badges
1. Adds a project root `.gitignore` for `node_modules` and `package-lock.json`

Update GH Actions and READMEs

---

packages/account/README.md
packages/block/README.md
packages/blockchain/README.md
packages/common/README.md
packages/tx/README.md
packages/vm/README.md

This way, people landing on the package home page from the original repos, can easily ensure they are seeing the right content.

Puts package names as README titles

---

packages/common/CHANGELOG.md
packages/common/package.json

common: Release Common 1.5.1

---

packages/vm/lib/index.ts
packages/vm/tests/api/runCall.js

Closes #796 
Can someone verify that `activatePrecompiles` is indeed what I expect it to mean? (See the issue)

[VM] fix activatePrecompiles

---

.github/workflows/vm-build.yml

This PR tries to fix storing the benchmarks results for runs on master.

Fix storing benchmarks results

---

packages/ethash/CHANGELOG.md

One further step to complete on the release notes for v5 and do UNRELEASED updates to change on the CHANGELOG process towards doing in-PR-updates. 😄

Ethash UNRELEASED release notes

---

packages/blockchain/CHANGELOG.md
packages/vm/CHANGELOG.md

This PR updates the changelog for blockchain similarly to #857, and adds two new entries to the VM changelog.

Blockchain UNRELEASED release notes, and two new VM changelog entries

---

packages/block/CHANGELOG.md
packages/block/src/block.ts
packages/block/src/header.ts
packages/block/test/difficulty.spec.ts
packages/block/test/header.spec.ts
packages/blockchain/test/index.ts
packages/blockchain/test/util.ts

BlockHeader Validation Method Changes / Corresponding Block Methods

---

packages/blockchain/CHANGELOG.md

docs: move blockchain compare link to bottom of release.

---

.github/workflows/node-versions.yml

fix CI node versions tests

---

packages/client/lib/sync/fetcher/blockfetcher.ts
packages/client/lib/sync/fullsync.ts
packages/vm/lib/index.ts
packages/vm/lib/runBlockchain.ts

Client FullSync changes

---

package-lock.json
packages/client/lib/net/protocol/ethprotocol.ts
packages/client/lib/rpc/modules/admin.ts
packages/client/lib/rpc/modules/eth.ts
packages/client/lib/rpc/modules/net.ts
packages/client/lib/rpc/modules/web3.ts
packages/client/lib/sync/fetcher/blockfetcher.ts
packages/client/lib/sync/fetcher/blockfetcherbase.ts
packages/client/lib/sync/fetcher/fetcher.ts
packages/client/lib/sync/fetcher/headerfetcher.ts
packages/client/lib/sync/fetcher/types.ts
packages/client/lib/sync/fullsync.ts
packages/client/lib/sync/lightsync.ts
packages/client/lib/sync/sync.ts
packages/client/lib/types.ts
packages/client/test/rpc/blockChainStub.ts
packages/client/test/sync/fetcher/blockfetcher.spec.ts
packages/client/test/sync/fetcher/fetcher.spec.ts
packages/client/test/sync/fetcher/headerfetcher.spec.ts
packages/client/test/sync/sync.spec.ts

This PR is very WIP. It currently makes the Fetcher a bit more typesafe, I am running into some type problems now with the HeaderFetcher and will need to do a bit more research what the types are intended to be under the hood and possibly have to introduce a third type on Fetcher.ts.
All `any` is now removed in Fetcher/BlockFetcher, need to fix HeaderFetcher, this has some nasty types which don't work with the type system I setup.

Client: make fetcher more typesafe

---

packages/vm/lib/runTx.ts
packages/vm/tests/api/runTx.spec.ts

This PR implements @jochem-brouwer's suggestion in #1014 
closes #1014

Add an option to disable the block gas limit check in runTx

---

packages/blockchain/README.md
packages/blockchain/package.json
packages/blockchain/src/index.ts
packages/blockchain/test/clique.spec.ts
packages/blockchain/test/reorg.spec.ts
packages/client/lib/service/ethereumservice.ts
packages/client/lib/sync/execution/vmexecution.ts
packages/vm/README.md

Fixes #1100
Got it, cause for the difficulty bug was the ordering of the signers mentioned in the issue. 😄 
Now there is an additional clique bug triggered some blocks down the road though, now with a pretty complex voting scenario. Here is the output:

Client, Blockchain: Fix Goerli Clique Difficulty Bug

---

packages/tx/src/eip2930Transaction.ts
packages/tx/test/eip2930.spec.ts

Fix default value for empty access lists

---

packages/tx/src/baseTransaction.ts
packages/tx/src/eip2930Transaction.ts
packages/tx/src/legacyTransaction.ts
packages/tx/test/eip2930.spec.ts
packages/tx/test/legacy.spec.ts

Tx: New hashMessage parameter for getMessageToSign()

---

packages/client/lib/net/server/rlpxserver.ts
packages/client/test/net/server/rlpxserver.spec.ts

This PR continues the efforts from #1222 to more reliably open the server connections.

Client: await DPT init

---

packages/common/src/eips/3529.json
packages/common/src/eips/index.ts
packages/common/src/hardforks/chainstart.json
packages/vm/lib/evm/interpreter.ts
packages/vm/lib/index.ts
packages/vm/lib/runTx.ts
packages/vm/tests/api/EIPs/eip-3529.spec.ts

This PR implements [EIP 3529](https://eips.ethereum.org/EIPS/eip-3529).

Implement EIP3529

---

packages/client/lib/rpc/modules/eth.ts
packages/client/test/rpc/eth/getUncleCountByBlockNumber.spec.ts

Add new RPC method `eth_getUncleCountByBlockNumber` and related tests

client: New rpc method `getUncleCountByBlockNumber`

---

packages/tx/src/baseTransaction.ts
packages/tx/src/eip1559Transaction.ts
packages/tx/test/eip1559.spec.ts
packages/vm/lib/runTx.ts
packages/vm/tests/api/runBlock.spec.ts
packages/vm/tests/api/runTx.spec.ts
packages/vm/tests/api/utils.ts

See https://github.com/ethereum/EIPs/pull/3594

1559: add more constraints to tx validation

---

packages/tx/README.md
packages/tx/docs/classes/basetransaction.basetransaction-1.md
packages/tx/docs/classes/eip1559transaction.default.md
packages/tx/docs/classes/eip2930transaction.default.md
packages/tx/docs/classes/legacytransaction.default.md
packages/tx/src/baseTransaction.ts
packages/tx/src/eip1559Transaction.ts
packages/tx/src/eip2930Transaction.ts
packages/tx/src/legacyTransaction.ts

This PR improves the tx library code documentation based on various recent discussions along the publication of the new EIP-1559/London compatible tx library release.

Tx: Improve Code Documentation

---

packages/block/README.md
packages/blockchain/README.md
packages/common/README.md
packages/devp2p/README.md
packages/trie/README.md
packages/tx/README.md
packages/vm/README.md

This PR fixes some of the gh actions badges and urls.

Readme gh actions url fixes

---

packages/client/lib/net/peerpool.ts
packages/client/lib/sync/fetcher/blockfetcher.ts
packages/client/lib/sync/fetcher/fetcher.ts
packages/client/lib/sync/fetcher/headerfetcher.ts

More clean-up items I ran across as I've been digging into the guts of the fetching process in the client.

Client: Small types clean-up

---

packages/client/lib/net/protocol/ethprotocol.ts
packages/client/lib/rpc/modules/eth.ts
packages/client/lib/service/fullethereumservice.ts
packages/client/lib/sync/txpool.ts
packages/client/test/integration/fullethereumservice.spec.ts
packages/client/test/sync/txpool.spec.ts

This implements the service functionality around the rebroadcasting of new pooled tx hashes received.
[WIP]

Client: New Pooled Tx Hashes Service Functionality (Re-broadcasting/Tracking) for TxPool

---

packages/devp2p/src/rlpx/peer.ts

Fixes #1416 
Ok, I was able to track this down. This has indeed a connection to the introduced snappy compression. Snappy should only be applied after the protocol handshake is finished and for `DISCONNECT` msgs it is often hard to decide if they were send along or after the initial handshake.
I've now applied a hotfix here which fixes the problem (in both directions) by retrying to RLP decode (this is where execution breaks) with the respective non-uncompressed/compressed message (only for `DISCONNECT`) and only then re-throw the error respectively give up. 😋
I am not 100% sure if I am not seeing the forest for all the trees and there *does exist* some clean way to distinguish here. So if someone has a clearer view here feel free to improve the PR.
I would otherwise recommend that we …

devp2p: fix `RLPx` snappy uncompress issue for `DISCONNECT` msgs along handshake

---

packages/client/README.md

Add readme updates for the new `--dev` parameter

client: readme updates for new dev param

---

packages/block/CHANGELOG.md
packages/block/package.json
packages/blockchain/CHANGELOG.md
packages/blockchain/package.json
packages/client/README.md
packages/client/bin/cli.ts
packages/client/package.json
packages/devp2p/package.json
packages/ethash/package.json
packages/vm/package.json

Ok, I've also included a few last minute client fixes.

Block, Blockchain: bugfix releases (client preparation) fixing London HF at block 0 or 1 handling

---

packages/client/CHANGELOG.md
packages/client/README.md
packages/client/package.json

Ok, I guess that's it.
I wrote some more digestable release notes, updated the version number and the README and also did some last consistency checks (sync tests on all major networks e.g.).
Rebuilding the docs is not so trivial - I tried but failed - but I guess this is not so critical atm and we should skip for now.
Ready for review. 😄
Planning the release for tomorrow morning (European time).
Note: CHANGELOG best to read as a rendered [preview file](https://github.com/ethereumjs/ethereumjs-monorepo/blob/15eb2d4ab3866d9cee34d017f24dacd9bcf51f8a/packages/client/CHANGELOG.md).

Client: first stable release v0.1.0 🎉

---

packages/util/README.md

util: fix buffer compare in demo script

---

packages/vm/examples/decode-opcodes/README.md
packages/vm/examples/decode-opcodes/index.ts
packages/vm/examples/decode-opcodes/package.json
packages/vm/examples/run-blockchain/README.md
packages/vm/examples/run-blockchain/index.ts
packages/vm/examples/run-solidity-contract/index.ts
packages/vm/examples/run-transactions-complete/README.md

vm: fix examples

---

.github/workflows/node-versions.yml
packages/rlp/bin/rlp

ci: fix node-versions run for node <16

---

packages/block/CHANGELOG.md
packages/block/package.json
packages/blockchain/package.json
packages/client/package.json
packages/devp2p/package.json
packages/ethash/package.json
packages/vm/package.json

Fixes #1680, follow-up on #1640

Block: New Release v3.6.1 (Minor Release Series Follow-Up Release)

---

packages/common/src/eips/3607.json
packages/common/src/eips/index.ts
packages/vm/src/index.ts
packages/vm/src/runTx.ts
packages/vm/tests/api/EIPs/eip-3607.spec.ts
packages/vm/tests/tester/config.ts
packages/vm/tests/tester/index.ts
packages/vm/tests/tester/runners/BlockchainTestsRunner.ts
packages/vm/tests/tester/runners/GeneralStateTestsRunner.ts

vm: add guard for EIP-3607

---

packages/client/kiln/README.md

Instructions update to join kiln v2 spec complaint devnet5!

client: devnet5 instructions

---

packages/client/lib/util/rpc.ts
packages/client/test/sync/fetcher/blockfetcher.spec.ts
packages/client/test/util/rpc.spec.ts

Small fixes, continued after #1775
- util/rpc.spec.ts: add more coverage cases
- re-add accidentially removed test
- slim withEngineMiddleware fn

client: kiln touchups

---

packages/common/src/eips/3651.json
packages/common/src/eips/index.ts
packages/vm/src/index.ts
packages/vm/src/runTx.ts
packages/vm/tests/api/EIPs/eip-3651-warm-coinbase.spec.ts

Implements [EIP 3651](https://eips.ethereum.org/EIPS/eip-3651). This is CFI in [Shanghai](https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/shanghai.md).

VM, Common -> Implement EIP 3651: Warm COINBASE

---

packages/common/src/eips/3074.json
packages/common/src/eips/index.ts
packages/vm/src/evm/eei.ts
packages/vm/src/evm/evm.ts
packages/vm/src/evm/message.ts
packages/vm/src/evm/opcodes/EIP2929.ts
packages/vm/src/evm/opcodes/codes.ts
packages/vm/src/evm/opcodes/functions.ts
packages/vm/src/evm/opcodes/gas.ts
packages/vm/src/exceptions.ts
packages/vm/src/index.ts
packages/vm/tests/api/EIPs/eip-3074-authcall.spec.ts

Implements https://eips.ethereum.org/EIPS/eip-3074

Implement EIP3074: Authcall

---

packages/client/lib/sync/fetcher/blockfetcher.ts
packages/client/lib/sync/fetcher/blockfetcherbase.ts
packages/client/lib/sync/fetcher/fetcher.ts
packages/client/lib/sync/fetcher/headerfetcher.ts
packages/client/lib/sync/fullsync.ts
packages/client/lib/sync/lightsync.ts
packages/client/lib/sync/sync.ts
packages/client/lib/types.ts
packages/client/test/sync/fetcher/blockfetcher.spec.ts
packages/client/test/sync/fetcher/headerfetcher.spec.ts
packages/client/test/sync/lightsync.spec.ts
packages/client/test/sync/sync.spec.ts

This PR makes some small adjustments, improvements, nits after #1858

client: improvments after #1858

---

packages/vm/README.md

vm/docs: mention that stack in step event can change

---

packages/client/package.json
packages/devp2p/CHANGELOG.md
packages/devp2p/package.json

devp2p: new release v4.2.2

---

packages/devp2p/test/integration/index.ts
packages/devp2p/test/integration/snap-simulator.ts
packages/devp2p/test/integration/util.ts

This PR adds two tests for the SNAP protocol that is being added to the client as well as a utility function for setting up two peers for SNAP communication.

devp2p: Snap devp2p tests

---

packages/block/src/header.ts
packages/tx/src/baseTransaction.ts
packages/tx/src/eip1559Transaction.ts
packages/tx/src/eip2930Transaction.ts
packages/tx/src/legacyTransaction.ts
packages/util/src/signature.ts
packages/util/test/signature.spec.ts
packages/vm/src/evm/opcodes/functions.ts
packages/vm/tests/api/EIPs/eip-3074-authcall.spec.ts

Replaces #1940 after #1943 merge

Util: Signature Code Cleanup (new)

---

packages/client/lib/sync/fetcher/blockfetcherbase.ts
packages/client/lib/sync/skeleton.ts
packages/client/lib/util/parse.ts
packages/client/test/sync/fetcher/reverseblockfetcher.spec.ts

Miscellaneous fixes for beacon sync in reverseblockfetcher, skeleton, merge forkhash
Discovered while running beacon sync on the kiln.

client: Miscellaneous fixes for beacon sync in reverseblockfetcher, skeleton, merge forkhash 

---

package.json
packages/block/test/difficulty.spec.ts
packages/block/test/testdata/dfGrayGlacier/difficultyGrayGlacier.json
packages/block/test/testdata/dfGrayGlacier/difficultyGrayGlacierForkBlock.json
packages/block/test/testdata/dfGrayGlacier/difficultyGrayGlacierMinus1.json
packages/block/test/testdata/dfGrayGlacier/difficultyGrayGlacierTimeDiff1.json
packages/block/test/testdata/dfGrayGlacier/difficultyGrayGlacierTimeDiff2.json
packages/common/src/chains/mainnet.json
packages/common/src/eips/5133.json
packages/common/src/eips/index.ts
packages/common/src/hardforks/grayGlacier.json
packages/common/src/hardforks/index.ts
packages/common/src/index.ts
packages/common/tests/hardforks.spec.ts
packages/vm/src/index.ts

Adds support for GrayGlacier Hardfork, EIP-5133 re: #1960 
Duplicates #1983 for V5 Maintenance branch.

Gray glacier support (v5)

---

package-lock.json
packages/block/CHANGELOG.md
packages/block/package.json
packages/blockchain/package.json
packages/client/package.json
packages/common/CHANGELOG.md
packages/common/README.md
packages/common/package.json
packages/devp2p/package.json
packages/ethash/package.json
packages/tx/package.json
packages/vm/CHANGELOG.md
packages/vm/README.md
packages/vm/package.json

Releases to integrate the new GrayGlacier HF, see #1984 for the associated implementation.

Common, Block, VM: GrayGlacier HF Releases

---

config/tsconfig.json

Scenario: goto definition for `TypedTransaction`
goes to `packages/tx/dist/.../types.d.ts`
Goes to `packages/tx/src/types.ts`
Closes #1965

Add declaration map

---

packages/vm/tsconfig.benchmarks.json

Fix benchmarks build issue

---

packages/block/README.md
packages/blockchain/README.md
packages/common/README.md
packages/devp2p/README.md
packages/ethash/README.md
packages/evm/README.md
packages/rlp/README.md
packages/statemanager/README.md
packages/trie/README.md
packages/tx/README.md
packages/util/README.md
packages/vm/README.md

This should be sufficient of at least a first rough updates on the READMEs from the other libraries.

Further README Updates

---

.github/ISSUE_TEMPLATE/package--ethereumjs-evm.md
.github/ISSUE_TEMPLATE/package--ethereumjs-statemanager.md
.github/ISSUE_TEMPLATE/package--rlp.md

Addresses item from #2032
Adds issue templates for `rlp`, `evm`, and `statemanager`

Add issue templates for new packages

---

.github/workflows/block-build.yml
.github/workflows/blockchain-build.yml
.github/workflows/client-build.yml
.github/workflows/common-build.yml
.github/workflows/devp2p-build.yml
.github/workflows/ethash-build.yml
.github/workflows/evm-build.yml
.github/workflows/examples.yml
.github/workflows/rlp-build.yml
.github/workflows/statemanager-build.yml
.github/workflows/trie-build.yml
.github/workflows/tx-build.yml
.github/workflows/util-build.yml
.github/workflows/vm-pr.yml

> Resolves https://github.com/ethereumjs/ethereumjs-monorepo/issues/1938
Not sure if you had any inputs in mind that should be possible to be entered.

ci: add `workflow_dispatch` event trigger

---

packages/evm/src/index.ts
packages/vm/src/types.ts

evm: add new exports requested by hardhat

---

.github/workflows/block-build.yml
.github/workflows/blockchain-build.yml
.github/workflows/client-build.yml
.github/workflows/common-build.yml
.github/workflows/devp2p-build.yml
.github/workflows/e2e-hardhat.yml.old
.github/workflows/ethash-build.yml
.github/workflows/evm-build.yml
.github/workflows/examples.yml
.github/workflows/node-versions.yml
.github/workflows/rlp-build.yml
.github/workflows/statemanager-build.yml
.github/workflows/trie-build.yml
.github/workflows/tx-build.yml
.github/workflows/util-build.yml
.github/workflows/vm-build.yml
.github/workflows/vm-nightly-test.yml
.github/workflows/vm-pr.yml

Optimize the github workflow checkouts

Optimize the github workflow checkouts

---

packages/client/lib/execution/vmexecution.ts
packages/client/lib/sync/beaconsync.ts
packages/client/lib/sync/fetcher/blockfetcher.ts
packages/client/lib/sync/fullsync.ts

Run execution in batches when not near head

client: Run execution in batches when not near head

---

packages/evm/src/evm.ts
packages/evm/src/types.ts
packages/vm/src/runTx.ts
packages/vm/src/types.ts
packages/vm/tests/api/runTx.spec.ts

Opening as a replacement for #2138 that had its git history corrupted for some reason.

adjust skipbalance logic

---

packages/statemanager/src/stateManager.ts
packages/statemanager/tests/stateManager.spec.ts

StateManager: add prefixcodehashes flag

---

packages/common/src/chains/mainnet.json

See and verify https://github.com/ethereum/execution-specs/blob/eefb60633047975c6b3dca6cc2b15bd4a56e74a2/network-upgrades/mainnet-upgrades/paris.md#proof-of-work-to-proof-of-stake-transition

common: add mainnet merge ttd

---

.github/workflows/evm-build.yml
packages/evm/package.json
packages/vm/tests/tester/runners/GeneralStateTestsRunner.ts

Bump EVM coverage

---

README.md
packages/block/CHANGELOG.md
packages/common/CHANGELOG.md
packages/ethash/README.md
packages/evm/CHANGELOG.md
packages/rlp/CHANGELOG.md
packages/statemanager/README.md
packages/trie/CHANGELOG.md
packages/trie/benchmarks/engines/level.ts
packages/tx/CHANGELOG.md
packages/vm/CHANGELOG.md

Some improvements on the docs based on release discussion on GitHub and Discord, also fixing some things from former PRs.
Still WIP.

Breaking Release Documentation Improvements and Fixes

---

packages/trie/README.md

Signed-off-by: Brian Faust <hello@basecode.sh>

docs(trie): make mention of upgrade guide

---

README.md

add lisibility on schema
```mermaid
graph TD
vm{vm}
client{client}
ethash --> blockchain
ethash --> client
devp2p --> client
block --> client
block --> blockchain
block --> ethash
block --> vm
blockchain --> client
blockchain --> vm
trie --> client
trie --> vm
trie --> blockchain
trie --> block
trie --> statemanager
common --> block
common --> statemanager
common --> tx
common --> blockchain
common --> vm
common --> evm
common --> client
common --> devp2p
evm --> vm
evm --> client
tx --> block
tx --> vm
vm --> client
statemanager --> vm
```

Update: README.md -> Graph

---

packages/blockchain/src/blockchain.ts
packages/blockchain/src/db/manager.ts
packages/blockchain/src/db/operation.ts
packages/blockchain/src/genesisStates/index.ts
packages/blockchain/test/util.ts

Extracts blockchain from #2233

blockchain: remove isTruthy and isFalsy

---

packages/ethash/src/index.ts

ethash: remove isTruthy and isFalsy

---

packages/statemanager/src/cache.ts
packages/statemanager/src/stateManager.ts

Extracts statemanger package from #2233

stateManager: remove isTruthy and isFalsy

---

packages/block/src/header-from-rpc.ts
packages/vm/benchmarks/util.ts
packages/vm/src/runBlock.ts
packages/vm/src/types.ts
packages/vm/tests/api/buildBlock.spec.ts

monorepo: remove receiptRoot inconsistency

---

packages/evm/src/evm.ts
packages/evm/src/interpreter.ts
packages/evm/src/opcodes/codes.ts
packages/evm/src/opcodes/gas.ts
packages/evm/src/precompiles/01-ecrecover.ts
packages/evm/src/precompiles/02-sha256.ts
packages/evm/src/precompiles/03-ripemd160.ts
packages/evm/src/precompiles/04-identity.ts
packages/evm/src/precompiles/05-modexp.ts
packages/evm/src/precompiles/06-ecadd.ts
packages/evm/src/precompiles/07-ecmul.ts
packages/evm/src/precompiles/08-ecpairing.ts
packages/evm/src/precompiles/09-blake2f.ts
packages/evm/src/precompiles/0a-bls12-g1add.ts
packages/evm/src/precompiles/0b-bls12-g1mul.ts
packages/evm/src/precompiles/0c-bls12-g1multiexp.ts
packages/evm/src/precompiles/0d-bls12-g2add.ts
packages/evm/src/precompiles/0e-bls12-g2mul.ts
packages/evm/src/precompiles/0f-bls12-g2multiexp.ts
packages/evm/src/precompiles/10-bls12-pairing.ts
packages/evm/src/precompiles/11-bls12-map-fp-to-g1.ts
packages/evm/src/precompiles/12-bls12-map-fp2-to-g2.ts
packages/evm/src/precompiles/index.ts

evm: remove isTruthy and isFalsy

---

packages/client/merge/README.md

Update merge instructions as lodestar latest release has some breaking changes in args https://github.com/ChainSafe/lodestar/releases/tag/v1.0.0

client: Update merge instructions

---

packages/evm/src/opcodes/functions.ts
packages/statemanager/src/ethersStateManager.ts
packages/statemanager/tests/ethersStateManager.spec.ts
packages/trie/src/trie/trie.ts

This again reports the right gas used but not the right roots.

Ethers state manager: implement storage cache

---

packages/client/lib/net/protocol/snapprotocol.ts
packages/client/test/net/protocol/snapprotocol.spec.ts
packages/util/src/account.ts

Match snap protocol's expected encoding/decoding as per the spec.

client: Fix snap protocol encoding decoding as per spec

---

packages/trie/UPGRADING.md
packages/trie/examples/level.js
packages/util/docs/README.md
packages/util/docs/classes/Account.md
packages/util/docs/interfaces/AccountData.md

Fixes #2273 
I tested this revised example locally with the `index.spec.ts` test to verify that importing a DB that implements this example still passes our tests.

Update upgrade guide to match recipe

---

packages/blockchain/src/blockchain.ts

- Clarifies various code comments
- Removes superfluous type casting

Blockchain comments/code cleanup

---

packages/blockchain/src/blockchain.ts

Removes `_getBlock` private method from `blockchain` class and replaces with public `getBlock` everywhere as `_getBlock` provides no additional functionality and is therefore an unnecessary abstraction at this point.

blockchain: remove duplicate _getBlock method

---

packages/rlp/README.md

Updated link for Recursive Length Prefix

Update RLP README.md

---

packages/client/lib/rpc/modules/eth.ts
packages/client/test/rpc/eth/getBlockTransactionCountByNumber.spec.ts

Adds support for 'eth_getBlockTransactionByNumber'.

implementation of eth_getBlockTransactionCountByNumber

---

packages/client/lib/service/fullethereumservice.ts
packages/client/test/service/fullethereumservice.spec.ts

Fix for issue #2391 
> The [handleEth](https://github.com/ethereumjs/ethereumjs-monorepo/blob/1e903db3f29f7b4f93db3b2c61248a3c1babad27/packages/client/lib/service/fullethereumservice.ts#L228) function is a mess of if...else if... that should be converted to use a switch statement based on the message.name to improve the clarity of this code.

Clean up `handleEth`

---

packages/common/src/common.ts
packages/common/src/enums.ts

Adding support for Arbitrum One layer 2 network

common: Arbitrum One support

---

packages/client/lib/miner/pendingBlock.ts
packages/client/lib/rpc/modules/engine.ts
packages/client/test/miner/pendingBlock.spec.ts

some build block fixes for client

client: Build block fixes

---

packages/common/src/common.ts
packages/common/test/timestamp.spec.ts

Update the forkhash calculation for time based hardforks as specified here: 
- https://github.com/ethereum/EIPs/pull/6122

common: Update forkhash calculation for timebased hardforks

---

packages/client/lib/sync/beaconsync.ts
packages/client/lib/sync/fetcher/blockfetcher.ts
packages/client/lib/sync/skeleton.ts
packages/client/test/sync/beaconsync.spec.ts
packages/client/test/sync/fetcher/blockfetcher.spec.ts

Handle withdrawal bodies in the blockfetcher and skeleton sync fixes for beacon syncing from a post sharding eip4844 devnet 3.

client: Handle withdrawal bodies in the blockfetcher and skeleton sync fixes

---

packages/vm/test/api/EIPs/eip-4200-static-relative.spec.ts

Implements [EIP 4200](https://eips.ethereum.org/EIPS/eip-4200), at version https://github.com/ethereum/EIPs/pull/6100
This PR also includes;
- Fix for EIP3670 where it is not possible to run EOF code in a CREATE environment (so CREATE tx, CREATE opcode, CREATE2 opcode)
TODOs
- ~~`RJUMP`/`RJUMPI`/`RJUMPV` with `JUMPDEST` as target~~
- ~~`relative_offset` is positive/negative/`0`~~
- ~~`RJUMP`/`RJUMPI`/`RJUMPV` with instruction other than `JUMPDEST` as target~~
- ~~`relative_offset` is positive/negative/`0`~~
- `RJUMPV` with various valid table sizes from 1 to 255
- `RJUMP`/`RJUMPI`/`RJUMPV` with truncated immediate
- `RJUMP`/`RJUMPI`/`RJUMPV` as a final instruction in code section
- `RJUMP`/`RJUMPI`/`RJUMPV` target outside of code section bounds
- `RJUMP`/`RJUMPI`/`RJUMPV` target push data …

Implement EIP 4200 (Static relative jumps)

---

packages/client/docs/interfaces/ConfigOptions.md
packages/client/docs/usage/RunAsElClient.md
packages/client/lib/config.ts
packages/client/lib/net/server/rlpxserver.ts
packages/common/docs/classes/Common.md
packages/common/src/common.ts

Fix: typos

---

packages/client/test/sync/beaconsync.spec.ts

Fix beaconsync test race condition

---

packages/client/bin/startRpc.ts

client: reuse jwt-token from default path

---

packages/client/bin/cli.ts
packages/client/bin/startRpc.ts
packages/client/lib/types.ts
packages/client/test/rpc/helpers.ts

client: typed client opts

---

packages/vm/test/tester/config.ts
packages/vm/test/tester/runners/BlockchainTestsRunner.ts

Add `ethereum/tests` Shanghai support

VM/tests: add support for Shanghai

---

packages/client/bin/cli.ts
packages/client/lib/client.ts
packages/client/lib/execution/execution.ts
packages/client/lib/execution/vmexecution.ts
packages/client/lib/logging.ts
packages/client/lib/rpc/util/CLConnectionManager.ts
packages/client/lib/service/fullethereumservice.ts
packages/client/lib/sync/skeleton.ts

Some interop related CLI Improvements for the client, WIP.

Interop Client CLI Improvements

---

packages/client/lib/rpc/modules/engine.ts

This PR fixes `forkchoiceUpdateV2`. See also https://github.com/ethereum/execution-apis/blob/main/src/engine/shanghai.md#engine_forkchoiceupdatedv2
If a payload with withdrawals is thus passed to fcuV2 then timestamp should be >= Shanghai. 
This PR also fixes the hive test:
`go run ./hive.go --client ethereumjs --sim ethereum/engine --sim.limit "engine-withdrawals/Withdrawals Fork on Block 2" `

client/rpc/engine: fix forkchoiceUpdateV2 shanghai

---

packages/client/lib/client.ts
packages/client/lib/net/peerpool.ts
packages/client/lib/rpc/modules/engine.ts
packages/client/lib/rpc/util/CLConnectionManager.ts
packages/client/lib/service/txpool.ts
packages/client/lib/sync/skeleton.ts
packages/client/lib/sync/sync.ts

More client interop improvements focusing on a better differentiation between the synchronizing and synced-and-chain-following logging post-Merge.

More Interop Improvements

---

packages/client/lib/rpc/modules/engine.ts

Some fixes on the extended HF agnostic Engine API semantics.

4844 Engine API Fixes

---

packages/client/bin/cli.ts
packages/client/lib/config.ts
packages/client/lib/rpc/modules/engine.ts
packages/client/lib/rpc/modules/eth.ts
packages/client/lib/service/txpool.ts
packages/client/lib/sync/sync.ts
packages/client/lib/types.ts
packages/client/test/rpc/eth/sendRawTransaction.spec.ts
packages/client/test/sim/simutils.ts
packages/client/test/sim/single-run.sh
packages/client/test/sync/sync.spec.ts

Fix client's sync state on startup or while mining or single node (test) runs
Closes #2517

client: Fix client's sync state on startup or while mining or single node (test) runs

---

packages/client/lib/miner/miner.ts
packages/client/test/miner/miner.spec.ts

Fixes issue #2390
`Support receipts when mining/sealing blocks`

Miner-support-for-saveReceipts

---

packages/client/bin/startRpc.ts
packages/client/lib/blockchain/chain.ts

Some last round UX improvments before releases.

Small Client UX Improvements

---

packages/blockchain/src/blockchain.ts
packages/client/lib/sync/fullsync.ts

Earlier when the putblockheader errored on hf bug, the blockchain would be corrupted because headblockhash/headheaderhash have dirty updates and were not being reverted
This PR reverts any head changes in case there is any putblock error

blockchain: Revert to previous sane heads if block or header put fails

---

packages/block/CHANGELOG.md
packages/blockchain/CHANGELOG.md
packages/blockchain/docs/classes/Blockchain.md
packages/client/CHANGELOG.md
packages/client/README.md
packages/client/lib/blockchain/chain.ts
packages/devp2p/CHANGELOG.md

Continuation on #2521 
Along the release process problems regarding syncing the Sepolia network were discovered and the release process stopped after the `@ethereumjs/rlp` release.
This PR picks releases up again and continues with the remaining releases.

New Releases (Continuation)

---

packages/common/src/chains/goerli.json

ref:
- https://github.com/ethereum/execution-specs/pull/724
- https://github.com/eth-clients/goerli/pull/160

common: Schedule shanghai on goerli

---

package-lock.json
packages/block/karma.conf.js
packages/blockchain/karma.conf.js
packages/client/karma.conf.js
packages/common/karma.conf.js
packages/evm/karma.conf.js
packages/statemanager/karma.conf.js
packages/trie/karma.conf.js
packages/tx/karma.conf.js
packages/tx/package.json
packages/util/karma.conf.js
packages/util/package.json
packages/vm/karma.conf.js

ref: 
- https://github.com/ChainSafe/ssz/pull/310

util/tx: Shift ssz back to case dependency free ES2019 compatible version

---

Dockerfile
packages/client/test/rpc/eth/sendRawTransaction.spec.ts

Fix breaking tests because of scheduled mainnet shanghai hf

client: Fix breaking tests because of scheduled mainnet shanghai hf

---

packages/trie/src/db/checkpoint.ts

It turned out that the current trie cache substantially slows down block execution in certain client block ranges respectively call/attack situations, likely in combination with late reverts since the trie cache just lazily stores all nodes in the hope that these will be re-usable eventually also in case of a revert.
Block range where slowing has been tested was the following, with and without a `--trieCache=0` addition:
```shell
node dist/bin/cli.js --dataDir=/Volumes/Eth-SSD/sync/ --executeBlocks=2433000-2433121
```
Trie cache enabled version was substantially slower here.
This PR somewhat mitigates this by switching to a more conservative cache behavior by only storing:
a) values which at least once made it to the trie (in `get`)
b) values which are in the process of being written to …

Trie: More Conservative Trie Cache Behavior

---

packages/evm/README.md

Fixes the README link for running EVM code in browser.

Fix link for running EVM code in browser

---

packages/common/src/eips/4844.json
packages/evm/src/opcodes/codes.ts
packages/evm/src/opcodes/functions.ts
packages/evm/test/runCall.spec.ts
packages/evm/test/versionedHashes.spec.ts

See https://github.com/ethereum/EIPs/pull/7001

evm/common: rename DATAHASH to BLOBHASH

---

package-lock.json

update the package-lock so as to not interfere with upcoming changes introduced by package update of c-kzg to big endian

Update package lock as per latest packages

---

packages/client/src/rpc/modules/engine.ts
packages/client/src/rpc/util/CLConnectionManager.ts
packages/client/test/rpc/engine/newPayloadV3VersionedHashes.spec.ts

fix newPayloadV3 validation errors as uncovered in devnet6

client: fix the newPayloadV3 validations

---

package-lock.json
packages/wallet/package.json

wallet: remove type/node devdependency

---

packages/util/src/genesis.ts

Adds missing file extensions on internal imports in `genesis.ts`

Add extensions for new `util` file

---

package.json

Check VM nightly tests status

---

packages/client/test/sim/4844-blobpost.md
packages/client/test/sim/4844-devnet.md
packages/client/test/sim/EOF.md
packages/client/test/sim/snapsync.md

update some prerequisites for successful sim test runs

client: update prerequisites to run sim tests

---

packages/client/src/rpc/modules/debug.ts

client: await dumpStorageRange in storageRangeAt rpc for errors to be properly handled

---

packages/trie/benchmarks/engines/level.ts
packages/trie/benchmarks/index.ts
packages/trie/benchmarks/suite.ts

This PR addresses #2968 by fixing broken imports in the trie package benchmark files.

Fix the Trie Package Benchmarks

---

packages/client/src/sync/fetcher/storagefetcher.ts
packages/client/test/miner/miner.spec.ts
packages/client/test/sync/fetcher/accountfetcher.spec.ts
packages/client/test/sync/fetcher/storagefetcher.spec.ts

This change implements the highest-known-hash optimization discussed in #2941 for the storage fetcher.

Snap Sync: Storage Fetcher Highest-Known-Hash Optimization

---

.github/workflows/block-build.yml
.github/workflows/blockchain-build.yml
.github/workflows/browser.yml
.github/workflows/client-build.yml
.github/workflows/common-build.yml
.github/workflows/devp2p-build.yml
.github/workflows/e2e-hardhat.yml.old
.github/workflows/ethash-build.yml
.github/workflows/evm-build.yml
.github/workflows/examples.yml
.github/workflows/lockfile.yml
.github/workflows/node-versions.yml
.github/workflows/rlp-build.yml
.github/workflows/statemanager-build.yml
.github/workflows/trie-build.yml
.github/workflows/tx-build.yml
.github/workflows/util-build.yml
.github/workflows/vm-build.yml
.github/workflows/vm-nightly-test.yml
.github/workflows/vm-pr.yml
.github/workflows/wallet-build.yml

Acts on several deprecation notices in Github Actions
- Updates `setup-docker-buildx` to v2
- Updates `setup-node` to v3

Update github actions to newer versions

---

packages/common/src/chains.ts
packages/common/test/hardforks.spec.ts

ref:
- https://github.com/eth-clients/holesky/pull/59

common: update the shanghai hf schedule for holesky

---

packages/wallet/docs/classes/hdkey.EthereumHDKey.md
packages/wallet/src/hdkey.ts
packages/wallet/test/hdkey.spec.ts

Backporting https://github.com/ethereumjs/ethereumjs-wallet/pull/192

Wallet: Add fromMnemonic function

---

packages/client/test/rpc/engine/getPayloadV3.spec.ts
packages/client/test/rpc/engine/newPayloadV3.spec.ts
packages/vm/src/runBlock.ts
packages/vm/test/api/EIPs/eip-4788-beaconroot.spec.ts

ref  eip-4788
- https://eips.ethereum.org/EIPS/eip-4788#specification

vm: update the beacon block root contract address

---

packages/evm/src/interpreter.ts
packages/evm/src/logger.ts
packages/vm/src/vm.ts

Adds static / dynamic gas columns.

evm/vm: profiler: add static/dynamic gas columns

---

packages/evm/src/evm.ts

evm: remove unnecessary line

---

packages/client/bin/cli.ts
packages/client/src/blockchain/chain.ts
packages/client/src/config.ts
packages/client/src/execution/vmexecution.ts
packages/client/src/rpc/util/CLConnectionManager.ts
packages/client/src/service/fullethereumservice.ts
packages/client/src/service/skeleton.ts
packages/client/test/rpc/util/CLConnectionManager.spec.ts

This is a series of small UX improvements and fixes to make the client CLI output more digestable.
Ready for review. 🙂

Client: Small UX Improvements

---

package-lock.json

This PR addresses this critical vulnerability: https://github.com/ethereumjs/ethereumjs-monorepo/security/dependabot/64

monorepo: address babel vulnerability

---

packages/client/DEVELOPER.md
packages/client/README.md

This PR adds instructions to run hive (also in the new "fast development" mode). It would be great if someone could also test the instructions to ensure these are correct (and readable :smile: )

client: add hive instructions

---

packages/statemanager/src/cache/index.ts
packages/statemanager/src/ethersStateManager.ts

Fixes #3160 and removes pain point for implementing one's own storage manager.

Export originalStorageCache

---

packages/client/src/net/peer/peer.ts
packages/client/src/net/peer/rlpxpeer.ts
packages/client/src/net/protocol/boundprotocol.ts
packages/client/src/net/protocol/protocol.ts
packages/client/test/integration/mocks/mockpeer.ts
packages/client/test/net/peer/peer.spec.ts
packages/client/test/net/peer/rlpxpeer.spec.ts
packages/client/test/net/protocol/boundprotocol.spec.ts
packages/client/test/net/protocol/protocol.spec.ts

Mitigate boundprotocol insanities

---

packages/genesis/README.md
packages/genesis/src/index.ts

- Adds a reference to Holesky genesis state in readme
- Removes ain obsolete code comment

Update `genesis` docs

---

packages/evm/src/opcodes/functions.ts
packages/evm/src/opcodes/gas.ts
packages/evm/test/runCall.spec.ts

Closes #3194
Ready for review, assuming CI passes

evm: fix CALL(CODE) gas

---

packages/block/src/header.ts
packages/common/src/chains.ts
packages/devp2p/src/ext/kbucket.ts
packages/trie/src/util/asyncWalk.ts
packages/tx/src/capabilities/eip2718.ts
packages/verkle/src/types.ts

Adds a few missing `.js` file endings

Add missed `.js file endings

---

packages/vm/src/runTx.ts

Some fine-tuning on the VM runTx() profiler run.

VM: runTx() Profiler Details

---

.github/workflows/block-build.yml
.github/workflows/blockchain-build.yml
.github/workflows/browser.yml
.github/workflows/client-build.yml
.github/workflows/common-build.yml
.github/workflows/devp2p-build.yml
.github/workflows/e2e-hardhat.yml.old
.github/workflows/ethash-build.yml
.github/workflows/evm-build.yml
.github/workflows/examples.yml
.github/workflows/genesis-build.yml
.github/workflows/lockfile.yml
.github/workflows/node-versions.yml
.github/workflows/rlp-build.yml
.github/workflows/statemanager-build.yml
.github/workflows/trie-build.yml
.github/workflows/tx-build.yml
.github/workflows/util-build.yml
.github/workflows/verkle-build.yml
.github/workflows/vm-build.yml
.github/workflows/vm-nightly-test.yml
.github/workflows/vm-pr.yml
.github/workflows/wallet-build.yml

Small maintenance PR, ready to be merged if CI goes through.

Monorepo: update GitHub Actions checkout and node setup to v4

---

package-lock.json
packages/client/package.json
packages/evm/CHANGELOG.md
packages/evm/package.json
packages/statemanager/CHANGELOG.md
packages/statemanager/package.json
packages/vm/CHANGELOG.md
packages/vm/package.json

Hotfix releases following #3271

Verkle Dependency-related Hotfix Releases

---

packages/evm/src/index.ts

This simply export `getOpcodesForHF`.

export getOpcodesForHF

---

packages/common/src/eips.ts
packages/evm/src/opcodes/functions.ts
packages/vm/src/runBlock.ts
packages/vm/test/api/EIPs/eip-2935-historical-block-hashes.spec.ts

Updates EIP 2935 to https://github.com/gballet/EIPs/pull/3 to commit https://github.com/gballet/EIPs/pull/3/commits/2e9ac09a142b0d9fb4db0b8d4609f92e5d9990c5

Update EIP-2935 to latest draft spec

---

config/vitest.browser.config.mts
package-lock.json
package.json

Removes a couple of unnecessary deps that were previously used for vitest browser testing and missed during #3281

Vitest browser cleanup

---

package-lock.json

This PR addresses the 2 moderate issues that were flagged by npm (by running npm audit fix)

monorepo: npm audit fix

---

packages/tx/src/baseTransaction.ts

fix(tx): Bug in error message

---

packages/block/src/block.ts
packages/block/src/from-beacon-payload.ts
packages/block/src/types.ts
packages/client/src/rpc/modules/engine/engine.ts
packages/client/src/rpc/modules/engine/types.ts
packages/client/src/rpc/modules/engine/validators.ts
packages/client/src/rpc/validation.ts
packages/client/test/rpc/engine/newPayloadV4.spec.ts
packages/util/src/requests.ts

to be merge after:
- https://github.com/ethereumjs/ethereumjs-monorepo/pull/3398
deposit requests field in payload is deposit receipts:
- https://github.com/ethereum/execution-apis/pull/544

client: add execution api v4 handling to engine

---

package-lock.json
packages/statemanager/package.json
packages/verkle/package.json

Update `verkle-cryptography-wasm` to latest version

Update verkle crypto dep

---

packages/client/src/rpc/modules/eth.ts
packages/client/test/rpc/eth/blobBaseFee.spec.ts

Fixes #3309 
Adds the `eth_blobBaseFee` RPC end point.

Add `eth_blobBaseFee` RPC endpoint

---

config/MONOREPO.md

Add information on how to launch test & watch a single file during dev.

Update MONOREPO.md with instruction fpr single file test watch

---

packages/common/src/constructors.ts

Cleanup item from #3556 to fix code docs

Cleanup of  `createCommonFromGethGenesis` docs

---

package-lock.json

This fixes some basic monorepo usage issues I had with latest master, then followed steps from https://stackoverflow.com/questions/65342769/install-node-on-m1-mac/67907214#67907214.

Update package-lock.json to fix Node/Mac issue

---

package-lock.json
package.json

Updates the vitest dependency set to v2 from the v2 beta releases.

Update vitest deps to v2

---

packages/block/test/block.spec.ts
packages/client/bin/cli.ts
packages/client/src/util/rpc.ts
packages/client/test/execution/vmexecution.spec.ts
packages/client/test/sync/skeleton.spec.ts
packages/evm/test/eips/eip-4200.spec.ts
packages/trie/src/trie.ts
packages/tx/src/util.ts
packages/vm/test/api/customChain.spec.ts
packages/vm/test/api/index.spec.ts
packages/vm/test/api/runBlock.spec.ts

This PR removes misc types issues and removes some ts-ignore clauses.

monorepo: fix misc type issues and remove ts-ignore clauses

---

packages/trie/README.md
packages/trie/benchmarks/engines/level.ts
packages/trie/examples/customLevelDB.ts
packages/trie/scripts/view.ts
packages/trie/src/trie.ts
packages/trie/src/util/asyncWalk.ts
packages/trie/test/official.spec.ts
packages/trie/test/proof/range.spec.ts
packages/trie/test/trie/secure.spec.ts
packages/trie/test/trie/trie.spec.ts
packages/trie/test/util/asyncWalk.spec.ts
packages/vm/test/tester/index.ts

This PR addresses #3620 and makes misc type improvements to the trie package.

trie: address type issues and type-related improvements

---

packages/evm/src/precompiles/bls12_381/noble.ts
packages/vm/test/tester/index.ts

Fix BLS usage

---

packages/evm/vite.config.bundler.ts
packages/util/src/bytes.ts
packages/util/src/kzg.ts
packages/vm/test/api/index.spec.ts

This addresses some (all) remaining deprecation notes.

Util: Small Deprecation Fixes

---

config/cspell-ts.json
packages/block/src/block/constructors.ts
packages/block/src/from-beacon-payload.ts
packages/block/src/header/header.ts
packages/block/test/eip7685block.spec.ts
packages/block/test/from-beacon-payload.spec.ts
packages/block/test/from-rpc.spec.ts
packages/client/archive/libp2p/cli-libp2p.spec.ts
packages/client/bin/cli.ts
packages/client/bin/startRPC.ts
packages/client/src/execution/vmexecution.ts
packages/client/src/rpc/helpers.ts
packages/client/src/rpc/modules/eth.ts
packages/client/src/rpc/modules/txpool.ts
packages/client/src/util/rpc.ts
packages/client/test/cli/cli.spec.ts
packages/client/test/rpc/engine/newPayloadV3.spec.ts
packages/client/test/rpc/engine/newPayloadV4.spec.ts
packages/common/examples/fromGeth.ts
packages/common/src/common.ts
packages/common/src/constructors.ts
packages/statemanager/examples/evm.ts
packages/wallet/test/index.spec.ts
scripts/check-dependencies.js

monorepo: more adjustments related to json and rpc

---

packages/util/src/units.ts
packages/util/test/units.spec.ts

Follow up on #3734 (see my review comments there, addressed those here)

util: Units follow-up PR

---

packages/client/README.md

This PR slightly improves the Kaustinen6 doc that was added in #3765

client: mention of upcoming testnets

---

packages/client/src/execution/vmexecution.ts
packages/client/test/rpc/engine/kaustinen6.spec.ts
packages/common/src/types.ts
packages/evm/test/verkle.spec.ts
packages/statemanager/src/statefulVerkleStateManager.ts
packages/statemanager/src/statelessVerkleStateManager.ts
packages/statemanager/src/types.ts
packages/statemanager/test/statefulVerkleStateManager.spec.ts
packages/statemanager/test/statelessVerkleStateManager.spec.ts
packages/util/src/verkle.ts
packages/util/test/verkle.spec.ts
packages/verkle/examples/diyVerkle.ts
packages/verkle/src/constructors.ts
packages/verkle/test/internalNode.spec.ts
packages/verkle/test/interop.spec.ts
packages/verkle/test/leafNode.spec.ts
packages/verkle/test/proof.spec.ts
packages/verkle/test/verkle.spec.ts
packages/vm/src/runBlock.ts
packages/vm/src/types.ts
packages/vm/test/api/EIPs/eip-6800-verkle.spec.ts
packages/vm/test/api/runBlock.spec.ts

This PR resolves #3774 by moving the verkleCrypto handling into common

common: refactor verkleCrypto into customCrypto from common

---

packages/common/src/interfaces.ts
packages/evm/src/chunkCache.ts
packages/evm/src/evm.ts
packages/evm/src/interpreter.ts
packages/evm/src/stemCache.ts
packages/evm/src/verkleAccessWitness.ts
packages/evm/test/verkle.spec.ts
packages/verkle/test/verkle.spec.ts
packages/vm/src/runBlock.ts
packages/vm/src/runTx.ts
packages/vm/test/tester/index.ts

Add simple cache to access witness

---

packages/vm/src/params.ts

Updated contract addresses:
EIP-7002: 0x0c15F14308530b7CDB8460094BbB9cC28b9AaaAA
EIP-7251: 0x00431F263cE400f4455c2dCf564e53007Ca4bbBb
EIP-2935: 0x0F792be4B0c0cb4DAE440Ef133E90C0eCD48CCCC

client: fix requests contract address (devnet-5)

---

config/vitest.config.browser.mts
package-lock.json
package.json
packages/ethash/vite.config.ts
packages/evm/test/precompiles/09-blake2f.spec.ts
packages/mpt/test/util/genesisState.spec.ts
packages/mpt/vitest.config.browser.mts
packages/statemanager/test/statefulVerkleStateManager.spec.ts
packages/statemanager/test/vmState.spec.ts
packages/tx/test/eip4844.spec.ts
packages/tx/test/t9n.spec.ts
packages/tx/test/transactionRunner.spec.ts
packages/vm/test/api/EIPs/eip-2935-historical-block-hashes.spec.ts
packages/vm/vite.config.ts

Update vitest to v3.0.2

---

packages/binarytree/src/binaryTree.ts
packages/binarytree/test/proof.spec.ts

BinaryTree
Implements proof methods:
- createBinaryProof
- fromProof
- verifyBinaryProof

binarytree: implement proof methods

---

packages/client/test/rpc/engine/kaustinen6.spec.ts
packages/client/test/rpc/helpers.ts
packages/client/test/testdata/blocks/beacon.ts

This PR improves the client types to implement and ajdust these two interfaces:
- GethGenesis
- StartClientOptions
It also makes misc improvements to improve type safety across the client package

client: improve startClient and related types

---

packages/tx/examples/accessListTx.ts
packages/tx/examples/blobTx.ts
packages/tx/examples/legacyTx.ts
packages/tx/examples/londonTx.ts
packages/tx/examples/transactions.ts
packages/util/src/bytes.ts

This PR fixes some data & types from the tx examples that were error-ing.

tx: fix example types

---

packages/vm/README.md

docs: updated inrenal structure part

---

packages/ethash/README.md

chore: fix link to article about ethash [ethash/README.md]

---

package-lock.json

Just testing on the package-lock stuff, not sure, what was happening where anymore (so if I rebuild locally, things work, but things might break on CI).

Rebuild package-lock.json

---

.github/workflows/vm-nightly-test.yml

Nightly CI Adjustments
